### ISSUE TITLE
远程控制不可用

### ISSUE THREAD

**Issue by leijuns** [MustangYM/WeChatExtension-ForMac#10]
感谢大佬的插件。使用期间遇到一个问题，使用远程控制时提示 `No such file or directory`，并且指令也不可用。

微信版本： Version. 2.3.24 (12222)

**Comment by xieao100** [comment]
是的 我这边也是
而且 选中群聊天选择置底 会闪退 有好几处有问题 作者可以统一全面的修复一下吗？谢谢了！

**Comment by MustangYM** [comment]
> 是的 我这边也是
> 而且 选中群聊天选择置底 会闪退 有好几处有问题 作者可以统一全面的修复一下吗？谢谢了！

置底闪退已经修复了

**Comment by MustangYM** [comment]
> 感谢大佬的插件。使用期间遇到一个问题，使用远程控制时提示 `No such file or directory`，并且指令也不可用。
> 
> 微信版本： Version. 2.3.24 (12222)
马上跟进

**Comment by xieao100** [comment]
还有使用系统浏览器打开微信的网页失效了
最新版取消置底没问题了 置底还是闪退

**Comment by xieao100** [comment]
> > 感谢大佬的插件。使用期间遇到一个问题，使用远程控制时提示 `No such file or directory`，并且指令也不可用。
> > 微信版本： Version. 2.3.24 (12222)
> > 马上跟进

1、使用系统浏览器打开微信的网页失效。
2、取消置底没问题了，置底还是闪退如果你那边可以 请多来回至底然后取消再至底试几次就会复现这个问题了
3、手机发送指令给自己失效 提示No such file or directory
求更新修复。谢谢！

**Comment by MustangYM** [comment]
> > > 感谢大佬的插件。使用期间遇到一个问题，使用远程控制时提示 `No such file or directory`，并且指令也不可用。
> > > 微信版本： Version. 2.3.24 (12222)
> > > 马上跟进
> 
> 1、使用系统浏览器打开微信的网页失效。
> 2、取消置底没问题了，置底还是闪退如果你那边可以 请多来回至底然后取消再至底试几次就会复现这个问题了
> 3、手机发送指令给自己失效 提示No such file or directory
> 求更新修复。谢谢！
已修复. 1.7.9版本.

**Comment by MustangYM** [comment]
> > > 感谢大佬的插件。使用期间遇到一个问题，使用远程控制时提示 `No such file or directory`，并且指令也不可用。
> > > 微信版本： Version. 2.3.24 (12222)
> > > 马上跟进
> 
> 1、使用系统浏览器打开微信的网页失效。
> 2、取消置底没问题了，置底还是闪退如果你那边可以 请多来回至底然后取消再至底试几次就会复现这个问题了
> 3、手机发送指令给自己失效 提示No such file or directory
> 求更新修复。谢谢！

使用系统浏览器打开这个我还没修复，我会尽快抽时间做

**Comment by MustangYM** [comment]
> > > 感谢大佬的插件。使用期间遇到一个问题，使用远程控制时提示 `No such file or directory`，并且指令也不可用。
> > > 微信版本： Version. 2.3.24 (12222)
> > > 马上跟进
> 
> 1、使用系统浏览器打开微信的网页失效。
> 2、取消置底没问题了，置底还是闪退如果你那边可以 请多来回至底然后取消再至底试几次就会复现这个问题了
> 3、手机发送指令给自己失效 提示No such file or directory
> 求更新修复。谢谢！

置顶和置底，手机发指令控制都修复了
