### ISSUE TITLE
可否增加对外api

### ISSUE THREAD

**Issue by wkj89** [MustangYM/WeChatExtension-ForMac#100]
比如自动回复可以开放api，这样可以接入ai机器人
比如开放回调 api   这样我们可以开发自定义功能

**Comment by MustangYM** [comment]
> 比如自动回复可以开放api，这样可以接入ai机器人
> 比如开放回调 api 这样我们可以开发自定义功能

这个我也不太清楚哦, 没研究到这里, 有兴趣可以一起讨论

**Comment by yuzd** [comment]
https://github.com/yuzd/wechatmac 自己加点代码就好了

**Comment by MustangYM** [comment]
> https://github.com/yuzd/wechatmac 自己加点代码就好了

good

**Comment by wkj89** [comment]
> https://github.com/yuzd/wechatmac 自己加点代码就好了

我去   你fork的项目被删了 毕竟我是后端    不会ios 开发啊   我还说对比下文件差异  看下怎么改  自己魔改一下的。。。心塞

**Comment by yuzd** [comment]
其实很简单，就是代码判断一下如果配置了自动回复的文本是一个url的话
就把文本post到这个url 拿到response之后在发出去

可以参考
https://github.com/yuzd/wechatmac/blob/master/WeChatPlugin/Sources/Hook/WeChat%2Bhook.m#L546

**Comment by stevenliuit** [comment]
看下我提的issues 
https://github.com/MustangYM/WeChatExtension-ForMac/issues/88

**Comment by jsdman** [comment]
https://github.com/jsdman/WeChatExtension-ForMac  我拉了个分支加了个这个功能，感兴趣的可以看下
