### ISSUE TITLE
手机端无法同步撤回消息

### ISSUE THREAD

**Issue by senfish** [MustangYM/WeChatExtension-ForMac#1014]
- MacOS版本 : 10.15.4
- 微信版本 : 3.0.4
- 小助手版本 : 2.8.5
- BUG描述 : 手机端无法接收被撤回的消息
- 操作场景 : 电脑端可以正常接收到别人撤回的消息，但是手机端并不会同步拦截。（手机微信版本：8.0.6安卓）

**Comment by wenyang94** [comment]
为啥我连电脑端都无法防撤回了

**Comment by SensFeng** [comment]
> 为啥我连电脑端都无法防撤回了

你可以试试重启微信

**Comment by wenyang94** [comment]
我更新了微信，现在都可以看撤回了

**Comment by SensFeng** [comment]
> 我更新了微信，现在都可以看撤回了

更新了什么微信，电脑端跟手机端都更新了吗

**Comment by Gfn8812** [comment]
https://github.com/MustangYM/WeChatExtension-ForMac/issues/999

看最后一贴

**Comment by senfish** [comment]
已解决
