### ISSUE TITLE
开启皮肤后，左侧的[朋友圈][联系人]等选项都消失了

### ISSUE THREAD

**Issue by wdy3334** [MustangYM/WeChatExtension-ForMac#1016]
- MacOS版本 : 10.16 build(20C69)
- 微信版本 :  3.0.1 (17837)
- 小助手版本 : 2.8.5
- BUG描述 : 1，开启皮肤后，左侧的【朋友圈】【联系人】【收藏】【文件】都没有了。2，开启群监控后微信闪退
- 操作场景 : 1，微信启动后。2，开启群监控时
-  截图
![微信图片_20210608175732](https://user-images.githubusercontent.com/19375478/121165679-f5f68200-c83f-11eb-878d-3cc02369eed4.png)

**Comment by wdy3334** [comment]
看之前的问题，好像更新到微信3.0.3就可以了？

**Comment by char1eslu** [comment]
你好，你开启迷离模式之后，搜索框背景也是透明的吗，不是和底下的文字糊在一起了吗，看不清唉

**Comment by MustangYM** [comment]
只适配BigSur
