### ISSUE TITLE
3.1.0启动微信，提示微信已被阻止，无法开启

### ISSUE THREAD

**Issue by interchen** [MustangYM/WeChatExtension-ForMac#1017]
### issue规范
- MacOS版本 : 11.4
- 微信版本 : 3.1.0
- 小助手版本 : 2.8.4
- BUG描述 : 启动微信，提示微信已被阻止，无法开启
- 操作场景 : 启动微信
- 
<img width="260" alt="F20BF9E1-D1F8-424A-AC1F-766151D2C75E" src="https://user-images.githubusercontent.com/2597576/121278292-e2611f00-c904-11eb-8467-7366a7b44647.png">

**Comment by hellodrf** [comment]
`sudo codesign --sign - --force --deep /Applications/WeChat.app`

**Comment by MustangYM** [comment]
baidu
