### ISSUE TITLE
3.0.3 安装之后，无法打开wechat

### ISSUE THREAD

**Issue by giki0318** [MustangYM/WeChatExtension-ForMac#1018]
### issue规范
- MacOS版本 : 11.4
- 微信版本 : Version 3.0.3 (18062)
- 小助手版本 : 最新的
- BUG描述 : 安装后无法打开微信

**Comment by McCree2020** [comment]
试一下这个CMD ：codesign --sign - --force --deep /Applications/WeChat.app

**Comment by senfish** [comment]
我也一样打不开微信
MacOS版本 : 10.15.4
微信版本 : Version 3.0.4
小助手版本 : 最新的
BUG描述 : 安装后无法打开微信，不安装小助手可以正常打开微信

**Comment by Leslied-Chueng** [comment]
MacOS版本 : 10.15.7
微信版本 : Version 3.0.4
小助手版本 : 最新的
问题描述 : 安装后无法打开微信，不安装小助手可以正常打开微信
-------------------------------------------------------------
终端运行：codesign --sign - --force --deep /Applications/WeChat.app
-------------------------------------------------------------
已经可以正常使用

**Comment by senfish** [comment]
> ## MacOS版本 : 10.15.7
> 微信版本 : Version 3.0.4
> 小助手版本 : 最新的
> 问题描述 : 安装后无法打开微信，不安装小助手可以正常打开微信
> ## 终端运行：codesign --sign - --force --deep /Applications/WeChat.app
> 已经可以正常使用
多谢，同步操作，也可以正常使用了。
