### ISSUE TITLE
僵尸粉检测入口在哪里 找不到

### ISSUE THREAD

**Issue by xiaowangqinghui** [MustangYM/WeChatExtension-ForMac#1021]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by xiaowangqinghui** [comment]
weishenme不回答一下就直接关了 真的找不到入口

**Comment by MustangYM** [comment]
@xiaowangqinghui 检测僵尸粉的版本只在微信和扣扣群里发布了一个beta, 没有在Github发布.
