### ISSUE TITLE
mac系统更新后到11.4版本，安装小助手后无法启动微信程序

### ISSUE THREAD

**Issue by zlzlife** [MustangYM/WeChatExtension-ForMac#1026]
### issue规范
- MacOS版本 : 11.4 (20F71)
- 微信版本 : 3.0.3 (18062)
- 小助手版本 : 2.8.5
- BUG描述 : 无法打开微信
- 操作场景 : 程序无法启动

### 系统版本截图
![image](https://user-images.githubusercontent.com/18114690/122189331-6e55e680-cec3-11eb-8c40-77f8be0d7f76.png)

**Comment by kavizzz** [comment]
我也是
