### ISSUE TITLE
微信截图的时候，出了微信本身，其他窗口都会被隐藏起来

### ISSUE THREAD

**Issue by qiaodaima** [MustangYM/WeChatExtension-ForMac#103]
mac: 10.15
weChat: 2.3.27
微信小助手：1.96

**Comment by MustangYM** [comment]
> mac: 10.15
> weChat: 2.3.27
> 微信小助手：1.96

额, 这个, 截图的问题, 可能不是插件的问题哦

**Comment by luckysonyu99** [comment]
这是Catalina系统的问题，到隐私设置里面把微信的屏幕录制权限添加了就行。
