### ISSUE TITLE
防撤回功能失效

### ISSUE THREAD

**Issue by Phoenix-Cjd** [MustangYM/WeChatExtension-ForMac#1030]
- MacOS版本 : 11.4
- 微信版本 : 3.0.3
- 小助手版本 : 2.8.3
- BUG描述 : 防撤回功能失效了.
- 操作场景 : 
![image](https://user-images.githubusercontent.com/33504355/122538768-7778bc00-d059-11eb-92d4-d62ee2b828e3.png)

**Comment by jourdon** [comment]
重新安装，小助手现在最新的是2.8.5
