### ISSUE TITLE
MacOS升级11.4后微信启动报错

### ISSUE THREAD

**Issue by yoyoig** [MustangYM/WeChatExtension-ForMac#1032]
- MacOS版本 : 11.4
- 微信版本 : 3.0.4
- 小助手版本 :  最新版本
- BUG描述 : 微信启动报错
- 操作场景 : 微信启动报错
- 错误截图
![image](https://user-images.githubusercontent.com/30428100/122545037-fa9d1080-d05f-11eb-9347-be81c4666d1e.png)

**Comment by MiderWong** [comment]
sudo codesign --sign - --force --deep /Applications/WeChat.app

**Comment by yoyoig** [comment]
> sudo codesign --sign - --force --deep /Applications/WeChat.app

问题解决，谢谢大佬

**Comment by MiderWong** [comment]
解决了就关闭了吧。

**Comment by zhujunchen** [comment]
> 解决了就关闭了吧。

我按照大佬的做法操作了还是不行，命令如下
![截屏2021-06-20 下午10 21 51](https://user-images.githubusercontent.com/37008074/122677833-a12b1200-d216-11eb-8a12-3f3e6d468474.png)

zhudeiMac:~ zhu$ sudo codesign --sign - --force --deep /Applications/WeChat.app
Password:
Sorry, try again.
Password:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Applications/WeChat.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Applications/WeChat.app/Contents/MacOS/Mini Program.app
