### ISSUE TITLE
bigSur无法启动微信

### ISSUE THREAD

**Issue by mio4** [MustangYM/WeChatExtension-ForMac#1038]
### issue规范
- MacOS版本 : 11.3 (20E232)
- 微信版本 : 3.1.0 (18631) Beta 11
- 小助手版本 : v2.8.5
- BUG描述 : 安装小助手之后，重启微信，无法打开微信
- 操作场景 :  bigSur系统下，安装后无法打开微信，显示程序已被破坏

**Comment by ehqwang** [comment]
这个回答可以解决#971[https://github.com/MustangYM/WeChatExtension-ForMac/issues/971](url)

**Comment by ehqwang** [comment]
这个问题中有答案[https://github.com/MustangYM/WeChatExtension-ForMac/issues/971](url)

**Comment by ehqwang** [comment]
这个问题答案在[#971](https://github.com/MustangYM/WeChatExtension-ForMac/issues/971)
