### ISSUE TITLE
弹出一个报错，有详细日志

### ISSUE THREAD

**Issue by zyflovelam** [MustangYM/WeChatExtension-ForMac#1041]
- MacOS版本 : 11.4 (20F71)
- 微信版本 : Version. 3.1.0 (18631) Beta 11
- 小助手版本 : 2.8.5
- BUG描述 : 闪退
-------
Process:               WeChat [2830]
Path:                  /Applications/微信.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               3.1.0 (18631)
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           WeChat [2830]
User ID:               501

Date/Time:             2021-06-21 09:14:42.723 +0800
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Anonymous UUID:        6636825B-E724-26CA-A8F0-FE17FE8A1D82

Time Awake Since Boot: 230 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Applications/微信.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/微信.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/微信.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature in (/Applications/微信.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension) not valid for use in process using Library Validation: library load denied by system policy
	/Applications/微信.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature in (/Applications/微信.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension) not valid for use in process using Library Validation: library load denied by system policy

Binary Images:
       0x104750000 -        0x1092f1fff +com.tencent.xinWeChat (3.1.0 - 18631) <11E116D3-36FF-313F-920C-0BE8B9331877> /Applications/微信.app/Contents/MacOS/WeChat
       0x11aa0a000 -        0x11aa50fff +org.sparkle-project.Sparkle (1.20.0 913-ge196a24d - 1.20.0) <50C08D08-2F05-3F4A-A50C-46CE14FD6420> /Applications/微信.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x11ab90000 -        0x11b0affff +com.tencent.ilinknetwork (1.1.4 - 1.1.4) <CD5ADA11-BB16-3650-B832-8C4C1A13770A> /Applications/微信.app/Contents/Frameworks/ilink_network.framework/Versions/A/ilink_network
       0x11b8a5000 -        0x11b9e5fff +com.tencent.WCDB (1.0.3 - 1) <9E3A8F9B-A58E-3BEC-96BB-29B6D8165B17> /Applications/微信.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x11bddc000 -        0x11bde1fff +com.tencent.MMLibHooks (1.0 - 1) <BDD2E0F3-E311-365D-B4D8-B25B01BCA662> /Applications/微信.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x11be07000 -        0x11be29fff +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/微信.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x11beb5000 -        0x11bed7fff +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/微信.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x11bf7a000 -        0x11c0c5fff +com.tencent.wc.mp.matrixreport (1.0 - 1) <C29DB913-09F8-3137-8325-0AA3A0E8C429> /Applications/微信.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x20abe0000 -        0x20ac7bfff  dyld (852) <1AC76561-4F9A-34B1-BA7C-4516CACEAED7> /usr/lib/dyld
    0x7ffdfff28000 -     0x7ffdfff9bfff +runtime (203.46) <C447D2A9-BB07-30A8-97AB-399362D14FC8> /Library/Apple/*/runtime
    0x7fff201ea000 -     0x7fff20223fff  libobjc.A.dylib (824) <5B2CC569-85DC-3E11-8EC6-90C8007403BD> /usr/lib/libobjc.A.dylib
    0x7fff202b0000 -     0x7fff20305fff  libc++.1.dylib (905.6) <B3812B86-4FCF-3A10-8866-DF67940A974C> /usr/lib/libc++.1.dylib
    0x7fff203ca000 -     0x7fff20867fff  com.apple.CoreFoundation (6.9 - 1776.103) <93677957-5935-3C00-AA42-DBCD35755BB0> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff20db5000 -     0x7fff20e32fff  com.apple.SystemConfiguration (1.20 - 1.20) <81EDA68C-051A-3F4C-B79E-B53B365B67B1> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff210a1000 -     0x7fff213fffff  com.apple.Foundation (6.9 - 1776.103) <3C3B967D-778D-30BF-A3F8-E734FAFD76F2> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff21891000 -     0x7fff21a76fff  com.apple.CoreText (677.5.0.5 - 677.5.0.5) <C148A259-D01A-3634-9449-119EB084ABA9> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff21a77000 -     0x7fff22107fff  com.apple.audio.CoreAudio (5.0 - 5.0) <E987DC18-3396-3AAD-A66A-2B755C8D242A> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff22108000 -     0x7fff2245cfff  com.apple.security (7.0 - 59754.120.12) <7C3D689E-9B3E-3F73-ACF0-F40C1297D180> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff2245d000 -     0x7fff226bcfff  libicucore.A.dylib (66112) <9957A773-012E-3ABA-9587-CFF787170AE8> /usr/lib/libicucore.A.dylib
    0x7fff22a2d000 -     0x7fff22adbfff  com.apple.framework.IOKit (2.0.2 - 1845.120.6) <C6E70E82-8508-3515-ACE1-361E575D466A> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff22b36000 -     0x7fff2387efff  com.apple.AppKit (6.9 - 2022.50.114) <02279013-2888-3A1D-8F28-0C39A64EF5FA> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff245d2000 -     0x7fff24a70fff  com.apple.CFNetwork (1240.0.4 - 1240.0.4) <83684BEF-A3CE-3227-8E10-A8A538CCA9AE> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff24e72000 -     0x7fff25523fff  com.apple.CoreGraphics (2.0 - 1463.14.2) <BC3FA68C-7826-3692-903E-D684DFF48981> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff26e0f000 -     0x7fff270ebfff  com.apple.QuartzCore (1.11 - 927.21) <F384A0C0-F855-3B4D-AAD0-E0F0550E226C> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff27414000 -     0x7fff274f6fff  libxml2.2.dylib (34.9) <08E7CAB2-0EED-376C-880A-E52CC01E82F3> /usr/lib/libxml2.2.dylib
    0x7fff274f7000 -     0x7fff27544fff  com.apple.CoreVideo (1.8 - 414.7) <29D4EA46-F0B6-3004-863C-0940ACD200C2> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff28482000 -     0x7fff284fefff  com.apple.corelocation (2420.19.23 - 2420.19.23) <0D8A0FDD-86BA-30B9-B5A2-0755D880CB2F> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff2866d000 -     0x7fff28757fff  com.apple.CoreMedia (1.0 - 2775.22) <9C15E6D0-245E-3A6E-BC67-C1DF67F7EB2A> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff28bf7000 -     0x7fff28e37fff  com.apple.ImageIO (3.3.0 - 2130.5.4) <2F14A831-9B6F-38F3-A589-AF7FCF183261> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff29a7f000 -     0x7fff29b51fff  com.apple.framework.CoreWLAN (16.0 - 1657) <42166AAE-D9EF-3EE6-A0F3-8B3E320BB39E> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff29e1e000 -     0x7fff29e22fff  com.apple.xpc.ServiceManagement (1.0 - 1) <7E760B22-944C-387A-903F-C9184CE788B9> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff2a3c1000 -     0x7fff2a3cdfff  libbz2.1.0.dylib (44) <CA69420A-25E7-344C-852F-808F09AD43D0> /usr/lib/libbz2.1.0.dylib
    0x7fff2a5cf000 -     0x7fff2a5e1fff  libz.1.dylib (76) <C1E6CE87-167E-39EC-8B8F-2C3213A0208E> /usr/lib/libz.1.dylib
    0x7fff2a69b000 -     0x7fff2a69cfff  libSystem.B.dylib (1292.120.1) <A8309074-31CC-31F0-A143-81DF019F7A86> /usr/lib/libSystem.B.dylib
    0x7fff2a6da000 -     0x7fff2a7cafff  libiconv.2.dylib (59) <B9FD3BC7-6001-3E60-A7FB-CE8AAE07C805> /usr/lib/libiconv.2.dylib
    0x7fff2bd1f000 -     0x7fff2be7dfff  com.apple.VideoToolbox (1.0 - 2775.22) <88A013B6-FAB1-3BF9-A5C0-A92D8951E9E3> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff2c9c7000 -     0x7fff2cd9dfff  libswiftCore.dylib (5.4 - 1205.0.24.15) <9A598760-3D5C-3CE9-A3BF-E5009845A6CD> /usr/lib/swift/libswiftCore.dylib
    0x7fff2ce60000 -     0x7fff2cf94fff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <1ABFDEA2-FB20-3E05-B4CC-84A2A796D089> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2d08b000 -     0x7fff2d0a3fff  libresolv.9.dylib (68) <0E0E7298-2781-3D72-B40F-5FF7DE7DF068> /usr/lib/libresolv.9.dylib
    0x7fff2e6ba000 -     0x7fff2e719fff  com.apple.QuickLookFramework (5.0 - 928.3) <25339711-C495-35F7-B3C4-9DF7C727E2C5> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff30184000 -     0x7fff30184fff  com.apple.CoreServices (1122.38 - 1122.38) <FEC6CD87-0909-3554-B8F5-CE65A5BB032C> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff30340000 -     0x7fff30340fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <70B5CC03-9123-3190-8581-9E605DA2017F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff306cf000 -     0x7fff30827fff  libswiftFoundation.dylib (25.103) <AD60EE7C-4F8F-39C2-B5C7-B9C34CED347D> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff3178d000 -     0x7fff317a2fff  libswiftDispatch.dylib (4.100.1) <2F86CF79-7DE9-3AC8-8602-4DE10DB6F574> /usr/lib/swift/libswiftDispatch.dylib
    0x7fff3370b000 -     0x7fff3370bfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <CD5DF240-D8F7-3349-88DC-423962E5A289> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff33792000 -     0x7fff33793fff  libswiftObjectiveC.dylib (3) <616E3D5A-1711-3A27-B3D6-149A35526CB5> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff35136000 -     0x7fff35139fff  com.apple.Cocoa (6.11 - 23) <2686C6E1-1182-34AA-9A3A-F7BC19DED4CB> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff365df000 -     0x7fff377cbfff  com.apple.JavaScriptCore (16611 - 16611.2.7.1.4) <DFBCB49C-2D23-3C51-BAD0-54C1B67585BA> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff3c0da000 -     0x7fff3c0e4fff  libswiftCoreGraphics.dylib (2) <B4CFA518-EB59-3BAC-B97E-27CCB0B7A498> /usr/lib/swift/libswiftCoreGraphics.dylib
    0x7fff3c0e5000 -     0x7fff3c0eefff  libswiftDarwin.dylib (??? - ???) <EC8FE24D-0F66-316E-9A7E-386E316B0568> /usr/lib/swift/libswiftDarwin.dylib
    0x7fff3c18a000 -     0x7fff3c965fff  com.apple.WebKit (16611 - 16611.2.7.1.4) <361E432A-6745-3CE5-A203-D30B82EBF2BE> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff3cb1c000 -     0x7fff3cb1ffff  com.apple.Carbon (160 - 164) <967F26C3-8582-3A33-945F-DDA8F103B2E2> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3cc18000 -     0x7fff3cc18fff  com.apple.avfoundation (2.0 - 2015.22.4.1) <8605C616-EB49-3FCE-9489-6CA5CFCDD006> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff3cc19000 -     0x7fff3cd33fff  com.apple.AVKit (1.1 - 732.4.8) <BF9846D2-126D-3019-A06D-CDF871FEEAE3> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff3d743000 -     0x7fff3d74bfff  libswiftCoreAudio.dylib (1.1) <4632C168-B1F6-3410-8CF4-C255D5260E32> /usr/lib/swift/libswiftCoreAudio.dylib
    0x7fff3d74c000 -     0x7fff3d74cfff  libswiftCoreFoundation.dylib (1.6) <59A269BC-424F-3706-BB62-B6A26D52EAF5> /usr/lib/swift/libswiftCoreFoundation.dylib
    0x7fff3d758000 -     0x7fff3d758fff  libswiftXPC.dylib (1.1) <0D74CE61-C1B0-3E8D-98D1-430E35CE38FB> /usr/lib/swift/libswiftXPC.dylib
    0x7fff3d759000 -     0x7fff3d759fff  libswiftCoreImage.dylib (1) <22E09E94-4375-3419-9166-237080CE18B3> /usr/lib/swift/libswiftCoreImage.dylib
    0x7fff3d75a000 -     0x7fff3d75afff  libswiftIOKit.dylib (1) <E7691225-19A2-36BC-B490-AAD08C77C96F> /usr/lib/swift/libswiftIOKit.dylib
    0x7fff3fd02000 -     0x7fff3fd1bfff  libswiftsimd.dylib (1.3) <AF258396-7ADF-38A2-8B64-67A7B18669F5> /usr/lib/swift/libswiftsimd.dylib
    0x7fff40fc6000 -     0x7fff40fc9fff  com.apple.quartzframework (1.5 - 25) <60A5AD3A-4B26-35E5-824B-70AF8DF69D79> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff4140c000 -     0x7fff4140dfff  libswiftCoreLocation.dylib (5) <3DF17D50-9B08-3860-96D5-34371E1CA44E> /usr/lib/swift/libswiftCoreLocation.dylib
    0x7fff41cff000 -     0x7fff41d03fff  libswiftCoreData.dylib (3) <4C3BC6E6-785E-3DEE-8BE7-8AF482ECFAFF> /usr/lib/swift/libswiftCoreData.dylib
    0x7fff45def000 -     0x7fff45df4fff  libswiftMetal.dylib (1.3.1) <8D37E386-78F6-35F2-9989-FFD69AEE9FB2> /usr/lib/swift/libswiftMetal.dylib
    0x7fff48387000 -     0x7fff4839bfff  libswiftAppKit.dylib (104) <04AD1E65-D847-30C0-8928-045AB2B3629B> /usr/lib/swift/libswiftAppKit.dylib
    0x7fff4839c000 -     0x7fff4839dfff  libswiftQuartzCore.dylib (1) <B0E15E5D-BB3E-3872-A802-9CD654A48689> /usr/lib/swift/libswiftQuartzCore.dylib
    0x7fff4e35e000 -     0x7fff4e396fff  libswiftCoreMedia.dylib (1) <F7E75976-6D91-3178-964D-F3D0EF6AA850> /usr/lib/swift/libswiftCoreMedia.dylib
    0x7fff4eefa000 -     0x7fff4ef00fff  libswiftAVFoundation.dylib (2015.22.4.1) <3B033623-7A29-3770-8680-EA35941ED70F> /usr/lib/swift/libswiftAVFoundation.dylib
    0x7fff6bc46000 -     0x7fff6bc55fff  com.apple.opengl (18.5.9 - 18.5.9) <1422D0CA-C3E2-3309-8897-018E651CB74E> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6ec16000 -     0x7fff6ec58fff  com.apple.MultipeerConnectivity (172 - 172) <376FD925-B8C6-3843-88FE-15220EBC6D64> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff6ec9e000 -     0x7fff6ecc0fff  com.apple.audio.OpenAL (1.8 - 1.8) <48C78FAC-0CFD-3547-A3AC-D6B8C1B9C99B> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL

Model: Macmini9,1, BootROM 6723.120.36, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Apr 28 2021 19:53:33 version 18.50.40.7.7.8.119 FWID 01-e6894c69
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet Adaptor (en5), Ethernet, en5
Network Service: Wi-Fi, AirPort, en1
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: USB Billboard Device
USB Device: USB OPTICAL MOUSE
USB Device: B
USB Device: 87EC-XRGB
USB Device: USB 3.0 Bus
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by MustangYM** [comment]
#816
