### ISSUE TITLE
切换主题皮肤，聊天框下拉有掉帧或者拖影感

### ISSUE THREAD

**Issue by Lvvin** [MustangYM/WeChatExtension-ForMac#1043]
- MacOS版本 : BigSur 11.4
- 微信版本 : 3.0.4
- 小助手版本 : 2.8.4
- BUG描述 : 切换主题皮肤，下拉移动时感觉掉帧
- 操作场景 : 选择主题->任意主题，双指下拉聊天窗口，有掉帧或者拖影的感觉
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
已经修复, 还没放出来, 后续会放出来, 请耐心等待

**Comment by Peauntxja** [comment]
> 已经修复, 还没放出来, 后续会放出来, 请耐心等待

可以的  能不能也 push 上来 每次qq群里不是很及时能看到

**Comment by Andy-YanHui** [comment]
QQ群号是什么？

**Comment by MustangYM** [comment]
> > 已经修复, 还没放出来, 后续会放出来, 请耐心等待
> 
> 可以的 能不能也 push 上来 每次qq群里不是很及时能看到

不可以, 需要内测

**Comment by Lvvin** [comment]
感谢，Thanks♪(･ω･)ﾉ😌

**Comment by MustangYM** [comment]
v2.9.1
