### ISSUE TITLE
上帝模式下皮肤会部分失效

### ISSUE THREAD

**Issue by shugo-chara** [MustangYM/WeChatExtension-ForMac#1057]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 最新
- 小助手版本 : 最新
- BUG描述 : 上帝模式下全透明皮肤时，点击公众号内容会导致右侧聊天框变成黑色背景，且会影响所有聊天框全部变成黑色背景。同样问题已有人提出过 [1029](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1029)
- 操作场景 : 微信启动后, 点击公众号内容触发

临时解决方法除了重启微信外，[1029](https://github.com/MustangYM/WeChatExtension-ForMac/issues/1029)里也有无需重启恢复正常的解决方法，切换联系人TAB再切回即可。

**Comment by MustangYM** [comment]
建议升级至bigSur
