### ISSUE TITLE
macOS 11.4 微信 3.1.2 版本，安装之后没有效果

### ISSUE THREAD

**Issue by CheukFaiho** [MustangYM/WeChatExtension-ForMac#1061]
### issue规范
- MacOS版本 : 11.4
- 微信版本 : 3.1.2
- 小助手版本 : 最新版
- BUG描述 : 微信 for macOS 3.1.2 版本，安装之后微信并没有出现任何改变

看到有人说 3.1.1 的问题，但是我 3.1.1 的版本也装不上小助手，也蛮奇怪的。安装的时候 Terminal 会提示
```/Users/XXX/Downloads/WeChatExtension-ForMac-master 3/WeChatExtension/Rely/Install.sh: line 59: /Users/XXX/Downloads/WeChatExtension-ForMac-master: is a directory ```

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/123744572-8bd27980-d8e1-11eb-8fdf-a4299f113a3e.png)
这里多了个空格,另外, 这个版本微信还没适配, 可能会有问题
