### ISSUE TITLE
建议在「使用系统浏览器」功能下，添加「视频号使用内置浏览器」的选项

### ISSUE THREAD

**Issue by GarboSun** [MustangYM/WeChatExtension-ForMac#1067]
- MacOS版本 : 11.4
- 微信版本 : 3.1.2
- 小助手版本 : 2.8.5

我遇到的问题是：
朋友圈视频号视频，不能用外置浏览器查看，只能使用微信内置浏览器。
但其余网页还是外置浏览器查看方便。
所以目前的使用是在两种设置中不断的切换着。
因此希望后续可以添加一个功能，减少这种切换。
比如，「使用系统浏览器」功能下，多一个「视频号使用内置浏览器」的选项，诸如此类的。
希望大佬考虑。

**Comment by 943203155** [comment]
附议，还有其他一些只能使用微信内置浏览器的内容，比如`群邀请消息`之类的，也可以支持一下。
