### ISSUE TITLE
建议增加“限时关闭通知”功能

### ISSUE THREAD

**Issue by 943203155** [MustangYM/WeChatExtension-ForMac#1068]
如图，类似于Telegram的这种功能，关闭通知时，可以选择关闭多长时间。
<img width="858" alt="Screen Shot 2021-07-02 at 10 51 10 AM" src="https://user-images.githubusercontent.com/53991651/124213735-abf17b00-db23-11eb-8de8-029d26ec4b96.png">

**Comment by Craige65** [comment]
非常不错的一个功能，建议增加+1
