### ISSUE TITLE
导致微信崩溃(必现)

### ISSUE THREAD

**Issue by DesmondX** [MustangYM/WeChatExtension-ForMac#107]
WeChat Version: 2.3.23 (11914)
macOS: Mojave 10.14.6
使用懒癌版安装后，重启微信，能正常启动，但是一点聊天框，选择其他聊天框的时候，就必定崩溃。将陷入无限重启微信的窘境。

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by MustangYM** [comment]
> WeChat版本：2.3.23（11914）
> macOS：Mojave 10.14.6
> 使用懒癌版安装后，重启微信，能正常启动，但是一点一点聊天框，选择其他聊天框的时候，就必定崩溃。的矛盾境。

你升级到最新的微信试试
