### ISSUE TITLE
点击聊天记录闪退

### ISSUE THREAD

**Issue by fishiu** [MustangYM/WeChatExtension-ForMac#1072]
- MacOS版本 : 11.4
- 微信版本 : 3.1.2
- 小助手版本 : 2.9.0
- BUG描述 : 点击聊天记录闪退
- 操作场景 : 任意聊天窗口，点击聊天记录图标

**Comment by GITHUBNULLING** [comment]
确实会闪退，另外僵尸粉检测也会很快被强制下线。

**Comment by WestRiverPub** [comment]
MacOS版本 : 11.4
微信版本 : 3.1.2 (18819) Beta 10
小助手版本 : 2.9.0
BUG描述 : 点击聊天记录闪退
操作场景 : 任意聊天窗口，点击聊天记录图标

**Comment by MustangYM** [comment]
v2.9.1已修复
