### ISSUE TITLE
Big Sur 11.4 经常会莫名其妙卡死

### ISSUE THREAD

**Issue by ethangogogo** [MustangYM/WeChatExtension-ForMac#1085]
### issue规范
- MacOS版本 : Big Sur 11.4
- 微信版本 : 3.1.2
- 小助手版本 : 2.9.1
- BUG描述 : 经常会莫名其妙卡死，只能退出重新登录
- 操作场景 : 微信启动后, 点着不同的对话框会突然点不动了，还有点击x叉后，在程序坞中无法重新点击打开，卡死，程序坞中右键退出，重新登录恢复
- 大家有遇到的吗

**Comment by MustangYM** [comment]
#1080
