### ISSUE TITLE
11.4的黑果系统，安装小助手不成功，打开如图

### ISSUE THREAD

**Issue by leexinfast** [MustangYM/WeChatExtension-ForMac#1088]
### issue规范
- MacOS版本 : 11.4
- 微信版本 : 3.1.2
- 小助手版本 : 2.9.1
- BUG描述 : 安装后，重启微信，如图
![image](https://user-images.githubusercontent.com/55288730/124624450-7647eb80-deaf-11eb-997a-2a585965631d.png)

**Comment by leexinfast** [comment]
有人像我一样吗，是不是黑果的原因，但是我另外一台又是可以的

**Comment by MustangYM** [comment]
#816

**Comment by coffeetang-haitao** [comment]
> 有人像我一样吗，是不是黑果的原因，但是我另外一台又是可以的

你好，从苹果地带看到你发了Z390 GAMING X 的opencore引导下载文章，为了下载充了会员，但是没有下载地址，麻烦您去苹果地带上传一下吧，或者分享到github也行。多谢了！
