### ISSUE TITLE
检测僵尸功能结果及反馈

### ISSUE THREAD

**Issue by kerncoola** [MustangYM/WeChatExtension-ForMac#1094]
先上两张图：
![image](https://user-images.githubusercontent.com/13283995/124724869-f701f880-df3e-11eb-81c3-5d4534affaf1.png)
![image](https://user-images.githubusercontent.com/13283995/124724883-fbc6ac80-df3e-11eb-9c62-3fb9e90bbaad.png)
检测速度大概2秒一个，确实是无感的，如果有被删的会显示在聊天记录里面，但检测完没有后续动作，要自己一个个删除。
建议增加检测完成一键删除功能，或者把所有检测到的僵尸好友加到一个标签里面，用PC通讯录管理一键删除。
目前检测完1300多个好友没有提示风险什么的，还算安全。

**Comment by no-today** [comment]
附议

**Comment by MustangYM** [comment]
这个功能就这样了, 不会再动了.
