### ISSUE TITLE
使用皮肤时左边sidebar没有东西

### ISSUE THREAD

**Issue by dievlone** [MustangYM/WeChatExtension-ForMac#1100]
### issue规范
- MacOS版本 : 11.4 intel芯片
- 微信版本 : 3.0.1
- 小助手版本 : 2.9.2
- BUG描述 : 使用皮肤后sidebar为空的，关闭皮肤才会显示
- 操作场景 : 打开皮肤时就会
![image](https://user-images.githubusercontent.com/53396060/124772989-1c0e5f80-df6f-11eb-8618-a693aa7a492d.png)

**Comment by MustangYM** [comment]
你试试更新到3.1以上的微信

**Comment by dievlone** [comment]
好 解决了现在
