### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by Clark-new** [MustangYM/WeChatExtension-ForMac#111]
![image](https://user-images.githubusercontent.com/48502502/67654907-fa7f6700-f989-11e9-830c-0ae8756eaa53.png)

**Comment by Clark-new** [comment]
Showing Recent Messages
Cp: /Applications/WeChat.app/Contents/MacOS/WeChat_backup: Permission denied

Cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework: Permission denied

/Applications/WeChat.app/Contents/MacOS/WeChat_backup: No such file or directory

**Comment by MustangYM** [comment]
> 显示最近的消息
> Cp：/Applications/WeChat.app/Contents/MacOS/WeChat_backup：权限被拒绝
> 
> cp：/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework：权限被拒绝
> 
> /Applications/WeChat.app/Contents/MacOS/WeChat_backup：没有这样的文件或目录

这个可能是系统权限问题, 你google一下

**Comment by qierkang** [comment]
你们的回答在摸鱼：https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/issues/136
