### ISSUE TITLE
微信3.1.2界面卡住

### ISSUE THREAD

**Issue by LLLgoyour** [MustangYM/WeChatExtension-ForMac#1110]
- MacOS版本 : 10.16 build(20F71)
- 微信版本 : 3.1.2 (18766)
- 小助手版本 : 2.9.2
- BUG描述 : 在前台/后台运行一段时间皆会卡住 无法操作需要退出重新登录
- 操作场景 : 点击对话框无反馈/点击头像框无反应/头像框一直在跳动/无法最小化+无法退出/点击菜单栏内容不显示内容

**Comment by Anthonyive** [comment]
我也遇到这种问题

**Comment by synr97** [comment]
+1

**Comment by LLLgoyour** [comment]
> 我也遇到这种问题

有点怪 我试试找原因

**Comment by hp0912** [comment]
我也遇到了这问题，唯一不同的是可以最小化。

**Comment by LLLgoyour** [comment]
> 我也遇到了这问题，唯一不同的是可以最小化。

后来我又遇到了好几次这种情况 确实是可以最小化的

**Comment by wgytcdx** [comment]
+1
