### ISSUE TITLE
被警告了

### ISSUE THREAD

**Issue by Shiyang980713** [MustangYM/WeChatExtension-ForMac#1115]
### issue规范
- MacOS版本 : 11.4
- 微信版本 : 3.1.2
- 小助手版本 : 2.9.2
- BUG描述 :被警告使用第三方软件
![811626057321_ pic_hd](https://user-images.githubusercontent.com/57209725/125222594-e36adf00-e2fc-11eb-841b-4751b75c0bec.jpg)

- 方便的话提供日志, 截图或者视频(可选)

**Comment by Qwenjin** [comment]
+1

**Comment by yang0806** [comment]
一样的情况，刚刚登陆被警告

**Comment by JohnyWu** [comment]
一样遇到了

**Comment by iDev01** [comment]
被警告了

**Comment by wooseng** [comment]
+1，刚被警告了

**Comment by yanlzhl** [comment]
卧槽，我也是刚刚 1分钟内 2个微信号都收到了，昨天用了清粉工具。

**Comment by cnxfire** [comment]
+1

**Comment by Shiyang980713** [comment]
我平时只用多开和防撤回功能

**Comment by cnxfire** [comment]
我也只用了防撤回,别的都没用,多开也没用

**Comment by cnvoa** [comment]
俺也一样，我还以为我干了什么坏事，艹

**Comment by lvaneasylam** [comment]
+1

**Comment by lvaneasylam** [comment]
我以为自己发了不该发的话

**Comment by strivecheng** [comment]
我刚刚也被警告了

**Comment by OaimIsGnay** [comment]
我就开了防撤回,免登陆,系统浏览器,禁止更新..啥事没有.

**Comment by ArchangelXu** [comment]
+1，刚被警告了
