### ISSUE TITLE
无限提示更新 2.9.2

### ISSUE THREAD

**Issue by iiDestiny** [MustangYM/WeChatExtension-ForMac#1149]
### issue规范
- MacOS版本 : 11.4 (20F71)
- 微信版本 :  3.1.5 (18846)
- 小助手版本 : 2.8.1
- BUG描述 : 一直提示更新 2.9.2，但是安装后还是 2.8.1 所以无限提醒更新
- 操作场景 : 微信启动后，会弹出更新 2.9.2，点击升级，下载完后，点击安装并重启，重启后还是会提示更新，微信小助手还是v 2.81
- 方便的话提供日志, 截图或者视频(可选)
![EF6400DF-949E-42E2-8333-61C36AC8053E](https://user-images.githubusercontent.com/17637481/125959735-a8800f6b-fce7-48a9-a193-39bf4fbc3ad3.png)

![image](https://user-images.githubusercontent.com/17637481/125959755-d53e8afa-f31d-42e5-96ab-03ea4ad89bb1.png)

![image](https://user-images.githubusercontent.com/17637481/125959832-a544db25-92e9-4172-a896-d007e735e85e.png)

**Comment by LoveJessyChen** [comment]
#1148 查看此文 注意使用2.9.2及以下的版本的风险

**Comment by iiDestiny** [comment]
@MustangYM

**Comment by iiDestiny** [comment]
@MustangYM
