### ISSUE TITLE
Alfred 4头像不显示

### ISSUE THREAD

**Issue by Magus4756** [MustangYM/WeChatExtension-ForMac#115]
重新安装了小助手后。。。依旧没有头像。。。
浏览器打开 http://127.0.0.1:52700/wechat-plugin/user
头像路径依然是
"icon":"\/Users\/username\/Library\/Containers\/com.tencent.xinWeChat\/Data\/Library\/Containers\/com.tencent.xinWeChat\/Data\/Library\/Caches\/com.tencent.xinWeChat\/2.0b4.0.9\/29903834bd9430d1fde446954ee1a012\/avatar\/fda7803163c4c24c2cb869d3ed856ad8"
小助手1.9.7，微信2.3.27
btw，更新日志里只写了日期没写版本号_(:з」∠)_

**Comment by ImNobody422** [comment]
git只更新了bug修复，没推新版本吧。。所以omw不能更新到1.9.8？
