### ISSUE TITLE
2.3.28出了 能更新吗

### ISSUE THREAD

**Issue by lvhe19880210** [MustangYM/WeChatExtension-ForMac#116]
微信2.3.27最近老无故退出，估计bug很多，想升级

**Comment by cuifeiran** [comment]
可以更新------------------ 原始邮件 ------------------
发件人: "lvhe19880210"<notifications@github.com>
发送时间: 2019年11月4日(星期一) 凌晨1:11
收件人: "MustangYM/WeChatExtension-ForMac"<WeChatExtension-ForMac@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [MustangYM/WeChatExtension-ForMac] 2.3.28出了 能更新吗 (#116)



微信2.3.27最近老无故退出，估计bug很多，想升级
 
&mdash;

**Comment by jhcao23** [comment]
升到`2.3.28`了么 感觉如何?
