### ISSUE TITLE
虽然……，但是……

### ISSUE THREAD

**Issue by Lessica** [MustangYM/WeChatExtension-ForMac#1172]
曾经被<del>南山必胜客、腾讯雇佣兵</del>按在地板上摩擦，现缓刑刑期剩余三年，忍不住说两句。

你应该庆幸你**开源了并且免费**，不然事情就没有这么简单了。
再强调三遍：干扰程序正常运行，或者注入内存**牟利**违法！注入内存**牟利**违法！注入内存**牟利**违法！

请诸位引以为戒，请勿发布此类插件或者应用。

玻璃心勿看：<del>如果诸位真的很牛逼，建议入职腾讯，然后推动这些功能合法、合规地实现出来。</del>

**Comment by shiruchao** [comment]
看你这口气，是你举报的吧

**Comment by JesseWeb** [comment]
跪着的人好好跪着，搭站着的人话干嘛？

**Comment by Wangnov** [comment]
楼上的大帽子戴的好啊。自己想想不管是从逆向的角度看还是从规则逻辑的角度看，防撤回之类的功能是不是不合理的？我承认它给使用者带来了便利，但是也的确创造了不公平。同楼主的说法，得亏是真的开源免费，捐赠也是做做样子，不然被腾讯真的盯上了，那哪里是封两个号这么简单。。。。。。
注意保护好自己，开源不死的前提是人还自由。

**Comment by JesseWeb** [comment]
承认了他好用，你用了，你就是受益者，你就是曾经的受赠人。
怎么现在人的东西没以前这么好用了，有副作用了，但同时也告诉你不要用了。
“现在就可以站上台阶，开始教育了？”
“得亏开源”这种话你我都没资格说。
同样也不需要各位以一副过来人的姿态告诉大家“这条龙很强，勇士们放弃吧”这种破道理。

**Comment by JesseWeb** [comment]
> 楼上的大帽子戴的好啊。自己想想不管是从逆向的角度看还是从规则逻辑的角度看，防撤回之类的功能是不是不合理的？我承认它给使用者带来了便利，但是也的确创造了不公平。同楼主的说法，得亏是真的开源免费，捐赠也是做做样子，不然被腾讯真的盯上了，那哪里是封两个号这么简单。。。。。。
> 注意保护好自己，开源不死的前提是人还自由。

你用了吗？
“用了”
合理吗？
“不合理”
你用着爽吗？
“挺便利的”
那你觉得公平吗？
“不公平”

真是又当又立啊

**Comment by CodingOX** [comment]
> 看你这口气，是你举报的吧

你这话说的，很不中听！

**Comment by youngzil** [comment]
人家可能也只是提个醒，没有其他的意思，不管怎么样，还是感谢，Respect！！！

**Comment by Lessica** [comment]
> 承认了他好用，你用了，你就是受益者，你就是曾经的受赠人。
> 怎么现在人的东西没以前这么好用了，有副作用了，但同时也告诉你不要用了。
> “现在就可以站上台阶，开始教育了？”
> “得亏开源”这种话你我都没资格说。
> 同样也不需要各位以一副过来人的姿态告诉大家“这条龙很强，勇士们放弃吧”这种破道理。

第一、和是否开源关系不太大，和作为量刑标准的是否牟利关系挺大的。
第二、我没有使用过该插件。
第三、我以自己作为反面教材进行告诫，但愿诸位插件编写者不要好心当作驴肝肺，出事了才悔不当初。
第四、我参与并开源的项目不在少数，开源精神是什么，相信我比你更懂。

以上。

**Comment by Lessica** [comment]
> 看你这口气，是你举报的吧

举报违法犯罪，是每位公民的义务。
