### ISSUE TITLE
禁止更新优化

### ISSUE THREAD

**Issue by xieao100** [MustangYM/WeChatExtension-ForMac#119]
现在方式太彻底了，自己点不了更新。
禁止更新禁止的应该是打开微信后微信自动检测 弹窗更新提示，
如果想自己检查一下看看有没有新版本可以更新，更新了什么内容 这样就完全看不到了 必须去官网搜索。
建议可以只屏蔽自动检查更新弹窗，可以自己选择点击更新查看新版本。

**Comment by MustangYM** [comment]
> 现在方式太彻底了，自己点不了更新。
> 禁止更新禁止的应该是打开微信后微信自动检测弹窗更新提示，
> 如果想自己检查一下看看有没有新版本可以更新，更新了什么内容这样就完全看不到了必须去官网搜索。
> 建议可以只屏蔽自动检查更新弹窗，可以自己选择点击更新查看新版本。

把禁止更新去掉勾选, 重启, 更新就有了
