### ISSUE TITLE
微信自带的截图有问题

### ISSUE THREAD

**Issue by huyuaning** [MustangYM/WeChatExtension-ForMac#121]
当在 finder 里 按空格键预览任意文件，弹出预览窗口，此时按截图快捷键，无法截此窗口的图。而是在预览窗口后面，还有一层一摸一样的窗口，移动第一层预览窗口放到一边（不挡到第二层），才可以截第二层预览窗口的图。

使用 /WeChatExtension-ForMac-master/WeChatExtension/Rely/Uninstall.sh 卸载掉本插件，重新登录微信，再使用截图恢复正常。

http://sdp-csm.oss-cn-beijing.aliyuncs.com/b47e876e880b0cb733363434224d32b6.png

找了 3 个使用同插件的同事，100% 复现此问题。

mac版微信2.3.27
系统版本 10.14.6 (18G103)
插件版本 1.9.8

**Comment by MustangYM** [comment]
> 当在 finder 里 按空格键预览任意文件，弹出预览窗口，此时按截图快捷键，无法截此窗口的图。而是在预览窗口后面，还有一层一摸一样的窗口，移动第一层预览窗口放到一边（不挡到第二层），才可以截第二层预览窗口的图。
> 
> 使用 /WeChatExtension-ForMac-master/WeChatExtension/Rely/Uninstall.sh 卸载掉本插件，重新登录微信，再使用截图恢复正常。
> 
> http://sdp-csm.oss-cn-beijing.aliyuncs.com/b47e876e880b0cb733363434224d32b6.png
> 
> 找了 3 个使用同插件的同事，100% 复现此问题。
> 
> mac版微信2.3.27
> 系统版本 10.14.6 (18G103)
> 插件版本 1.9.8

凑合用吧, 不打算修复这个场景很少的BUG, 因为其实微信的这个截图我是不怎么用的, 因为不太方便, Snipaste这个软件截图吧, 超屌, 超爽, 超好👌
