### ISSUE TITLE
聊天多选删除有问题

### ISSUE THREAD

**Issue by lchecho** [MustangYM/WeChatExtension-ForMac#122]
多选聊天，然后右键删除，微信会退出，必现

**Comment by hexid26** [comment]
我这边没有问题。

ENV | Version
:-- | :--
MacOS | Catalina 10.15.1 (19B88)
WeChat | Version 2.3.28 (12864)
WeChatExtension | commit 3341cb21ab32f9f624e03df5ef0bfb4c0e9c7775 (HEAD -> master, origin/master, origin/HEAD)<br>Author: MustangYM <ymoomy@yeah.net><br>Date:   Thu Nov 7 14:15:50 2019 +0800<br>Update README.md

**Comment by MustangYM** [comment]
> 多选聊天，然后快捷删除，微信会退出，必现

1.9.9版本已修复
