### ISSUE TITLE
1.9.9 一些问题汇总

### ISSUE THREAD

**Issue by nstylec** [MustangYM/WeChatExtension-ForMac#124]
1. 自带更新小助手功能无法正常使用
2. 开启消息防撤回的菜单显示了assistant.menu.revoke
3. 主菜单显示assistant.menu.version1.9.9

**Comment by MustangYM** [comment]
> 1. 自带更新小助手功能无法正常使用
> 2. 开启消息防撤回的菜单显示了assistant.menu.revoke
> 3. 主菜单显示assistant.menu.version1.9.9

2.1.2已修复
