### ISSUE TITLE
为什么最近老被限制了,不清楚为什么被鉴定为使用外挂

### ISSUE THREAD

**Issue by rhymed-liu** [MustangYM/WeChatExtension-ForMac#1273]
### issue规范
- MacOS版本 : 10.15.5
- 微信版本 : 当前最新版
- 小助手版本 : 当前最新版
- BUG描述 : 被系统提示使用外挂,等...

**Comment by Zirkfied** [comment]
没看最新的read.me吗

**Comment by rhymed-liu** [comment]
刚检测了提示更新,更新完微信奔溃了.重新下载试试看.在观察一下
