### ISSUE TITLE
Version. 2.3.29 (12934)版本防撤回失效了

### ISSUE THREAD

**Issue by xt-input** [MustangYM/WeChatExtension-ForMac#128]

**Comment by MustangYM** [comment]
> _没有提供描述。_

微信最新才2.3.28啊

**Comment by xt-input** [comment]
外测版，撤回那个方法多加了一个参数

发自我的iPhone

**Comment by MustangYM** [comment]
> 外测版，撤回那个方法多加了一个参数发自我的iPhone
> […](#)
> 在 2019年11月21日，11:33，MustangYM ***@***.***> 写道： ﻿ 没有提供描述。 微信最新才2.3.28啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

正式上线了再说吧
