### ISSUE TITLE
微信最新版本不能防撤回

### ISSUE THREAD

**Issue by WangXuanGuo** [MustangYM/WeChatExtension-ForMac#131]
微信版本：[2019-11-28 17:20:11] v2.3.29.17 (12948)
防撤回无效

**Comment by xiangjunbo** [comment]
是的！

**Comment by MustangYM** [comment]
AppStore还没上2.3.29, 等AppStore上架了最新的版本我会处理.

**Comment by wednesday** [comment]
坐等大佬更新

**Comment by MustangYM** [comment]
> 微信版本：[2019-11-28 17:20:11] v2.3.29.17（12948）
> 防撤回无效

2.2.0版本已适配微信2.3.29, 欢迎使用

**Comment by MustangYM** [comment]
> 坐等大佬更新

2.2.0版本已适配微信2.3.29, 欢迎使用

**Comment by MustangYM** [comment]
> 是的！

2.2.0版本已适配微信2.3.29, 欢迎使用
