### ISSUE TITLE
感觉翻译好像是有点问题唉。。。

### ISSUE THREAD

**Issue by char1eslu** [MustangYM/WeChatExtension-ForMac#132]
我是直接更新的，然后更新完之后就变成中英文混杂的了，之前还挺好的，然后我又重启微信→不行，卸载小助手然后重新安装→还是不行。。。macOS 10.15.1，WeChat Version 2.3.28 (12864)
![image](https://user-images.githubusercontent.com/20885743/70104173-2cb27180-1678-11ea-8080-5918261202eb.png)

**Comment by Jerry007s** [comment]
+1

**Comment by cdwmhcc** [comment]
> +1

![image](https://user-images.githubusercontent.com/8030134/70111929-c1c06500-168e-11ea-80e2-142806135af2.png)
2.1.2还是这样

**Comment by MustangYM** [comment]
> > +1
> 
> ![图片](https://user-images.githubusercontent.com/8030134/70111929-c1c06500-168e-11ea-80e2-142806135af2.png)
> 2.1.2还是这样

新的2.1.2已经修复了

**Comment by MustangYM** [comment]
> +1

新的2.1.2已经修复了

**Comment by MustangYM** [comment]
> 我是直接更新的，然后更新完之后就变成中英文混杂的了，之前还挺好的，然后我又重启微信→不行，卸载小助手然后重新安装→还是不行。。。macOS 10.15.1，WeChat Version 2.3.28 (12864)
> ![image](https://user-images.githubusercontent.com/20885743/70104173-2cb27180-1678-11ea-8080-5918261202eb.png)

新的2.1.2已经修复了

**Comment by char1eslu** [comment]
![image](https://user-images.githubusercontent.com/20885743/70121016-b37f4280-16a8-11ea-8f1d-d861fad302e1.png)
刚刚安装的2.1.2 版本，重启，卸载重装，还是这样
