### ISSUE TITLE
截图问题

### ISSUE THREAD

**Issue by younger228** [MustangYM/WeChatExtension-ForMac#137]
v2.1.1 截图的时候，只会定位微信的界面， 卸载完助手，还是会有这个问题，怎么完全删除助手的文件，我使用的是懒人安装

**Comment by MustangYM** [comment]
> v2.1.1截图的时候，只会定位微信的界面，卸载完毕助手，还是会有这个问题，怎么完全删除助手的文件，我使用的是懒人安装

执行Uninstall.sh这个脚本
