### ISSUE TITLE
AI撩妹无法使用，微信2.3.28 (12864)

### ISSUE THREAD

**Issue by salayidin** [MustangYM/WeChatExtension-ForMac#138]
我是微信 2.3.28 (12864)
尝试了下更新中最吸引人的AI撩妹，但是无法使用，毫无反应。
希望这个功能能够尽快可以正常使用 😂

**Comment by MustangYM** [comment]
> 我是微信2.3.28（12864）尝试
> 了下更新中最吸引人的AI撩妹，但是无法使用，毫无反应。
> 希望这个功能能够尽快可以正常使用😂

你设置了你的妹子么, 设置你的妹子后, 妹子发消息给你, 才能自动帮你回啊

**Comment by WGwangguan** [comment]
> > 我是微信2.3.28（12864）尝试
> > 了下更新中最吸引人的AI撩妹，但是无法使用，毫无反应。
> > 希望这个功能能够尽快可以正常使用😂
> 
> 你设置了你的妹子么, 设置你的妹子后, 妹子发消息给你, 才能自动帮你回啊

设置了之后也是无反应的，今天刚更新想玩玩，然而并不行。

**Comment by stevenliuit** [comment]
我的也是这样

**Comment by stevenliuit** [comment]
以前的自动回复也没了 终于做了一份字典 没了 哎……！！！

**Comment by MustangYM** [comment]
> > > 我是微信2.3.28（12864）尝试
> > > 了下更新中最吸引人的AI撩妹，但是无法使用，毫无反应。
> > > 希望这个功能能够尽快可以正常使用😂
> > 
> > 
> > 你设置了你的妹子么，设置你的妹子后，妹子发消息给你，才能自动帮你回啊
> 
> 设置了之后也是无反应的，今天刚更新想玩玩，却并不行。

进群里截图问吧, 这里太慢了

**Comment by MustangYM** [comment]
> 我的也是这样

进群里截图问吧, 这里太慢了

**Comment by MustangYM** [comment]
> 我是微信 2.3.28 (12864)
> 尝试了下更新中最吸引人的AI撩妹，但是无法使用，毫无反应。
> 希望这个功能能够尽快可以正常使用 😂

进群里截图问吧, 这里太慢了

**Comment by MustangYM** [comment]
统一回复2.1.3已经修复
