### ISSUE TITLE
可以变更一下开启消息防撤回的快捷键吗?

### ISSUE THREAD

**Issue by dominicing** [MustangYM/WeChatExtension-ForMac#14]
有的时候浏览器和iterm等软件的打开新窗口就是这个command + T 会出现误操作 thank you ~

**Comment by MustangYM** [comment]
> 有的时候浏览器和iterm等软件的打开新窗口就是这个command + T 会出现误操作 thank you ~

这个感觉没必要, 照顾大多数人吧. 老哥
