### ISSUE TITLE
一直提示更新

### ISSUE THREAD

**Issue by cdwmhcc** [MustangYM/WeChatExtension-ForMac#140]
![image](https://user-images.githubusercontent.com/8030134/70320809-9e4d1400-1860-11ea-8007-0738cb8b3ead.png)

**Comment by shichen35** [comment]
Same here

**Comment by char1eslu** [comment]
+1，。而且好像又不适配英文系统了，卸载重装也不行

**Comment by YvanYifeiLi** [comment]
+2

**Comment by tututu-patch** [comment]
+3

**Comment by MustangYM** [comment]
修复代码已经上传了, 没有发新版本. 重装即可
