### ISSUE TITLE
微信封号的可能原因及解决方案

### ISSUE THREAD

**Issue by levie-vans** [MustangYM/WeChatExtension-ForMac#1431]
根据开发者的可能的检测逻辑思考，应该至少会检测两个部分：
1. 微信app的官方签名是不是完整有效，这一步腾讯其实从2月份安装了小助手的微信无法启动需要重签名的时候就布局好了；
2. 检测加载的dylib文件中是不是有小助手的名字：“WeChatExtension”。
3. 如果再进一步，可能会检测某些函数是否被Hook，某些函数返回值是否与设计不同。

所以根据这个思路，我先将扩展的文件改名，比如改成“AFNetworking”、“CocoaLumberjack”等等，然后使用DYLD_INSERT_LIBRARIES加载扩展，我测了三四天了，一直很稳，未再出现警告。也可以根据这个思路写一个shell脚本，打包成app来使用，具体程序我就不放了，看懂的可以直接做。

供参考！

**Comment by MustangYM** [comment]
就我的分析来看，微信的检测方式很low，阁下多虑了

**Comment by zsbai** [comment]
使用将近一年，没有任何风险提示，直至接收到最后一次更新，打开闪退才发现已经停更了，会不会也和账号有关？（如老号就不会有这么严格的检测）or也可能我只是一个漏网之鱼

**Comment by levie-vans** [comment]
目前测试了6 天了，这种加载方式一直很稳定。

**Comment by levie-vans** [comment]
> 使用将近一年，没有任何风险提示，直至接收到最后一次更新，打开闪退才发现已经停更了，会不会也和账号有关？（如老号就不会有这么严格的检测）or也可能我只是一个漏网之鱼

应该是老版本的微信没有加载检测功能，也没有动态执行远程代码的功能，所以不会提示风险。

**Comment by zsbai** [comment]
> > 使用将近一年，没有任何风险提示，直至接收到最后一次更新，打开闪退才发现已经停更了，会不会也和账号有关？（如老号就不会有这么严格的检测）or也可能我只是一个漏网之鱼
> 
> 应该是老版本的微信没有加载检测功能，也没有动态执行远程代码的功能，所以不会提示风险。

我使用的是3.0.0版本，看到最新为3.1.1，确实比较老了；

**Comment by levie-vans** [comment]
> > > 使用将近一年，没有任何风险提示，直至接收到最后一次更新，打开闪退才发现已经停更了，会不会也和账号有关？（如老号就不会有这么严格的检测）or也可能我只是一个漏网之鱼
> > 
> > 
> > 应该是老版本的微信没有加载检测功能，也没有动态执行远程代码的功能，所以不会提示风险。
> 
> 我使用的是3.0.0版本，看到最新为3.1.1，确实比较老了；

嗯，很多用2.7.x版的一直很稳
