### ISSUE TITLE
建议把现在的AI回复的网址接口暴露出来，大家都可以自定义

### ISSUE THREAD

**Issue by Songkeys** [MustangYM/WeChatExtension-ForMac#144]
这样作者也不需要满足不同人的需求了，既省事大家又开心。

**Comment by CharlesChen0431** [comment]
万一有人拿来做什么违法的事情，作者可能要背锅，比如，AI回复种小链接

**Comment by ericchuhong** [comment]
这个不是腾讯的AI免费开放接口吗？ 还需要暴露？ 连源码都给你连

**Comment by Songkeys** [comment]
> 这个不是腾讯的AI免费开放接口吗？ 还需要暴露？ 连源码都给你连
@ericchuhong 不好意思，可能我没有表达清楚，是把这个 webhook 接口做成可以自定义的。所有消息经过我的服务器，并自行处理返回内容发回来。相当于实现机器人需求。

**Comment by MustangYM** [comment]
> 这样作者也不需要满足不同人的需求了，既省事大家又开心。

对不起, 我认为你有灰产嫌疑

**Comment by Songkeys** [comment]
> > 这样作者也不需要满足不同人的需求了，既省事大家又开心。
> 
> 对不起, 我认为你有灰产嫌疑

@MustangYM 

首先，感谢作者在原项目（<https://github.com/TKkk-iOSer/WeChatPlugin-MacOS>）关闭之后能接手这个项目继续开发维护。

我在提这个 issue 的初衷是看到之前的自动回复变成现在的 AI 撩妹后，又有人（#139 #133 #154）希望变回去，或者觉得这个功能太差。相信作者对回滚肯定是拒绝的。而一个更好的解决办法，我认为是这种自定义接口暴露的方式，因为能扩大使用场景，并解决当前的一些矛盾。

另外，当我们谈论一个可以实现的技术点时，可以说「我认为这个技术可能为灰产带来便利，考虑到法律问题，所以不予实现」，而不是对提出者说「你有灰产嫌疑」。

最后，我相信真正做灰产的，不会来这个地方发个 issue，而是要么选择更稳定廉价的群控软件平台，要么自己直接 fork 一份，开发成本也仅仅是改一下链接配置就行，（如果他真的愿意在 Mac 上用这个软件的话）。

当然，你可以说「对不起，我觉得现在的 AI 自动回复撩妹的想法可能更适合普遍使用场景。请自行 fork 满足需求」。

**Comment by MustangYM** [comment]
之前版本的自动回复已经加回去了，代码还没有push上来，我会抽时间仔细测试后发布。至于你提出的这个AI问题，你可以自己改一下，代码很简单。




| |
晏茂
|
|
邮箱：ymoomy@yeah.net
|

签名由 网易邮箱大师 定制

在2019年12月19日 18:59，Songkeys 写道：

这样作者也不需要满足不同人的需求了，既省事大家又开心。

对不起, 我认为你有灰产嫌疑

@MustangYM

首先，感谢作者在原项目（https://github.com/TKkk-iOSer/WeChatPlugin-MacOS）关闭之后能接手这个项目继续开发维护。

我在提这个 issue 的初衷是看到之前的自动回复变成现在的 AI 撩妹后，又有人（#139#133#154）希望变回去，或者觉得这个功能太差。相信作者对回滚肯定是拒绝的。而一个更好的解决办法，我认为是这种自定义接口暴露的方式，因为能扩大使用场景，并解决当前的一些矛盾。

另外，当我们谈论一个可以实现的技术点时，可以说「我认为这个技术可能为灰产带来便利，考虑到法律问题，所以不予实现」，而不是对提出者说「你有灰产嫌疑」。

最后，我相信真正做灰产的，不会来这个地方发个 issue，而是要么选择更稳定廉价的群控软件平台，要么自己直接 fork 一份，开发成本也仅仅是改一下链接配置就行，（如果他真的愿意在 Mac 上用这个软件的话）。

当然，你可以说「对不起，我觉得现在的 AI 自动回复撩妹的想法可能更适合普遍使用场景。请自行 fork 满足需求」。
