### ISSUE TITLE
启动以后自定义表情的预览变成绿色方块

### ISSUE THREAD

**Issue by 3abc** [MustangYM/WeChatExtension-ForMac#145]
![image](https://user-images.githubusercontent.com/46010137/70691822-e019f800-1c6e-11ea-8405-828801589ad6.png)

如图

**Comment by MustangYM** [comment]
> ![图片](https://user-images.githubusercontent.com/46010137/70691822-e019f800-1c6e-11ea-8405-828801589ad6.png)
> 
> 就像

应该是微信本身的BUG
