### ISSUE TITLE
统一回复你叫什么：“我叫小豪豪”

### ISSUE THREAD

**Issue by zy21802** [MustangYM/WeChatExtension-ForMac#147]
只要涉及名字的全部都是豪豪，作者能增加一个自定义窗口吗。我朋友跟我聊天的时候他都快笑死了

**Comment by MustangYM** [comment]
> 只要涉及名字的全部都是豪豪，作者能增加一个自定义窗口吗。我朋友跟我聊天的时候他都快笑死了

腾讯这个AI还是太智障了, 找时间把别的几个AI加进去

**Comment by hzxulin** [comment]
是啊，附议，感觉重新设置为当前昵称就好了
