### ISSUE TITLE
张小龙你妈死了

### ISSUE THREAD

**Issue by shujuecn** [MustangYM/WeChatExtension-ForMac#1473]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by xyamzw** [comment]
合影

**Comment by LightToDo** [comment]
张小龙你妈死了

**Comment by LightToDo** [comment]
今天张小龙没有妈(码)可扫

**Comment by xyamzwqwq** [comment]
> 今天张小龙没有妈(码)可扫

支持😋
