### ISSUE TITLE
希望增加消息定时发送功能

### ISSUE THREAD

**Issue by dramaticmeow** [MustangYM/WeChatExtension-ForMac#149]
感谢开发人员的辛苦付出🙏🙏在这里提一个小小的建议：有的时候半夜突然想到一件事情又怕打扰到别人休息，但第二天再发又容易忘记，所以如果有定时发送的话就会方便很多，希望开发团队可以考虑一下下("⋆ω⋆)

**Comment by MustangYM** [comment]
> 感谢开发人员的辛苦付出🙏🙏在这里提一个小小的建议：有的时候半夜突然想到一件事情又怕打扰到别人休息，但第二天再发又容易忘记，所以如果有定时发送的话就会方便很多，希望开发团队可以考虑一下下("⋆ω⋆)

有时候突然...使用频率太少太少了, 可能暂时不会考虑
