### ISSUE TITLE
发送文件时卡顿的问题

### ISSUE THREAD

**Issue by WeirdStar0** [MustangYM/WeChatExtension-ForMac#15]
目前使用发现个小问题，发送文件时打开文件夹的时候会有明显卡顿，无法选取要发送文件，基本要卡顿个3-4秒才恢复正常，在之前tk大佬的版本也会这样，不知道是不是mojave的问题，印象中在之前的mac版本上不会有这个问题

**Comment by MustangYM** [comment]
> 目前使用发现个小问题，发送文件时打开文件夹的时候会有明显卡顿，无法选取要发送文件，基本要卡顿个3-4秒才恢复正常，在之前tk大佬的版本也会这样，不知道是不是mojave的问题，印象中在之前的mac版本上不会有这个问题

会跟进

**Comment by MustangYM** [comment]
目前还是没有发现这个问题哦
