### ISSUE TITLE
什么时候支持 【表情、语音、视频、聊天记录】类型的消息同步到手机呢？

### ISSUE THREAD

**Issue by JoffreyN** [MustangYM/WeChatExtension-ForMac#150]
什么时候支持 【语音、表情、视频、聊天记录】类型的消息同步到手机呢？
意义很大呀！

**Comment by MustangYM** [comment]
> 什么时候支持 【语音、表情、视频、聊天记录】类型的消息同步到手机呢？
> 意义很大呀！

我可能会考虑做, 我可能时间不太多
