### ISSUE TITLE
可能需要一个 fix

### ISSUE THREAD

**Issue by hexid26** [MustangYM/WeChatExtension-ForMac#151]
长期 watch，感谢 MustangYM 坚持更新这么好用的插件。

主要是长期配合 Alfred 的TKWechat插件。所以这两天更新后发现少了一个功能。估计需要在`TKWebServerManager.m` 文件中做一点修复。

使用 Alfred 的插件时，微信 2.3.29 ➕WeChatExtension master 无法获得和任意联系人的聊天记录。

看 python 脚本是使用 `http://127.0.0.1:52700/wechat-plugin/chatlog?userId=USER_ID&count=45` 这个连接获取 json 文件。
这个文件是通过 `TKWebServerManager.m` 文件生成的。如果没有找错的话，应该是第 152 行开始的吧。。。

大大有空的话，检查下是不是这个文件和微信的内部接口不匹配了。个人确实没有能力修复这个问题。。。也不晓得这个对于您是不是也是刚需。不强求🤣

再次感谢一直以来的坚持🙏🏻

**Comment by MustangYM** [comment]
> 长期 watch，感谢 MustangYM 坚持更新这么好用的插件。
> 
> 主要是长期配合 Alfred 的TKWechat插件。所以这两天更新后发现少了一个功能。估计需要在`TKWebServerManager.m` 文件中做一点修复。
> 
> 使用 Alfred 的插件时，微信 2.3.29 ➕WeChatExtension master 无法获得和任意联系人的聊天记录。
> 
> 看 python 脚本是使用 `http://127.0.0.1:52700/wechat-plugin/chatlog?userId=USER_ID&count=45` 这个连接获取 json 文件。
> 这个文件是通过 `TKWebServerManager.m` 文件生成的。如果没有找错的话，应该是第 152 行开始的吧。。。
> 
> 大大有空的话，检查下是不是这个文件和微信的内部接口不匹配了。个人确实没有能力修复这个问题。。。也不晓得这个对于您是不是也是刚需。不强求🤣
> 
> 再次感谢一直以来的坚持🙏🏻

已修复, 但是没有发版本, 跟着下个版本发出来, 如果你很急的话可以clone最新的代码自己安装.

**Comment by alzj96** [comment]
首先感谢 mustang YM更新mac的微信插件，帮助大家解决了很多问题

这里还是同样类似的问题。 就 http://127.0.0.1:52700/wechat-plugin/chatlog?userId=USER_ID&count=45 这个链接获取聊天记录 只能获取到从电脑端发送的聊天， 无法接受到对方的聊天记录。查看微信窗口，发现是电脑发送信息时，新开了一个窗口，而不是获取原本的聊天记录。不知道可否请大大尝试修复一下。

再次感谢大大的努力和坚持。
