### ISSUE TITLE
装了小助手后不能分享

### ISSUE THREAD

**Issue by xt-input** [MustangYM/WeChatExtension-ForMac#152]
装了小助手之后点击分享选择微信然后选择朋友不能调起朋友列表

**Comment by MustangYM** [comment]
> 装了小助手之后点击分享选择微信然后选择朋友不能调起朋友列表

从哪点击的分享? 给个截图

**Comment by xt-input** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/27754416/70984789-108de600-20f6-11ea-8f39-0e0951b94167.png">

**Comment by xt-input** [comment]
新版的微信在10.15上没有这个分享，这是内测包

**Comment by xt-input** [comment]
附件将于2020年1月16日过期
点按以下载
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAbQ5lQ8_BggSYjBTP0naQQU4-tmqAXjh1huzTaOJhyXmvTQc4k5SdPsW%2F%24%7Bf%7D%3Fo%3DAq3YGZXbbi_iBzzA9U9ONyzEAgCufwdkJkcOBbnx3lbW%26v%3D1%26x%3D3%26a%3DCAogrMmGpJtzOV4rSBzR8FG8Vfj69NtOWX6Dtpj_LF4vfLkSJxDZqaqa8S0Y2bml7votIgEAKggByAD_EU2EQ1IEOPrZqloEUnT7Fg%26e%3D1579168652%26k%3D%24%7Buk%7D%26fl%3D%26r%3D6402E61F-E376-4D75-9B2F-AFACA605BDBD-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DEBA3D985-A623-49EA-8F7B-A2B23DBDA9FD%26p%3D43%26s%3DmtOh3wWj0lVtCk5egf8dN-HlWC4&uk=4HA8ojJES4D_fNRB3y31Jw&f=wechat-daily-12984-1576552055.dmg&sz=27246055>wechat-daily-12984-1576552055.dmg
27.2 MB

**Comment by MustangYM** [comment]
我在2.6.1版本的小助手上可以分享
