### ISSUE TITLE
AI自动回复太不智能了，使用被吐槽了

### ISSUE THREAD

**Issue by taolin2107** [MustangYM/WeChatExtension-ForMac#154]
<img width="504" alt="WX20191217-165023@2x" src="https://user-images.githubusercontent.com/2200131/70979935-66aa5b80-20ed-11ea-85c1-235c94449894.png">

**Comment by MustangYM** [comment]
要不整个收费版的图灵机器人? 那玩意智能, 看你愿不愿意充钱了.
