### ISSUE TITLE
Bug请求修复

### ISSUE THREAD

**Issue by Huuuu0** [MustangYM/WeChatExtension-ForMac#1557]
### issue规范- MacOS版本 : 10.14.6
- 微信版本 : 2.3.24
- 小助手版本 : 2.9.2
- BUG描述 : 打开好友会话框一直显示拦截到崩溃
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, [截图或者视频(可选)]
- 
<img width="421" alt="屏幕快照 2021-08-19 上午10 19 41" src="https://user-images.githubusercontent.com/83866307/130115276-143706a2-af02-4dbb-9d78-13dcca141afd.png">

**Comment by SpectatorNan** [comment]
项目已经终止了，会产生封号的风险。已经提醒卸载了
