### ISSUE TITLE
更新后奔溃

### ISSUE THREAD

**Issue by asmc** [MustangYM/WeChatExtension-ForMac#158]
1

**Comment by MustangYM** [comment]
说下微信版本, 小助手版本, 崩溃场景

**Comment by ptthisdan** [comment]
WeChatPlugin-MacOS-1.7.5
WeChat Version 2.3.29 (13326)
微信启动时就崩，第一次登录时勾选了“自动同步消息”，后来怀疑同步的消息太多再登陆就把这个勾选去了，但还是崩

/Applications/WeChat.app/Contents/MacOS/WeChat already exists. Overwrite it? [y/n] y
LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat
./WeChatPlugin-MacOS-1.7.5/Other/UpdateRemoteControlCommandsPlist.py:43: DeprecationWarning: The readPlist function is deprecated, use load() instead
  remote_plist = plistlib.readPlist(PLIST_REMOTE_PATH)
./WeChatPlugin-MacOS-1.7.5/Other/UpdateRemoteControlCommandsPlist.py:50: DeprecationWarning: The readPlist function is deprecated, use load() instead
  local_plist = plistlib.readPlist(user_plist_dir)
./WeChatPlugin-MacOS-1.7.5/Other/UpdateRemoteControlCommandsPlist.py:52: DeprecationWarning: The writePlist function is deprecated, use dump() instead
  plistlib.writePlist(new_plist, user_plist_dir)

**Comment by MustangYM** [comment]
> WeChatPlugin-MacOS-1.7.5
> WeChat Version 2.3.29 (13326)
> 微信启动时就崩，第一次登录时勾选了“自动同步消息”，后来怀疑同步的消息太多再登陆就把这个勾选去了，但还是崩
> 
> /Applications/WeChat.app/Contents/MacOS/WeChat already exists. Overwrite it? [y/n] y
> LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
> Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat
> ./WeChatPlugin-MacOS-1.7.5/Other/UpdateRemoteControlCommandsPlist.py:43: DeprecationWarning: The readPlist function is deprecated, use load() instead
> remote_plist = plistlib.readPlist(PLIST_REMOTE_PATH)
> ./WeChatPlugin-MacOS-1.7.5/Other/UpdateRemoteControlCommandsPlist.py:50: DeprecationWarning: The readPlist function is deprecated, use load() instead
> local_plist = plistlib.readPlist(user_plist_dir)
> ./WeChatPlugin-MacOS-1.7.5/Other/UpdateRemoteControlCommandsPlist.py:52: DeprecationWarning: The writePlist function is deprecated, use dump() instead
> plistlib.writePlist(new_plist, user_plist_dir)

最新版2.3.0了, 你更更新下吧
