### ISSUE TITLE
休眠唤醒后崩溃问题

### ISSUE THREAD

**Issue by TomLiu-GitHub** [MustangYM/WeChatExtension-ForMac#16]
# 一休眠再打开就出现崩溃
![image](https://user-images.githubusercontent.com/32833966/57194365-bb430100-6f78-11e9-8f90-ac6b34784b9a.png)

**Comment by MustangYM** [comment]
> # 一休眠再打开就出现崩溃
> ![image](https://user-images.githubusercontent.com/32833966/57194365-bb430100-6f78-11e9-8f90-ac6b34784b9a.png)

是手机发送休眠命令后再打开就崩溃，还是电脑自己休眠后再打开崩溃？
