### ISSUE TITLE
yyds，江湖见！弱弱问下---》无法打开“insert_dylib”，因为无法验证开发者。

### ISSUE THREAD

**Issue by AugustPharmacist** [MustangYM/WeChatExtension-ForMac#1604]
### issue规范

设备类型：MacBookPro15,2
系统版本：版本11.5.2（版号20G95）
系统语言：zh-Hans
微信版本：[2021-09-03 23:21:40] v3.2.0.16 (19442) #1c905fa707
微信语言：zh-Hans
历史版本：[2021-08-07 17:31:08] v3.1.5.16 (18851) #9dfb2032a7
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(1440x900)/Retina

- 小助手版本 : 终章
- BUG描述 : 更新微信后，启动小助手脚本失败
- 操作场景 : 启动Install.sh脚本
- ![image](https://user-images.githubusercontent.com/42291120/133221614-fe478811-35d1-42ed-bcca-c160940acce8.png)

**Comment by yangjiao82** [comment]
> 找到解决方案了吗？

同问
