### ISSUE TITLE
最新的代码(恢复原有自动回复功能后) 下载后微信一直闪退

### ISSUE THREAD

**Issue by lipingcoding** [MustangYM/WeChatExtension-ForMac#162]
微信版本 2.3.29
小助手版本 680d356293a8d84581cb36ed608c71e4adc96119

**Comment by MustangYM** [comment]
> 微信版本2.3.29 
> 小助手版本[680d356](https://github.com/MustangYM/WeChatExtension-ForMac/commit/680d356293a8d84581cb36ed608c71e4adc96119)

能提供一下崩溃日志嘛

**Comment by lipingcoding** [comment]
check 了最新的代码 f38f2b9520fae50c8d2896099826de5d45b233b4, 可以正常使用了现在
