### ISSUE TITLE
今日微信被强制下线，这个优秀的插件迎来最后一天：感谢作者! 开源不死! 江湖再见!

### ISSUE THREAD

**Issue by LQHHHHH** [MustangYM/WeChatExtension-ForMac#1635]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by JianGuoPaPa** [comment]
同，我给别人以前用过一段时间，现在隔很久没有使用了的也被强制下线了

**Comment by sheatming** [comment]
我也是昨天下午还好好的，晚上也聊着。洗完澡在上微信就不行了。

**Comment by junglone** [comment]
我也是下午还好好的，晚上聊着聊着就掉线了，再上线的时候提示我被举报使用插件啥的让我认证。
可怕
tx 搞人还是有一套

**Comment by SallyOne** [comment]
我也是小伙伴们

**Comment by liubangde88** [comment]
有啥用，有心人真要用这个用两年前的源码随便改改就能用
