### ISSUE TITLE
这个新功能会消失。。。

### ISSUE THREAD

**Issue by xieao100** [MustangYM/WeChatExtension-ForMac#166]
![1577090256464](https://user-images.githubusercontent.com/15829332/71346527-13c81c80-25a3-11ea-85f6-2042a0eb2c20.jpg)

就是这个同步手机版标签页的东西。
第一次点击手机登录或者退出登录后再点击手机登录才会有。
如果登录过，杀死app再打开直接进入微信页面是不会有的。
估计是这个的功能只在点击登录后才去请求导致的。
系统、微信、助手均为最新版。
旧版本的微信、助手也存在此问题。
求修复，谢谢大佬~

**Comment by etzheng10** [comment]
同样问题，求修复大佬！！

**Comment by etzheng10** [comment]
关闭免认证登录就正常，如果打开免认证登录也能用就好了。
