### ISSUE TITLE
使用了大半年后，微信被冻结

### ISSUE THREAD

**Issue by ljwheyxy** [MustangYM/WeChatExtension-ForMac#1661]
作者您好！首先感谢您的程序！
前几个月我的微信大号突然被封禁，提示说使用了外挂，不过之后我立刻实名解封了，我无法确定是否是这个插件的缘故，但是那段时间不敢再用这个插件。现在心痒痒，准备接着使用！
我相信这个插件总体还是安全的，不过我是微信重度用户，可能也是被识别而后封禁的原因。
希望作者能够分析一下此插件是否有封禁的风险，风险大小如何！
感谢！

**Comment by TUO1500** [comment]
这个很多使用此插件的微信号在去年78月被大规模封了
