### ISSUE TITLE
M1 Pro 14 寸的啥时候支持,直接现实微信打不开

### ISSUE THREAD

**Issue by mayonghua** [MustangYM/WeChatExtension-ForMac#1664]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by BenjaminX** [comment]
还没提供 ARM64 架构支持，估计要等了。

**Comment by zhinianling** [comment]
访达->应用程序->微信->右键->显示简介->通用->使用Rosetta打开勾选上就可以了
![image](https://user-images.githubusercontent.com/23735978/179892196-0d37b596-92ab-4162-b3f4-4c0d94f3d682.png)

**Comment by BenjaminX** [comment]
> 访达->应用程序->微信->右键->显示简介->通用->使用Rosetta打开勾选上就可以了
> ![image](https://user-images.githubusercontent.com/23735978/179892196-0d37b596-92ab-4162-b3f4-4c0d94f3d682.png)

Rosetta2 转义肯定是可以的，直接能支持 ARM 架构更好嘛，没有效能损失。

**Comment by MustangYM** [comment]
@BenjaminX 等我啥时候上M1的时候再适配
