### ISSUE TITLE
弹窗报错

### ISSUE THREAD

**Issue by magisk317** [MustangYM/WeChatExtension-ForMac#1674]
### issue规范
- MacOS版本 : 12.5 Beta版(21G5027d)
- 微信版本 : Version. 3.3.0 (20989) Beta 10
- 小助手版本 : 3.3.1 安全版
- BUG描述 : 不时弹窗报错
- 操作场景 : 微信启动后, 不需任何操作
- 方便的话提供日志, 截图或者视频(可选)

![image](https://user-images.githubusercontent.com/93979778/169224830-03bbf56a-5736-4de6-8f5a-1726aab3947d.png)
![image](https://user-images.githubusercontent.com/93979778/169224858-d3868f28-4ec9-4ed6-aeeb-883081cf9d47.png)

**Comment by magisk317** [comment]
更换版本已经搞定，close issue

**Comment by HSczy** [comment]
请问您更新的版本是3.3.1还是3.4.0。如果是3.3.1的话能否给个下载链接
