### ISSUE TITLE
程序员对这些盈利为目的的网站进行友好访问啊！

### ISSUE THREAD

**Issue by uu-xixi** [MustangYM/WeChatExtension-ForMac#1676]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/43702671/169456701-ad05cec3-23c0-4292-9625-fb0ae2cf1a31.png">

- 日常问候：https://www.imacapp.net/
- 
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/43702671/169456947-5529f912-a2f5-4d77-84c7-bedfbdb32472.png">

<img width="716" alt="image" src="https://user-images.githubusercontent.com/43702671/169469794-b64e2ade-1d46-460e-a0ba-a433744a086c.png">

**Comment by tanghengvip** [comment]
开源免费的拿来卖，D死他
