### ISSUE TITLE
微信3.3.1配最新的asset无法使用

### ISSUE THREAD

**Issue by qveinole** [MustangYM/WeChatExtension-ForMac#1678]
### issue规范
- MacOS版本 : 12.4
- 微信版本 : 3.3.1
- 小助手版本 : 3.3.1
- BUG描述 : 无法打开，重新签名后显示意外退出。

![Uploading image.png…]()

<img width="372" alt="image" src="https://user-images.githubusercontent.com/33279115/169807979-964d75a2-6887-4f94-8cb6-0b775e638203.png">

- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by UPennftz** [comment]
我是MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports) i5
系统OS12.3.1 (21E258)
其余一样一切正常
