### ISSUE TITLE
m1 微信版本3.3.1 小助手版本3.3.1 安装后打不开有解吗？

### ISSUE THREAD

**Issue by mooneee** [MustangYM/WeChatExtension-ForMac#1679]
### issue规范
- MacOS版本 : 12.4
- 微信版本 : 3.3.1
- 小助手版本 : 3.3.1
- BUG描述 : 安装助手后微信打不开
- 操作场景 : 如题
<img width="266" alt="image" src="https://user-images.githubusercontent.com/58715815/169876938-f7335064-f014-47d9-bc31-df59e5312042.png">

**Comment by bulusite** [comment]
MacOS版本 : 10.15.7
微信版本 : 3.3.1
小助手版本 : 3.3.1

目前小号测试两天,无异常

**Comment by iocool** [comment]
解决办法之前大佬发过

codesign --sign - --force --deep /Applications/WeChat.app

重新签名一下,如果可以打开,只是报错,在 Applications 中右键,勾选 使用 Rosetta 打开

**Comment by HSczy** [comment]
有3.3.1版本的微信可以提供一下么？

**Comment by iscaswang** [comment]
我昨天在appstore上更新的微信，虽然appstore上看着版本是3.4，但是更新完显示是3.3.1，可以使用这个插件

**Comment by mooneee** [comment]
> 有3.3.1版本的微信可以提供一下么？

https://mydown.yesky.com/macsoft/99890696/versions/  版本大全，我安装了3.1.5，问题解决了
