### ISSUE TITLE
【请求功能新增】自动转发

### ISSUE THREAD

**Issue by yt2639** [MustangYM/WeChatExtension-ForMac#168]
感谢作者继续维护这个插件！❤️❤️
想请问能不能新增一个小功能：`自动转发`
现在有一个功能叫做`自动回复`，里面有一个选项叫做`开启特定回复`。
感觉只需要在此基础上让大家指定某(些)人或某(些)群，然后对指定的对象所发送的内容进行自动转发，转发给指定的某(些)人或某(些)群（此部分已经在`开启特定回复`中有实现）。
谢谢作者！！

使用这个功能其实是因为有很多人可能会有两个微信，但是不能同时登录查看消息。
本来可以用itchat的python接口实现自动转发的(itchat使用了web微信端口登录)，但是微信总是禁用web微信的端口，我查了好久好久都没查到怎么解决。然后一旦web微信端口被封，就只能通过mac微信登录了。于是想请求作者新增这个`自动转发`功能。

非常感谢❤️！ @MustangYM

**Comment by yt2639** [comment]
或者能告诉我应该是改哪一个文件才能新增这个功能呢？
本机MacOS 10.14.6  XCode 11.2.1
能看懂C和C++  会python  感觉这个可能可以自己试一试改  但是不知道改哪个文件🤦‍♀️

**Comment by Wetoria** [comment]
emmmm，这个功能我自己加了一个😂

**Comment by mourenli** [comment]
> emmmm，这个功能我自己加了一个😂
> https://juejin.im/post/5d6bda81f265da03c23eecb7基于TK的原项目自动转发，并且还能在第二个帐户回复回复：来回复消息

我是一个小白 请问我要如何才能实现这个功能呢？

**Comment by Wetoria** [comment]
> > emmmm，这个功能我自己加了一个😂
> > [https://juejin.im/post/5d6bda81f265da03c23eecb7基于TK的原项目自动转发，并且还能在第二个帐户回复回复：来回复消息](https://juejin.im/post/5d6bda81f265da03c23eecb7%E5%9F%BA%E4%BA%8ETK%E7%9A%84%E5%8E%9F%E9%A1%B9%E7%9B%AE%E8%87%AA%E5%8A%A8%E8%BD%AC%E5%8F%91%EF%BC%8C%E5%B9%B6%E4%B8%94%E8%BF%98%E8%83%BD%E5%9C%A8%E7%AC%AC%E4%BA%8C%E4%B8%AA%E5%B8%90%E6%88%B7%E5%9B%9E%E5%A4%8D%E5%9B%9E%E5%A4%8D%EF%BC%9A%E6%9D%A5%E5%9B%9E%E5%A4%8D%E6%B6%88%E6%81%AF)
> 
> 我是一个小白 请问我要如何才能实现这个功能呢？

1.自行百度`pod install`，并解决其中遇到的问题
2.耐心看完我写的问题

做到这些，你在你的本地机器上可以实现转发的功能。剩下的自己折腾吧。

**Comment by mourenli** [comment]
好的 我尝试下 谢谢

**Comment by HackerBigJoe** [comment]
顶上来，很实用的功能，希望能官方支持！

**Comment by Wetoria** [comment]
这个功能我集成进小助手了，各位可以看看。@MustangYM 是不是可以关闭这个issue了？
