### ISSUE TITLE
mpb14 M1pro 不兼容arm64?

### ISSUE THREAD

**Issue by foruniverse** [MustangYM/WeChatExtension-ForMac#1693]
### issue规范
- MacOS版本 : 12.4
- 微信版本 : 3.3.1
- 小助手版本 : 2.9.2
- BUG描述 : 启动闪退 查询错误日志发现不兼容arm64?
- 操作场景 : 下载2.9.3手动安装, 对微信签名后, 3.3.1 微信就无法启动了
- 方便的话提供日志, 截图或者视频(可选)
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/32241199/175162126-0ce7d5fa-69f9-4d09-8024-3dc11a41422a.png">

**Comment by WPF0414** [comment]
都不维护了就别用这个了,为啥不换一个呢

**Comment by MustangYM** [comment]
@WPF0414 没看到发新版本？另外这个问题已经解答过，不再赘述。
