### ISSUE TITLE
请问什么时候可以支持下吗

### ISSUE THREAD

**Issue by Cheung0927** [MustangYM/WeChatExtension-ForMac#1695]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by Cheung0927** [comment]
请问什么时候大佬可以支持下m1

**Comment by MustangYM** [comment]
M1一直支持的
