### ISSUE TITLE
关闭窗口在打开窗口，窗口失去焦点

### ISSUE THREAD

**Issue by xaopohi** [MustangYM/WeChatExtension-ForMac#1697]
MacOS版本 : 12.2.1 (21D62)
 微信版本 : 3.4.1(21938)
-小助手版本 : 3.4.1安全版
- BUG描述 : 快捷键关闭窗口后，在使用快捷键打开，会卡顿很久，并且点不了聊天框，菜单栏的菜单也显示空白
- 操作场景 : 关闭窗口在打开窗口
[文件太大了无法上传，请点击链接观看视频](https://www.aliyundrive.com/s/QDMtkfnnZjC)

**Comment by GaoGuohao** [comment]
+1

**Comment by zwzheng45** [comment]
小助手版本为3.4.1
微信3.5.0有这个问题
升级到3.5.5后问题消失
不知道是不是和微信本身有关。

**Comment by xaopohi** [comment]
升级到3.5.5后问题消失
