### ISSUE TITLE
用xcode编译 报错  请问怎么解决

### ISSUE THREAD

**Issue by reechou** [MustangYM/WeChatExtension-ForMac#17]
/clang:-1: linker command failed with exit code 1 (use -v to see invocation)

![image](https://user-images.githubusercontent.com/949857/57501097-b8e5fb80-7318-11e9-99fe-3e4f34d6d504.png)
![Uploading image.png…]()

**Comment by MustangYM** [comment]
> /clang👎 linker command failed with exit code 1 (use -v to see invocation)

编译白色的workSpace文件而不是蓝色proj文件,
