### ISSUE TITLE
今天账号被封了

### ISSUE THREAD

**Issue by mzzxuyi** [MustangYM/WeChatExtension-ForMac#170]
说是因为使用了未被授权的微信插件，然后账号被封了

**Comment by mzzxuyi** [comment]
请问各位有人遇到这个问题了吗

**Comment by a645162** [comment]
请问你微信什么版本，插件什么版本？这么恐怖吗？

**Comment by a645162** [comment]
我看你的github的star，你是不是Android用了防撤回插件了？

**Comment by sumous** [comment]
我的是Version. 2.3.24 (12246)，今天早上退出了三次，后面就没有在退出了

**Comment by MustangYM** [comment]
Mac的小助手暂时没有迹象显示会导致封号，放心使用
