### ISSUE TITLE
m1登陆的时候会爆m_arrSession 错误

### ISSUE THREAD

**Issue by pzp12** [MustangYM/WeChatExtension-ForMac#1702]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
明显的api不匹配导致的版本错误，认真看release所匹配的版本

**Comment by liubangde88** [comment]
因为版本不对，最新的版本里MMSessionMgr 取消了arrSession。 
接口应该增加@property(retain, nonatomic) MMSessionStorage *m_storage;  
然后修改 NSMutableArray *arrSession  为
  NSMutableArray *arrSession = sessionMgr.m_storage.getAllSessionInfo;
然后重新编译后搞定

**Comment by MustangYM** [comment]
是的
