### ISSUE TITLE
M1运行3.4.1闪退的解决方案

### ISSUE THREAD

**Issue by vulntor** [MustangYM/WeChatExtension-ForMac#1715]
亲测M1 3.4.1微信+3.4.1助手 方式1安装可用
闪退是因为助手不支持arm架构，而微信已经内置同时支持x86_64 和arm ,默认打开优先走了arm架构所以报错，闪退时点开report可窥一二。
在terminal使用以下命令运行微信即可,我是英文系统,中文系统可能是 微信.app
`arch -arch x86_64  /Applications/WeChat.app/Contents/MacOS/WeChat`

**Comment by xiaomikaiyuan** [comment]
> 

我的M1安装小助手闪退，然后看到你这个解决方案，受启发，我想到了另一个方法：应用程序>选择微信>右键>显示简介>勾选 使用roseate打开 即可

**Comment by vulntor** [comment]
> > 
> 
> 我的M1安装小助手闪退，然后看到你这个解决方案，受启发，我想到了另一个方法：应用程序>选择微信>右键>显示简介>勾选 使用roseate打开 即可

这个方法更方便了 赞

**Comment by MustangYM** [comment]
rosetta, 随便翻一下issue便知.
