### ISSUE TITLE
感谢开发者

### ISSUE THREAD

**Issue by magisk317** [MustangYM/WeChatExtension-ForMac#1720]
### 先上图：
![origin_img_v2_b42d8377-78f8-4f47-8a4a-3c038c31876l](https://user-images.githubusercontent.com/93979778/188053941-e13472e9-8919-4f0f-8c20-258983636432.png)
### 再说事
我们的开发者简直是人间天使，别人提了个建议，问下这个功能怎么关闭，然后我附和了两句，因为我个人也不太喜欢这个功能，你可以加，没人会说什么，至少搞个开关吧？结果呢，口吐芬芳，然后踢人了事，我就不明白了，这么明显费力不讨好的事情，难道他看不出来？果不其然，今天更新，开关就加上了，有图为证：
![OOrXeTfEbv](https://user-images.githubusercontent.com/93979778/188054268-e76f1614-bb0f-42ad-85eb-c1e5c94f3b39.jpg)
你说何必呢？这跟聊天记录里我说的最后一句话对比一看，嗨呀，我这老脸是没地放了
### 其他
QQ踢出截图：
![middle_img_v2_9591438c-7812-4692-a497-9fbbe24c99al](https://user-images.githubusercontent.com/93979778/188054329-bfb9e042-b49a-4f87-95bc-3bc13019e9ac.png)
TG踢出截图：
![gk0sl4hIge](https://user-images.githubusercontent.com/93979778/188054356-d05472b3-1143-4497-8181-97deda83bedc.jpg)
频道禁止评论截图：
![dRqN4CCSLJ](https://user-images.githubusercontent.com/93979778/188054391-f129ddb9-4ec3-4b0e-8bc3-5ace782c419c.jpg)
微信踢出截图没有了，后续有空补上
### 最后
如果我说的，做的不对，我为我自己的行为道歉，我并不觉得我提个建议，就值得开发者全平台封杀，小助手是第一个连TG都给我拉黑的，之前还真没遇到过，真的感谢开发者，也希望其他人能看见这段故事吧

**Comment by magisk317** [comment]
哦，二群也被踢了，不仅不思悔改，还给你脸了是吧？揭你伤口了？脸没地放放了？
![image](https://user-images.githubusercontent.com/93979778/188057864-fa876695-3fbd-44e1-92e2-74a949d2734d.png)

**Comment by MustangYM** [comment]
首先这个项目, 我有在使用说明里写君子协定, 正因为你们这种傻逼太多, 导致开源难以推进, 个个都觉得自己是少爷, 都要按照你们的想法前进, 易出现的问题我已经全部写在说明书里了, 而且公告置顶, 但是你这种傻逼就是不会去看, 不会去阅读, 永远都伸手党, 以为自己是上帝, 我收钱了吗? 你这种巨婴我见一个踢一个, 见一个拉黑一个, 爱j8用不用, 傻逼玩意.
![image](https://user-images.githubusercontent.com/21478687/188355332-2e02a1ee-b379-49df-9a21-c5efa2740dd8.png)
![image](https://user-images.githubusercontent.com/21478687/188355354-d367a4b5-ad55-4d19-a61c-6169bbd84a6c.png)

**Comment by chenshuaikang** [comment]
雪崩时，没有一片雪花是无辜的。

且用且珍惜，好用就用，不好用就卸载。

**Comment by MustangYM** [comment]
这种傻逼永远不知道我们这些幕后顶了多少压力重启这个项目, 我们测试了多少微信号, 我们作了多少努力, 上来就是这里不满意, 那里不舒服, 回答过的问题反复问反复提, 置顶不看, 说明书打包到zip里也不看 ! 这不是个商业产品, 这是我们施舍给你用的, 你要记住, 是施舍! 爱鸡巴用不用, 不用就滚.

**Comment by magisk317** [comment]
> @magisk317 首先这个项目, 我有在使用说明里写君子协定, 正因为你们这种傻逼太多, 导致开源难以推进, 个个都觉得自己是少爷, 都要按照你们的想法前进, 易出现的问题我已经全部写在说明书里了, 而且公告置顶, 但是你这种傻逼就是不会去看, 不会去阅读, 永远都伸手党, 以为自己是上帝, 我收钱了吗? 你这种巨婴我见一个踢一个, 见一个拉黑一个, 爱j8用不用, 傻逼玩意. ![image](https://user-images.githubusercontent.com/21478687/188355332-2e02a1ee-b379-49df-9a21-c5efa2740dd8.png) ![image](https://user-images.githubusercontent.com/21478687/188355354-d367a4b5-ad55-4d19-a61c-6169bbd84a6c.png)

图片1，没人试图教你做交互，只不过说一下这个功能而已（你认为是吐槽也好，建议也罢，无所谓），如果这都不让讨论，那建群的意义何在？真就是群主夸夸群？与其踢出，不如解散

图片2，你只是解决了误触问题（而我，说实话，从来没有误触过），我只是希望有个开关，仅此而已，事实是，你加了开关，却把我踢了？

再说说这个功能，我知道是别人无偿提供的，我也没浪费的意思，你总觉得点击之后不发出去留在输入框，会有人总在那点，浪费服务器资源，然而实际情况是，不管直接发出去，还是放在输入框，你限制的是时间间隔，难不成，我写一个几秒钟发一个脚本不浪费接口资源？我正常使用放在输入框考虑发不发会浪费资源？综上，浪不浪费资源，跟直不直接发出去没半毛钱关系

最后再说说你这个回复，撇开问题，就你这张口闭口不是生殖器就是滚，你的老师和父母没教你做人，只教你做事了？空有一身技术，思想不对，越有文化越反动，这句话送给你正合适

**Comment by magisk317** [comment]
> 雪崩时，没有一片雪花是无辜的。
> 
> 且用且珍惜，好用就用，不好用就卸载。

是啊，我卸载了软件，而纵观作者意图，不仅仅是希望你卸载，而是希望你在各个地方滚出他的视野

不过，能遇到个说人话也不容易，看了这么多comment，都不堪入目，唉
