### ISSUE TITLE
能不能加个显示群成员微信号的选项

### ISSUE THREAD

**Issue by WolfMobileDev** [MustangYM/WeChatExtension-ForMac#1722]
MacOS版本 : 12.5
微信版本 : 3.4.1
小助手版本 : 3.4.7
操作场景 :
Mac老版本的微信无论是否是好友都显示群员微信号，新版本不显示非好友的微信号了，能不能做个选项可以显示

**Comment by MustangYM** [comment]
em...私有版有加, 暂时并未打算放出来

**Comment by WolfMobileDev** [comment]
有放出计划吗，这个功能太重要了
