### ISSUE TITLE
Tg 群没了吗？

### ISSUE THREAD

**Issue by CoderDawnKing** [MustangYM/WeChatExtension-ForMac#1725]

**Comment by MustangYM** [comment]
https://t.me/WeChatExtension

**Comment by CoderDawnKing** [comment]
> https://t.me/WeChatExtension
@MustangYM 加不进去啊老哥？是把我踢了吗?
<img width="800" alt="image" src="https://user-images.githubusercontent.com/16617921/189846183-169b6054-84c2-4171-9a3a-b8f6fc31a825.png">

**Comment by CoderDawnKing** [comment]
我每天都有在签到啊，为什么被踢了？
