### ISSUE TITLE
M1 MacMini 下安装了之后无法启动微信.app

### ISSUE THREAD

**Issue by Daydaylw3** [MustangYM/WeChatExtension-ForMac#1728]
### issue规范
- Mac 型号：Mac mini (M1, 2020)
- MacOS版本 : 12.5 (21G72)
- 微信版本 : Version. 3.5.5 (23481)
- 小助手版本 : 2022年9月13日的master分支的版本
- BUG描述 : 执行 Install.sh 之后运行微信显示无法打开
- 操作场景 : 执行 Install.sh 之后运行微信显示无法打开
- ![image](https://user-images.githubusercontent.com/38597251/189861129-9a76aa1e-daba-4c71-97e7-145d1b8d6f62.png)

**Comment by kubai087** [comment]
使用rosseta打开即可

**Comment by Daydaylw3** [comment]
> 

请问这个是啥呢? rosseta，有无使用教程呢~

**Comment by kubai087** [comment]
> 

右键微信APP，选择【显示简介】，然后勾选使用rosseta打开

**Comment by Daydaylw3** [comment]
> Reference in new i

感谢！搞定了~
