### ISSUE TITLE
好像函数名封装有问题

### ISSUE THREAD

**Issue by Wu-J** [MustangYM/WeChatExtension-ForMac#173]
自动回复、转账金额等有些功能好像没有封装中文名称，直接显示了函数名[assistant.msgInfo.wcpay.transfer ] 
虽然功能没啥影响，就是怪别扭的233

**Comment by MustangYM** [comment]
> 自动回复，转账金额等某些功能好像没有封装的中文名称，直接显示了函数名[assistant.msgInfo.wcpay.transfer]
> 虽然功能没啥影响，就是怪别扭的233

已解决
