### ISSUE TITLE
搜索栏

### ISSUE THREAD

**Issue by AzraelDrew** [MustangYM/WeChatExtension-ForMac#1731]
### issue规范
- MacOS版本 : 12.6
- 微信版本 : 3.5.5
- 小助手版本 : 3.4.1
- BUG描述 : 迷离模式下搜索栏搜索时为透明而不是模糊
- 操作场景 : 迷离模式下搜索栏搜索时
- ![截屏2022-09-21 10 16 00](https://user-images.githubusercontent.com/65553612/191399481-85608092-b80d-4a5a-b4f5-d4a4ca13755a.jpg)

**Comment by MustangYM** [comment]
进tg群记得更新, 都3.4.7.1了...

**Comment by AzraelDrew** [comment]
好的
