### ISSUE TITLE
M1机型安装后直接报错

### ISSUE THREAD

**Issue by sandomingo** [MustangYM/WeChatExtension-ForMac#1733]
### Issue 1733
- MacOS版本 : 12.5.1
- 微信版本 : 3.5.5
- 小助手版本 : 3.4.1
- BUG描述 : 点击窗口报错
- 操作场景 : 微信启动时直接报错，看起来应该是对于M1芯片的适配问题（机型：MacBook Pro (14-inch, 2021)）

Reason: tried: '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '' (no such file), 

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/2668791/191541776-fa03ecf3-748c-4e69-9c3c-10ff87833351.png">

**Comment by MustangYM** [comment]
rosetta打开
