### ISSUE TITLE
【请求功能新增】不要拦截自己撤回的消息

### ISSUE THREAD

**Issue by Saafo** [MustangYM/WeChatExtension-ForMac#174]
RT，现在连撤回自己的消息都会被拦截，就用不了再次编辑的功能。很麻烦，现在每次撤回自己消息想重新编辑的时候还得把撤回功能手动关掉。

**Comment by MustangYM** [comment]
> RT，现在连撤回自己的消息都会被拦截，就用不了再次编辑的功能。很麻烦，现在每次撤回自己消息想重新编辑的时候还得把撤回功能手动关掉。

只是你自己能看到而已

**Comment by Saafo** [comment]
> > RT，现在连撤回自己的消息都会被拦截，就用不了再次编辑的功能。很麻烦，现在每次撤回自己消息想重新编辑的时候还得把撤回功能手动关掉。
> 
> 只是你自己能看到而已

![image](https://user-images.githubusercontent.com/46736350/71572362-a58ed700-2b19-11ea-9a60-878a49ac0f1e.png)
我的yi's意思是我在自己这里也不希望拦截，想用到这个`edit`

**Comment by MustangYM** [comment]
> > > RT，现在连撤回自己的消息都会被拦截，就用不了再次编辑的功能。很麻烦，现在每次撤回自己消息想重新编辑的时候还得把撤回功能手动关掉。
> > 
> > 
> > 只是你自己能看到而已
> 
> ![image](https://user-images.githubusercontent.com/46736350/71572362-a58ed700-2b19-11ea-9a60-878a49ac0f1e.png)
> 我的意思是我在自己这里也不希望拦截，想用到这个`edit`

没有做的意义

**Comment by MustangYM** [comment]
> > > RT，现在连撤回自己的消息都会被拦截，就用不了再次编辑的功能。很麻烦，现在每次撤回自己消息想重新编辑的时候还得把撤回功能手动关掉。
> > 
> > 
> > 只是你自己能看到而已
> 
> ![image](https://user-images.githubusercontent.com/46736350/71572362-a58ed700-2b19-11ea-9a60-878a49ac0f1e.png)
> 我的意思是我在自己这里也不希望拦截，想用到这个`edit`

设置中有不撤回自己消息的选项

**Comment by MustangYM** [comment]
> > > RT，现在连撤回自己的消息都会被拦截，就用不了再次编辑的功能。很麻烦，现在每次撤回自己消息想重新编辑的时候还得把撤回功能手动关掉。
> > 
> > 
> > 只是你自己能看到而已
> 
> ![image](https://user-images.githubusercontent.com/46736350/71572362-a58ed700-2b19-11ea-9a60-878a49ac0f1e.png)
> 我的意思是我在自己这里也不希望拦截，想用到这个`edit`

设置中有不撤回自己消息的选项
