### ISSUE TITLE
已经打开任何来源还是出现微信无法打开

### ISSUE THREAD

**Issue by AzraelDrew** [MustangYM/WeChatExtension-ForMac#1742]
### issue规范
- MacOS版本 : 13.0

- 小助手版本 : 3.4.7
- BUG描述 : 已经打开任何来源还是出现微信无法打开
<img width="251" alt="image" src="https://user-images.githubusercontent.com/65553612/198816103-b4818a75-dacb-4f94-bb02-c753e4053be8.png">
<img width="470" alt="image" src="https://user-images.githubusercontent.com/65553612/198816113-6af2eb72-df52-4f70-8b38-3af4866c6fd0.png">

**Comment by MustangYM** [comment]
baidu
