### ISSUE TITLE
消息搜索框bug

### ISSUE THREAD

**Issue by cuifeiran** [MustangYM/WeChatExtension-ForMac#1748]
- MacOS版本 : MacBook Pro14 M1pro芯片 12.3-12.6.1
- 微信版本 : 3.3.0-3.6.0
- 小助手版本 : 3.3.1-3.4.1
- BUG描述 : 设置皮肤模式下，搜索框搜索消息时毛玻璃效果消失，检索结果与好友消息列表重叠。经测试上述版本均有此问题
- 操作场景 : 微信启动后, 设置迷离模式或其他皮肤，然后搜索消息
- 方便的话提供日志, 截图或者视频(可选)

![image](https://user-images.githubusercontent.com/26172548/200884106-a9966a0d-59e0-4253-a61d-608d8c5fe23b.png)

**Comment by MustangYM** [comment]
tg新版早就修复了

**Comment by cuifeiran** [comment]
tg群号多少呀😳
