### ISSUE TITLE
突然之后安装就弹出崩溃，并微信提示修复

### ISSUE THREAD

**Issue by liuzhe101** [MustangYM/WeChatExtension-ForMac#1757]
### issue规范
- MacOS版本 : 13.0.1
- 微信版本 : 3.6.0
- 小助手版本 : 十月份下载的最新版本
- BUG描述 : 点击窗口闪退
- 操作场景 : 昨天之前 13.0.1 系统，更新微信 3.6.0 后从新安装后即可使用，但是昨天之后 突然出现崩溃 ，至此从新安装在打开都不行。
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
什么叫十月下载的最新版?

**Comment by liuzhe101** [comment]
> Owner

助手版本3.4.1

**Comment by MustangYM** [comment]
从未说过3.4.1适配3.6微信, 最新版在tg群, 地址readme顶部

**Comment by liuzhe101** [comment]
> 从未说过3.4.1适配3.6微信, 最新版在tg群, 地址readme顶部

大佬我翻不出去啊。进不去啊
