### ISSUE TITLE
近期有封号的吗

### ISSUE THREAD

**Issue by corgy-w** [MustangYM/WeChatExtension-ForMac#1762]
### issue规范
- MacOS版本 : 13.0.1 (22A400)
- 微信版本 : 3.6.0
- 小助手版本 : 3.4.1

刚安装想问一下大家最近封号频繁吗 刚上车不想被弄下来 微信还挺重要的

**Comment by Marcus9530** [comment]
没封号，就是别更新微信版本，最新版本微信已经不让使用这个插件了。。有点难受
