### ISSUE TITLE
每次点开微信都会弹窗

### ISSUE THREAD

**Issue by saki990423** [MustangYM/WeChatExtension-ForMac#1763]
### issue规范
- MacOS版本 : 13.0.1
- 微信版本 :3.6.1
- 小助手版本 : 3.4.1
- BUG描述 : 每次点开微信弹窗
- 操作场景 : 微信最小化后，再次打开微信弹窗
<img width="264" alt="截屏2022-12-02 上午11 39 44" src="https://user-images.githubusercontent.com/56117746/205210596-e933fefd-1ecb-47de-b180-ca2e332509a0.png">

**Comment by lfcypo** [comment]
关闭“免认证登陆”并使用工具对微信绕过签名后问题出现的概率降低
