### ISSUE TITLE
程序崩溃异常

### ISSUE THREAD

**Issue by nf1994** [MustangYM/WeChatExtension-ForMac#1764]
### issue规范
- MacOS版本 : 11.0.1
- 微信版本 : 3.6.1
- 小助手版本 : 3.4.1
- BUG描述 : 运行一段时间后程序崩溃
- 操作场景 : 微信启动后，就正常使用，无特殊场景就突然崩溃。最近升级了微信重新安装了最新的小助手才出现这个情况
- 日志如下：
<img width="724" alt="image" src="https://user-images.githubusercontent.com/14307059/205442229-57133540-0ccf-4bf3-8078-54832d87ef11.png">
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/14307059/205442246-3d1fd9be-05df-4938-a2ed-caac4189c939.png">
<img width="975" alt="image" src="https://user-images.githubusercontent.com/14307059/205442258-18a2c48f-b05c-4e1e-96fc-f914ea685619.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/14307059/205442269-14405256-b254-40b0-8520-a2c2e45b631b.png">
后面还有很多不知道怎么贴上来

**Comment by MustangYM** [comment]
谁给你说这个版本小助手支持3.6.1微信
