### ISSUE TITLE
无法截图

### ISSUE THREAD

**Issue by dw-zhang** [MustangYM/WeChatExtension-ForMac#1765]
### issue规范
- MacOS版本 : 12.6
- 微信版本 : Version. 3.6.1 (24205)
- 小助手版本 : V 3.6.1
- BUG描述 : 无法截图
- 操作场景 :  截图的时候提示前往设置，设置了配置好了还是一样的
- 
![image](https://user-images.githubusercontent.com/62228059/206422369-f2d9f9cd-b861-4d07-bd49-73db84761ef8.png)

**Comment by MustangYM** [comment]
我不信.

**Comment by weber-cd** [comment]
我也一样的问题呢
