### ISSUE TITLE
图片撤回后微信直接崩溃了

### ISSUE THREAD

**Issue by foxwithboy** [MustangYM/WeChatExtension-ForMac#1766]
MacOS版本 : 12.4
微信版本 :3.6.1
小助手版本 : 3.4.1
BUG描述 : 每次点开微信崩溃
操作场景 :  用小号发送一张图片后撤回，微信就崩溃了
@MustangYM 

![image](https://user-images.githubusercontent.com/12912755/206647903-7275e908-1946-48b5-bd54-905c311944e9.png)

**Comment by MustangYM** [comment]
tg群有新版, 早已解决此问题, 自取.
