### ISSUE TITLE
发现问题，如截图

### ISSUE THREAD

**Issue by Dylan-Du** [MustangYM/WeChatExtension-ForMac#1767]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)
<img width="260" alt="image" src="https://user-images.githubusercontent.com/59590156/207495863-bcab319f-7d8a-4d09-941c-8678c9d1ce9a.png">

**Comment by kilvn** [comment]
你这版本号啥的都没写，提了issue有啥用

**Comment by Dylan-Du** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        设备类型：MacBookPro15,1系统版本：版本13.0.1（版号22A400）系统语言：zh-Hans微信版本：[2022-12-16 14:38:58] v3.6.2.17 (24456) #923999e2ed p_0微信语言：zh-Hans历史版本：[2022-11-17 10:29:59] v3.6.1.17 (24205) #61c0e3be6c
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                347656408
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年01月3日 11:54
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [MustangYM/WeChatExtension-ForMac] 发现问题，如截图 (Issue #1767)
        
      
    
  
  

你这版本号啥的都没写，提了issue有啥用



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
