### ISSUE TITLE
[Feature]能否支持ChatGPT接入，以完善自动回复！

### ISSUE THREAD

**Issue by C-starm** [MustangYM/WeChatExtension-ForMac#1768]
### issue规范
- MacOS版本 : 13.0 (22A380)
- 微信版本 : [2022-12-16 14:38:58] v3.6.2.17 (24456) #923999e2ed p_0
- 小助手版本 : V3.4.1
- BUG描述 :  能否支持ChatGPT接入，以完善自动回复！
- 操作场景 : 不涉及
- 方便的话提供日志, 截图或者视频(可选)： 不涉及

**Comment by MustangYM** [comment]
考虑过，目前并不适合
