### ISSUE TITLE
AI群自动回复，非@回复，也进行回复。

### ISSUE THREAD

**Issue by wdkGitHub** [MustangYM/WeChatExtension-ForMac#177]
设置群ai自动回复，提示只对此群@此群的进行回复，实际确是非图片发言都进行回复

微信版本： 2.3.29 (13326)
插件版本：2.3.0

**Comment by MustangYM** [comment]
> 设置群ai自动回复，提示只对此群@此群的进行回复，实际确是非图片发言都进行回复
> 
> 微信版本： 2.3.29 (13326)
> 插件版本：2.3.0

@这个符号没有别的意思, 只是凸显群名字的一个标记而已, 只要能识别的文字消息都会回复
