### ISSUE TITLE
下载完小助手后提示“微信”已损坏，无法打开。 您应该将它移到废纸篓。这个怎么解决

### ISSUE THREAD

**Issue by LIJIAMING1339** [MustangYM/WeChatExtension-ForMac#1779]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
#1780
