### ISSUE TITLE
小助手安装失败 No such file or directory

### ISSUE THREAD

**Issue by Kerwin-Ma** [MustangYM/WeChatExtension-ForMac#1780]
### issue规范
- MacOS版本 : 13.0.1 (22A400)
- 微信版本 : 3.6.2 (24456)
- 小助手版本 : 3.4.1
- BUG描述 : 使用三种安装方式，均无法安装小助手
- 操作场景 : 下载安装包或者 omw 方式安装小助手都 失败
- 方便的话提供日志, 截图或者视频(可选)

- 下载安装包安装失败
![install-error pic](https://user-images.githubusercontent.com/33769470/217178149-47e83038-361f-41a8-9610-a592dbd4bc08.jpg)

- omw 安装截图
 ![omw-install pic](https://user-images.githubusercontent.com/33769470/217177635-7869d88a-8222-4626-a345-27372f9b76f3.jpg)

- omw load 失败
![omw-load pic](https://user-images.githubusercontent.com/33769470/217177960-89e953a4-3fa3-4862-bb93-fc56fd6f3809.jpg)

**Comment by MustangYM** [comment]
readme中有tg群, 进去取最新的

**Comment by fingershuaib** [comment]
> 

readme中没有啊

**Comment by Kerwin-Ma** [comment]
> 

README中的tg群，群里有最新的安装包
