### ISSUE TITLE
【生活插件】能否不自动发送？

### ISSUE THREAD

**Issue by KingAmo** [MustangYM/WeChatExtension-ForMac#1781]
### issue规范
- MacOS版本 : 13.1
- 微信版本 : 3.6.2
- 小助手版本 : 3.6.2
---
点击`生活插件`的菜单按钮，消息自动发出去了，能否先把消息放在输入框，用户判断信息有用再手动发送消息？

**Comment by MustangYM** [comment]
每次调用都要花钱的, 当然这不需要大家付款, @小白同学自费买的接口. 所以不可能让你有"挑选"这个行为.
