### ISSUE TITLE
拦截到崩溃

### ISSUE THREAD

**Issue by taochangle** [MustangYM/WeChatExtension-ForMac#1783]
### issue规范
- MacOS版本 : 13.2
- 微信版本 : 3.6.2
- 小助手版本 : 3.4.1
- BUG描述 : 点击窗口闪退
- 操作场景 : 收到微信消息后，直接收到了弹窗，如下图
- 截图如下：
<img width="260" alt="image" src="https://user-images.githubusercontent.com/7435144/217747719-8b07605d-dbb0-4b17-8a25-045964fad9f8.png">

**Comment by MustangYM** [comment]
首页read me有tg群, 进群领取最新的, Github待不下去了!
