### ISSUE TITLE
撤回图片消息闪退

### ISSUE THREAD

**Issue by zyxiaofeng** [MustangYM/WeChatExtension-ForMac#1784]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 3.6.1
- 小助手版本 : 2.x.x
- BUG描述 : 撤回图片闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的图片撤回
- 方便的话提供日志, 截图或者视频(可选)
0   CoreFoundation                      0x00007ff814d59cd3 __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007ff8148aa10a objc_exception_throw + 48
2   CoreFoundation                      0x00007ff814d81eb6 _CFBundleGetValueForInfoKey + 0
3   AppKit                              0x00007ff817d64161 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 307
4   AppKit                              0x00007ff817d50f4f -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1247
5   AppKit                              0x00007ff817eeb412 -[NSPanel _initContent:styleMask:backing:defer:contentView:] + 50
6   AppKit                              0x00007ff817d50a69 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
7   AppKit                              0x00007ff817eeb3cb -[NSPanel initWithContentRect:styleMask:backing:defer:] + 59
8   AppKit                              0x00007ff817d4ef88 -[NSWindowTemplate nibInstantiate] + 354
9   AppKit                              0x00007ff817d1d42a -[NSIBObjectData instantiateObject:] + 222
10  AppKit                              0x00007ff817d1cb9c -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 476
11  AppKit                              0x00007ff817d1167f loadNib + 420
12  AppKit                              0x00007ff817d10a67 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 737
13  AppKit                              0x00007ff817d10691 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
14  AppKit                              0x00007ff8180637a0 -[NSAlert init] + 101
15  AppKit                              0x00007ff8182b303e +[NSAlert(NSAlertDeprecated) alertWithMessageText:defaultButton:alternateButton:otherButton:informativeTextWithFormat:] + 111
16  WeChatExtension                     0x000000011bbb7406 dynamicMethodIMP + 1046
17  CoreFoundation                      0x00007ff814cc5fcc __invoking___ + 140
18  CoreFoundation                      0x00007ff814cc5e6e -[NSInvocation invoke] + 305
19  CoreFoundation                      0x00007ff814cf4cf6 -[NSInvocation invokeWithTarget:] + 70
20  WeChatExtension                     0x000000011bbb75d3 -[NSObject(Safe) safe_forwardInvocation:] + 115
21  CoreFoundation                      0x00007ff814cc48aa ___forwarding___ + 742
22  CoreFoundation                      0x00007ff814cc4538 _CF_forwarding_prep_0 + 120
23  WeChatExtension                     0x000000011bb9cc1f -[YMDownloadManager downloadImageWithMsg:] + 447
24  WeChatExtension                     0x000000011bc4db60 -[YMMessageManager asyncRevokeMessage:] + 4384
25  WeChatExtension                     0x000000011bb74950 -[NSObject(WeChatHook) _doParseRevokeMsg:msgData:arg1:arg2:arg3:] + 1360
26  WeChatExtension                     0x000000011bb7421e -[NSObject(WeChatHook) hook_FFToNameFavChatZZ:sessionMsgList:] + 398

**Comment by zyxiaofeng** [comment]
MacOS 13.0.1
助手版本 3.4.1

**Comment by MustangYM** [comment]
#1783

**Comment by zyxiaofeng** [comment]
加不上群，点击是错误，方便发一下

**Comment by zyxiaofeng** [comment]
@MustangYM

**Comment by zyxiaofeng** [comment]
<img width="764" alt="image" src="https://github.com/MustangYM/WeChatExtension-ForMac/assets/42363209/e16852d4-c1f2-4c49-b737-5791a7369b05">

**Comment by MustangYM** [comment]
@zyxiaofeng tg群里有
