### ISSUE TITLE
感觉退群提醒会把历史退群消息都显示出来

### ISSUE THREAD

**Issue by W-quan** [MustangYM/WeChatExtension-ForMac#180]

**Comment by dengxiaozhen** [comment]
确实存在这个问题
![image](https://user-images.githubusercontent.com/8529528/72200684-5df83b80-3487-11ea-8b02-3322f59df149.png)

**Comment by jerry9032** [comment]
同问，7天前退群的人今天又全部蹦出来了，吓我一跳 :joy:

**Comment by MustangYM** [comment]
[已经移除](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.1)
