### ISSUE TITLE
安装提示 Operation not permitted 和 No such file or directory

### ISSUE THREAD

**Issue by Jin-Yx** [MustangYM/WeChatExtension-ForMac#1809]
### issue规范
- MacOS版本 : Ventura 13
- 微信版本 : 3.8.1
- 小助手版本 : 3.8.2.1
- BUG描述 : 运行 ./Install.sh，输入密码后提示 chown /Applications/WeChat.app/**: Operation not permitted; 以及 cp: /Applications/WeChat.app/**: No such file or directory
- 操作场景 : 运行 ./Install.sh，输入密码后
- 日志：

![image](https://github.com/MustangYM/WeChatExtension-ForMac/assets/33388372/6023383e-6d10-4457-bbba-e1b98c9c3b0f)

**Comment by MustangYM** [comment]
#1810

**Comment by Xlff** [comment]
还未解决么

**Comment by tsaievan** [comment]
> 还未解决么

关闭SIP后安装
