### ISSUE TITLE
无法登录第二个微信账号

### ISSUE THREAD

**Issue by plutopaner** [MustangYM/WeChatExtension-ForMac#181]
微信版本：Version. 2.3.29 (13326)
OS版本：10.15.2 (19C57)

现象描述：
登录首个微信，功能正常。选择登录新微信，弹出新的微信窗口，登录的账号为首个微信，无法进行第二个账号的登录。

**Comment by WTNameIsOk** [comment]
同版本OSX
`登陆新微信`无任何弹窗响应

**Comment by px200** [comment]
微信版本：Version 2.3.25 (12482)
OS版本：10.15.3

点击新微信，无任何弹窗响应
