### ISSUE TITLE
微信 3.8.4 成功安装后不显示小助手

### ISSUE THREAD

**Issue by toplyb** [MustangYM/WeChatExtension-ForMac#1849]
- MacOS版本 : 13.0.1
- 微信版本 : 3.8.4
- 小助手版本 : 3.8.2
- Oh My WeChat 版本：2.1.4
- BUG描述 : 执行 `curl -o- -L https://omw.limingkai.cn/install.sh | bash -s`，`omw ` 后，打开微信，微信主题已经改变，但是左上角 tab 栏不展示小助手栏目，也不支持防撤回

<img width="447" alt="image" src="https://github.com/MustangYM/WeChatExtension-ForMac/assets/38663116/cbcd0758-b4da-43f4-bc81-fc3fc66cf95e">

<img width="874" alt="image" src="https://github.com/MustangYM/WeChatExtension-ForMac/assets/38663116/5761bd61-9b5f-4551-8659-03786a37bd94">

**Comment by ChaXxl** [comment]
参考： #1841

**Comment by toplyb** [comment]
> 参考： #1841

好的，感谢
