### ISSUE TITLE
Mac book M2 芯片 3.8.6.6小助手，微信相关问题

### ISSUE THREAD

**Issue by evileonline** [MustangYM/WeChatExtension-ForMac#1869]
### issue规范
- MacOS版本 : 14.2
- 微信版本 : 3.8.6
- 小助手版本 : 3.8.6.6
- BUG描述 : 
- 问题1:安装时，显示文件已损坏，无法安装，进入程序界面右键重新打开，无法操作成功；需要使用mac os小助手通过绕过签名方式后，方能打开。
- 问题2:打开后，功能基本正常，但会导致顶部边栏消失，整个电脑边框缩小。
- 问题3:如果覆盖安装3.8.6.5版本小助手，刘海屏消失问题会复现。
- 问题4:系统内已无其他版本（小助手及原版微信），纯净版本直接安装此版本，会显示文件已损坏，需要通过mac os小助手绕过签名，方能打开；打开后，无法双开第二个微信，会一直弹窗，需要允许数据访问；
- - 操作场景 : 微信启动后, 这个第二的问题就会存在，重新安装也不行；覆盖安装（无论使用原版最新系统，还是小助手版本）问题2依旧存在。
- BUG描述 : 系统内已无其他版本（小助手及原版微信），如果使用群内提供的微信3.8.0（老助手3.8.4）先安装，之后再覆盖安装3.8.6.5版本小助手，可进行微信双开。但是，仍存在刘海屏消失问题。并且，微信双开时，视频麦克风弹窗再次出现；如果单微信登陆，视频允许问题不存在（工作微信与生活微信同时登陆，互相打时，视频允许弹窗频繁出现）。
- 上一个3.8.6.5版本是存在连接视频时，每一次都要允许麦克风5次左右；此版本视频允许问题消失。
-
![Snip20240419_7](https://github.com/MustangYM/WeChatExtension-ForMac/assets/36870868/1362844e-125c-4d78-84e4-d50cabd9f21b)

**Comment by evileonline** [comment]
M2芯片是有刘海屏的

**Comment by WanGZiChenn** [comment]
顶部显示不了小助手怎么解决啊

**Comment by evileonline** [comment]
> 顶部显示不了小助手怎么解决啊

你现在的版本是哪个？

**Comment by guowenzhuang** [comment]
3.8.7不显示微信小助手

**Comment by GarboYang** [comment]
小助手版本 : 3.8.6.6的版本，在哪里呢，现在不是只能下3.8.2.1版本吗

**Comment by evileonline** [comment]
> 小助手版本 : 3.8.6.6的版本，在哪里呢，现在不是只能下3.8.2.1版本吗

https://t.me/WeChatExtension
进群，置顶里有
