### ISSUE TITLE
退群提醒会多次出现，重复出现

### ISSUE THREAD

**Issue by mumudm** [MustangYM/WeChatExtension-ForMac#195]
![image](https://user-images.githubusercontent.com/46308185/73541186-ba3df200-446c-11ea-9b54-964d2a5c11e2.png)
退群监控会多次重复出现，经常性出现在第二天开机的时候多个群同时出现大片的退群监控，同一个人的退出信息会出现多次
微信版本：2.3.29
小助手版本：2.3.0

**Comment by WangDanpeng** [comment]
我也遇到了

**Comment by D-R-L** [comment]
相同情况，
微信版本：2.3.30 (13189)
小助手版本：2.4.1

**Comment by neutron1988** [comment]
同样的情况，每天开启微信都有可能出现完全一样的信息。
微信：2.4.0 (13941) Beta 146
小助手：2.4.1

**Comment by MustangYM** [comment]
[已经移除](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.1)
