### ISSUE TITLE
安装后不起在作用？？？

### ISSUE THREAD

**Issue by BitionSong** [MustangYM/WeChatExtension-ForMac#198]
微信版本是2.3.29.插件也已经安装上去的，

**Comment by chloeiu** [comment]
我和你是一样的 不知道哪里出现了问题

**Comment by chloeiu** [comment]
我和你是一样的 不知道哪里出现了问题

**Comment by remixchao** [comment]
我也是，尝试了重新安装，重新安装微信。都不行。

Version 2.3.29 (13326)

**Comment by remixchao** [comment]
刚试了下微信测试版2.4，也不起作用。

**Comment by remixchao** [comment]
应该是上次更新的时候出了点问题，用release里最后一版，可以用。

**Comment by BitionSong** [comment]
可以用了，用了的3种安装步行的，第一种安装起来就好了

**Comment by hotwow** [comment]
> 可以用了，用了的3种安装步行的，第一种安装起来就好了

第一种安装也不行
