### ISSUE TITLE
转发语音的功能 作者是否有考虑

### ISSUE THREAD

**Issue by caihuoche** [MustangYM/WeChatExtension-ForMac#199]

**Comment by hx2nn** [comment]
语音转发功能确实很需要

**Comment by mourenli** [comment]
对对对 这个功能可以有！！！哈哈 我目前都是用手动替换

**Comment by Aprilming** [comment]
我现在都是手机上进行语音转发，手机上还有一个好玩的功能就是文字转语音，希望能开发一下

**Comment by caihuoche** [comment]
> 我现在都是手机上进行语音转发，手机上还有一个好玩的功能就是文字转语音，希望能开发一下

手机怎么语音转发的,是哪个插件

**Comment by Aprilming** [comment]
> > 我现在都是手机上进行语音转发，手机上还有一个好玩的功能就是文字转语音，希望能开发一下
> 
> 手机怎么语音转发的,是哪个插件

知少小白源的多语音插件（带转发），源地址:http://apt.xbsite.cn

**Comment by MustangYM** [comment]
不会考虑这个功能, 这个功能的弊大于利, 只会造成一些不必要的麻烦
