### ISSUE TITLE
不会还像WeChatPlugin一样收集用户微信信息叭？

### ISSUE THREAD

**Issue by LuckyMango** [MustangYM/WeChatExtension-ForMac#2]

**Comment by Liuchunqi3240** [comment]
都开源了 你自己改改代码不就好了

**Comment by MustangYM** [comment]
> _没有提供说明。_
没有所谓收集用户信息的说法, 只是说用户在腾讯所说的那样特定的操作下会导致被攻击的风险. 但是本插件并不会收集用户信息, 因为没啥意义

**Comment by hsworkshop** [comment]
好奇猜到 FFToNameFavChatZZ这个命名的思路是什么

**Comment by MustangYM** [comment]
> 好奇猜到FFToNameFavChatZZ这个命名的思路是什么

没有猜， 通过动态调试知道的。

**Comment by wicked-wei** [comment]
腾讯说的特定操作下导致被攻击的风险的代码我看了，要避免的话有几个办法：
1. 不启用alfred功能。调试和检查代码发现GCDWebServer只有启用alfred的时候才会开启。所以不启用alfred功能时不会被攻击到。
2. 不点开别人给的恶意链接（根据dns rebinding攻击原理，应该警惕任何非默认http/https端口的链接）
3. 自己修改源码端口的52700为其他端口，然后编译安装。（这个我还没试验，不知道修改端口会不会影响alfred功能）
