### ISSUE TITLE
「手机端也能收到被撤回的消息」能有个开关吗，这功能有点干扰手机端

### ISSUE THREAD

**Issue by poorzerg** [MustangYM/WeChatExtension-ForMac#20]
一旦有人撤回消息，手机就会反馈一次，活跃的群一多，反馈的频率就有点高

**Comment by poorzerg** [comment]
一旦有人测回消息，手机就会反馈一次，活跃的群一多，反馈的频率就有点高

**Comment by MustangYM** [comment]
> 一旦有人撤回消息，手机就会反馈一次，活跃的群一多，反馈的频率就有点高

已加.v1.8.4
