### ISSUE TITLE
屏幕上大量的退群提醒，怎么关闭该功能

### ISSUE THREAD

**Issue by alterem** [MustangYM/WeChatExtension-ForMac#205]
屏幕上大量的退群提醒，怎么关闭该功能
![image](https://user-images.githubusercontent.com/16953053/74807072-82ff8a00-5322-11ea-85a7-6d32eefbb3b0.png)

**Comment by alterem** [comment]
![image](https://user-images.githubusercontent.com/16953053/74807307-13d66580-5323-11ea-9c47-433c7557679c.png)

**Comment by MustangYM** [comment]
> 屏幕上大量的退群提醒，怎么关闭该功能
> ![图片](https://user-images.githubusercontent.com/16953053/74807072-82ff8a00-5322-11ea-85a7-6d32eefbb3b0.png)

更新到新版本会有开关关闭

**Comment by alterem** [comment]
![image](https://user-images.githubusercontent.com/16953053/74901401-ba7f3c80-53dd-11ea-812f-a0e047fbe11d.png)
已经是最新版本，而且并没有勾选开关

**Comment by MustangYM** [comment]
> ![图片](https://user-images.githubusercontent.com/16953053/74901401-ba7f3c80-53dd-11ea-812f-a0e047fbe11d.png)
> 已经是最新版本，而且并没有插入开关

第四个选项, "退群监控"

**Comment by alterem** [comment]
你没发现已经是关闭状态了吗
