### ISSUE TITLE
【请求功能新增】隐藏dock图标

### ISSUE THREAD

**Issue by czydbb** [MustangYM/WeChatExtension-ForMac#206]
RT，有没有可能能隐藏微信在dock上的图标。

**Comment by MustangYM** [comment]
> RT，有没有可能能隐藏微信在dock上的图标。

这个....emmmmm, 隐藏了怎么打开...不懂的朋友又来报BUG

**Comment by MustangYM** [comment]
> RT，有没有可能能隐藏微信在dock上的图标。

emmmmm......没有这个打算哦

**Comment by h-jia** [comment]
一行命令就可以了：
`/usr/libexec/PlistBuddy -c 'Add :LSUIElement bool true' /Applications/Wechat.app/Contents/Info.plist`
