### ISSUE TITLE
2.4 小程序有bug

### ISSUE THREAD

**Issue by goldencolor** [MustangYM/WeChatExtension-ForMac#207]
2.4 打开小程序有的时候无法打开，会重新开启一个登录窗口

**Comment by Victarry** [comment]
MAC微信Version 2.4.0 (13941) Beta 146， 出现同样的问题

**Comment by MustangYM** [comment]
> 2.4 打开小程序有的时候无法打开，会重新开启一个登录窗口

[https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.4.0](url) 已解决

**Comment by MustangYM** [comment]
> MAC微信Version 2.4.0 (13941) Beta 146， 出现同样的问题

[https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.4.0](2.4.0)已解决

**Comment by MustangYM** [comment]
> 2.4 打开小程序有的时候无法打开，会重新开启一个登录窗口

[2.4.0已解决](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.4.0)

**Comment by MustangYM** [comment]
> MAC微信版本2.4.0（13941）Beta 146，出现同样的问题

[2.4.0已解决](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.4.0)

**Comment by linguo2625469** [comment]
> > MAC微信版本2.4.0（13941）Beta 146，出现同样的问题
> 
> [2.4.0已解决](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.4.0)

更新后一样的问题

**Comment by MustangYM** [comment]
你是什么样的问题




| |
MustangYM
|
|
邮箱：ymoomy@yeah.net
|

Signature is customized by Netease Mail Master

在2020年02月26日 09:57，linguo2625469 写道：

MAC微信版本2.4.0（13941）Beta 146，出现同样的问题

2.4.0已解决

更新后一样的问题
