### ISSUE TITLE
2.3.24.17 多开不成功

### ISSUE THREAD

**Issue by HarrisHan** [MustangYM/WeChatExtension-ForMac#21]
Mac Version 10.14 (18A391)

有人遇到么？

**Comment by HarrisHan** [comment]
open -n /Applications/WeChat.app Dock 中会闪一下微信启动图标然后消失

**Comment by MustangYM** [comment]
> open -n /Applications/WeChat.app

你小助手是什么版本的

**Comment by HarrisHan** [comment]
> > open -n /Applications/WeChat.app
> 
> 你小助手是什么版本的

master分支源码跑的

**Comment by HarrisHan** [comment]
> > open -n /Applications/WeChat.app
> 
> 你小助手是什么版本的

master分支源码跑的

**Comment by MustangYM** [comment]
> > > open -n /Applications/WeChat.app
> > 
> > 
> > 你小助手是什么版本的
> 
> master分支源码跑的

...可以把顶部"微信小助手"点开, 截图发出来我看看嘛
