### ISSUE TITLE
【新增功能】好友检测

### ISSUE THREAD

**Issue by goldencolor** [MustangYM/WeChatExtension-ForMac#211]
【新增功能】好友检测

1.大佬是否能否增加一个好友被删监测功能，刚需啊
2.能否hook所有聊天记录，单独导出或下载

**Comment by mourenli** [comment]
有windows现成的啊！！！还不错

**Comment by raycool** [comment]
> 有windows现成的啊！！！还不错

求问地址。

**Comment by MustangYM** [comment]
我尝试去解决这个问题, 暂时没有发现好的方法. 抱歉
