### ISSUE TITLE
【已解决】安装了新版本（2.4.0），点击小程序还是无法打开，仍然是微信多开

### ISSUE THREAD

**Issue by wwmix** [MustangYM/WeChatExtension-ForMac#213]
如题，微信和插件都重新安装过了，还是如此。

**Comment by linguo2625469** [comment]
一样

**Comment by MustangYM** [comment]
> 如题，微信和插件都重新安装过了，还是如此。

能截图看看你的小助手版本和微信版本么

**Comment by Mrycp** [comment]
是的我也遇得到了，还以为这次更新主要就是为了解决这个问题呢

**Comment by wwmix** [comment]
<img width="568" alt="iShot     2020-02-26 下午01 02 38" src="https://user-images.githubusercontent.com/47473353/75313631-53a7ca80-5898-11ea-8e16-3a9e509b82b5.png">
<img width="498" alt="iShot     2020-02-26 下午01 02 56" src="https://user-images.githubusercontent.com/47473353/75313634-55718e00-5898-11ea-9ad5-d932e4abddc5.png">

**Comment by wwmix** [comment]
![](https://tva1.sinaimg.cn/large/0082zybply1gc9pxtmbetj30vk0m4wg4.jpg)
![](https://tva1.sinaimg.cn/large/0082zybply1gc9py3mkgpj30ro0ogq8y.jpg)

**Comment by wwmix** [comment]
> > 如题，微信和插件都重新安装过了，还是如此。
> 
> 能截图看看你的小助手版本和微信版本么

![微信版本](https://tva1.sinaimg.cn/large/0082zybply1gc9q0kdvetj30vk0m4wg4.jpg)
![小助手版本](https://tva1.sinaimg.cn/large/0082zybply1gc9q0w1na1j30ro0ogq8y.jpg)

**Comment by li-xunhuan** [comment]
正常使用。。

<img width="550" alt="QQ20200226-162733@2x" src="https://user-images.githubusercontent.com/10476982/75326183-2289c300-58b5-11ea-9e34-e4ef2a687447.png">
<img width="480" alt="QQ20200226-162834@2x" src="https://user-images.githubusercontent.com/10476982/75326191-261d4a00-58b5-11ea-921f-9bab1390dfa1.png">
<img width="773" alt="QQ20200226-162855@2x" src="https://user-images.githubusercontent.com/10476982/75326194-261d4a00-58b5-11ea-9007-6a0155674ec3.png">

**Comment by linguo2625469** [comment]
> 正常使用。。
> 
> <img alt="QQ20200226-162733@2x" width="550" src="https://user-images.githubusercontent.com/10476982/75326183-2289c300-58b5-11ea-9e34-e4ef2a687447.png">
> 
> <img alt="QQ20200226-162834@2x" width="480" src="https://user-images.githubusercontent.com/10476982/75326191-261d4a00-58b5-11ea-921f-9bab1390dfa1.png">
> 
> <img alt="QQ20200226-162855@2x" width="773" src="https://user-images.githubusercontent.com/10476982/75326194-261d4a00-58b5-11ea-9007-6a0155674ec3.png">

你的是小助手自动更新的吗  我们的关于怎么不太一样

**Comment by Mrycp** [comment]
> > 正常使用。。
> > <img alt="QQ20200226-162733@2x" width="550" src="https://user-images.githubusercontent.com/10476982/75326183-2289c300-58b5-11ea-9e34-e4ef2a687447.png">
> > <img alt="QQ20200226-162834@2x" width="480" src="https://user-images.githubusercontent.com/10476982/75326191-261d4a00-58b5-11ea-921f-9bab1390dfa1.png">
> > <img alt="QQ20200226-162855@2x" width="773" src="https://user-images.githubusercontent.com/10476982/75326194-261d4a00-58b5-11ea-9007-6a0155674ec3.png">
> 
> 你的是小助手自动更新的吗 我们的关于怎么不太一样
我想知道你们是怎么安装的，我试过了几次了还是都不行。点击小程序就多开微信

**Comment by yaolee** [comment]
<img width="991" alt="截屏2020-02-26 下午6 21 17" src="https://user-images.githubusercontent.com/22741350/75335697-dd6d8d00-58c4-11ea-8003-0b9bea2c617d.png">
正常使用。

**Comment by li-xunhuan** [comment]
> > > 正常使用。。
> > > <img alt="QQ20200226-162733@2x" width="550" src="https://user-images.githubusercontent.com/10476982/75326183-2289c300-58b5-11ea-9e34-e4ef2a687447.png">
> > > <img alt="QQ20200226-162834@2x" width="480" src="https://user-images.githubusercontent.com/10476982/75326191-261d4a00-58b5-11ea-921f-9bab1390dfa1.png">
> > > <img alt="QQ20200226-162855@2x" width="773" src="https://user-images.githubusercontent.com/10476982/75326194-261d4a00-58b5-11ea-9007-6a0155674ec3.png">
> > 
> > 
> > 你的是小助手自动更新的吗 我们的关于怎么不太一样
> > 我想知道你们是怎么安装的，我试过了几次了还是都不行。点击小程序就多开微信

`git checkout v2.4.0`
然后运行Install.sh

**Comment by Mrycp** [comment]
> > > > 正常使用。。
> > > > <img alt="QQ20200226-162733@2x" width="550" src="https://user-images.githubusercontent.com/10476982/75326183-2289c300-58b5-11ea-9e34-e4ef2a687447.png">
> > > > <img alt="QQ20200226-162834@2x" width="480" src="https://user-images.githubusercontent.com/10476982/75326191-261d4a00-58b5-11ea-921f-9bab1390dfa1.png">
> > > > <img alt="QQ20200226-162855@2x" width="773" src="https://user-images.githubusercontent.com/10476982/75326194-261d4a00-58b5-11ea-9007-6a0155674ec3.png">
> > > 
> > > 
> > > 你的是小助手自动更新的吗 我们的关于怎么不太一样
> > > 我想知道你们是怎么安装的，我试过了几次了还是都不行。点击小程序就多开微信
> 
> `git checkout v2.4.0`
> 然后运行Install.sh

不知道为什么，我的还是不行。两个版本都是最新的了。手动安装也试过了还是不行。点击小程序就跳出多登录

**Comment by Leeiio** [comment]
遭遇了同样的问题，但是我一开始安装时是好的，后来就坏了不知道怎么回事。期间多开过一次微信以及开启了退群监控，不知道是否有帮助调试

**Comment by Mrycp** [comment]
> 遭遇了同样的问题，但是我一开始安装时是好的，后来就坏了不知道怎么回事。期间多开过一次微信以及开启了退群监控，不知道是否有帮助调试

我也觉得和多开有关系，第一次点多开的时候提示重启，重启完之后小程序就无法使用了。

**Comment by lvhe19880210** [comment]
一样 点过一次多开就不行了 重装也不行

**Comment by xujipm** [comment]
Version. 2.4.0 (13962) Beta 147

**Comment by gqbre** [comment]
本插件如何重置设置？没找到配置文件放在哪

**Comment by MustangYM** [comment]
[新版本已经解决了这个问题](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.4.1)

**Comment by wwmix** [comment]
> 新版本已经解决了这个问题

辛苦啦！～ 感谢～

**Comment by Mrycp** [comment]
谢谢，确实新增了一个开启小程序的按钮。好评，不过和微信多开功能是互斥的。
