### ISSUE TITLE
只要点击左边的聊天栏，微信立马崩。

### ISSUE THREAD

**Issue by st-lucifer** [MustangYM/WeChatExtension-ForMac#214]
环境：微信2.3.22版本和2.3.23版本 
运行小助手后，只要点击微信左边的任何一个聊天窗口，微信程序立马崩掉。

**Comment by MustangYM** [comment]
> 环境：微信2.3.22版本和2.3.23版本
> 运行小助手后，只要单击微信左边的任何一个聊天窗口，微信程序立马崩溃掉。

更新到最新微信客户端和小助手
