### ISSUE TITLE
【功能】撤回样式改进，可以参考 WeChatTweak-macOS

### ISSUE THREAD

**Issue by woxiqingxian** [MustangYM/WeChatExtension-ForMac#215]
如题：

目前消息撤回拦截体验比较差

推荐可以参考 WeChatTweak-macOS 的遮罩撤回拦截

**Comment by MustangYM** [comment]
> 如题：
> 
> 目前消息撤回拦截体验比较差
> 
> 推荐可以参考 WeChatTweak-macOS 的遮罩撤回拦截

能截图看看么

**Comment by woxiqingxian** [comment]
![image](https://user-images.githubusercontent.com/8405482/75600640-a5e12980-5aec-11ea-8d93-4a59e440a43a.png)

**Comment by woxiqingxian** [comment]
> > 如题：
> > 目前消息撤回拦截体验比较差
> > 推荐可以参考 WeChatTweak-macOS 的遮罩撤回拦截
> 
> 能截图看看么

![image](https://user-images.githubusercontent.com/8405482/75600640-a5e12980-5aec-11ea-8d93-4a59e440a43a.png)
就是遮罩模式，黄色的那部分是对方撤回的。
这种看起来很简洁，而且整个聊天时间线很清晰。

**Comment by MustangYM** [comment]
> > > 如题：
> > > 目前消息撤回拦截体验比较差
> > > 推荐可以参考 WeChatTweak-macOS 的遮罩撤回拦截
> > 
> > 
> > 能截图看看么
> 
> ![image](https://user-images.githubusercontent.com/8405482/75600640-a5e12980-5aec-11ea-8d93-4a59e440a43a.png)
> 就是遮罩模式，黄色的那部分是对方撤回的。
> 这种看起来很简洁，而且整个聊天时间线很清晰。

可是我觉得我这个更好看, 更简洁.
