### ISSUE TITLE
【功能请求】开发者api

### ISSUE THREAD

**Issue by JokeNeverSoke** [MustangYM/WeChatExtension-ForMac#216]
能否透过obj-c在本地开http监听来让开发者自己写消息回复之类的？

**Comment by MustangYM** [comment]
> 能否透过obj-c在本地开http监听来让开发者自己写消息回复之类的？

暂时没有这个打算, 抱歉. 我只是业余时间写来供大众用, 既然是开发者, 其实OC代码很容易就能看懂, 每个人需求不一, 都是开源的, 自己定制一下吧
