### ISSUE TITLE
【功能请求】自动同步消息

### ISSUE THREAD

**Issue by zxcvb5788** [MustangYM/WeChatExtension-ForMac#218]
电脑端开启免认证登陆，晚上电脑关机，第二天开机后电脑端微信不能同步晚间手机端微信收到的消息，必须手机端强制退出电脑端微信登陆，再重新认证登陆之后才能进行消息同步，可否调整一下此功能？
助手版本：2.4.0
微信版本：2.3.30 Mac

**Comment by MustangYM** [comment]
> 电脑端开启免认证登陆，晚上电脑关机，第二天开机后电脑端微信不能同步晚间手机端微信收到的消息，必须手机端强制退出电脑端微信登陆，再重新认证登陆之后才能进行消息同步，可否调整一下此功能？
> 助手版本：2.4.0
> 微信版本：2.3.30 Mac

做不到
