### ISSUE TITLE
[BUG]AirPods无法语音或视频

### ISSUE THREAD

**Issue by jarryyen** [MustangYM/WeChatExtension-ForMac#219]
wechat version : 2.3.29
wechat plugin version : last
macos version : 10.14.6 (18G3020)
问题是使用最新的插件,再使用AirPods 二代使用微信视频或者语音的时候 听不到,说话对方也无法听到.

**Comment by MustangYM** [comment]
> wechat版本：2.3.29
> wechat插件版本：最新
> macos版本：10.14.6（18G3020）
> 问题是使用最新的插件，重新使用AirPods。

没这毛病
