### ISSUE TITLE
微信群成员撤回消息没有群成员的昵称

### ISSUE THREAD

**Issue by xt-input** [MustangYM/WeChatExtension-ForMac#22]
手机端收到的撤回消息里没有群成员的昵称，这个功能不能做到吗？

**Comment by MustangYM** [comment]
> 手机端收到的撤回消息里没有群成员的昵称，这个功能不能做到吗？

会改进

**Comment by MustangYM** [comment]
> 手机端收到的撤回消息里没有群成员的昵称，这个功能不能做到吗？

已解决
