### ISSUE TITLE
请问一下远程监控怎么使用

### ISSUE THREAD

**Issue by ityulong** [MustangYM/WeChatExtension-ForMac#221]
感谢博主的插件 相当棒！！
要怎么使用远程监控啊
还有菜单栏的 启动Alfred 是干嘛的

**Comment by MustangYM** [comment]
> 感谢博主的插件 相当棒！！
> 要怎么使用远程监控啊
> 还有菜单栏的 启动Alfred 是干嘛的

手机端发相应命令 --> 电脑端 , 自己发给自己. Alfred你百度下吧.
