### ISSUE TITLE
【文本更改小建议】英文版的退群监测的文本更改

### ISSUE THREAD

**Issue by eugeneYWang** [MustangYM/WeChatExtension-ForMac#226]
英文版里，退群监测的对应名称是 “Quit Monitor”，这里的Quit很容易把Quit理解为动词，就会把退群监测误解为“退出监测”，类似 “退出软件”那个意思。

如果作者大大想要参考翻译的话，我个人的意见是：“Group-Quitting Monitor”

**Comment by MustangYM** [comment]
> 英文版里，退群监测的对应名称是 “Quit Monitor”，这里的Quit很容易把Quit理解为动词，就会把退群监测误解为“退出监测”，类似 “退出软件”那个意思。
> 
> 如果作者大大想要参考翻译的话，我个人的意见是：“Group-Quitting Monitor”

感谢感谢, 下个版本就改

**Comment by eugeneYWang** [comment]
@MustangYM 不客气哈，谢谢你的劳动成果。

顺便在此问一问： 有没有办法把插件的英文菜单转换成中文文本呢？在我不换系统语言的前提下
