### ISSUE TITLE
退群监控 - 同一人7天内多次退群能否每次都提示？

### ISSUE THREAD

**Issue by gaoyangyiqiao** [MustangYM/WeChatExtension-ForMac#228]
目前是7天内同一个人仅提示一次退群，但是我遇到了一个极端case，有个群里同学会连续多次被拉进群然后退群......请问能否支持每次都提示？

**Comment by MustangYM** [comment]
[已经移除](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.1)
