### ISSUE TITLE
微信小组手1.7.8版本登录新微信双开，之前登录的微信账号退出

### ISSUE THREAD

**Issue by sheng930920** [MustangYM/WeChatExtension-ForMac#23]
微信小组手1.7.8版本登录新微信双开，之前登录的微信账号退出，使用系统浏览器也无效
![image](https://user-images.githubusercontent.com/13199067/58605212-9a48a400-82c9-11e9-9ae9-8abf701c69a7.png)

![image](https://user-images.githubusercontent.com/13199067/58605019-070f6e80-82c9-11e9-8c00-a2f12e4cc2fe.png)

![image](https://user-images.githubusercontent.com/13199067/58605006-fb23ac80-82c8-11e9-982b-9e138784da22.png)

![image](https://user-images.githubusercontent.com/13199067/58604996-f19a4480-82c8-11e9-9598-d5c8042def34.png)

![image](https://user-images.githubusercontent.com/13199067/58604980-e0513800-82c8-11e9-9ec6-1ad0cf3a05a4.png)

**Comment by MustangYM** [comment]
> 微信小组手1.7.8版本登录新微信双开，之前登录的微信账号退出，使用系统浏览器也无效
> ![image](https://user-images.githubusercontent.com/13199067/58605212-9a48a400-82c9-11e9-9ae9-8abf701c69a7.png)
> 
> ![image](https://user-images.githubusercontent.com/13199067/58605019-070f6e80-82c9-11e9-8c00-a2f12e4cc2fe.png)
> 
> ![image](https://user-images.githubusercontent.com/13199067/58605006-fb23ac80-82c8-11e9-982b-9e138784da22.png)
> 
> ![image](https://user-images.githubusercontent.com/13199067/58604996-f19a4480-82c8-11e9-9598-d5c8042def34.png)
> 
> ![image](https://user-images.githubusercontent.com/13199067/58604980-e0513800-82c8-11e9-9ec6-1ad0cf3a05a4.png)

之前的微信退出, 是闪退, 还是账号退出? 系统浏览器的问题, 你微信升级到2.3.25就好了

**Comment by sheng930920** [comment]
> > 微信小组手1.7.8版本登录新微信双开，之前登录的微信账号退出，使用系统浏览器也无效
> > ![图片](https://user-images.githubusercontent.com/13199067/58605212-9a48a400-82c9-11e9-9ae9-8abf701c69a7.png)
> > ![图片](https://user-images.githubusercontent.com/13199067/58605019-070f6e80-82c9-11e9-8c00-a2f12e4cc2fe.png)
> > ![图片](https://user-images.githubusercontent.com/13199067/58605006-fb23ac80-82c8-11e9-982b-9e138784da22.png)
> > ![图片](https://user-images.githubusercontent.com/13199067/58604996-f19a4480-82c8-11e9-9598-d5c8042def34.png)
> > ![图片](https://user-images.githubusercontent.com/13199067/58604980-e0513800-82c8-11e9-9ec6-1ad0cf3a05a4.png)
> 
> 之前的微信退出，是闪退，还是账号退出？系统浏览器的问题，你微信升级到2.3.25就好了

账号退出

**Comment by MustangYM** [comment]
> 微信小组手1.7.8版本登录新微信双开，之前登录的微信账号退出，使用系统浏览器也无效
> ![图片](https://user-images.githubusercontent.com/13199067/58605212-9a48a400-82c9-11e9-9ae9-8abf701c69a7.png)
> 
> ![图片](https://user-images.githubusercontent.com/13199067/58605019-070f6e80-82c9-11e9-8c00-a2f12e4cc2fe.png)
> 
> ![图片](https://user-images.githubusercontent.com/13199067/58605006-fb23ac80-82c8-11e9-982b-9e138784da22.png)
> 
> ![图片](https://user-images.githubusercontent.com/13199067/58604996-f19a4480-82c8-11e9-9598-d5c8042def34.png)
> 
> ![图片](https://user-images.githubusercontent.com/13199067/58604980-e0513800-82c8-11e9-9ec6-1ad0cf3a05a4.png)

双开后之前的账号退出的问题, 可能你开启了面认证登录, 所以第二个微信打开会自动把第一个微信已登录的账号顶下去, 所以要双开, 请把免认证关闭. 由于对系统api进行了hook, 暂时没有找到更优雅的办法.
