### ISSUE TITLE
希望软件支持置底排序和组功能

### ISSUE THREAD

**Issue by zszen** [MustangYM/WeChatExtension-ForMac#231]
因为很多群/人属于不是很需要获得对方信息或者内容, 又迫不得已不能删除, 能否把置底底列表支持排序, 另外能否把所有的列表进行分组折叠

比如 工作一个组, 里面就是同事, 项目等, 他们里面如果有未读信息会包含 重要消息提醒数 和 勿扰消息提醒数
然后生活, 娱乐, 爱好等都单独分开组, 我觉得这样的设计更人性化一些, 单很可能实现难度过大

**Comment by MustangYM** [comment]
> 因为很多群/人属于不是很需要获得对方信息或者内容, 又迫不得已不能删除, 能否把置底底列表支持排序, 另外能否把所有的列表进行分组折叠
> 
> 比如 工作一个组, 里面就是同事, 项目等, 他们里面如果有未读信息会包含 重要消息提醒数 和 勿扰消息提醒数
> 然后生活, 娱乐, 爱好等都单独分开组, 我觉得这样的设计更人性化一些, 单很可能实现难度过大

emmmmm....已经置底了, 还排啥列, 联系人分组嘛, 我感觉没啥必要. 抱歉
