### ISSUE TITLE
Dark Mode 深色模式优化

### ISSUE THREAD

**Issue by Jax0rz** [MustangYM/WeChatExtension-ForMac#233]
新版本dark mode强力点赞，非常好，但是有些细节适配的还不是很完善：
<img width="942" alt="Xnip2020-03-17_19-22-11" src="https://user-images.githubusercontent.com/7557357/76851806-e084e900-6884-11ea-9a3d-24c7e86e3c1f.png">
<img width="942" alt="Xnip2020-03-17_19-22-42" src="https://user-images.githubusercontent.com/7557357/76851809-e2e74300-6884-11ea-8b25-ccaff5fc01d4.png">
<img width="942" alt="Xnip2020-03-17_19-22-42" src="https://user-images.githubusercontent.com/7557357/76851813-e4b10680-6884-11ea-8d7c-a7df6c171ceb.png">
<img width="942" alt="Xnip2020-03-17_19-22-52" src="https://user-images.githubusercontent.com/7557357/76851816-e7136080-6884-11ea-81eb-f2122661aee9.png">

**Comment by MustangYM** [comment]
收藏页面已经修复了的, 没有发版本,你手动更新下就有了. 至于别的窗口, 暂时没有打算去适配.
