### ISSUE TITLE
需要少女粉主题

### ISSUE THREAD

**Issue by houyukun** [MustangYM/WeChatExtension-ForMac#234]
哈哈哈

**Comment by houyukun** [comment]
这个黑色模式,颜色不够深啊,应该更黑才好,现在有点白灰

**Comment by joescon** [comment]
> 这个黑色模式,颜色不够深啊,应该更黑才好,现在有点白灰

是的。微信下面是白晃晃的QQ界面，有一瞬间我还以为微信这个 dark mode 是有点透明的。。。
