### ISSUE TITLE
强迫症犯者表示能否增加日语本地化

### ISSUE THREAD

**Issue by hououinkami** [MustangYM/WeChatExtension-ForMac#235]
日语系统的菜单变成英文看着好别扭，如果可以的话麻烦添加一下日语本地化，我可以帮忙翻译，谢谢

**Comment by MustangYM** [comment]
> 日语系统的菜单变成英文看着好别扭，如果可以的话麻烦添加一下日语本地化，我可以帮忙翻译，谢谢

暂不考虑日语的本地化.
