### ISSUE TITLE
能否根据系统自动开启/关闭黑暗模式？

### ISSUE THREAD

**Issue by XYZliang** [MustangYM/WeChatExtension-ForMac#237]
如题，能自动切换就最好了。黑暗模式还是很不错的，主要的地方都覆盖了。就是输入框的灰色有点怪怪的哈哈哈。

还有黑暗模式下，当有消息来时，侧边栏图标上的小数字把消息的图标给挡住了。如图：（github上传不了）https://imgchr.com/i/8wFwDg

**Comment by MustangYM** [comment]
> 黑暗模式还是很不错的，主要的地方都覆盖了。就是输入框的灰色有点怪怪的哈哈哈。
> 
> 还有黑暗模式下，当有消息来时，侧边栏图标上的小数字把消息的图标给挡住了。如图：（github上传不了）https://imgchr.com/i/8wFwDg

好

**Comment by XYZliang** [comment]
ps：我是Version. 2.4.0 (13962) Beta 147，不知道是不是测试板的问题

**Comment by yaolee** [comment]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/22741350/77066074-72bff500-6a1d-11ea-80cd-466b6b8fc16b.png">

**Comment by Mother-Ship** [comment]
同求

**Comment by bunney** [comment]
开发者辛苦，但是同求一个  关闭暗黑的操作

**Comment by MustangYM** [comment]
如果系统的是动态变的，实际上改变皮肤的时候做一次客户端重启才能生效，体验极差，不考虑这功能
