### ISSUE TITLE
公众号文章丢失

### ISSUE THREAD

**Issue by iizvv** [MustangYM/WeChatExtension-ForMac#24]
![Snip20190530_3](https://user-images.githubusercontent.com/15830996/58635884-95afda00-8321-11e9-8c36-11b9860ae06a.png)
![Snip20190530_4](https://user-images.githubusercontent.com/15830996/58635947-bbd57a00-8321-11e9-9147-ecf8e4191336.png)
![Snip20190530_5](https://user-images.githubusercontent.com/15830996/58635978-d14aa400-8321-11e9-8c28-dbad0c27e691.png)

**Comment by MustangYM** [comment]
暂时没有复现出来此问题, 先关闭
