### ISSUE TITLE
优化Dark Mode 输入框按钮配色

### ISSUE THREAD

**Issue by Jax0rz** [MustangYM/WeChatExtension-ForMac#241]
原本黑色的按钮在深色模式下面应该改成浅色
<img width="942" alt="Xnip2020-03-20_08-40-52" src="https://user-images.githubusercontent.com/7557357/77127221-ad11ac80-6a86-11ea-9810-a58079cbd458.png">

**Comment by MustangYM** [comment]
> 原本黑色的按钮在深色模式下面应该改成浅色
> <img alt="Xnip2020-03-20_08-40-52" width="942" src="https://user-images.githubusercontent.com/7557357/77127221-ad11ac80-6a86-11ea-9810-a58079cbd458.png">
不太好改
