### ISSUE TITLE
一直在等待小窗口功能，官方也不支持，不知是否是mac系统所限？

### ISSUE THREAD

**Issue by cnbiao** [MustangYM/WeChatExtension-ForMac#242]
小窗口功能在日常使用中还是非常需要等一个功能，多个会话的时候 分别小窗口形式平铺在屏幕上，就不需要有新消息来回切换窗口了。
插件不知道能否做这样的事情。

**Comment by MustangYM** [comment]
> 小窗口功能在日常使用中还是非常需要等一个功能，多个会话的时候 分别小窗口形式平铺在屏幕上，就不需要有新消息来回切换窗口了。
> 插件不知道能否做这样的事情。

可能实现起来较复杂, 暂时没有这个打算
