### ISSUE TITLE
微信 2.3.30 安装成功， 未显示微信小助手

### ISSUE THREAD

**Issue by babyhai** [MustangYM/WeChatExtension-ForMac#245]
微信2.3.30 安装时提示 ：
<img width="535" alt="CleanShot 2020-03-21 at 11 28 35@2x" src="https://user-images.githubusercontent.com/22759331/77218546-68117700-6b67-11ea-96e7-213b70f29391.png">

然后我 执行 ` xattr -r -d com.apple.quarantine  /WeChatExtension-ForMac/WeChatExtension/Rely/Install.sh`
 
重启微信 没有显示微信小助手。 再次将 Rely/Install.sh 文件拖到终端执行的时候， 提示安装成功， 系统重启也没有显示出微信小助手

![Uploading CleanShot 2020-03-21 at 11.37.41@2x.png…]()

**Comment by MustangYM** [comment]
> 微信2.3.30安装时提示：
> 
> 
> 然后我执行 xattr -r -d com.apple.quarantine /WeChatExtension-ForMac/WeChatExtension/Rely/Install.sh
> 
> 再次将Rely / Install.sh文件拖到终端执行的时候，提示安装成功，系统重启也没有显示出微信小助手。

[百度一下](https://www.baidu.com/s?wd=%E5%9B%A0%E4%B8%BA%E6%97%A0%E6%B3%95%E9%AA%8C%E8%AF%81%E5%BC%80%E5%8F%91%E8%80%85&rsv_spt=1&rsv_iqid=0xb3968b6c0001691d&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_dl=tb&rsv_sug2=0&inputT=4607&rsv_sug4=5238)
