### ISSUE TITLE
黑暗主题颜色

### ISSUE THREAD

**Issue by MingdaLin** [MustangYM/WeChatExtension-ForMac#246]
可否新增sublimetext上的Monokai颜色主题，或者参考Mojave黑暗主题调一下色调，感觉现在的黑色主题看着很鬼魅，另外对比度也需要调一下，谢谢！

**Comment by MustangYM** [comment]
> 可否新增sublimetext上的Monokai颜色主题，或者参考Mojave黑暗主题调一下色调，感觉现在的黑色主题看着很鬼魅，另外对比度也需要调一下，谢谢！

emmm....前几天有人说太灰了, 深一点, 有人叫我参照telegram, 现在我参照telegram的配色. 所以呢, 关于配色问题,  现在我觉得挺好, 不再接受建议.

**Comment by MingdaLin** [comment]
开发者您好，我自己打开xcode工程修改了主题颜色并成功运行通过了测试，但不知道要怎么部署到应用程序上，希望可以得到您的帮助。
祝好！
