### ISSUE TITLE
2.5版的小助手不能关闭黑暗模式

### ISSUE THREAD

**Issue by aixufan** [MustangYM/WeChatExtension-ForMac#247]
能像之前的版本给个开关自己选择主题么

**Comment by taIes** [comment]
我也遇见这种问题了， ，黑暗模式用着反而不舒服呢，也没办法关闭

**Comment by MustangYM** [comment]
> 能像之前的版本给个开关自己选择主题么

开关在里面啊

**Comment by MustangYM** [comment]
> 我也遇见这种问题了，，黑暗模式用着反而不舒服呢，也没办法关闭

主题模式-->黑夜模式 再次点击可以关闭

**Comment by aixufan** [comment]
> > 能像之前的版本给个开关自己选择主题么
> 
> 开关在里面啊

好吧，完全不想到
