### ISSUE TITLE
暗黑模式下文件预览和搜索问题

### ISSUE THREAD

**Issue by MingdaLin** [MustangYM/WeChatExtension-ForMac#249]
暗黑模式下，文件预览是空白的，并且搜索好友时，搜索结果底框是白色的，看着很不舒服，希望可以得到优化。谢谢！

**Comment by MustangYM** [comment]
> 暗黑模式下，文件预览是空白的，并且搜索好友时，搜索结果底框是白色的，看着很不舒服，希望可以得到优化。谢谢！

你的小助手是什么版本的

**Comment by mzzxuyi** [comment]
<img width="643" alt="Screen Shot 2020-03-22 at 2 25 59 PM" src="https://user-images.githubusercontent.com/32437256/77243801-20fbb280-6c49-11ea-818a-d831c64e496d.png">
<img width="283" alt="Screen Shot 2020-03-22 at 2 26 20 PM" src="https://user-images.githubusercontent.com/32437256/77243802-222cdf80-6c49-11ea-9f29-ddb4921b71b1.png">

**Comment by p0we7** [comment]
![image](https://user-images.githubusercontent.com/8407573/77248565-5a4a1780-6c75-11ea-9e65-332e7baee62f.png)

微信： 2.3.30
小助手： 2.5.1

**Comment by mzzxuyi** [comment]
<img width="1058" alt="Screen Shot 2020-03-22 at 8 06 09 PM" src="https://user-images.githubusercontent.com/32437256/77248955-99c63300-6c78-11ea-95b6-de3b30865a9e.png">
![WechatIMG486](https://user-images.githubusercontent.com/32437256/77248957-9d59ba00-6c78-11ea-870b-b8b680c808e1.jpeg)
微信： 2.3.30 (13329)
小助手： 2.5.0

**Comment by MustangYM** [comment]
[2.5.2已经修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.2), 另外, 最好升级2.4以上版本微信, 黑暗模式没有做低于2.4版本微信的适配, 百度一下下载地址
