### ISSUE TITLE
防撤回同步到手机的图片很模糊，能否还原高清

### ISSUE THREAD

**Issue by izozo** [MustangYM/WeChatExtension-ForMac#25]

**Comment by MustangYM** [comment]
> _No description provided._

只要你收到撤回图片消息, 就是原图

**Comment by izozo** [comment]
> > _No description provided._
> 
> 只要你收到撤回图片消息, 就是原图

我在mac 的微信客户端拦截到撤回消息  然后在手机查看拦截到的图片对比发现清晰度很模糊
