### ISSUE TITLE
纯黑主题

### ISSUE THREAD

**Issue by Jax0rz** [MustangYM/WeChatExtension-ForMac#251]
现在版本的深色模式整体是偏蓝色的，能否提供一个纯黑的，参考Telegram这两个主题：
<img width="492" alt="Xnip2020-03-22_15-21-39" src="https://user-images.githubusercontent.com/7557357/77244551-e7c74080-6c50-11ea-9348-a92f8d375da8.png">
<img width="492" alt="Xnip2020-03-22_15-21-21" src="https://user-images.githubusercontent.com/7557357/77244553-eb5ac780-6c50-11ea-9d54-6a9eb933d6f7.png">

**Comment by MustangYM** [comment]
> 现在版本的深色模式整体是偏蓝色的，能否提供一个纯黑的，参考电报这两个主题：
> <img alt="Xnip2020-03-22_15-21-39" width="492" src="https://user-images.githubusercontent.com/7557357/77244551-e7c74080-6c50-11ea-9348-a92f8d375da8.png">
> <img alt="Xnip2020-03-22_15-21-21" width="492" src="https://user-images.githubusercontent.com/7557357/77244553-eb5ac780-6c50-11ea-9d54-6a9eb933d6f7.png">

参考的就是电报的颜色
