### ISSUE TITLE
怎么切换回默认主题

### ISSUE THREAD

**Issue by GuYueJiaJie** [MustangYM/WeChatExtension-ForMac#252]
更新之后出现了黑色和粉色主题，挺不错的功能，如果我都不想用怎么切换回默认主题呢？
没有找到切换回默认主题的设置呀，只看到了黑色和粉色之间的切换，主题模式好像没法关闭。

**Comment by you-hengh** [comment]
同问,主题模式好像无法关闭?
![image](https://user-images.githubusercontent.com/34816426/77244682-c36c6380-6c52-11ea-8df0-64f9b5193c30.png)

**Comment by MustangYM** [comment]
> 更新之后出现了黑色和粉色主题，挺不错的功能，如果我都不想用怎么切换回切换主题呢？
> 没有找到切换回切换主题的设置呀，只看到了黑色和粉色之间的切换，主题模式好像没法关闭。

主题模式-->黑夜模式 再点击一次就关闭了
