### ISSUE TITLE
Colored mode flaws report

### ISSUE THREAD

**Issue by yiran7324** [MustangYM/WeChatExtension-ForMac#253]
![Screen Shot 2020-03-22 at 7 19 32 PM](https://user-images.githubusercontent.com/30183249/77248201-93cd5380-6c72-11ea-9f7d-6ecef68e97da.png)

- Header of searching remains the original color.

![Screen Shot 2020-03-22 at 7 23 06 PM](https://user-images.githubusercontent.com/30183249/77248204-96c84400-6c72-11ea-9774-66a249d18ac2.png)

- Buttons disappear left corner of the bottom.

WeChat - `Version 2.3.30 (13189)`
WA - `2.5.1`

**Comment by MustangYM** [comment]
[2.5.2fixed](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.2)
