### ISSUE TITLE
收不到微信通知

### ISSUE THREAD

**Issue by ProjectL2018** [MustangYM/WeChatExtension-ForMac#254]
大概从2.4.x开始（具体版本号不可考），微信不再进行消息提醒，消息中心里也没有记录，但是图标上的Badge是有的。检查了系统的提醒设置，一切正常。不太清楚和小助手有没有直接关系。

**Comment by joescon** [comment]
> 大概从2.4.x开始（具体版本号不可考），微信不再进行消息提醒，消息中心里也没有记录，但是图标上的Badge是有的。检查了系统的提醒设置，一切正常。不太清楚和小助手有没有直接关系。

试下升级到最新版？
我的
微信 2.3.30 （13329）
小助手 2.5.1 
目前一切正常，有消息推送有弹窗

**Comment by ProjectL2018** [comment]
一直保持在最新版。
