### ISSUE TITLE
黑夜模式下播放wx视频, 把鼠标悬浮在视频弹窗伤, 视频会被灰色蒙板覆盖

### ISSUE THREAD

**Issue by zszen** [MustangYM/WeChatExtension-ForMac#256]

**Comment by D-R-L** [comment]
相同问题

**Comment by MustangYM** [comment]
[2.5.2已经修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.2)

**Comment by wgxdz** [comment]
更新到2.5.3，但是黑暗模式下，微博小程序的视频依然有遮罩

![image](https://user-images.githubusercontent.com/3621048/78001155-2791c600-72ea-11ea-8203-207794792990.png)
