### ISSUE TITLE
希望支持屏蔽新消息提示的功能

### ISSUE THREAD

**Issue by zszen** [MustangYM/WeChatExtension-ForMac#257]
比如某些群的消息, 有红点, 总想去点, 分散了注意力

**Comment by MustangYM** [comment]
> 比如某些群的消息, 有红点, 总想去点, 分散了注意力

emmm...有会话置底功能

**Comment by zszen** [comment]
> > 比如某些群的消息, 有红点, 总想去点, 分散了注意力
> 
> emmm...有会话置底功能

就是置底的一堆群信息里, 有红点, 总去点

**Comment by MustangYM** [comment]
> > > 比如某些群的消息, 有红点, 总想去点, 分散了注意力
> > 
> > 
> > emmm...有会话置底功能
> 
> 就是置底的一堆群信息里, 有红点, 总去点

1. 微信本身有屏蔽消息提示功能, 此时收到新消息只是会话头像上依然有红点, 总的消息提示上并不会有红点  2. 此时会话置底, 你既看不见这个会话, 也看不见这个红点.

**Comment by MustangYM** [comment]
> > > 比如某些群的消息, 有红点, 总想去点, 分散了注意力
> > 
> > 
> > emmm...有会话置底功能
> 
> 就是置底的一堆群信息里, 有红点, 总去点

如果会话都置底了, 要翻几十上百个会话才能到底, 你还想去红点,  我实在不明白你为何要这样, 你为何不退出这个群.
