### ISSUE TITLE
一看就是程序员自学设计做的深色模式。给您提供个参考，加油。

### ISSUE THREAD

**Issue by smart-z** [MustangYM/WeChatExtension-ForMac#259]
虽然比较简单，还是首先感谢开发暗色模式。
没有时间给开发者提供太多支持，简单表达一下，希望可以给您提供一些内容。

深色模式现在比较简单，您可以参考一下，telegrram有mac版本，里面自带深色模式；
此外，配色也可以参考手机端的其他app的配色，比如whatsapp也有iOS的深色模式；

如下图，右侧这种配色设计方式美观度是不太灵的。左边画了个示意图，如果可以，给您提供一点参考，我也帮不上太多忙。感谢您开发小工具。

<img width="686" alt="iShot2020-03-2321 00 01" src="https://user-images.githubusercontent.com/1166675/77319152-4a036c80-6d49-11ea-84c4-f5bcbae171c7.png">

**Comment by MustangYM** [comment]
> 虽然比较简单，还是首先感谢开发暗色模式。
> 没有时间给开发者提供太多支持，简单表达一下，希望可以给您提供一些内容。
> 
> 深色模式现在比较简单，您可以参考一下，telegrram有mac版本，里面自带深色模式；
> 此外，配色也可以参考手机端的其他app的配色，比如whatsapp也有iOS的深色模式；
> 
> 如下图，右侧这种配色设计方式美观度是不太灵的。左边画了个示意图，如果可以，给您提供一点参考，我也帮不上太多忙。感谢您开发小工具。
> 
> <img alt="iShot2020-03-2321 00 01" width="686" src="https://user-images.githubusercontent.com/1166675/77319152-4a036c80-6d49-11ea-84c4-f5bcbae171c7.png">

爱你
