### ISSUE TITLE
2.5.1版小助手又打不开小程序了？

### ISSUE THREAD

**Issue by junglegiant** [MustangYM/WeChatExtension-ForMac#262]
WeChat是在App Store里更新到Version. 2.3.30 (13329)这一版（目前最新版），上一个版本的小助手奇迹般地打开过小程序，今天更新到2.5.1的小助手，发现又打不开小程序了欸。

![image](https://user-images.githubusercontent.com/42445235/77392890-e758b200-6dd6-11ea-9e9c-2bca12e03dbe.png)
![image](https://user-images.githubusercontent.com/42445235/77392913-f5a6ce00-6dd6-11ea-87ec-796b67a75d62.png)

**Comment by MustangYM** [comment]
> WeChat是在App Store里更新到Version. 2.3.30 (13329)这一版（目前最新版），上一个版本的小助手奇迹般地打开过小程序，今天更新到2.5.1的小助手，发现又打不开小程序了欸。
> 
> ![image](https://user-images.githubusercontent.com/42445235/77392890-e758b200-6dd6-11ea-9e9c-2bca12e03dbe.png)
> ![image](https://user-images.githubusercontent.com/42445235/77392913-f5a6ce00-6dd6-11ea-87ec-796b67a75d62.png)

微信本身2.4才能打开小程序

**Comment by junglegiant** [comment]
你们的微信都到2.4了吗

**Comment by MustangYM** [comment]
> 你们的微信都到2.4了吗

是的
