### ISSUE TITLE
touchbar 也粉了

### ISSUE THREAD

**Issue by taochangle** [MustangYM/WeChatExtension-ForMac#263]
![image](https://user-images.githubusercontent.com/7435144/77396566-f4799f00-6dde-11ea-8fb4-851bbbda6c1c.png)

**Comment by shencw** [comment]
+1

**Comment by MustangYM** [comment]
[2.5.2已经修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.2)
