### ISSUE TITLE
黑夜模式下边框展示颜色问题？建议把这个颜色也同步更新下。

### ISSUE THREAD

**Issue by shencw** [MustangYM/WeChatExtension-ForMac#264]
![image](https://user-images.githubusercontent.com/30680771/77398542-b2525c80-6de2-11ea-9923-5a2cbd4e5500.png)

**Comment by shencw** [comment]
历史记录也有类似的问题  :-)

**Comment by MustangYM** [comment]
[2.5.2已经修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.2)

**Comment by shencw** [comment]
Nice~
