### ISSUE TITLE
部分小程序不显示详情

### ISSUE THREAD

**Issue by pxz666** [MustangYM/WeChatExtension-ForMac#268]
![截屏2020-03-2513.41.23](https://gitee.com/pengxizhong/oss/raw/master/uPic/截屏2020-03-2513.41.23.png)

小程序详情：新浪微博转发
os:mac catalina
小助手最新版

**Comment by skpalan** [comment]
发现同样问题，问题如图。
<img width="342" alt="test01" src="https://user-images.githubusercontent.com/49622175/78273209-86b72c80-74dc-11ea-9e59-0c5ede13eedc.png">

OS: 10.15.2
小助手: 2.5.3
Wechat: 2.3.31
小程序: 热门微博，动森图鉴，Jump

**Comment by naihuayang** [comment]
2.4.0 的mac微信才支持

**Comment by joescon** [comment]
去下载了微信2.4.0的beta版本用上了
小程序可以打开，小助手也可以用。小助手似乎要重新安装一次
暂没发现其它冲突
