### ISSUE TITLE
在微信左上角搜索聊天记录等展示或需要优化？

### ISSUE THREAD

**Issue by shencw** [MustangYM/WeChatExtension-ForMac#269]
类似这种

![image](https://user-images.githubusercontent.com/30680771/77515388-6cb19480-6eb3-11ea-801b-d905337852ca.png)

![image](https://user-images.githubusercontent.com/30680771/77515646-d762d000-6eb3-11ea-92f1-3ab899c36256.png)

**Comment by shencw** [comment]
附加  聊天记录搜索内容

![image](https://user-images.githubusercontent.com/30680771/77515903-5b1cbc80-6eb4-11ea-9e21-6eba795efef5.png)

**Comment by MustangYM** [comment]
> 附加 聊天记录搜索内容
> 
> ![image](https://user-images.githubusercontent.com/30680771/77515903-5b1cbc80-6eb4-11ea-9e21-6eba795efef5.png)

这里可能不会优化
