### ISSUE TITLE
一直提示1.8.8更新，安装完成后却还是1.8.7

### ISSUE THREAD

**Issue by itjiazu** [MustangYM/WeChatExtension-ForMac#27]
一直提示1.8.8更新，安装完成后却还是1.8.7，安装完成后提示重启微信，然后还是会重复提示更新1.8.8

**Comment by itjiazu** [comment]
<img width="420" alt="Snipaste_2019-06-06_00-51-46" src="https://user-images.githubusercontent.com/11578898/58974631-63a4e900-87f5-11e9-9a37-45fa4781e142.png">

**Comment by UknowHui** [comment]
+1

**Comment by nstylec** [comment]
更新完版本号仍然显示1.8.7

**Comment by UJohn** [comment]
+1

**Comment by wdkGitHub** [comment]
+1 git fetch 重新覆盖还是1.8.7的版本

**Comment by whosnothungry** [comment]
+1

**Comment by tyl569** [comment]
而且设置 置底 和取消置底 直接闪退了

**Comment by zqso** [comment]
> 而且设置 置底 和取消置底 直接闪退了

我没有这个问题。
1. 最新微信.25
2. 最新助手1.8.7
3. mojave 10.14.5

**Comment by MustangYM** [comment]
> 一直提示1.8.8更新，安装完成后却还是1.8.7，安装完成后提示重启微信，然后还是会重复提示更新1.8.8

已经修复

**Comment by MustangYM** [comment]
> +1

已经修复

**Comment by MustangYM** [comment]
> 更新完版本号仍然显示1.8.7

已经修复

**Comment by MustangYM** [comment]
> +1,重新下载覆盖安装也一样

已经修复

**Comment by MustangYM** [comment]
> +1 git fetch 重新覆盖还是1.8.7的版本

已经修复

**Comment by MustangYM** [comment]
> +1

已经修复

**Comment by MustangYM** [comment]
> 而且设置 置底 和取消置底 直接闪退了

已经修复

**Comment by MustangYM** [comment]
> > 而且设置 置底 和取消置底 直接闪退了
> 
> 我没有这个问题。
> 
> 1. 最新微信.25
> 2. 最新助手1.8.7
> 3. mojave 10.14.5

已经修复

**Comment by MustangYM** [comment]
> 而且设置 置底 和取消置底 直接闪退了

你更新下插件和微信, 这个早就修复了的
