### ISSUE TITLE
请问作者大大可以增加一个转移微信聊天记录的功能吗？

### ISSUE THREAD

**Issue by ma3252788** [MustangYM/WeChatExtension-ForMac#270]
换电脑需要转移聊天记录，感觉这个功能应该很多人想要吧~

**Comment by MustangYM** [comment]
> 换电脑需要转移聊天记录，感觉这个功能应该很多人想要吧~

左下角 -> 备份与恢复  -> 备份聊天记录至电脑  || 恢复聊天记录至手机, 官方已经给出这个功能了
