### ISSUE TITLE
Alfred workflow无法配合此插件使用了

### ISSUE THREAD

**Issue by huguiqi** [MustangYM/WeChatExtension-ForMac#276]
alfred 输入wx 一直显示请先启动微信或是否安装插件

**Comment by huguiqi** [comment]
我微信版本是:2.3.29, 下载的是最新版本的插件和workflow

**Comment by bosconb** [comment]
> 我微信版本是:2.3.29, 下载的是最新版本的插件和workflow

App Version: Version. 2.4.0 (13941) Beta 146
Verbose: v2.4.0.146 (0x12040092)
System: OSX 10.15.4 build(19E242d)

正常使用

**Comment by huguiqi** [comment]
请问下你们mac版的2.4版本微信在哪下载，官网下载的最新app版本是：

2.3.30(13189)

**Comment by bosconb** [comment]
[官方2.4.0公测版](https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg)
