### ISSUE TITLE
退群监控在聊天框内显示不出来

### ISSUE THREAD

**Issue by DRL25** [MustangYM/WeChatExtension-ForMac#277]
微信版本 2.3.30 (13189)
小助手版本 2.5.2
外边可以看到有提示，点进去后什么都不显示，但是有一大片空白在那

![image](https://user-images.githubusercontent.com/30776662/77748235-fb144a80-705a-11ea-9f20-585733973099.png)
![image](https://user-images.githubusercontent.com/30776662/77748257-02d3ef00-705b-11ea-930d-cc8c4109d4aa.png)

还有个就是老问题，第二天点进微信群详情里后会显示一堆退群监控，现在显示不出来的情况下就是一大段空白

**Comment by MustangYM** [comment]
[已经移除](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.1)
