### ISSUE TITLE
输入法深色模式

### ISSUE THREAD

**Issue by Jax0rz** [MustangYM/WeChatExtension-ForMac#279]
可以用`defaults write com.tencent.xinWeChat NSRequiresAquaSystemAppearance 0`控制深色模式，但是最新版本输入无法改成深色
<img width="942" alt="Xnip2020-03-28_20-54-28" src="https://user-images.githubusercontent.com/7557357/77823488-7991ea80-7136-11ea-9f16-c5aedec6e92f.png">

**Comment by MustangYM** [comment]
我没试过这种方式, 我不太清楚作用是啥

**Comment by JasonCaodev** [comment]
之前版本可以用这个方法改成深色？

**Comment by MustangYM** [comment]
不懂你想表达的point
