### ISSUE TITLE
退群监控提醒次数过多了

### ISSUE THREAD

**Issue by BruceChao** [MustangYM/WeChatExtension-ForMac#281]
退群监控每次重新登录微信就需要再次手动打开；

屏幕解锁之后也有几率需要手动重新打开；

主要是这星期每个人的退群提示已经看了8遍了。。

希望大大能对退群监控加强下。

**Comment by MustangYM** [comment]
好, 我会修复这个问题

**Comment by xiaokaike** [comment]
@MustangYM 
你好，退群hook方法 `UpdateGroupMemberDetailIfNeeded`  是实时的么？还是有什么条件触发？

**Comment by MustangYM** [comment]
> @MustangYM
> 你好，退群hook方法 `UpdateGroupMemberDetailIfNeeded` 是实时的么？还是有什么条件触发？

群成员的刷新就会调用, 这个方法调用频率极高, 因为我目前并没有找到更好的办法去监听群成员的变化

**Comment by xiaokaike** [comment]
可以参数 hook
`objc_getClass("MMLogger"), @selector(logWithMMLogLevel:module:file:line:func:message:)`
这个方法，貌似有群人数的变化

**Comment by MustangYM** [comment]
[已经移除](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.1)
