### ISSUE TITLE
希望增加一个mac和ipad之间消息同步的功能

### ISSUE THREAD

**Issue by echo-cool** [MustangYM/WeChatExtension-ForMac#282]
因为目前mac和ipad微信客户端只能登录一个，使用起来很不方便。
因为微信小助手能读取到微信消息内容，如果不能实现两端同时登陆的话，可以考虑开放自定义接口功能，把收到的数据post到用户指定的服务器。

**Comment by MustangYM** [comment]
> 因为目前mac和ipad微信客户端只能登录一个，使用起来很不方便。
> 因为微信小助手能读取到微信消息内容，如果不能实现两端同时登陆的话，可以考虑开放自定义接口功能，把收到的数据post到用户指定的服务器。

这不是常规使用场景
