### ISSUE TITLE
主题模式很棒，建议可以自定义颜色

### ISSUE THREAD

**Issue by leon-hw** [MustangYM/WeChatExtension-ForMac#283]
新增加了这个主题模式功能，感觉暗黑颜色不是很好，会有很多信息和颜色显示相冲突，影响阅读；粉色相对好一些，可以作为小女生使用，但男生用起来有点不合适。
建议：
1、可以新增自定义颜色或者配色，增加透明度的调节；
2、如果不能增加自定义，可以多增加几套颜色模式。
多谢！

**Comment by MustangYM** [comment]
没时间弄了
