### ISSUE TITLE
搜索下拉深色模式

### ISSUE THREAD

**Issue by Jax0rz** [MustangYM/WeChatExtension-ForMac#284]
搜索下拉框，可否支持深色
<img width="942" alt="Xnip2020-03-30_11-16-37" src="https://user-images.githubusercontent.com/7557357/77871875-07c1ba00-7278-11ea-8f85-156d0b22c32b.png">

**Comment by MustangYM** [comment]
> 搜索下拉框，可否支持深色
> <img alt="Xnip2020-03-30_11-16-37" width="942" src="https://user-images.githubusercontent.com/7557357/77871875-07c1ba00-7278-11ea-8f85-156d0b22c32b.png">

不准备适配这里
