### ISSUE TITLE
增加了太多功能，引发问题

### ISSUE THREAD

**Issue by PageGuo** [MustangYM/WeChatExtension-ForMac#288]
我们只需要一些基础功能：拦截消息撤回、多个微信登录这些。
不要再多添加东西了，新版小助手使用之后有bug
1、收到消息之后列表跳动；
2、列表里点击对话，名称跳动。

建议有一个稳定版本，然后有个体验版本。。没有这么大的精力测试，还不如完美一些

**Comment by MustangYM** [comment]
> 我们只需要一些基础功能：拦截消息撤回、多个微信登录这些。
> 不要再多添加东西了，新版小助手使用之后有bug
> 1、收到消息之后列表跳动；
> 2、列表里点击对话，名称跳动。
> 
> 建议有一个稳定版本，然后有个体验版本。。没有这么大的精力测试，还不如完美一些

现在好几个人爆这个BUG, 但是我这边实在无法复现, 所以你提供下微信什么版本, 小助手什么版本, 我具体看下

**Comment by PageGuo** [comment]
微信Version. 2.3.30 (13329)，小助手2.5.2。
在聊天列表切换对话，切换到之前未点击过的特别明显

**Comment by MustangYM** [comment]
> 微信Version. 2.3.30 (13329)，小助手2.5.2。
> 在聊天列表切换对话，切换到之前未点击过的特别明显

我已经找到问题并修复了, 晚点可能会发个版, 顺便发布另外一些修复

**Comment by PageGuo** [comment]
好的，感谢~已经回退到上一个版本了，等修复再更新

**Comment by MustangYM** [comment]
[2.5.3](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.3)

**Comment by xieao100** [comment]
是的 我这里也发现这个问题了，来消息时你刷新了整个消息列表，应该只刷新某个item即可

**Comment by PageGuo** [comment]
现在每发出一条消息的时候，消息列表都会刷新

**Comment by MustangYM** [comment]
> 现在每发出一条消息的时候，消息列表都会刷新

2.5.3

**Comment by PageGuo** [comment]
> > 现在每发出一条消息的时候，消息列表都会刷新
> 
> 2.5.3

2.5.3解决了点击抖动，发送消息后列表刷新没有解决
