### ISSUE TITLE
微信打开网页链接显示异常

### ISSUE THREAD

**Issue by ueiu** [MustangYM/WeChatExtension-ForMac#290]
![屏幕快照 2020-03-31 下午3 58 50](https://user-images.githubusercontent.com/39592269/78002021-23f15400-7369-11ea-9405-3992bf60e50e.jpg)
点击微信内分享的网页链接不会正常显示内容，并且窗口大小过长
小助手版本：2.5.2
微信版本：2.3.30

**Comment by ueiu** [comment]
[操作视频.zip](https://github.com/MustangYM/WeChatExtension-ForMac/files/4407615/default.zip)

附件zip是具体的操作，不是偶发的问题

**Comment by MustangYM** [comment]
你连接有问题吧

**Comment by ueiu** [comment]
手机打开是正常的，但电脑微信的话每个链接都会这样

**Comment by MustangYM** [comment]
贴一下连接

**Comment by ueiu** [comment]
第一个：https://mp.weixin.qq.com/s/x8gfghe91Wb2_PUT6HLXIA
第二个：https://mp.weixin.qq.com/s/QUaYgMYFf5TaWQWFWn0LZQ
第三个：https://github.com/avelino/awesome-go
以上链接都是在电脑微信无法打开浏览，但手机微信正常

**Comment by MustangYM** [comment]
> 第一个：https://mp.weixin.qq.com/s/x8gfghe91Wb2_PUT6HLXIA
> 第二个：https://mp.weixin.qq.com/s/QUaYgMYFf5TaWQWFWn0LZQ
> 第三个：https://github.com/avelino/awesome-go
> 以上链接都是在电脑微信无法打开浏览，但手机微信正常

我测试了下, 是可以访问的...

**Comment by ueiu** [comment]
这么神奇的问题嘛。。微信版本号是一样的吗

MustangYM <notifications@github.com> 于2020年3月31日周二 下午5:39写道：

**Comment by ueiu** [comment]
我把微信、微信小助手卸载重装后，正常了。。估计是微信一些莫名其妙的问题。
