### ISSUE TITLE
深色模式，左侧聊天列表选中高亮后，一会就不高亮了。

### ISSUE THREAD

**Issue by nickyjokey** [MustangYM/WeChatExtension-ForMac#291]
深色模式，左侧聊天列表选中高亮后，一会就不高亮了。
这个有的时候反应自己在哪个群聊天要反应一下，容易出错。
建议改为和普通模式一样，左侧选中有个高亮样式。

**Comment by MustangYM** [comment]
> 深色模式，左侧聊天列表选中高亮后，一会就不高亮了。
> 这个有的时候反应自己在哪个群聊天要反应一下，容易出错。
> 建议改为和普通模式一样，左侧选中有个高亮样式。

这个是故意而为之的, 不是bug
