### ISSUE TITLE
微信 2.4.0 (13962) Beta 147，小助手 2.5.3 暗黑模式小程序不显示，非暗黑模式正常

### ISSUE THREAD

**Issue by ehlxr** [MustangYM/WeChatExtension-ForMac#292]
![image](https://user-images.githubusercontent.com/11313370/78006250-52722d80-736f-11ea-95ad-6ff8f0f15cfa.png)

**Comment by luckysonyu99** [comment]
我也有相同的情况，请问你的解决了吗？

**Comment by ehlxr** [comment]
没有，没用暗黑模式了
