### ISSUE TITLE
免认证登录不能同步聊天记录

### ISSUE THREAD

**Issue by doersa** [MustangYM/WeChatExtension-ForMac#297]
如题！

**Comment by fg4084** [comment]
也有同样的问题，这一点没有完善吗？

**Comment by n00d1e5** [comment]
将 Forbid Update 取消勾选，则可同步聊天记录。
此时 Free-Login 保持勾选。
WeChat 2.4.0 (13962) Beta 147
Wechat Assistant 2.5.5

BTW, WeChat 的 C 应该大写，Wechat Assistant 很多处为小写。

**Comment by lujianzhao** [comment]
禁止更新取消勾选，免认证登录保持勾选。
但还是不能同步聊天记录。
版本：
WeChatExtension-ForMac：2.5.7
微信版本：2.3.31 (13331)

**Comment by rootphantomer** [comment]
免登陆后会出现这样的问题
![image](https://user-images.githubusercontent.com/6481352/88247371-14a76500-ccd0-11ea-8a02-a4c2752bdedf.png)
