### ISSUE TITLE
黑暗模式下 收藏的内容字体部分区域字体颜色为黑色,跟背景融合了,看不清楚文字

### ISSUE THREAD

**Issue by yuebanme** [MustangYM/WeChatExtension-ForMac#299]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/21034270/78215170-7c4f5f80-74e9-11ea-9db8-001497c411b6.png">

可以优化下,黑暗模式时的字体颜色

**Comment by mingjun97** [comment]
查看别人转发的聊天记录也有这个问题～

**Comment by lexrus** [comment]
@yuebanme @mingjun97
Hi，#316 已经修了这个问题，包括转发的聊天记录页面，可以从 master 分支尝试。
