### ISSUE TITLE
好几处闪退，微信2.3.24

### ISSUE THREAD

**Issue by xieao100** [MustangYM/WeChatExtension-ForMac#3]
比方说点击关于小助手 取消聊天框置底 求更新修复

**Comment by MustangYM** [comment]
会更进，目前在五一休假，会慢一点哈哈

**Comment by plutopaner** [comment]
微信版本：Version. 2.3.24 (12246)
OS版本：10.14.4 (18E226)。
微信无法多开。。。

**Comment by MustangYM** [comment]
> 比方说点击关于小助手取消聊天框置底求更新修复

好的

**Comment by MustangYM** [comment]
> 微信版本：版本。2.3.24（12246）
> OS版本：10.14.4（18E226）。
> 微信无法多开...

我特意升级到了10.14.4, 我这边是能多开的, 我再看看

**Comment by MustangYM** [comment]
> 比方说点击关于小助手 取消聊天框置底 求更新修复

已修复

**Comment by VincentLau0928** [comment]
微信版本：Version. 2.3.24 (12246)
系统版本：10.14.4 (18E226)
点击对话框多选后会闪退

**Comment by MustangYM** [comment]
> 微信版本：Version. 2.3.24 (12246)
> 系统版本：10.14.4 (18E226)
> 点击对话框多选后会闪退
1.7.7已修复

**Comment by xieao100** [comment]
> > 微信版本：Version. 2.3.24 (12246)
> > 系统版本：10.14.4 (18E226)
> > 点击对话框多选后会闪退
> > 1.7.7已修复

1.78最新版体验反馈：
1、使用系统浏览器打开微信的网页失效。
2、取消置底没问题了，置底还是闪退如果你那边可以 请多来回至底然后取消再至底试几次就会复现这个问题了
3、手机发送指令给自己失效 提示No such file or directory
求更新修复。谢谢！

**Comment by luistrong** [comment]
> > > 微信版本：Version. 2.3.24 (12246)
> > > 系统版本：10.14.4 (18E226)
> > > 点击对话框多选后会闪退
> > > 1.7.7已修复
> 
> 1.78最新版体验反馈：
> 1、使用系统浏览器打开微信的网页失效。
> 2、取消置底没问题了，置底还是闪退如果你那边可以 请多来回至底然后取消再至底试几次就会复现这个问题了
> 3、手机发送指令给自己失效 提示No such file or directory
> 求更新修复。谢谢！

本来置底没闪退, 看了你的评论取消置底后再置底就闪退了, 后来就没再成功过一直闪退..

**Comment by MustangYM** [comment]
> > > > 微信版本：Version. 2.3.24 (12246)
> > > > 系统版本：10.14.4 (18E226)
> > > > 点击对话框多选后会闪退
> > > > 1.7.7已修复
> > 
> > 
> > 1.78最新版体验反馈：
> > 1、使用系统浏览器打开微信的网页失效。
> > 2、取消置底没问题了，置底还是闪退如果你那边可以 请多来回至底然后取消再至底试几次就会复现这个问题了
> > 3、手机发送指令给自己失效 提示No such file or directory
> > 求更新修复。谢谢！
> 
> 本来置底没闪退, 看了你的评论取消置底后再置底就闪退了, 后来就没再成功过一直闪退..

经测试, 1.7.9版本应该是没有这个问题的, 我修复了的
