### ISSUE TITLE
能否添加一个「关键词拉群」的小功能

### ISSUE THREAD

**Issue by bellafay** [MustangYM/WeChatExtension-ForMac#303]
就是设置一个关键词，在私聊中提到这个关键词，就会自动触发特定群的邀请链接。方便邀请别人进群。

**Comment by MustangYM** [comment]
> 就是设置一个关键词，在私聊中提到这个关键词，就会自动触发特定群的邀请链接。方便邀请别人进群。

奇怪的需求

**Comment by bellafay** [comment]
这个功能很多很多软件都有的，并不小众。但基本上都是win版的，mac端目前没有提供此类功能的软件。
还有，那个「退群监控」如果增加一些细节设置就更好了。比如：「监控特定某群的退群情况」、「t退群消息可以直接转发给自己或某个设定的微信号」、「退群消息内容再丰富些，比如：对方昵称、微信号、wxid、退群时间等」……
只是一些自己体验上的小建议，大佬如果可以实现的话就更好了。

**Comment by MustangYM** [comment]
> 这个功能很多很多软件都有的，并不小众。但基本上都是win版的，mac端目前没有提供此类功能的软件。
> 还有，那个「退群监控」如果增加一些细节设置就更好了。比如：「监控特定某群的退群情况」、「t退群消息可以直接转发给自己或某个设定的微信号」、「退群消息内容再丰富些，比如：对方昵称、微信号、wxid、退群时间等」……
> 只是一些自己体验上的小建议，大佬如果可以实现的话就更好了。

如果需要这种自动化的邀请进群方式, 而且是固定关键词, 必然是大批量了, 要么灰产, 要么盈利相关, 一定要我点破吗......

**Comment by bellafay** [comment]
首先不是什么灰产，我只是想提高一下拉群效率罢了。微信里拉人进群要点右上角，选中指定的人才行，实在有些麻烦。如果在聊天中触发一个指令，自动发邀请链接，多省事。
其次，如果是黑产，我直接上win版软件弄就行了，甚至还可以挂服务器上。如此大批量的操作还用mac的话，成本似乎有点高。

这些都是我使用中的感觉，说出来罢了。只是希望能够更好而已。

**Comment by simbawus** [comment]
作为一个社交达人 同求支持此功能

**Comment by PlayerYK** [comment]
如果限制为单人聊天，自动拉群可以做吗？
