### ISSUE TITLE
微信小程序没看到，还是原来的消息

### ISSUE THREAD

**Issue by cilla123** [MustangYM/WeChatExtension-ForMac#304]
![image](https://user-images.githubusercontent.com/15205392/78505465-44c10b80-77a6-11ea-9357-94351f0c6798.png)
![image](https://user-images.githubusercontent.com/15205392/78505479-4db1dd00-77a6-11ea-8033-3ff914649d6d.png)

**Comment by MustangYM** [comment]
微信2.4版本才开始支持小程序
