### ISSUE TITLE
播放视频时一直有滋啦的声音

### ISSUE THREAD

**Issue by D-R-L** [MustangYM/WeChatExtension-ForMac#305]
微信版本 2.3.30 (13189)
小助手版本 2.5.3

点开群里的视频 所有的播放都一直伴随着滋啦声
用其他软件点开本地的群视频没事

**Comment by D-R-L** [comment]
奇怪的是发完这个issue后 这两天又没出现过这情况了……

**Comment by MustangYM** [comment]
小助手没有对播放器做修改
