### ISSUE TITLE
能否提供一下自动回复里面匹配规则的使用方法？

### ISSUE THREAD

**Issue by fsnhljz** [MustangYM/WeChatExtension-ForMac#307]
我网上搜索过正规则是什么东西，但还是不懂用，希望能够提供几个例如让我能够参看一下。例如，我希望对方一段文字里面有“我想你”三个字，就能够匹配回复“我也想你了”。我试过，对方发来“我想你了”多了一个“了”就不能匹配，应该用正规则能实现的吧？

**Comment by MustangYM** [comment]
[在线正则测试](https://tool.oschina.net/regex/)
