### ISSUE TITLE
腾讯投票 黑暗模式内容全黑

### ISSUE THREAD

**Issue by yangjianyao** [MustangYM/WeChatExtension-ForMac#311]
App Version: Version. 2.4.0 (13962) Beta 147
Verbose: v2.4.0.147 (0x12040093)
System: OSX 10.15.4 build(19E287)
Model: MacBookPro15,2
Hash: 203338290
Build Date: Mar  6 2020
Build Time: 22:17:04
Lang: zh-Hans-CN

打开微信投票小程序，内容全黑，什么都看不到，但是可以点击，应该是适配问题
![image](https://user-images.githubusercontent.com/44353471/78983798-7ac01000-7b57-11ea-9029-c93548a613ec.png)

**Comment by MustangYM** [comment]
[2.5.5](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.5)
