### ISSUE TITLE
mac catalina 10.15.1 闪退

### ISSUE THREAD

**Issue by DNSun** [MustangYM/WeChatExtension-ForMac#315]
今天更新新版本后微信打开闪退

**Comment by maimai123** [comment]
我也是！！

**Comment by MustangYM** [comment]
> 今天更新新版本后微信打开闪退

微信是什么版本, 2.3.31还是2.4

**Comment by TigerZhag** [comment]
> > 今天更新新版本后微信打开闪退
> 
> 微信是什么版本, 2.3.31还是2.4

微信2.3.26版本，系统是 10.15.3
手机授权登录后微信闪退


[wechat.log](https://github.com/MustangYM/WeChatExtension-ForMac/files/4467733/wechat.log)

**Comment by TigerZhag** [comment]
更新到最新版微信后就可以了

**Comment by DNSun** [comment]
是的,更新后可以了
