### ISSUE TITLE
防撤回消息bug

### ISSUE THREAD

**Issue by L1cardo** [MustangYM/WeChatExtension-ForMac#32]
撤回了一个消息以后，会显示拦截到一条撤回消息，然后这个后面有一个昵称，，，
但是这个不是我的昵称，或者不是现在使用的，我想问一下这个是哪里获取的昵称信息？
![IMG_0035](https://user-images.githubusercontent.com/33802186/59146470-2886fd80-8a21-11e9-8273-865da516a747.jpg)

**Comment by L1cardo** [comment]
我看了一下代码，上面显示获取用户名或者昵称，但是我的用户名昵称都不是abudureyimujiang啊。。。。
<img width="536" alt="屏幕快照2019-06-08下午7 12 30" src="https://user-images.githubusercontent.com/33802186/59146548-093ca000-8a22-11e9-9fae-dec0a4601e42.png">

**Comment by MustangYM** [comment]
> 我看了一下代码，上面显示获取用户名或者昵称，但是我的用户名昵称都不是abudureyimujiang啊。。。。
> <img alt="屏幕快照2019-06-08下午7 12 30" width="536" src="https://user-images.githubusercontent.com/33802186/59146548-093ca000-8a22-11e9-9fae-dec0a4601e42.png">

sendTextMessage:A  toUserName:B ....参数A和B都是你自己, 相当于自己发给自己, 才能同步到手机, 而这个显示出来的昵称是消息发送者的昵称

**Comment by L1cardo** [comment]
就算是自己发送给自己的，但是都不是我的用户名和昵称。

**Comment by MustangYM** [comment]
> 就算是自己发送给自己的，但是都不是我的用户名和昵称。

显示出来的昵称或者微信号或者微信id是从微信原始消息内容里爬的, 你再验一下?

**Comment by L1cardo** [comment]
![C7343453-0ED1-4349-BF9E-692BE5C0AD12](https://user-images.githubusercontent.com/33802186/59169542-65f8a180-8b6d-11e9-97df-3b5f849ae88a.jpeg)

微信号，微信昵称就是上面这个。你说的微信id怎么看我不知道。他从哪里爬的....

**Comment by MustangYM** [comment]
> ![C7343453-0ED1-4349-BF9E-692BE5C0AD12](https://user-images.githubusercontent.com/33802186/59169542-65f8a180-8b6d-11e9-97df-3b5f849ae88a.jpeg)
> 
> 微信号，微信昵称就是上面这个。你说的微信id怎么看我不知道。他从哪里爬的....

微信消息发送使用的唯一id, 原则上是内部使用, 老用户界面上不会显示出来(因为自定义微信号). 小部分会直接显示出来, 就是 "wxid_"开头的那种.

**Comment by L1cardo** [comment]
那这个就是腾讯的锅了？麻烦你了

**Comment by MustangYM** [comment]
> 那这个就是腾讯的锅了？麻烦你了

我看了代码, 原则上应该不会出现你说的问题. 正好. 凑合将就把之前的这块BUG处理下, 下午你重新拉代码看看, 但是可能不会做更新, 因为改动很小.

**Comment by L1cardo** [comment]
我也不是搞编程的，只能说略懂一二。还是希望你把这个还称获取用户名的，别人看起来也方便些。有问题的话我也会协助你的

**Comment by MustangYM** [comment]
> 我也不是搞编程的，只能说略懂一二。还是希望你把这个还称获取用户名的，别人看起来也方便些。有问题的话我也会协助你的

就是在处理这个问题

**Comment by L1cardo** [comment]
我看你昨天做了一些更新，是还没发布吗？
看来得要自己xcode run一下啦

**Comment by MustangYM** [comment]
获取陌生人昵称的方法我暂时还没找到，最近也比较忙，容我再琢磨琢磨




| |
晏茂
|
|
邮箱：ymoomy@yeah.net
|

签名由 网易邮箱大师 定制

在2019年06月11日 09:48，Licardo 写道：

我看你昨天做了一些更新，是还没发布吗？
看来得要自己xcode run一下啦

**Comment by L1cardo** [comment]
我也发现了，陌生人的还是wechatid，今天群聊消息撤回我发现了。还有一个问题，就是群聊消息撤回把手机搞炸了。加一个筛选项目吧。#34
