### ISSUE TITLE
[建议]取消或变更防撤回的快捷键位

### ISSUE THREAD

**Issue by SeanGol** [MustangYM/WeChatExtension-ForMac#323]
![image](https://user-images.githubusercontent.com/8014327/79181339-bd773600-7e3e-11ea-90d2-025769f6f88c.png)

### 需求来源:

cmd + T 这个快捷键的使用频率较高, 如: Chrome新建标签页, VSCode跳转功能, iTerm 新建窗口等等, 导致经常误触, 关闭了防撤回功能. 

### 预计实现:

取消或更改该快捷键位

**Comment by gwsh** [comment]
Agree

**Comment by zqso** [comment]
+1. 

如果有使用Keyboard Maestro，可以自动检查防撤回是否选中。

![image](https://user-images.githubusercontent.com/15665504/80290813-e29c5c00-86fc-11ea-868c-33c782655f10.png)

**Comment by all4fun** [comment]
+1
