### ISSUE TITLE
暗黑模式能根据系统来自动适配吗？

### ISSUE THREAD

**Issue by DreamsCat** [MustangYM/WeChatExtension-ForMac#324]
现在暗黑模式需要手动开启，能根据系统自动切换日间模式和暗黑模式吗

**Comment by MustangYM** [comment]
> 现在暗黑模式需要手动开启，能根据系统自动切换日间模式和暗黑模式吗

当时做了手动开关的原因就是怕有的人会不喜欢这样强制变, 众口难调啊

**Comment by DreamsCat** [comment]
很感谢作者，希望可以两者相结合一下，既提供一个开关，打开后就可以根据系统来进行自动适配的，这样的话相要哪种模式都是可以的

**Comment by DreamsCat** [comment]
> > 现在暗黑模式需要手动开启，能根据系统自动切换日间模式和暗黑模式吗
> 
> 当时手工手动开关的原因就是怕有的人会不喜欢这样强制变，众口难调啊

很感谢作者，希望可以两者之间相结合一下，既提供一个开关，打开后就可以根据系统来进行自动适应的，这样的话相要与此模式都是可以的

**Comment by MustangYM** [comment]
> > > 现在暗黑模式需要手动开启，能根据系统自动切换日间模式和暗黑模式吗
> > 
> > 
> > 当时手工手动开关的原因就是怕有的人会不喜欢这样强制变，众口难调啊
> 
> 很感谢作者，希望可以两者之间相结合一下，既提供一个开关，打开后就可以根据系统来进行自动适应的，这样的话相要与此模式都是可以的

没必要, 几乎没人会常改变系统颜色

**Comment by DreamsCat** [comment]
> > > > 现在暗黑模式需要手动开启，能根据系统自动切换日间模式和暗黑模式吗
> > > 
> > > 
> > > 当时手工手动开关的原因就是怕有的人会不喜欢这样强制变，众口难调啊
> > 
> > 
> > 很感谢作者，希望可以两者之间相结合一下，既提供一个开关，打开后就可以根据系统来进行自动适应的，这样的话相要与此模式都是可以的
> 
> 没必要, 几乎没人会常改变系统颜色

再次感谢作者的回复，在最新版本的系统上，浅色和深色模式是可以根据日落时间自动切换的，我相信开启自动切换浅色和深色模式的人也不在少数，我对比了一下其他常用的软件，大部分都是可以根据系统自动切换浅色和深色，这是我提供的一点小小的建议，谢谢🙏

**Comment by hologerry** [comment]
谢谢作者，同求此功能🙏
