### ISSUE TITLE
开启免认证登陆，在开启自动登陆后，自动登陆就无法取消了

### ISSUE THREAD

**Issue by yiliuchen** [MustangYM/WeChatExtension-ForMac#325]

**Comment by MustangYM** [comment]
> _No description provided._

这个功能在第一次打开后就默认打开了, 从此后都自动登录了. 如果你要取消, 证明你不需要登录, 去掉免认证登录就好了

**Comment by MustangYM** [comment]
> _没有提供描述。_

在手机端打开微信，点退出Mac微信
Mac端就可以回到登录界面了
