### ISSUE TITLE
[建议]希望自动回复能支持导出倒入功能

### ISSUE THREAD

**Issue by zszen** [MustangYM/WeChatExtension-ForMac#329]
给某个群做了云分享的自动回复，创建起来还是很麻烦的， 希望有备份和恢复的功能， 这样不会数据丢失白辛苦

**Comment by MustangYM** [comment]
> 分享的自动回复，创建起来还是很麻烦的，希望有备份和恢复的功能，这样不会数据丢失白辛苦

微信自己有

**Comment by zszen** [comment]
> > 分享的自动回复，创建起来还是很麻烦的，希望有备份和恢复的功能，这样不会数据丢失白辛苦
> 
> 微信自己有

我说的是“自动回复”这个插件的备份和恢复功能, 不是聊天的备份和恢复
