### ISSUE TITLE
是不是多开和小程序只能二选一了？

### ISSUE THREAD

**Issue by UJohn** [MustangYM/WeChatExtension-ForMac#330]
Issue示例
1. MacOS版本 : 10.15.3
2. 微信版本 : 2.4.0 beta
3. 小助手版本 : 2.5.4
4. BUG描述 : 
1）选择多开就无法启动小程序，选择小程序就无法多开。
2）Mac控制失灵无反应
5. 操作场景 : 正常操作

**Comment by MustangYM** [comment]
其实可以多开和小程序打开共存, 比方现在我打开了微信A和微信B, 那么极有可能出现其中一个微信不能打开小程序, 而另一个却可以, 所以做了这个二选一. Mac控制失灵是指远程控制吗.有效的, 在Mac上登录微信, 手机端 -->   自己发送给自己相应的指令
