### ISSUE TITLE
 黑夜模式打开小程序/excel/word文档黑屏无法正常显示

### ISSUE THREAD

**Issue by FengFeng-is-me** [MustangYM/WeChatExtension-ForMac#332]
Issue示例
1. MacOS版本 :10.15.5
2. 微信版本 :2.4.0 beat
3. 小助手版本 : 2.5.4
4. BUG描述 : 黑夜模式打开小程序全黑,并且除了正常聊天其他字体颜色不适应影响正常阅读,希望下个版本能改一下,参考手机的黑页模式取色.
![image](https://user-images.githubusercontent.com/32693877/79375810-d04b5100-7f8b-11ea-9691-38022dce0a33.png)

**Comment by MustangYM** [comment]
> 问题示例
> 
> 1. MacOS版本：10.15.5
> 2. 微信版本：2.4.0 beat
> 3. 小助手版本：2.5.4
> 4. BUG描述：黑夜模式打开小程序全黑，并且除了正常聊天其他字体颜色不适应影响正常阅读，希望下一个版本能改一下，参考手机的黑页模式取色。
>    ![图片](https://user-images.githubusercontent.com/32693877/79375810-d04b5100-7f8b-11ea-9691-38022dce0a33.png)

[2.5.5](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.5)

**Comment by FengFeng-is-me** [comment]
太棒了吧,刚提没一天就补了.......
