### ISSUE TITLE
微信收藏的笔记一栏显示有两条大白边

### ISSUE THREAD

**Issue by ForrestWang-su** [MustangYM/WeChatExtension-ForMac#333]
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.0
3. 小助手版本 : 2.5.5
4. BUG描述 : 微信收藏的笔记一栏显示有异常,并且在全部收藏中只要是属于笔记的也会出现这个白边

![image](https://user-images.githubusercontent.com/32693877/79480951-68efd880-8041-11ea-8c01-13592fda5a9e.png)

**Comment by MustangYM** [comment]
[v2.5.6](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.6)
