### ISSUE TITLE
能否组织志愿者进行代码审查？

### ISSUE THREAD

**Issue by cow8** [MustangYM/WeChatExtension-ForMac#334]
能否组织志愿者进行代码审查？

**Comment by MustangYM** [comment]
> 能否组织志愿者进行代码审查？

这太好了, 我非常乐意, 因为我个人的时间和经历确实不太够用了

**Comment by sherlockfff** [comment]
> > 能否组织志愿者进行代码审查？
> 
> 这太好了, 我非常乐意, 因为我个人的时间和精力确实不太够用了

你好，我想问一下免登录功能是如何实现的？会保存手机端微信的session吗？
