### ISSUE TITLE
Mac 版本微信公众号列表批量多选、全选删除

### ISSUE THREAD

**Issue by feeltens** [MustangYM/WeChatExtension-ForMac#337]
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.0
3. 小助手版本 : 2.5.5
4. BUG描述 : 微信公众号列表不支持批量多选、全选删除
5. 操作场景 : 2.5.5小助手只支持会话列表的多选批量删除，不支持微信公众号列表的批量多选、全选删除。

**Comment by finding** [comment]
1. MacOS版本 : 10.15.2
2. 微信版本 : 2.4.0
3. 小助手版本 : 2.5.5
4. BUG描述 : 开启免认证登录后, 登录前手机收到的消息无法同步电脑. 关闭自动登录后就可以同步
5. 操作场景 : 小助手 > 开启免认证登录

**Comment by MustangYM** [comment]
[v2.5.6](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.6)
