### ISSUE TITLE
这几天没注意，小助手居然自动不见了

### ISSUE THREAD

**Issue by 44886** [MustangYM/WeChatExtension-ForMac#339]
之前是安装过小助手的。

这几天一直没注意，今天突然发现有人撤回了消息，这一看顶部任务栏，才发现小助手居然不见了，

在 oh my wechat 中更新发现：提示小助手没有安装。

你们遇到这样的情况没

**Comment by MustangYM** [comment]
是不是更新过微信客户端，重新安装下小助手即可
