### ISSUE TITLE
能否增加“撤回消息同步到手机”这个功能的筛选

### ISSUE THREAD

**Issue by DarcyLau** [MustangYM/WeChatExtension-ForMac#34]
比如开启后可选择所有消息或者只同步单聊消息

**Comment by DarcyLau** [comment]
如果遇到撤回多的群，怕是微信会炸掉~~

**Comment by Maturelittleman** [comment]
对对对, 没有筛选的话手机要炸

**Comment by L1cardo** [comment]
哈哈哈哈  刚准备要提，就有别人提了。我今天也是群聊撤回把手机搞炸了

**Comment by MustangYM** [comment]
> 如果遇到撤回多的群，怕是微信会炸掉~~

已更新

**Comment by MustangYM** [comment]
> 对对对, 没有筛选的话手机要炸

已更新

**Comment by MustangYM** [comment]
> 哈哈哈哈 刚准备要提，就有别人提了。我今天也是群聊撤回把手机搞炸了

已更新
