### ISSUE TITLE
微信重启后，自定义的开关配置被重置了

### ISSUE THREAD

**Issue by kevin-xk** [MustangYM/WeChatExtension-ForMac#341]
1. MacOS版本 : 版本 10.14.5（版号 18F132）
2. 微信版本 : Version. 2.3.30 (13189)
3. 小助手版本 : 2.5.5
4. BUG描述 : 微信重启后，微信小助手里的自定义配置被重置了
5. 操作场景 : 
问题1）微信小助手——>退群监控——>勾选，退出微信重新登录，你会发现退群监控又被取消了
问题2）同上，打开"允许打开小程序"，重启后也无法生效

**Comment by MustangYM** [comment]
> 1. MacOS版本：版本10.14.5（版号18F132）
> 2. 微信版本：版本。2.3.30（13189）
> 3. 小助手版本：2.5.5
> 4. BUG描述：微信重启后，微信小助手里的自定义配置被重置了
> 5. 操作场景：
>    问题1）微信小助手->退群监控->重置，退出微信重新登录，你会发现退群监控又被取消了
>    问题2）同上，打开“允许打开小程序”，重启后也无法体现

我测试了, 退群监控确实有这个BUG, 已经修复了下个版本会发出来, "允许打开小程序"是和"微信多开"互斥的, 当你打开微信多开的时候, 小程序这个"勾"会自动去掉
