### ISSUE TITLE
免认证登录消息无法同步

### ISSUE THREAD

**Issue by finding** [MustangYM/WeChatExtension-ForMac#342]
Issue示例
1. MacOS版本 : 10.15.2
2. 微信版本 : 2.4.0
3. 小助手版本 : 2.5.5
4. BUG描述 : 开启免认证登录后, 登录前手机收到的消息无法同步电脑. 关闭自动登录后就可以同步
5. 操作场景 : 小助手 > 开启免认证登录 
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
#297
