### ISSUE TITLE
点击微信公众号文章导致微信闪退

### ISSUE THREAD

**Issue by Suremotoo** [MustangYM/WeChatExtension-ForMac#343]
设备类型：MacBookPro11,4
系统版本：版本10.15.4（版号19E287）
系统语言：zh-Hans
微信版本：[2020-04-24 11:13:32] v2.4.0.149 (14390) #d873f721b5
微信语言：zh-Hans
历史版本：[2020-04-14 12:02:00] v2.4.0.148 (14091) #2c2457391e
网络状态：Reachable via WiFi
显  示  器：*(1440x900)/Retina
小助手版本 : 2.5.5
BUG描述 : 查看公众号微信闪退
操作场景 : 微信启动后, 选择微信公众号的一条信息，点击后微信直接闪退,另外小助手开启了使用系统浏览器，不使用该选项就没问题
操作效果

http://i2.tiimg.com/717484/394121da3a66b16a.gif

**Comment by TomANDJarry** [comment]
10.15.3也是这样

**Comment by MustangYM** [comment]
[v2.5.6](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.6)
