### ISSUE TITLE
小助手 2.5.6 版本更新后一直提示 WARNING FOR CRASH

### ISSUE THREAD

**Issue by Haojen** [MustangYM/WeChatExtension-ForMac#344]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.3.31
3. 小助手版本 : 2.5.6
4. BUG描述 :  每次从其他窗口切换到微信都弹出如下图所示：“WARNING FOR CRASH”
![image](https://user-images.githubusercontent.com/6928850/80301182-35494700-87d5-11ea-8a0e-944dc1dda51b.png)

**Comment by hehaohan** [comment]
同样的报错提示+1

**Comment by MustangYM** [comment]
已修复，重装一下

**Comment by Haojen** [comment]
验证已修复， @MustangYM  thx
