### ISSUE TITLE
V2.5.6没有修改软件内部版本号？

### ISSUE THREAD

**Issue by ShineUnM** [MustangYM/WeChatExtension-ForMac#346]
更新到最新版，还是反复提示有4月26的2.5.6更新，下拉菜单显示版本号还是2.5.5
不知道是我更新失败，还是2.5.6忘了给版本号+1

**Comment by ShineUnM** [comment]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/41404523/80303566-b14a8b80-87e3-11ea-974e-3833a158695f.png">
<img width="234" alt="image" src="https://user-images.githubusercontent.com/41404523/80303587-c6271f00-87e3-11ea-8a4b-8434efc3846c.png">

**Comment by MustangYM** [comment]
你没有更新成功
