### ISSUE TITLE
更新后一直无限弹框报错

### ISSUE THREAD

**Issue by mikumikulch** [MustangYM/WeChatExtension-ForMac#347]
Issue示例
1. MacOS版本 : 10.15.2
2. 微信版本 : 2.3.31
3. 小助手版本 : 2.5.6
4. BUG描述 : 打开微信后一直报错：拦截到崩溃
5. 操作场景 : 微信启动后就无限报错
6. 方便的话提供日志, 截图或者视频(可选)

<img width="617" alt="image" src="https://user-images.githubusercontent.com/15964712/80307768-c3d1be80-87fd-11ea-9048-f363e5aa7c13.png">

**Comment by MustangYM** [comment]
@mikumikulch 这个已经修复了, 你重新安装下
