### ISSUE TITLE
搜索框背景颜色不兼容‘暗黑模式’

### ISSUE THREAD

**Issue by DraculaPrince** [MustangYM/WeChatExtension-ForMac#348]
Issue示例
1. MacOS版本 : 10.15.4 (19E287)
2. 微信版本 : 2.3.31 (13292)
3. 小助手版本 : 2.5.6
4. BUG描述 : 搜索框背景颜色不兼容‘暗黑模式’
5. 操作场景 : 微信启动后, 鼠标左键点击搜索框后
6. 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/12658493/80331188-f3bea780-8879-11ea-9085-f740a4520196.png)
![image](https://user-images.githubusercontent.com/12658493/80331240-181a8400-887a-11ea-8119-fa98a2c9e35f.png)

**Comment by MustangYM** [comment]
@DraculaPrince 这里我尝试过几次， 没有一个完美的解决方案，暂时就搁置了
