### ISSUE TITLE
调起微信出现错误提示

### ISSUE THREAD

**Issue by notCoolBean** [MustangYM/WeChatExtension-ForMac#349]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.3.31（13331）
3. 小助手版本 : 2.5.6
4. BUG描述 : 调起微信出现错误提示
5. setAllowsCollapsingCandidateList: 错误

**Comment by MustangYM** [comment]
@notCoolBean 已经修复了，没有发新版本，重新手动安装下即可

**Comment by MustangYM** [comment]
#347

**Comment by notCoolBean** [comment]
![image](https://user-images.githubusercontent.com/26993086/80348206-064bd780-88a0-11ea-8f11-be1933c1d791.png)
