### ISSUE TITLE
黑夜模式下无法看清消息引用内容

### ISSUE THREAD

**Issue by JokerHB** [MustangYM/WeChatExtension-ForMac#350]
1. MacOS版本 : 0.15.4 (19E287)
2. 微信版本 :  2.4.0 (14390) Beta 149
3. 小助手版本 : 2.5.6
4. BUG描述 : 黑夜模式下无法看清消息引用内容
5. 操作场景 : 微信启动后，鼠标左键点击消息，选择引用，在聊天窗口中无法看清消息内容。
6. 方便的话提供日志, 截图或者视频(可选)
    6.1 在消息编辑框中，被引用的消息内容无法看清。
    
<img width="434" alt="截屏2020-04-27 下午4 08 07" src="https://user-images.githubusercontent.com/11409054/80349237-8888cb80-88a1-11ea-99a7-3d7bd4fd1eeb.png">

    6.2 在对话列表中，被引用 的消息内容无法看清。

<img width="431" alt="截屏2020-04-27 下午4 08 21" src="https://user-images.githubusercontent.com/11409054/80349261-90e10680-88a1-11ea-8eaa-1c541ac0c3c5.png">

**Comment by lexrus** [comment]
微信正式版是好的，beta 版貌似改了引用的呈现方式。请问哪里下载 2.4.0 beta 版呢？

**Comment by wqk317** [comment]
> 微信正式版是好的，beta 版貌似改了引用的呈现方式。请问哪里下载 2.4.0 beta 版呢？

https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg

**Comment by lexrus** [comment]
<img width="488" alt="Screen Shot 2020-04-28 at 8 49 25 PM" src="https://user-images.githubusercontent.com/219689/80488997-ca913a80-8991-11ea-9c8b-6f2db5b9cab7.png">
修了一下，等下一版吧。

**Comment by JokerHB** [comment]
坐等，极好。
