### ISSUE TITLE
[Suggestion]小助手更新能否记住上次设置？

### ISSUE THREAD

**Issue by MuyePeikon** [MustangYM/WeChatExtension-ForMac#351]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.0
3. 小助手版本 : 更新至 2.5.6
4. BUG描述 : 更新后小助手设置被清空
5. 操作场景 : 小助手自动提示的更新
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
em...严格来说不算bug
