### ISSUE TITLE
2.5.6 主题模式为什么没有日间了？？

### ISSUE THREAD

**Issue by DreamsCat** [MustangYM/WeChatExtension-ForMac#352]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.3.31
3. 小助手版本 : 2.5.6
4. BUG描述 : 主题模式只有夜间和少女粉，日间模式去哪里了？

**Comment by DreamsCat** [comment]
为何关闭了，原本用的好好的日间模式为什么突然没了

**Comment by MustangYM** [comment]
@DreamsCat 认真读readme
