### ISSUE TITLE
黑夜模式下无法看清静音标志

### ISSUE THREAD

**Issue by zqso** [MustangYM/WeChatExtension-ForMac#353]
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.0 (14390) Beta 149
3. 小助手版本 : 2.5.6
4. BUG描述 : 黑暗模式下无法看清静音标志（暗红色）。因为静音图标极小，黑暗模式下能否改成白色或其他亮色。
5. 操作场景 : 黑暗模式下。
6. 截图：
![image](https://user-images.githubusercontent.com/15665504/80364960-a885a400-883b-11ea-8827-931fc207cfd7.png)

**Comment by MustangYM** [comment]
@zqso 你看代码可以得知，这里用的是纯红色，出来的效果也仅此而已，其实不太好改，你懂我意思吧。。。
