### ISSUE TITLE
我也不大清楚是怎么了

### ISSUE THREAD

**Issue by SupremeSaper** [MustangYM/WeChatExtension-ForMac#354]
<img width="446" alt="屏幕快照 2020-04-28 下午08 15 49 上午" src="https://user-images.githubusercontent.com/43092729/80433731-43f54280-892a-11ea-86e0-37c9260824bd.png">
1. MacOS版本 : 10.15.1 Beta版(19B77a)
2. 微信版本 : App Version: Version. 2.3.31 (13292)
Verbose: v2.3.31.19 (0x12031f13)
System: OSX 10.15.1 build(19B77a)
3. 小助手版本 : 2.5.6

**Comment by MustangYM** [comment]
@SupremeSaper 已经修复了，没有发版，重新安装即可
