### ISSUE TITLE
无法使用系统浏览器打开

### ISSUE THREAD

**Issue by wqk317** [MustangYM/WeChatExtension-ForMac#355]
Issue示例
1. MacOS版本 : 10.15.5
2. 微信版本 : Version. 2.4.0 (14390) Beta 149
3. 小助手版本 : 2.5.6
4. BUG描述 : 无法使用系统浏览器打开
5. 操作场景 : 打开此功能, 然后在微信李点击链接, 弹窗报错, 如下图
6. 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/13175615/80476169-995a3f80-897c-11ea-9480-1914125c32cf.png)

**Comment by MustangYM** [comment]
@wqk317 已经修复了的，没有发新版，你重装一下最新的

**Comment by wqk317** [comment]
> @wqk317 已经修复了的，没有发新版，你重装一下最新的

大佬666, 回复神速, 问题也已经解决👏
