### ISSUE TITLE
2个小问题反馈

### ISSUE THREAD

**Issue by Depth-** [MustangYM/WeChatExtension-ForMac#360]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.3.31
3. 小助手版本 : 最新的
4. BUG描述 : 
  问题1:主题模式适配问题
  在使用了小程序暗黑模式之后，微信里面使用搜索功能的内容展示样式未适配，仍旧有大面积留白。
  问题2:截图问题
  当使用了该小程序后，使用微信截图快捷键，进行截图，会提示没有开启微信的屏幕权限，但是实际去检查配置的时候，该权限已经是开启的了，卸载该小程序后，可正常使用截图。

**Comment by mengoreo** [comment]
> Issue示例
> 
> 1. MacOS版本 : 10.15.4
> 2. 微信版本 : 2.3.31
> 3. 小助手版本 : 最新的
> 4. BUG描述 :
>    问题1:主题模式适配问题
>    在使用了小程序暗黑模式之后，微信里面使用搜索功能的内容展示样式未适配，仍旧有大面积留白。
>    问题2:截图问题
>    当使用了该小程序后，使用微信截图快捷键，进行截图，会提示没有开启微信的屏幕权限，但是实际去检查配置的时候，该权限已经是开启的了，卸载该小程序后，可正常使用截图。

前两天挣扎了好久，也没找着那个页面的类，最后能达到的最好结果也只是表头适配黑色，后来就放弃了，凑活着用了。希望 owner 大佬能早日hook到🙏🏻

**Comment by lexrus** [comment]
@mengoreo Xcode 运行启动这个微信插件后用 Debug View Hierarchy 可以看到各个界面分别是哪些类，如图：
<img width="1185" alt="Screen Shot 2020-05-01 at 9 16 15 AM" src="https://user-images.githubusercontent.com/219689/80773478-9e8dd900-8b8c-11ea-9e81-5ef5b0734430.png">

我看了一下是需要 hook 这几个类：
```
MMSearchTableCellView
MMSearchContactTableCellView
MMSearchTableSectionHeaderView
MMSearchChatLogResultTableCellView
```

然后找它们有什么方法可以 hook，可以用 Hopper 之类的工具：
<img width="1002" alt="Screen Shot 2020-05-01 at 9 18 20 AM" src="https://user-images.githubusercontent.com/219689/80773775-7a7ec780-8b8d-11ea-85d7-1755ea5185c4.png">

你有兴趣修复一下这个问题吗？

**Comment by MustangYM** [comment]
[修复了搜索界面的bug](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.7)
