### ISSUE TITLE
微信多开无法关闭 

### ISSUE THREAD

**Issue by Matear890** [MustangYM/WeChatExtension-ForMac#362]
Issue示例
1. MacOS版本 : 10.xx.x
2. 微信版本 : 2.x.x
3. 小助手版本 : 2.x.x
4. BUG描述 : 会话头像抖动
5. 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by Matear890** [comment]
怎么关闭

**Comment by Matear890** [comment]
勾选框总是开启的

**Comment by MustangYM** [comment]
微信多开和允许打开小程序是互斥的

**Comment by Matear890** [comment]
谢谢
