### ISSUE TITLE
2.5.6版本下拦截的崩溃:setAllowsCollapsingCandidateList

### ISSUE THREAD

**Issue by iamStephenFang** [MustangYM/WeChatExtension-ForMac#364]
Issue
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.0 (14390) Beta 149 
3. 小助手版本 : 2.5.6
4. BUG描述 : 拦截崩溃:setAllowsCollapsingCandidateList
5. 操作场景 : 微信启动后即弹出窗口提示“setAllowsCollapsingCandidateList: 错误”，点击任一聊天对象报错窗口会叠加显示
6. 提供日志, 截图或者视频
![144221588251653_ pic](https://user-images.githubusercontent.com/40275062/80713981-dfeb9d80-8b26-11ea-969c-aaef04a79b6a.jpg)
暂时没有找到日志读取入口，若需要麻烦告知

**Comment by MustangYM** [comment]
@iamStephenFang 已经修复了,没有发版, 重新安装就好了
