### ISSUE TITLE
多开后小程序打不开

### ISSUE THREAD

**Issue by DJBERYL** [MustangYM/WeChatExtension-ForMac#366]
Issue示例
1. MacOS版本 : 最新版
2. 微信版本 : 最新版
3. 小助手版本 : 最新版
4. BUG描述 : 多开后，小程序打不开，崩溃
5. 操作场景 : 
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
这两是互斥的, readme有写, 暂时没有特别好的解决方案使每一个微信示例都能正常打开小程序
