### ISSUE TITLE
未来有可能支持把mac的聊天记录同步到手机吗？换机把手机的记录都丢了，只有mac上有完整的。

### ISSUE THREAD

**Issue by leo1217** [MustangYM/WeChatExtension-ForMac#367]
如题，不知道这个功能是否能实现，也不知道作者大大有没有时间。小小的问一下，这个有没有办法做到。因为之前换手机，聊天记录备份在手机里面，还没有导出来，就把手机格式化了。用了很多方法都恢复不出手机的数据，现在只有mac上微信因为一直都在登陆，所以有完整都记录。之前去找了个土办法把微信的数据库导出，但是也只能换到另一台电脑，实现不了同步回手机。😭

**Comment by MustangYM** [comment]
Mac微信本身官方就有这个功能,  左下角--备份与恢复--恢复聊天记录至手机

**Comment by wqk317** [comment]
> Mac微信本身官方就有这个功能, 左下角--备份与恢复--恢复聊天记录至手机

他的意思是之前没有备份，但是PC端有完整记录，想同步下来，但是好像是做不到。。。

**Comment by MustangYM** [comment]
@wqk317 em.....这个补救场景使用太少太少太少了....我不太想做

**Comment by leo1217** [comment]
> @wqk317 em.....这个补救场景使用太少太少太少了....我不太想做

好吧。我再找找其他办法。谢大佬

**Comment by flute** [comment]
同求~

**Comment by flute** [comment]
@leo1217  老铁有找到解决方案吗
