### ISSUE TITLE
暗黑模式下部分元素较难辨认

### ISSUE THREAD

**Issue by RichardZengYY** [MustangYM/WeChatExtension-ForMac#368]
目前发现的有：静音图标，个人名片
![Xnip2020-05-06_12-49-25](https://user-images.githubusercontent.com/19625678/81139510-91ac2380-8f98-11ea-8f7c-c77bfbea062e.jpg)
希望可以参照ios微信黑色模式配色

**Comment by quanru** [comment]
暗黑模式下，使用方向键控制左侧列表，无法看出哪个被选中，希望被选中的保持高亮

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/81293187-7b3cbf80-909f-11ea-8bb2-5a848cfeb146.png)
我可能不会再回答类似问题, 对不起.
