### ISSUE TITLE
无法切换黑夜模式

### ISSUE THREAD

**Issue by unx123475** [MustangYM/WeChatExtension-ForMac#369]
1. MacOS版本 : 10.11
2. 微信版本 : 2.3.30
3. 小助手版本 : 刚下的
4. BUG描述 : 无法切换回正常模式
5. 操作场景 : 微信启动后，直接是黑夜模式，想调回去的时候直接卡住，不知道什么原因。

**Comment by MustangYM** [comment]
再次点击'黑夜模式'的时候, 有弹窗嘛, 点击弹窗的按钮重启后, 才会关闭黑夜模式

**Comment by unx123475** [comment]
我主要就是点了关闭之后微信就卡住了🤣🤣

**Comment by MustangYM** [comment]
@unx123475 你更新到2.4的微信吧, 如果还有这问题, 我得排查下了

**Comment by unx123475** [comment]
我只能更新到2.3.31，我刚刚还试了一下切换小程序去双开，然后发现也会卡住，弹窗还没出来。是不是请求重启出了问题

**Comment by MustangYM** [comment]
@unx123475 我大概知道原因了, 很有可能NSAlert的函数导致的, 升级一下系统吧应该能暂时解决你的问题
