### ISSUE TITLE
微信版本2.3.25，安装后其他功能都可用，但是防撤回功能为什么手机端没有呢

### ISSUE THREAD

**Issue by ayayou** [MustangYM/WeChatExtension-ForMac#37]
微信版本2.3.25，安装后其他功能都可用，但是防撤回功能为什么手机端没有呢

**Comment by MustangYM** [comment]
> 微信版本2.3.25，安装后其他功能都可用，但是防撤回功能为什么手机端没有呢

防撤回同步到手机要自己勾选
