### ISSUE TITLE
使用小助手的aflred功能后，微信cpu占用达90%多

### ISSUE THREAD

**Issue by linuxliu** [MustangYM/WeChatExtension-ForMac#370]
Issue示例
1. MacOS版本 : 10.15
2. 微信版本 : 2.3.31
3. 小助手版本 : 2.5.6
4. BUG描述 : 开启alfred功能后，请求http get 52700 端口，出现，TCP localhost:52700->localhost:62247 (CLOSE_WAIT) 然后微信的cpu占用率达到90%多
5.复现手顺，使用python request 请求 http://127.0.0.1:52700/wechat-plugin/chatlog?userId=gh_57664c0df1c5&count=1 然后kill 掉，lsof -i tcp:52700 看到 有close_wait 此时微信cpu占用率异常的高

**Comment by MustangYM** [comment]
普通使用不会出现这个问题, 所以我也不得而知问题出在哪里
