### ISSUE TITLE
选择使用系统浏览器，打开网页提示崩溃

### ISSUE THREAD

**Issue by wangyouhua2019** [MustangYM/WeChatExtension-ForMac#371]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.0
3. 小助手版本 : 2.5.7
4. BUG描述 : 选择使用系统浏览器，打开网页提示崩溃
5. 操作场景 : 点击订阅号文章等
6. 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/50011119/81266108-c55d7b00-9076-11ea-9530-a9c1f1906973.png)

**Comment by MustangYM** [comment]
[更新下版本](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.7)
