### ISSUE TITLE
群成员退群提示

### ISSUE THREAD

**Issue by xxx-bu2** [MustangYM/WeChatExtension-ForMac#374]
1.有一个大群，已经有100多人退群了，然后每隔7天就会刷屏一次100多人退群信息……
2.开启退群提醒功能时，很久以前退群的人也会刷屏提醒一遍……

这两点就很困扰，如果恰巧有一个人在这时退群，或者我看到有人退群了然后第一次开启退群提醒功能，我也无法得知到底是谁退群了。

如果可以精准提醒有人在此时此刻退群的话，能否利用「防撤回同步到手机」的功能，转发精准的退群信息到个人聊天窗口

**Comment by renheon** [comment]
提议不错 +1 待解决

**Comment by MuyePeikon** [comment]
两个月后，移除了退群提醒功能=。=

**Comment by MustangYM** [comment]
[v2.6.5已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.5)
