### ISSUE TITLE
撤回消息后，被撤回的消息依然以正常消息存在

### ISSUE THREAD

**Issue by JokerHB** [MustangYM/WeChatExtension-ForMac#379]
Issue示例
1. MacOS版本 : 10.15.4 
2. 微信版本 :  2.4.0 (14436) Beta 150
3. 小助手版本 : 2.5.7
4. BUG描述 : 撤回消息后，被撤回的消息依然存在
5. 操作场景 : 在微信的正常聊天对话框中撤回一条消息，被撤回的消息仍然是以正常对话气泡的方式存在。
6. 方便的话提供日志, 截图或者视频(可选)
6.1. 在聊天中第一次选择消息撤回后的截图
<img width="520" alt="WechatIMG3" src="https://user-images.githubusercontent.com/11409054/81668625-87e25e80-9477-11ea-9747-24bbe6351bf5.png">

6.2. 再次打开聊天时的截图
<img width="454" alt="iShot2020-05-12下午05 38 38" src="https://user-images.githubusercontent.com/11409054/81668637-8b75e580-9477-11ea-9432-a241157a9042.png">

**Comment by MustangYM** [comment]
一直是这样，不是bug。
