### ISSUE TITLE
感谢，请问对MAC OS版本有要求吗？怎么卸载呢？

### ISSUE THREAD

**Issue by lolstudio** [MustangYM/WeChatExtension-ForMac#38]
rt

**Comment by MustangYM** [comment]
> rt

卸载的教程已更新在readme中了

**Comment by lolstudio** [comment]
在MAC 10.10安装失败，麻烦解决
![image](https://user-images.githubusercontent.com/11715848/60076617-97bb5c00-975a-11e9-9880-8765b28b99c7.png)
![image](https://user-images.githubusercontent.com/11715848/60076644-aa359580-975a-11e9-9543-804b3024a1a0.png)

**Comment by MustangYM** [comment]
过十分钟你上github获取最新的版本, 我刚刚commit了适配10.9的包, 你的10.10应该兼容了




| |
晏茂
|
|
ymoomy@yeah.net
|
签名由网易邮箱大师定制


在2019年06月25日 15:05，lolstudio<notifications@github.com> 写道：

在MAC 10.10安装失败，麻烦解决

**Comment by lolstudio** [comment]
已经可以了，感谢，但【手机端也能收到被撤回的消息】这个功能为啥不成功，都已经勾选了但手机端不会显示。
![image](https://user-images.githubusercontent.com/11715848/60093299-ae25df80-977b-11e9-8e0f-cf22919e2d00.png)
![image](https://user-images.githubusercontent.com/11715848/60093419-eaf1d680-977b-11e9-93ab-df3942df157f.png)
