### ISSUE TITLE
打字卡顿比较严重

### ISSUE THREAD

**Issue by Tsn-09** [MustangYM/WeChatExtension-ForMac#381]
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.1（14470）
3. 小助手版本 : 2.5.7
4. BUG描述 : 百度输入法，在微信聊天窗口打字，卡顿严重

**Comment by Tsn-09** [comment]
不单纯是打字，整个微信用起来都是一卡一卡的，包括上下滑动，切换聊天窗口…就像幻灯片

**Comment by MustangYM** [comment]
@Tsn-09 别的应用此时卡嘛，卸载小助手试试还卡不卡，是在某种场景下必现的，还是说偶现的

**Comment by Tsn-09** [comment]
别的应用正常。在活动监视器里看，只有微信占用的内存很大，最多的时候4G多，卸载小助手微信就正常了……内存占用才150M

**Comment by snakejordan** [comment]
我也有这种情况，CPU 占用率非常高，现在不知道是微信的问题还是小助手的问题。
微信版本：2.3.31（App Store 版本）
小助手版本：2.5.7

**Comment by snakejordan** [comment]
> @Tsn-09 别的应用此时卡嘛，卸载小助手试试还卡不卡，是在某种场景下必现的，还是说偶现的

现在基本上找不到规律，关闭微信之后会好，再开微信过一段时间就这样了，内存泄漏？

**Comment by snakejordan** [comment]
> @Tsn-09 别的应用此时卡嘛，卸载小助手试试还卡不卡，是在某种场景下必现的，还是说偶现的

![image](https://user-images.githubusercontent.com/3376284/82074895-00624d00-970e-11ea-9c71-17e9d6f526be.png)

**Comment by MustangYM** [comment]
@snakejordan @Tsn-09 我暂时没找到导致这个问题的原因, 我会慢慢排查这个问题

**Comment by snakejordan** [comment]
如何能帮到你呢？

MustangYM <notifications@github.com>于2020年5月16日 周六10:04写道：

**Comment by MustangYM** [comment]
@snakejordan 因为我确实没遇到过这个问题, 比较奇怪吧, 昨天我打开xcode监控了一天, 也比较重度使用, 暂时还未发现有问题, 所以其实你也帮不了我.

**Comment by snakejordan** [comment]
OK，如果需要帮助随时联系。

MustangYM <notifications@github.com>于2020年5月16日 周六10:16写道：

**Comment by HarryWang29** [comment]
原来好多人遇到这个问题……

**Comment by lisanzhu** [comment]
我也遇到了卡顿的现象，就是微信打字的时候，在WPS里面打字是不卡的，在Leetcode上面也是不卡的。

**Comment by snakejordan** [comment]
楼上各位出现卡顿的情况的伙伴是不是都用了小助手的主题模式？
@MustangYM 貌似我关闭了主题模式后 CPU 飙升内存占满的情况就不怎么发生了。

**Comment by HarryWang29** [comment]
确实开启了dark模式，刚关掉，使用一天试试看，不过我开了两个微信，一个消息比较少的基本也不会卡，感觉还是消息多了之后导致的

**Comment by zhan8863** [comment]
各位童鞋们可以关闭主题，使用默认的白色主题，应该就没有卡顿现象了~

**Comment by Tsn-09** [comment]
> 各位童鞋们可以关闭主题，使用默认的白色主题，应该就没有卡顿现象了~

确实是，不使用主题就正常了

**Comment by Murmanskz** [comment]
不实用主题色就不卡了

**Comment by fanlinhu** [comment]
> 4\. BUG描述 : 百度输入法，在微信聊天窗口打字，卡顿严重
搜狗也是， 打字卡的没法用，想砸键盘，已经卸载了，就好了

**Comment by MustangYM** [comment]
[2.6.0](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.0)已经修复
