### ISSUE TITLE
【功能建议】希望添加：同一问题一定时间内只触发一次

### ISSUE THREAD

**Issue by Designdocs** [MustangYM/WeChatExtension-ForMac#383]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.7
4. BUG描述 : 无

【功能建议】希望添加：同一问题一定时间内只触发一次

比如： 一小时内，同一个关键词只触发一次 自动回复，避免被对方刷屏

**Comment by MustangYM** [comment]
可能不会考虑，抱歉。
