### ISSUE TITLE
群成员退群信息每个人重复了三遍

### ISSUE THREAD

**Issue by WangDanpeng** [MustangYM/WeChatExtension-ForMac#384]
Issue示例
1. MacOS版本 : 10.14.6
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.7
4. BUG描述 : 退群信息每个人重复了三遍
5. 操作场景 : 今天更新小助手以后打开微信, 几个群里的退群信息重新刷了一遍, 而且每个人都发了三遍

**Comment by WangDanpeng** [comment]
![image](https://user-images.githubusercontent.com/20870505/82023455-e0f10300-96c0-11ea-8361-961f5a61c43f.png)

**Comment by dawson-z** [comment]
对，好像么诶个一段时间都会收到重复退群的提醒

**Comment by dawson-z** [comment]
对，好像每隔一段时间都会收到重复退群的提醒

**Comment by acloudyh** [comment]
这个退群提醒会经常出现重复提醒

![image](https://user-images.githubusercontent.com/33645878/82628680-15644200-9c20-11ea-972f-ba16f5306acb.png)

**Comment by junglegiant** [comment]
+1

**Comment by renheon** [comment]
+1  每过一会儿点击群聊天就显示一次

**Comment by MustangYM** [comment]
[已经移除](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.1)

**Comment by dawson-z** [comment]
> [已经去除](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.1)

没有什么是删除解决不了的问题，这下解决的真彻底😂😂😂
