### ISSUE TITLE
微信通过app store自动升级之后插件自动消失了

### ISSUE THREAD

**Issue by wjinxing** [MustangYM/WeChatExtension-ForMac#388]
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.7
4. BUG描述 : 微信从2.3版本通过app store自动升级为2.4.1之后，再打开微信后自动恢复成了微信的原始界面，在菜单栏中也不显示微信小助手。
5. 操作场景 : 通过app store升级后，重新打开微信，要求通过手机验证才可以登录，然后验证之后微信就恢复成了原始界面。

**Comment by JinFWang** [comment]
更新了肯定就没了哇，重新安装就好啦

**Comment by guoxianpeng** [comment]
无法重新安装了 omw小助手一直安装不成功 ，懒癌一键安装网址403端口不通

**Comment by MustangYM** [comment]
更新了微信就要重新安装小助手。安装的话请保持科学上网。
