### ISSUE TITLE
一直提醒更新

### ISSUE THREAD

**Issue by L1cardo** [MustangYM/WeChatExtension-ForMac#39]
你刚刚更新我就收到了邮件，目前1.8.8版本 ，提醒更新到1.8.9  点击更新后重启微信，还是提醒更新，版本号还是1.8.8 ，看来一键更新没有生效
我等下下载源码重新安装一遍试试

**Comment by MustangYM** [comment]
> 你刚刚更新我就收到了邮件，目前1.8.8版本 ，提醒更新到1.8.9 点击更新后重启微信，还是提醒更新，版本号还是1.8.8 ，看来一键更新没有生效
> 我等下下载源码重新安装一遍试试

这个问题出现两次了, 我已经修复了, OSX的文件替换逻辑有问题....
