### ISSUE TITLE
微信2.4.1失效

### ISSUE THREAD

**Issue by HernandoR** [MustangYM/WeChatExtension-ForMac#391]
1. MacOS版本 : 10.15.4
2. 微信版本 :  2.4.1 (14485)
3. 小助手版本 : 2.5.7
4. BUG描述 : 失效
5. 操作场景 : 微信启动后, 菜单栏中无小助手标签
6.
<img width="298" alt="截屏2020-05-25 下午1 00 40" src="https://user-images.githubusercontent.com/45709656/82779813-bf91d300-9e87-11ea-8ae1-1d7dd7edfe97.png">

**Comment by MustangYM** [comment]
你更新或者重装微信后要重新安装小助手
