### ISSUE TITLE
什么时候支持微信2.4.1版本啊！感谢大佬

### ISSUE THREAD

**Issue by brandlee** [MustangYM/WeChatExtension-ForMac#392]
Issue示例
1. MacOS版本 : 10.xx.x
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.x.x
4. BUG描述 : 尚未支持微信版本2.4.1
5. 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
6. 方便的话提供日志, 截图或者视频(可选)
: ./WeChatExtension-ForMac-2.5.7/WeChatExtension/Rely/Install.sh: No such file or directory

**Comment by MustangYM** [comment]
你这是没安装成功.
