### ISSUE TITLE
功能在微信2.4.1版本失灵

### ISSUE THREAD

**Issue by chkdsk228** [MustangYM/WeChatExtension-ForMac#394]
Issue示例
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.1
3. 小助手版本 : 直接git0525的最新版
4. BUG描述 :所有功能失灵。无操作菜单。
5. 操作场景 : 微信启动后,无操作菜单。所有功能失灵。
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
小助手是“寄生”在微信客户端里的，每次更新微信后，小助手会被覆盖掉，所以请重新安装小助手！

**Comment by chkdsk228** [comment]
> 小助手是“寄生”在微信客户端里的，每次更新微信后，小助手会被覆盖掉，所以请重新安装小助手！

根据懒癌版命令行重新安装。重启微信还是无操作菜单。
