### ISSUE TITLE
macOS 10.15.5 小助手崩溃

### ISSUE THREAD

**Issue by neutron1988** [MustangYM/WeChatExtension-ForMac#397]
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.7
4. BUG描述 : 无法启动微信，无限崩溃

安装2.2.2版本小助手，可以正常使用，但时间长了还是会崩溃（低频，基本不影响使用）

**Comment by char1eslu** [comment]
2.5.7的小助手最高支持的微信版本是2.4.0，等更新吧，我mac 微信还没升级就是小助手还没更新呢

**Comment by neutron1988** [comment]
> 2.5.7的小助手最高支持的微信版本是2.4.0，等更新吧，我mac 微信还没升级就是小助手还没更新呢

在macOS 10.15.4下，2.5.7可以完美配合微信2.4.1使用，没有任何问题。
