### ISSUE TITLE
消息撤回后，手机端不显示撤回了什么消息吗？

### ISSUE THREAD

**Issue by iyish** [MustangYM/WeChatExtension-ForMac#40]
设备类型：MacBookPro14,1
系统版本：版本 10.12.6（版号 16G1918）
系统语言：zh-Hans
微信版本：[2019-05-31 12:41:02] v2.3.25.21 (12481) #6df30b55c
微信语言：zh-Hans
历史版本：[2019-01-15 14:01:47.207] Version. 2.3.22 (11875)  v2.3.22.18 (0x12031612) #9057f0fc9
网络状态：Reachable via WiFi
显  示  器：*(1440x900)/Retina

手机端  version 7.0.4  Android 9

**Comment by MustangYM** [comment]
默认应该是不开启撤回同步到手机的, 要在上方导航栏自行开启
