### ISSUE TITLE
微信 2.4.1 版本 小程序问题

### ISSUE THREAD

**Issue by Sandural** [MustangYM/WeChatExtension-ForMac#401]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.7
4. BUG描述 : 小程序不能显示

![image](https://user-images.githubusercontent.com/16163090/83115083-70a0a380-a0fc-11ea-87b5-57706f5025a3.png)

**Comment by MustangYM** [comment]
这不是小助手的问题

**Comment by Sandural** [comment]
那是什么问题?

**Comment by MustangYM** [comment]
@Sandural 有的小程序是显示不出来， 这是微信自己的逻辑。

**Comment by xiao0yy** [comment]
@MustangYM  有什么小程序已经确定是可以显示的呢，测试了几个都是不行，包括在Readme里展示的

<img width="1328" alt="CleanShot 2020-07-05 at 21 41 46@2x" src="https://user-images.githubusercontent.com/9213939/86534110-59798080-bf08-11ea-8af7-6cedf04670b0.png">

MacOS：10.15.5
微信版本：2.4.1
小助手版本：2.6.0
