### ISSUE TITLE
退群监控会重复列出之前已经退群了的所有人名单

### ISSUE THREAD

**Issue by qazwyw** [MustangYM/WeChatExtension-ForMac#402]
比如说只有一个人退群了，他会把前段时间退群的一大段人都列出来，人数多点的群就会被这个退群监控刷屏，你们有遇到吗

**Comment by Firef0x** [comment]
有遇到，而且同一次退群推送还会重复。
![image](https://user-images.githubusercontent.com/2487841/83492181-796eec00-a4e5-11ea-8383-bb5efdeb6f6a.png)

**Comment by jochne** [comment]
+1

**Comment by ZDCSunny** [comment]
我也是

**Comment by ZDCSunny** [comment]
是不是因为距离上一次提醒超过7天了就会再次提醒

**Comment by chenjiweicn** [comment]
me too

**Comment by phpxcn** [comment]
+1

**Comment by gangming** [comment]
建议出一个“不在提醒的功能”

**Comment by MustangYM** [comment]
[已经移除](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.1)
