### ISSUE TITLE
微信版本 2.4.1 小助手不生效

### ISSUE THREAD

**Issue by bubblexin** [MustangYM/WeChatExtension-ForMac#405]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : Version. 2.4.1 (14485)
3. 小助手版本 : 2.5.7
4. BUG描述 :  微信升级到 2.4.1 之后，重新安装小助手，重启微信，小助手不生效，试了多次，都不行
5. 操作场景 : 使用 oh-my-wechat（ https://github.com/lmk123/oh-my-wechat ） 懒人安装，提示安装成功，重启微信小助手不生效，微信上一版本没问题，升级到 2.4.1 之后不可，试了多次，都不行
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
手动安装

**Comment by bubblexin** [comment]
ok，手动安装可以了
