### ISSUE TITLE
免登录功能时候会保存移动端微信的session之类造成风险？

### ISSUE THREAD

**Issue by fanwqi** [MustangYM/WeChatExtension-ForMac#409]
微信扫码登录的流程中，登录是需要移动端微信主动发起请求的，大概的需要携带二维码中的uuid和当前登录微信的session标识之类。
我想问下这里的免登录功能是如何实现的？是否会有风险？

**Comment by MustangYM** [comment]
AccountService自己有个AutoAuth API
