### ISSUE TITLE
搜索框无法匹配皮肤

### ISSUE THREAD

**Issue by yaaisinile** [MustangYM/WeChatExtension-ForMac#410]
1. MacOS版本 : 10.13.2
2. 微信版本 : 2.3-2.4
3. 小助手版本 : 2.5.7
4. BUG描述 : 搜索框没有皮肤,还是默认白色
5. 操作场景 : 一直
问题截图:
![TIM截图20200602173138](https://user-images.githubusercontent.com/52902895/83505808-e63fb180-a4f8-11ea-9fb2-5fbcfaec6f13.png)

**Comment by MustangYM** [comment]
升级Mac系统

**Comment by yaaisinile** [comment]
> 升级Mac系统

硬件限制了升不了最新系统.我先关闭皮肤吧
