### ISSUE TITLE
大佬能搞个扣扣的吗？

### ISSUE THREAD

**Issue by xiebruce** [MustangYM/WeChatExtension-ForMac#411]
如题，扣扣应该也很多人有这需求，之前[TKkk-iOSer](https://github.com/TKkk-iOSer)大佬有搞[这个](https://github.com/TKkk-iOSer/QQPlugin-macOS)，不知道大佬能不能搞搞支持一下新版本，感谢大佬！

**Comment by MustangYM** [comment]
暂时没有太多时间去复活QQ这个插件
