### ISSUE TITLE
僵尸粉

### ISSUE THREAD

**Issue by freedomct** [MustangYM/WeChatExtension-ForMac#412]
Issue示例
1. MacOS版本 : 10.15.1
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.8(最新僵尸粉版本)
4. BUG描述 : 点击僵尸粉功能 查询所有联系人 拉群 通过小号测试大号 并且有好友看到我发送的加群邀请链接
6. 方便的话提供日志, 截图或者视频(可选)
![IMG_3646](https://user-images.githubusercontent.com/8709108/83616186-1ac77200-a5ba-11ea-8721-9dcfdbbf4453.jpg)

**Comment by MustangYM** [comment]
打开窗口，点击开始，自己会检测，不要在检测群里发任何消息，别人看不见的

**Comment by freedomct** [comment]
> 打开窗口，点击开始，自己会检测，不要在检测群里发任何消息，别人看不见的

没有发信息  我就是看到一直再拉人到群里 然后我就停止了 我点开拉去人的对话框 发现有邀请链接 
而且我大号也能看到那个群 
![Snip20200603_3](https://user-images.githubusercontent.com/8709108/83616983-0afc5d80-a5bb-11ea-91f1-97e4cc72bb56.png)

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/83618633-4d269e80-a5bd-11ea-9f90-2fa61b3dd7a3.png)
我不太清楚你这里做了什么操作

**Comment by canyesh** [comment]
一检测僵尸粉，就提示登录异常，然后就被踢出登录了

**Comment by freedomct** [comment]
> ![image](https://user-images.githubusercontent.com/21478687/83618633-4d269e80-a5bd-11ea-9f90-2fa61b3dd7a3.png)
> 我不太清楚你这里做了什么操作

一、点击检测 对话列表中  多了一个对话框 新建了一个群聊 然后就是对话框列表就一直在刷新
每个好友都被新开了一个对话框
二、停止检测 点开被添加到新建群聊中好友 看到好友对话框中 有一个邀请链接
三、点击邀请连接 显示无效已过期

**Comment by MustangYM** [comment]
我也不清楚啥情况。。。只建了一个群，按理说不应该这样的。。

**Comment by freedomct** [comment]
> 我也不清楚啥情况。。。只建了一个群，按理说不应该这样的。。

好的 辛苦啦 谢谢 看后续能解决不

**Comment by LeUKi** [comment]
同样是这个问题，把全部人拉进同一个群了，当场社会性死亡

**Comment by MustangYM** [comment]
@LeUKi 是会建立这样一个检测群，但是只要你不在群里说话，这个群理论上是不算成立的，别的所有人都不知道这个群的存在，不要慌

**Comment by LeUKi** [comment]
那我刚刚把他们全部踢出群了....岂不是全部人都知道了😂

**Comment by MustangYM** [comment]
@LeUKi 只要你自己一旦退出这个群，这个群就算解散了，什么事都没发生

**Comment by LeUKi** [comment]
好的吧 谢谢解答

**Comment by Luminoid** [comment]
```
[groupStorage AddGroupMembers:@[member] withGroupUserName:chatroom completion:^(NSString *str) {
    NSLog(@"验证-添加成功");
}];
```
这里如果群人数超过100会发加入群聊邀请吗

**Comment by ap0806109** [comment]
> 一检测僵尸粉，就提示登录异常，然后就被踢出登录了

换个网络可以继续，比如连手机的热点

**Comment by iOSleep** [comment]
我自己也是自己的联系人 然后检测人数会比最大的加一 最后就卡在 

**0分钟 279/278**

然后不动了

**Comment by MustangYM** [comment]
检测人数这个，已经修复了，没有发新版本，重新安装即可

**Comment by freedomct** [comment]
> 检测人数这个，已经修复了，没有发新版本，重新安装即可

辛苦 感谢

**Comment by MustangYM** [comment]
@freedomct 不是你所说的这个问题哦。你那个好像是企业微信的人导致的，我还没有去排查

**Comment by malusama** [comment]
有一个单向好友会一直弹框....

**Comment by kacok** [comment]
建议别所有好友，添加功能个可以选部分好友进行检测

**Comment by RainshawGao** [comment]
你好，我使用此功能时，当检测到达一定人数时，好像就没有再运行了，群的人数也没有再发生变化。

**Comment by closernow** [comment]
> 你好，我使用此功能时，当检测到达一定人数时，好像就没有再运行了，群的人数也没有再发生变化。

对，我也是。一直维持在40人就无法增加了，不知道是不是微信有在检测

**Comment by MustangYM** [comment]
[已下架此功能](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.9)
