### ISSUE TITLE
使用僵尸粉检测半分钟后被封

### ISSUE THREAD

**Issue by xiaotianxt** [MustangYM/WeChatExtension-ForMac#413]
Issue示例
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.8
4. BUG描述 : 无
5. 操作场景 : 启动微信直接被封
6. 方便的话提供日志, 截图或者视频(可选)
<img width="445" alt="image" src="https://user-images.githubusercontent.com/17041194/83633257-3a1ec900-a5d3-11ea-9556-b6ba13afd40c.png">

**Comment by yi-ge** [comment]
我测试也是这样的。

**Comment by MustangYM** [comment]
这个目前情况未知，但这不是封号，重新安装即可

**Comment by xiaotianxt** [comment]
> 这个目前情况未知，但这不是封号，重新安装即可

好的，关闭清理僵尸粉功能后，冷却了若干小时。现在可以正常登录。

**Comment by closernow** [comment]
应该是微信本身异地登录了吧，我帮朋友检测也是。不过我自己的没有，就是检测多了几次，就让我一小时后再试，但是过了一天还是这样提示

**Comment by MustangYM** [comment]
[已下架此功能](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.9)
