### ISSUE TITLE
僵尸粉扫描后 loading不结束, 数值也没对手

### ISSUE THREAD

**Issue by zszen** [MustangYM/WeChatExtension-ForMac#414]
Issue示例
1. MacOS版本 : 10.15.3
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.8
4. BUG描述 : 
僵尸粉扫描最后不结束, 只能手动关闭
![Snip20200603_9](https://user-images.githubusercontent.com/1890538/83639120-cd103100-a5dc-11ea-9dcc-c35420f6f4f2.png)

5. 操作场景 : 打开僵尸粉工具

我猜是因为在扫描的过程中, 进行删除导致的

**Comment by MustangYM** [comment]
最新版已经修复，没有发新版本，重新安装即可
