### ISSUE TITLE
僵尸粉检测后，新拉的群还存在

### ISSUE THREAD

**Issue by Kito0615** [MustangYM/WeChatExtension-ForMac#415]
Issue示例
1. MacOS版本 : 10.12.6
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.8
4. BUG描述 : 僵尸粉检测后，新拉的群依然存在
5. 操作场景 : 启动僵尸粉检测后，新拉的群依然存在。我作为已经群主已经删除的该群，群主自动变成另一好友了，所以还有好友还能看到群。好像并不是自己退出，群就自动解散了，而会变成第一个被邀请的人作为群主。
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
只要你不在群里首先说话，别人的会话列表里就不会有这个群出现。
