### ISSUE TITLE
【检测僵尸粉】 检测个数问题

### ISSUE THREAD

**Issue by wdkGitHub** [MustangYM/WeChatExtension-ForMac#416]
1. MacOS版本 : OSX 10.15.5 build(19F101)
2. 微信版本 : Version. 2.4.1 (14470)
3. 小助手版本 : 2.5.8
4. BUG描述 :  【检测僵尸粉】  检测个数和微信显示的个数不同，正在检测个数大于总检测个数。
 
   检测出好友列表中没有的好友【weibo】见图，检测结束一直存在转圈圈的图
  
<img width="415" alt="WechatIMG431" src="https://user-images.githubusercontent.com/12813051/83717332-0c826000-a665-11ea-8312-6432b12b04ea.png">

<img width="436" alt="WechatIMG430" src="https://user-images.githubusercontent.com/12813051/83717244-d349f000-a664-11ea-9703-b4c379bc3b5f.png">

----

![WechatIMG429 1](https://user-images.githubusercontent.com/12813051/83717214-b7464e80-a664-11ea-8344-4a8810bfee05.jpeg)

**Comment by MustangYM** [comment]
已经修复，只是没有发版
