### ISSUE TITLE
安装小助手提示 No such file or directory

### ISSUE THREAD

**Issue by z937010871** [MustangYM/WeChatExtension-ForMac#417]
1. MacOS版本 : 10.14.1
2. 微信版本 : 2.3.30
3. 小助手版本 : 2.5.8
4. BUG描述 :/Users/My/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/4a05fa49b8a451762a4e500e6d6ff735/Message/MessageTemp/e0b92677e6cfdb6cb3467dc56e349731/File/WeChatExtension-ForMac-master/WeChatExtension/Rely/Install.sh: line 44: /Users/My/Library/Containers/com.tencent.xinWeChat/Data/Library/Application: No such file or directory

**Comment by MustangYM** [comment]
我其实不太想回答这个问题，对不起。

**Comment by z937010871** [comment]
> 我其实不太想回答这个问题，对不起。

为什么不想回答这个问题呀... 可以麻烦告知下么

**Comment by lvhe19880210** [comment]
> > 我其实不太想回答这个问题，对不起。
> 
> 为什么不想回答这个问题呀... 可以麻烦告知下么

我好想遇到过这个问题  解决办法就是彻底重新装
