### ISSUE TITLE
检测僵尸粉  工具里显示人数和我好友列表人数不一致

### ISSUE THREAD

**Issue by trulynb** [MustangYM/WeChatExtension-ForMac#418]
Issue示例
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.8
4. BUG描述 : 检测僵尸粉  工具里显示人数和我好友列表人数不一致
5. 操作场景 : 启用检测僵尸粉
6. 方便的话提供日志, 截图或者视频(可选)
<img width="291" alt="Xnip2020-06-04_15-19-16" src="https://user-images.githubusercontent.com/17597573/83726945-e1087100-a676-11ea-89b4-375549a5790c.png">
<img width="372" alt="Xnip2020-06-04_15-20-02" src="https://user-images.githubusercontent.com/17597573/83726952-e36acb00-a676-11ea-83cf-40e6d13ae3ff.png">

**Comment by MustangYM** [comment]
@trulynb 是通过sex来判断是否是人，所以可能有误差

**Comment by trulynb** [comment]
哈哈哈哈  看来我好友里没填性别的人挺多的

**Comment by trulynb** [comment]
还有就是好像只能识别到单删   不能识别到拉黑    我这有个把我拉黑的好友（该好友微信上设置了性别）   但是小工具没检测到她

**Comment by MustangYM** [comment]
@trulynb 拉黑识别不了
