### ISSUE TITLE
聊天记录尾字符消失

### ISSUE THREAD

**Issue by vvvvvicabd** [MustangYM/WeChatExtension-ForMac#419]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.3.30
3. 小助手版本 : 2.5.7
4. BUG描述 : 聊天记录尾字符消失
5. 操作场景 : 微信启动后, 搜索关键字，出来的记录超出一定长度结尾字符会消失
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
能截图看看嘛

**Comment by MustangYM** [comment]
@vvvvvicabd 能截图看看嘛

**Comment by ffanwq** [comment]
> @vvvvvicabd 能截图看看嘛

我也是同样的问题，截图如下：
![image](https://user-images.githubusercontent.com/19601210/83896448-c7eee580-a786-11ea-8ca2-57591c16c662.png)

**Comment by MustangYM** [comment]
[V2.5.9](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.9)
