### ISSUE TITLE
退出时保留聊天记录希望可以关闭。

### ISSUE THREAD

**Issue by nlnlnull** [MustangYM/WeChatExtension-ForMac#42]
感谢大佬的继续维护，原库一直有一个问题，就是关闭不了“退出时保留聊天记录”这个选项，原作者说是因为多开登录无法区分账号的原因。

希望大佬可以解决一下这个问题。

**Comment by MustangYM** [comment]
> 感谢大佬的继续维护，原库一直有一个问题，就是关闭不了“退出时保留聊天记录”这个选项，原作者说是因为多开登录无法区分账号的原因。
> 
> 希望大佬可以解决一下这个问题。

可以做, 方式也有, 但是做的价值不大. 大部分人就是那么一两个账号在自己的机器上跑着.

**Comment by liubiantao** [comment]
@MustangYM  有什么命令可以清楚聊天记录吗
