### ISSUE TITLE
多开功能怎么关闭?

### ISSUE THREAD

**Issue by pinklinux** [MustangYM/WeChatExtension-ForMac#420]
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.0 (14091)
3. 小助手版本 : 2.5.8
4. BUG描述 : 打开微信多开功能无法关闭
5. 操作场景 : 打开微信多开功能无法关闭,之后点击小程序会打开新的微信登录.请问怎么关闭这个多开啊...

**Comment by MustangYM** [comment]
read me 有写

**Comment by pinklinux** [comment]
> read me 有写

就是点击了之后,直接打开新的登录窗口了.无法关闭呀.
<img width="211" alt="image" src="https://user-images.githubusercontent.com/37838492/83884180-1bf1ce00-a777-11ea-9a43-2cf295c6970f.png">

**Comment by ffanwq** [comment]
同样的问题

**Comment by pinklinux** [comment]
<img width="144" alt="image" src="https://user-images.githubusercontent.com/37838492/86440076-6c3f5a00-bd3c-11ea-8f7b-5ccc8d35fd7b.png"> 


> 同样的问题
