### ISSUE TITLE
僵尸粉功能不能用

### ISSUE THREAD

**Issue by spfeng** [MustangYM/WeChatExtension-ForMac#421]
1. MacOS版本 : 10.16.6beta
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.5.8
4. BUG描述 : 僵尸粉功能第一次使用到一半就停了，后来点开始提示“检测失败，微信系统反方，一小时后再试“，半天后仍然无法启动

**Comment by MustangYM** [comment]
[已下架此功能](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.9)
