### ISSUE TITLE
检测僵尸粉，对方有提示

### ISSUE THREAD

**Issue by iwangjin** [MustangYM/WeChatExtension-ForMac#422]
如果好友中有企业微信好友，会生成企业微信群聊，对方会有群聊提示。
而且如果要退出检测僵尸粉的功能后，会自动退出群聊，但好友还在群中，非常尴尬。😂

**Comment by MustangYM** [comment]
@iwangjin 企业微信这个我确实没想到，我会尽快修复这个问题

**Comment by ParfoisMeng** [comment]
我。。。香菇

**Comment by supergithuber** [comment]
我今天刚刚使用完这个功能，微信好友中也有企业微信好友，并没有这个现象

**Comment by shadow198** [comment]
> 如果好友中有企业微信好友，会生成企业微信群聊，对方会有群聊提示。
> 而且如果要退出检测僵尸粉的功能后，会自动退出群聊，但好友还在群中，非常尴尬。😂

同尴尬

**Comment by MustangYM** [comment]
[已下架此功能](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.9)
