### ISSUE TITLE
升级新版微信和小助手后选择了使用系统浏览器打开链接会闪退

### ISSUE THREAD

**Issue by GPPyeye** [MustangYM/WeChatExtension-ForMac#426]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.1 官网dmg版本
3. 小助手版本 : 1.9.6
4. BUG描述 : 选择了使用系统浏览器打开聊天链接会闪退
5. 操作场景 : 选择了使用系统浏览器打开聊天链接会闪退
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
现在小助手最新版本[V2.5.8](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.5.8)了
