### ISSUE TITLE
为啥把僵尸粉功能下架了

### ISSUE THREAD

**Issue by ManutdGTA** [MustangYM/WeChatExtension-ForMac#433]
Issue示例
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.1(14485)
3. 小助手版本 : 2.5.8
4. BUG描述 : 无
5. 操作场景 : 无

小助手很好用,没啥问题.

就好奇想问下,大佬为啥把僵尸粉功能下架了,这功能挺好用的啊.

**Comment by MustangYM** [comment]
@ManutdGTA 版本更新信息里有
