### ISSUE TITLE
最新更新的 在手机上拍一拍 无法看到自己拍一拍别人的信息

### ISSUE THREAD

**Issue by D-R-L** [MustangYM/WeChatExtension-ForMac#434]

**Comment by likeSo** [comment]
还没适配最新版本微信吧，现在最新版本微信是2.4.1 (14491)，readme里面写的是2.4.0

**Comment by likeSo** [comment]
尴尬，我还以为不适配了，脱离小助手好多天了，看其他issue试了下手动安装是可以的

**Comment by likeSo** [comment]
尴尬，我还以为不适配了，脱离小助手好多天了，看其他issue试了下手动安装是可以的
好像确实看不到自己发出的拍一拍消息，别人发出的可以看到，我也出现这个问题了

**Comment by D-R-L** [comment]
> 尴尬，我还以为不适配了，脱离小助手好多天了，看其他issue试了下手动安装是可以的
> 好像确实看不到自己发出的拍一拍消息，别人发出的可以看到，我也出现这个问题了

是这样，自己主动触发的，无论是拍自己还是别人都不会提醒

**Comment by MustangYM** [comment]
@D-R-L 跟小助手有啥关系。。。。

**Comment by D-R-L** [comment]
> @D-R-L 跟小助手有啥关系。。。。

微信官方适配的问题么……？
