### ISSUE TITLE
无法安装成功

### ISSUE THREAD

**Issue by YoleYu** [MustangYM/WeChatExtension-ForMac#435]
Issue示例
1. MacOS版本 : 10.14.6
2. 微信版本 : Version. 2.4.1 (14485)
3. 小助手版本 : ？？
4. BUG描述 : 无法安装成功
5. 操作场景 :a. curl -o- -L https://omw.limingkai.cn/install.sh | bash -s  安装
                     b. 重启微信
                     c. 发现小助手没有生效
6. 开始下载 Oh My WeChat...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11965  100 11965    0     0  22813      0 --:--:-- --:--:-- --:--:-- 22790
成功安装 Oh My Wechat！即将安装微信小助手……
[16:34:32] 当前 Oh My WeChat 版本为 v1.3.2
[16:34:32] 当前没有安装微信小助手
[16:34:32] 未安装微信小助手，也没有下载过安装包，所以即使使用了 -n 参数，仍需要检查并下载新版本
[16:34:32] 正在查询新版本……
[16:34:33] 微信小助手的最新版本为 v2.5.9
[16:34:33] 开始下载微信小助手 v2.5.9……
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64    0    64    0     0    531      0 --:--:-- --:--:-- --:--:--   533
[2.5.9.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 2.5.9.zip or
        2.5.9.zip.zip, and cannot find 2.5.9.zip.ZIP, period.
mv: rename wechatextension-formac to WeChatExtension-ForMac-2.5.9: No such file or directory
[16:34:33] 下载完成
[16:34:33] 开始安装微信小助手……
/Users/yoleyu/.oh_my_wechat/omw: line 249: ./WeChatExtension-ForMac-2.5.9/WeChatExtension/Rely/Install.sh: No such file or directory
[16:34:33] 微信小助手安装完成。
[16:34:33] 检测到微信正在运行，请重启微信让小助手生效。

**Comment by MustangYM** [comment]
看起来是解压失败的问题，试试执行这个命令 `brew install p7zip` 安装p7zip后，解压是否还失败。如果还失败，那就用手动安装吧

**Comment by YoleYu** [comment]
安装p7zip后，还是无法安装。
手动安装成功了。但是失败原因不详。
