### ISSUE TITLE
检测僵尸粉建议

### ISSUE THREAD

**Issue by xxx-bu2** [MustangYM/WeChatExtension-ForMac#436]
这几天用了几次检测僵尸粉的功能，刚刚也看了一些issue里关于僵尸粉的问题，我想说下自己的观察。
现象1：拉满到40人之后，就不再拉人进群了。
猜测：微信40人的时候可以设置管理员，不知是否与此有关。
现象2：检查到100人之后，检查的人数还在增加，但是群动态并没有拉人入群的动态，手动拉一个人入群提示太过繁忙稍后再试。
猜测：请求太过频繁，被微信官方限制请求。
现象3：每次检查都要从头开始。
现象4：关闭检测窗口时会删除群。

建议：
1.检查某个人的时候，先拉入群，然后踢出群。这样既不会达到40人的限制，即使误发了消息也好解释，不会社会性死亡。
2.当微信限制请求时，停止请求，在僵尸粉页面显示检测状态，每隔10分钟或者30分钟或者1小时去尝试拉人入群，如果依旧限制则继续等待，如果不再限制则继续进行检测。
3.记录上次检测到了哪位好友，不再重复检测，记录保存在内存中，重新登录后清空记录。或者，可以手动选择100人进行检测。
4.关闭窗口时不删除群，只是把好友全部踢出，这样这个群的动态里还会保留那些提示「xx不是好友，请先加好友」，手机上很方便就可以点「提示」去查看僵尸粉的个人信息。

**Comment by MustangYM** [comment]
@xxx-bu2 僵尸粉检测功能已经删除掉了, 目前的实现方式还不是很稳定.
