### ISSUE TITLE
主题模式能否选择系统自带的，现在这个看个人资料，聊天时有点难受

### ISSUE THREAD

**Issue by fafuzuoluo** [MustangYM/WeChatExtension-ForMac#437]
主题模式能否选择系统自带的，现在这个看个人资料，聊天时有点难受，有些文字都看不清

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/85219171-1bdb0a80-b3d4-11ea-85ae-b5259bb2229e.png)

**Comment by fafuzuoluo** [comment]
太棒了
