### ISSUE TITLE
 微信登录后卡死

### ISSUE THREAD

**Issue by gaoyuqiang** [MustangYM/WeChatExtension-ForMac#439]
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.4.0
4. BUG描述 : mac微信登录后卡死，界面出不来，微信未响应！我从应用程序删除微信，重新装了好几次也不行，小助手卸载了仍然不行！这是微信app自己的bug吗？昨天突然不能用的，之前一直好好的。难道是因为我前两天更新mac系统到最新10.15.5的问题吗？实在找不到原因

**Comment by MustangYM** [comment]
不清楚

**Comment by gaoyuqiang** [comment]
重启电脑好了，跟插件没有关系.....
