### ISSUE TITLE
希望能够将黑暗/深邃模式下，UI的白色底框改成灰色/浅色！

### ISSUE THREAD

**Issue by zhuozhiyongde** [MustangYM/WeChatExtension-ForMac#444]
Issue示例
1. MacOS版本 : 10.xx.x
2. 微信版本 : 2.x.x
3. 小助手版本 : 2.x.x
4. BUG描述 : 会话头像抖动
5. 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by zhuozhiyongde** [comment]
新增：黑暗/深邃模式下，公众号界面标题并未改成灰色/白色，仍为黑色x

**Comment by MustangYM** [comment]
不好改。
