### ISSUE TITLE
可不可以增加视频不降低其他应用音量的功能

### ISSUE THREAD

**Issue by befuture** [MustangYM/WeChatExtension-ForMac#446]
可不可以增加一个选项让WeChat启动视频的时候不会让其他Application的音量降低。

这个功能是通过API AudioDeviceDuck来实现的，目前可以通过lldb来实现：

printf "p *(char*)(void(*)())AudioDeviceDuck=0xc3\nq" | lldb -n WeChat

希望能够集成这个功能。

**Comment by MustangYM** [comment]
NO
