### ISSUE TITLE
内存泄露我的ＭＡＣ无法删除文件了怎么办

### ISSUE THREAD

**Issue by wangfpp** [MustangYM/WeChatExtension-ForMac#447]
Issue示例
3. 小助手版本 : 2.６．０

**Comment by MustangYM** [comment]
@wangfpp 能具体说下嘛？

**Comment by wangfpp** [comment]
@MustangYM  用了2.6.0的版本　内存就不够用了，　./Uninstall.sh也是无法卸载
我在Terminal中rm -rf 或者文件管理中删除文件都是提示`内存不足`无法删除

最后无奈重启　我还怕重启会引起文件丢失　重启后解决了．．．．
感谢你的回复
