### ISSUE TITLE
由于工作原因，小程序正常使用和双开微信的需求希望能实现（即使只有一个微信可以打开小程序也可以）

### ISSUE THREAD

**Issue by leeyi19910708** [MustangYM/WeChatExtension-ForMac#448]
Issue示例
1. MacOS版本 : 10.15.5 (19F101)
2. 微信版本 : 2.4.1 (14491)
3. 小助手版本 : 2.6.0(2020-06-30)
4. BUG描述 : 非BUG，为需求
5. 操作场景 : 工作原因，在平时上班需要用mac登录两个微信的需求已经满足的前提下，本人经常需要用到小程序进行一些业务操作，如果可以在电脑上进行操作，会便利许多。希望可以提供一个解决方案，个人认为当同时登录两个微信时，只有其中一个可以打开小程序这个实现是可以接受的。

**Comment by MustangYM** [comment]
不会放开此功能，会导致很多人认为这是个BUG

**Comment by stevenliuit** [comment]
解决这个最好的方式是 你装个mac的虚拟机 或者准备两台电脑 既然是公司的工作 让老板采购两台
