### ISSUE TITLE
[需求] 怎么能够发送视频

### ISSUE THREAD

**Issue by losswei** [MustangYM/WeChatExtension-ForMac#457]
大佬，求问怎么发送视频，观察了下MessageService的方法，没找到合适的方法。

**Comment by MustangYM** [comment]
MMMessageSendLogic下的sendVideoMessageWithFileUrl方法

**Comment by losswei** [comment]
> MMMessageSendLogic下的sendVideoMessageWithFileUrl方法

我也看到了这个方法，但是他入参只有一个，感觉不太可能，给谁发未定义。

**Comment by MustangYM** [comment]
@losswei 自己试都不试, 怎么知道不可能?
