### ISSUE TITLE
【新功能建议】：能否增加聊天背景的支持？

### ISSUE THREAD

**Issue by joescon** [MustangYM/WeChatExtension-ForMac#458]
背景：工作群比较多，有时候光看群名字不明显，容易发错信息。如果能像手机端一样，不同群设置不同的背景图片就好了。
需求：同步显示手机端的群聊天背景；或者在小助手加上添加背景的功能

请开发者考虑一下？其他朋友如有此需求也可以评论反馈
谢谢。

Issue示例
1. MacOS版本 : 10.xx.x
2. 微信版本 : 2.x.x
3. 小助手版本 : 2.x.x
4. BUG描述 : 会话头像抖动
5. 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
不太好实现
