### ISSUE TITLE
有人退群 退群监控其他群之前的退群信息也都会显示

### ISSUE THREAD

**Issue by y451687300** [MustangYM/WeChatExtension-ForMac#464]
Issue示例
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.x
3. 小助手版本 : 2.4.1
4. BUG描述 :有人退群 退群监控其他群之前的退群信息也都会显示
5. 操作场景 : 有人退群 退群监控其他群之前的退群信息也都会显示
6. 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/35559412/87288424-e7b7bd00-c52d-11ea-806c-60eaa3e86354.png)

**Comment by MustangYM** [comment]
[已经移除](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.1)
