### ISSUE TITLE
能不适配暗黑就不要再适配暗黑了

### ISSUE THREAD

**Issue by Michomzhudaisheng** [MustangYM/WeChatExtension-ForMac#465]
Issue示例
1. MacOS版本 : 10.15.5 (19F101)
2. 微信版本 : 2.4.1 (14492) Beta 144
3. 小助手版本 : 2.6.1
4. BUG描述 : 能不适配暗黑就不要再适配暗黑了，有问题！！！
5. 操作场景 : 
![image](https://user-images.githubusercontent.com/18712902/87292640-ae824b80-c533-11ea-83ee-7db903defa5e.png)

**Comment by MustangYM** [comment]
1. 你是叫我不适配黑夜主题 2.还是说你在原始主题下产生了这个问题 3.还是说你本身使用了黑夜主题，而出现的效果却图所示？
ps：我是想说，what a u talking about？先学会怎么说话。另，小助手是我个人兴趣，不挣钱也不靠这吃饭，你爱用不用。

**Comment by Michomzhudaisheng** [comment]
大佬脾气都不好么

**Comment by Michomzhudaisheng** [comment]
> 1. 你是叫我不适配黑夜主题 2.还是说你在原始主题下产生了这个问题 3.还是说你本身使用了黑夜主题，而出现的效果却图所示？
>    ps：我是想说，what a u talking about？先学会怎么说话。另，小助手是我个人兴趣，不挣钱也不靠这吃饭，你爱用不用。

**Comment by FWangZil** [comment]
为什么总有伸手党可以这么理直气壮？没有能力提PR请先学会保持谦虚，好好沟通（而且我发现你微信还用的beta版本）。作者又不欠谁的
