### ISSUE TITLE
2.4.1版微信，小程序收到显示“你收到了一个小程序 请在手机上查看”

### ISSUE THREAD

**Issue by msn1983aa** [MustangYM/WeChatExtension-ForMac#467]
Issue示例
1. MacOS版本 : 10.15.5（版号19F101）
2. 微信版本 : v2.4.1.16 (14485)
3. 小助手版本 : 2.6.1
4. BUG描述 : 同版本微信，同事的未装小助手打开小程序正常，我这台机器装了小助手，收到小程序都显示“你收到了一个小程序 请在手机上查看”，而且卸载小助手和微信后，只重装store版本微信，小程序依然无法显示。之前用过2.4.0的beta版微信配合小助手是正常打开过小程序的。
5. 操作场景 : 收到小程序后，无法打开，小助手里已勾选“允许打开小程序”，而且这个勾选无论点几次都无法反选。

**Comment by junjzhang** [comment]
一样的问题

**Comment by MustangYM** [comment]
有的小程序是会这样，这是微信官方的问题

**Comment by msn1983aa** [comment]
> 有的小程序是会这样，这是微信官方的问题

谢谢！
