### ISSUE TITLE
为什么要移出退群监控呢？

### ISSUE THREAD

**Issue by bpguide** [MustangYM/WeChatExtension-ForMac#468]
非常有用的功能哇，怎么就不要了呢

**Comment by MustangYM** [comment]
我在寻思新的实现方式

**Comment by garethyang527** [comment]
@MustangYM 请问下历史版本的退群监控的代码逻辑，当前提示的信息是群昵称，我想要改成获取到微信ID信息，能否贴下具体的代码所在段落？

**Comment by bpguide** [comment]
> 我在寻思新的实现方式

不是移除就行，我就不担心啦。哈哈

**Comment by takeTrace** [comment]
> 我在寻思新的实现方式

可以加个开关设成默认关闭吗, 关键时候没有就很....
