### ISSUE TITLE
微信v2.4.2消息列表不显示问题

### ISSUE THREAD

**Issue by adlered** [MustangYM/WeChatExtension-ForMac#474]
Issue示例
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.1
4. BUG描述 : 消息列表不显示
5. 操作场景 : 
问题1.  小助手安装后，第一次打开微信，多点几下消息列表里的好友，会出现多选的情况；
问题2. 使用cmd+Q彻底关闭微信，重新启动微信后，消息列表完全消失 （卸载插件后恢复正常）

**Comment by DeMeng33** [comment]
消息列表不显示+1  
MacOS版本 : 10.15.5
微信版本 : 2.4.2
小助手版本 : 2.6.1

**Comment by DeMeng33** [comment]
目前卸载了，期待修复

**Comment by AllenYSL** [comment]
测试了一下，关闭免认证功能可以正常使用

**Comment by adlered** [comment]
微信回退到2.4.1版本，正常使用，感谢大大维护

**Comment by P1kAju** [comment]
更新版本后重启微信不展示聊天列表。
MacOS version : 11.0 Beta
Wechat version：2.4.2

**Comment by Steven-WGD** [comment]
> 更新版本后重启微信不展示聊天列表。
> MacOS version : 11.0 Beta
> Wechat version：2.4.2

我也是这个问题今天早上更新最新版微信客户端后重新安装小助手，登录后聊天列表就不显示了，期待修复
> MacOS version : 10.15.6 (19G73)
> Wechat version：2.4.2 (15039)

**Comment by Garlichead** [comment]
我也是遇到了这种情况 吓我一跳 感觉卸载 别被删除了聊天记录就好

**Comment by Suremotoo** [comment]
同问微信版本：2.4.2
![image](https://user-images.githubusercontent.com/26423989/88018123-a476d300-cb59-11ea-87a3-bc757eb91389.png)

**Comment by cooper1x** [comment]
一样的问题

**Comment by yangcht** [comment]
同样的问题。

**Comment by chendeben** [comment]
更新了插件之后，出现相同的问题，卸载后正常，期待修复

**Comment by Kerr19** [comment]
Version. 2.4.2 (15040) Beta 144 问题依旧存在

**Comment by itcodes** [comment]
关闭认证登录后正常。

**Comment by yangnaihua** [comment]
+1

**Comment by Xchn** [comment]
不实用免认证登陆就没问题了

**Comment by nkbai** [comment]
如何退回到2.4.1呢，我不小心更新到了2.4.2

**Comment by itcodes** [comment]
> 如何退回到2.4.1呢，我不小心更新到了2.4.2

关闭那个认证登录也可以。。要么就是重新装下微信。

**Comment by nkbai** [comment]
重装微信就可以么？

**Comment by nkbai** [comment]
删掉微信，重装就可以了，我的版本是2.4.2 @itcodes

**Comment by MustangYM** [comment]
[v2.6.3已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.3)
