### ISSUE TITLE
小程序选项勾选后无法取消

### ISSUE THREAD

**Issue by char1eslu** [MustangYM/WeChatExtension-ForMac#478]
Issue示例
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.4.1 (14485)
3. 小助手版本 : 2.6.2
4. BUG描述 : Allow MiniProgram to Open勾选后 收到小程序依然提示在手机打开，遂准备取消勾选，结果发现怎么点都取消不了，退出再点也无用

**Comment by MustangYM** [comment]
read me有写

**Comment by char1eslu** [comment]
咦，我不是多开呢，就一个微信，然后想取消勾选也不行
