### ISSUE TITLE
会话名称少了一个字

### ISSUE THREAD

**Issue by zhenghan12138** [MustangYM/WeChatExtension-ForMac#480]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 :  2.4.1
3. 小助手版本 : 2.6.2
4. BUG描述 : 会话名称少了一个字
5. 操作场景 : 朋友列表与会话框对比少了一个字
![image](https://user-images.githubusercontent.com/27910093/88122931-6383ca80-cbfc-11ea-9a77-897706973824.png)
![image](https://user-images.githubusercontent.com/27910093/88122949-71d1e680-cbfc-11ea-96e8-6ac351c5c03a.png)

**Comment by MustangYM** [comment]
[v2.6.3已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.3)
