### ISSUE TITLE
fuzzy mode （透明主题） icon的颜色还是dark mode的颜色

### ISSUE THREAD

**Issue by yangcht** [MustangYM/WeChatExtension-ForMac#482]
Issue示例
1. MacOS版本 : 10.15.6 (19G73)
2. 微信版本 : Version 2.4.2 (15039)
3. 小助手版本 : 2.6.2
4. BUG描述 : fuzzy mode icon的颜色还是dark mode的颜色
5. 操作场景 : 微信在启动fuzzy颜色模式开启后
6. 截图 
<img width="663" alt="Screenshot 2020-07-22 at 01 13 39" src="https://user-images.githubusercontent.com/806801/88137112-dbc89c80-cbb8-11ea-8478-34af2808ea77.png">

**Comment by MustangYM** [comment]
在某些启动场景下会出现此情况

**Comment by lsave** [comment]
@MustangYM  dark mode中有办法hook修改聊天气泡的背景色（现在还是白色有点刺眼）？或可以指点一下方法，微调了一下UI，比较舒服了，就差这个聊天气泡。

**Comment by MustangYM** [comment]
@lsave 气泡不能调，这个会影响聊天信息的阅读

**Comment by MustangYM** [comment]
[已解决](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.4)
