### ISSUE TITLE
微信小组手免认证登录后,聊天列表为空

### ISSUE THREAD

**Issue by VFiee** [MustangYM/WeChatExtension-ForMac#485]
Issue示例
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.2 
3. 小助手版本 : 2.6.2
4. BUG描述 : 免认证登录
5. 操作场景 : 勾选微信小组手免认证登录后,重启微信后  聊天列表为空
截图:
![image](https://user-images.githubusercontent.com/42051272/88353620-d02fce00-cd90-11ea-95b9-919f09658238.png)
![image](https://user-images.githubusercontent.com/42051272/88353647-ea69ac00-cd90-11ea-901e-4b4fac50153a.png)

**Comment by MustangYM** [comment]
#474

**Comment by rokey-xia** [comment]
手机退出，然后重新登录就解决了
