### ISSUE TITLE
更换主题，消息列表消失了，换回主题无效

### ISSUE THREAD

**Issue by AskeyNil** [MustangYM/WeChatExtension-ForMac#487]
Issue示例
1. MacOS版本 : 10.15.5
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.2
4. BUG描述 : 
![image](https://user-images.githubusercontent.com/20418220/88386799-b4a1e300-cde3-11ea-8090-3b15db733605.png)

5. 操作场景 : 切换回主题，所有的消息列表都消失了。
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
2.4.2还没适配, 把免认证登录关掉就好了

**Comment by AskeyNil** [comment]
ok，把免认证登录关闭，目前正常。

**Comment by Wooge123** [comment]
用回微信2.4.0版本，即可正常使用，扫码获取下载地址：

<img src="https://user-images.githubusercontent.com/17154921/88478795-b0113200-cf7d-11ea-854e-52230ad23673.png" width="200px" />

**Comment by ailinal** [comment]
请问可不可以不修改主题，我只是想要一个免认证登陆。
希望能可以提供不换主题的选择

**Comment by MustangYM** [comment]
@ailinal 再点一次关闭（认真读read me）

**Comment by ailinal** [comment]
> @ailinal 再点一次关闭（认真读read me）

哈哈哈，我点了半天一级菜单没反应，没想到是在二级点

**Comment by MustangYM** [comment]
[v2.6.3已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.3)
