### ISSUE TITLE
最新版微信自动登录后白屏（app store更新）

### ISSUE THREAD

**Issue by fanyiwei233** [MustangYM/WeChatExtension-ForMac#488]
只能二维码登录后才有聊天记录

![iShot2020-07-25上午08 12 30](https://user-images.githubusercontent.com/34305320/88444292-0fbcef80-ce4f-11ea-9849-a35a8e7cd3de.png)

**Comment by fanyiwei233** [comment]
![iShot2020-07-25上午08 19 40](https://user-images.githubusercontent.com/34305320/88444423-9b368080-ce4f-11ea-8751-c37c8a18c2dc.png)

**Comment by fanyiwei233** [comment]
不勾选自动登录，仅免认证登录也是白屏

**Comment by monotone** [comment]
+1

**Comment by daliang1215** [comment]
+1

**Comment by nkbai** [comment]
期待作者解决

**Comment by ulpyuxa** [comment]
我也一样，应该是新版还没兼容，期待作者更新。

**Comment by Derekxxzzyy** [comment]
我也一样，不过我有微X模块

**Comment by YangAidi** [comment]
期望作者更新，给跪了

**Comment by Wooge123** [comment]
可以装回微信2.4.0公测版，免认证登陆功能依然可用，下载地址：

![image](https://user-images.githubusercontent.com/17154921/88478795-b0113200-cf7d-11ea-854e-52230ad23673.png)

**Comment by zwsn** [comment]
同，等待修复的第三天

**Comment by OMGZui** [comment]
同

**Comment by cftcn** [comment]
同

**Comment by zifeng-chen** [comment]
在手机上，退出Mac微信，然后Mac端重新登录微信就好了

**Comment by YangAidi** [comment]
> 在手机上，退出Mac微信，然后Mac端重新登录微信就好了

十分感谢，好了，完美解决方案

**Comment by fanyiwei233** [comment]
> 在手机上，退出Mac微信，然后Mac端重新登录微信就好了

@zifeng-chen 但是退出Mac微信后，下次再打开点击“自动登录”还是白屏😓

**Comment by MustangYM** [comment]
[v2.6.3已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.3)
