### ISSUE TITLE
撤回消息显示备注

### ISSUE THREAD

**Issue by L1cardo** [MustangYM/WeChatExtension-ForMac#49]
有没有办法撤回的消息显示撤回人的备注？
现在直接显示撤回人的昵称，这样的话也认不出是谁了。
现在放暑假了，时间也比较充裕，希望你可以研究一下....哈哈哈哈

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by MustangYM** [comment]
> 有没有办法撤回的消息显示撤回人的备注？
> 现在直接显示撤回人的昵称，这样的话也认不出是谁了。
> 现在放暑假了，时间也比较充裕，希望你可以研究一下....哈哈哈哈
> 
> Sent from [PPHub For GitHub](https://itunes.apple.com/cn/app/id1314212521)

实现不难, 只要是通讯录里的人撤回, 就能显示备注. 如果是群撤回就不行了

**Comment by L1cardo** [comment]
是通讯录里面的人，昨天撤回了，但是显示的是他的昵称

**Comment by MustangYM** [comment]
已经好了
