### ISSUE TITLE
麻烦检查好再release行不？每次更新没过半小时又重新release

### ISSUE THREAD

**Issue by FlameMida** [MustangYM/WeChatExtension-ForMac#491]
Issue示例
1. MacOS版本 : 10.xx.x
2. 微信版本 : 2.x.x
3. 小助手版本 : 2.x.x
4. BUG描述 : 会话头像抖动
5. 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
@FlameMida 这么大项目, 就我一个人开发, 没有测试人员, 很难啊

**Comment by augusl** [comment]
> Issue示例
> 
> 1. MacOS版本 : 10.xx.x
> 
> 2. 微信版本 : 2.x.x
> 
> 3. 小助手版本 : 2.x.x
> 
> 4. BUG描述 : 会话头像抖动
> 
> 5. 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
> 
> 6. 方便的话提供日志, 截图或者视频(可选)
> 
> 

这么大项目, 就作者一个人开发, 没有测试人员, 他很难啊

**Comment by augusl** [comment]
> Issue示例
> 
> 1. MacOS版本 : 10.xx.x
> 
> 2. 微信版本 : 2.x.x
> 
> 3. 小助手版本 : 2.x.x
> 
> 4. BUG描述 : 会话头像抖动
> 
> 5. 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
> 
> 6. 方便的话提供日志, 截图或者视频(可选)
> 
> 

这么大项目, 就作者一个人开发, 没有测试人员, 他很难啊

**Comment by augusl** [comment]
这么大项目, 就作者一个人开发, 没有测试人员, 他很难啊

**Comment by 0yueyunfei0** [comment]
白嫖别人的成果意见还挺多的啊

**Comment by FWangZil** [comment]
出现了，白嫖埋怨怪！
