### ISSUE TITLE
请问怎么使用微信小程序

### ISSUE THREAD

**Issue by lihj** [MustangYM/WeChatExtension-ForMac#493]
Issue示例
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.3
4. BUG描述 : 之前微信2.4.1的时候微信小程序可以正常使用，更新成2.4.2之后，小程序不能用了，只提示 [你收到了一个小程序，请在手机上查看]

**Comment by lihj** [comment]
各种安装方式卸载安装都试过了。。还是一样

**Comment by MustangYM** [comment]
这是微信自己的问题
