### ISSUE TITLE
迷离模式主题页面空白

### ISSUE THREAD

**Issue by LuHaikun** [MustangYM/WeChatExtension-ForMac#494]
Issue示例
1. MacOS版本 : 最新
2. 微信版本 : 最新
3. 小助手版本 : 最新
4. BUG描述 : 迷离模式主题页面空白
5. 操作场景 : 开启迷离模式跟免认证登入进入主页
6. 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/16951645/88633539-b9b6a900-d0e7-11ea-8810-df1bf71acb83.png)

**Comment by MustangYM** [comment]
#488
