### ISSUE TITLE
微信forMac2.4.2 版本无法打开小程序，打开弹窗登陆新微信窗口

### ISSUE THREAD

**Issue by NotWang** [MustangYM/WeChatExtension-ForMac#496]
微信版本 : 2.4.2
小助手版本 : 2.6.3
微信forMac2.4.2 版本无法打开小程序，打开弹窗登陆新微信窗口
已启用允许使用小程序，未开启免认证登陆，未双开

**Comment by NotWang** [comment]
![image](https://user-images.githubusercontent.com/32693877/88662541-acf87c00-d10c-11ea-81bd-a38d0d8a17b8.png)

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/88666569-d4524780-d112-11ea-98ad-087e0b5fcfb1.png)

**Comment by NotWang** [comment]
我知道是互斥的，但是就是你看下图的配置就是无法打开小程序
![image](https://user-images.githubusercontent.com/32693877/88673547-521a5100-d11b-11ea-9f9e-f85e58dcef67.png)

**Comment by msn1983aa** [comment]
<img width="436" alt="QQ20200729-085353@2x" src="https://user-images.githubusercontent.com/12170480/88744160-26c64f00-d179-11ea-86d0-a2656a820404.png">
请问2.4.2版本的微信+2.6.3版本的小助手，所有的小程序都是这样的显示如何破？

**Comment by steeephen145** [comment]
> <img alt="QQ20200729-085353@2x" width="436" src="https://user-images.githubusercontent.com/12170480/88744160-26c64f00-d179-11ea-86d0-a2656a820404.png">
> 
> 请问2.4.2版本的微信+2.6.3版本的小助手，所有的小程序都是这样的显示如何破？各种卸载重装都不好使。

我也有这个问题

**Comment by msn1983aa** [comment]
> > <img alt="QQ20200729-085353@2x" width="436" src="https://user-images.githubusercontent.com/12170480/88744160-26c64f00-d179-11ea-86d0-a2656a820404.png">
> > 请问2.4.2版本的微信+2.6.3版本的小助手，所有的小程序都是这样的显示如何破？各种卸载重装都不好使。
> 
> 我也有这个问题

我上午又想了想这个问题和小助手无关，所以先把小助手卸载，再用cleanmymac把微信深度卸载了，再重装微信和小助手就好了，case close.
