### ISSUE TITLE
迷离模式点击图片缩放过程中特别卡

### ISSUE THREAD

**Issue by ppttvs** [MustangYM/WeChatExtension-ForMac#497]
Macbook 15寸 2017款  macOS 10.15.6
如果不开独显的话点击图片查看的过程中缩放动画特别卡顿，并且图片要花更长的时间才能从马赛克状态变清晰，开了独显就不会这样。我在想是不是毛玻璃特效占用过多显卡资源导致的。
来Mark一下

**Comment by MustangYM** [comment]
这里有个性能问题，我下个版本解决

**Comment by ppttvs** [comment]
> 这里有个性能问题，我下个版本解决

老哥稳

**Comment by MustangYM** [comment]
[v2.6.5](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.5)
