### ISSUE TITLE
这个没有Alfred插件吗?

### ISSUE THREAD

**Issue by Glen93** [MustangYM/WeChatExtension-ForMac#5]

**Comment by lixingguang** [comment]
自带的吧

**Comment by MustangYM** [comment]
感觉alfred用得少，五一节后搞一下

**Comment by ibmsoft** [comment]
alfred 直接用原来的就可以

**Comment by Glen93** [comment]
只能查聊天记录 不能定位到微信聊天界面发消息,难道是我设置的有问题吗?

**Comment by 77321660** [comment]
> alfred 直接用原来的就可以

使用原来的workflow闪退，无法使用；
macOS：10.14.6
微信：2.3.26
插件：1.9.5
原来的workflow：by Tkkk
