### ISSUE TITLE
主题色： 能否支持原画，  默认的4个主题色，很不适应，希望有选项

### ISSUE THREAD

**Issue by nieshiming** [MustangYM/WeChatExtension-ForMac#502]
Issue示例
1. MacOS版本 : 10.15.3
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.3
4. BUG描述 : 无
优化点： 希望支持主题色原画

**Comment by gzdzss** [comment]
+1 希望支持原主体.

**Comment by nieshiming** [comment]
> +1 希望支持原主题

刚找到了解决办法了：
主题模式-->黑夜模式 再点击一次就关闭了

**Comment by gzdzss** [comment]
可以了, 大佬 优秀!
