### ISSUE TITLE
放发错群功能

### ISSUE THREAD

**Issue by zhangshuge** [MustangYM/WeChatExtension-ForMac#504]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.6.3
4. 需求描述 : 是否可以增加一个指定的群发送确认功能，防止消息发错群。   发之前提示下发送是否确认发送，或者指定的群输入框特殊颜色提示灯。

**Comment by MustangYM** [comment]
不考虑。
