### ISSUE TITLE
选择不同步消息,但是历史消息还在

### ISSUE THREAD

**Issue by gzdzss** [MustangYM/WeChatExtension-ForMac#505]
Issue示例
1. MacOS版本 : 10.15.3
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.5.3
4. BUG描述 : 登录的时候选择不同步消息, 但是原来的历史消息还在.
5. 操作场景 : 登录,  选择不自动同步消息

期望, 

选择自动同步消息,  登录以后 清空历史.

**Comment by gzdzss** [comment]
![image](https://user-images.githubusercontent.com/41991766/88992929-2499f700-d317-11ea-8395-f992b5572f76.png)


无法关闭设置中的 退出保留聊天记录,

**Comment by Mapleshade20** [comment]
同issue

**Comment by wuyuehyang** [comment]
+1
