### ISSUE TITLE
允许打开小程序不管用

### ISSUE THREAD

**Issue by gzvincen** [MustangYM/WeChatExtension-ForMac#507]
Issue示例
1. MacOS版本 : 0.15.4 (19E287)
2. 微信版本 : 2.4.2 (15067)
3. 小助手版本 : 2.6.3
4. BUG描述 : 开启了 允许打开小程序，但是在接收到小程序的时候，依旧显示的是收到小程序 xxxxx

**Comment by MustangYM** [comment]
微信的问题
