### ISSUE TITLE
微信始终悬浮于活动窗口之上

### ISSUE THREAD

**Issue by wangzi0218** [MustangYM/WeChatExtension-ForMac#508]
Issue示例
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.3
4. BUG描述 : 除非关闭微信窗口，微信始终置于所有窗口顶部
5. 操作场景 : 微信启动后, 鼠标左键点击其他 app（如 chrome，excel 等），微信都不会被其他活动窗口覆盖。卸载小助手之后问题消失。
6. 方便的话提供日志, [截图或者视频(可选)]

[屏幕录制2020-08-03 下午6.03.36.mov.zip](https://github.com/MustangYM/WeChatExtension-ForMac/files/5015269/2020-08-03.6.03.36.mov.zip)

**Comment by MustangYM** [comment]
你是否选择了窗口置顶？

**Comment by wangzi0218** [comment]
并没有选择窗口置顶。而且微信也无法窗口置顶。

对比后发现卸载微信小助手后现象就消失。

**Comment by MustangYM** [comment]
@wangzi0218 小助手有窗口置顶功能，你可能误按了快捷键

**Comment by wangzi0218** [comment]
@MustangYM 

验证了，确实是误触快捷键所致。感谢回复。
