### ISSUE TITLE
新增图片，链接过滤能力

### ISSUE THREAD

**Issue by Su27SK** [MustangYM/WeChatExtension-ForMac#51]
1. 可以新增一些过滤广告能力，比如饿了么红包分享啥的，以及一些广告贴
2. 增加对图片的过滤能力，主要是一些无关紧要的广告图片

**Comment by MustangYM** [comment]
> 1. 可以新增一些过滤广告能力，比如饿了么红包分享啥的，以及一些广告贴
> 2. 增加对图片的过滤能力，主要是一些无关紧要的广告图片

做不到.
