### ISSUE TITLE
迷离模式下的若干显示bug

### ISSUE THREAD

**Issue by Mapleshade20** [MustangYM/WeChatExtension-ForMac#510]
MacOS版本 : 10.15.6
微信版本 : 2.4.2 (15064) Beta 145
小助手版本 : 2.6.3 (2020-07-27)
BUG描述 : 
  1. 迷离模式下，**快速连续点击**任意会话（至少两次）后，该会话颜色不再会变淡，而是保持在选中模式，具体见视频；
![都是快速双击](https://user-images.githubusercontent.com/62641761/89389591-32e17c00-d738-11ea-970c-8f992b057a1f.gif)
  2. 迷离模式下，公众号列表界面顶部的「公众号」三个字是黑色，不符合UI，应该是白色；还有一条突兀的白线；
<img width="442" alt="image" src="https://user-images.githubusercontent.com/62641761/89389978-b307e180-d738-11ea-8dec-8b1cf54de30c.png">
  3. 迷离模式下，“收藏”和“文件”窗中的图标都是黑色，，不符合UI，应该是白色。
<img width="131" alt="image" src="https://user-images.githubusercontent.com/62641761/89390057-c9ae3880-d738-11ea-9c63-139c056530a3.png">

**Comment by MustangYM** [comment]
第一条我会考虑修改。第二和第三条改起来并不容易。
