### ISSUE TITLE
界面显示问题

### ISSUE THREAD

**Issue by christioner** [MustangYM/WeChatExtension-ForMac#512]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.3
4. BUG描述 : 界面配色及文字显示问题
5. 操作场景 : 微信启动后, 所显示的各个地方（各个模式都有）
6. 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/60873198/89496492-0471a880-d7ed-11ea-86fc-03b31e5e566b.png)
![image](https://user-images.githubusercontent.com/60873198/89496854-b4dfac80-d7ed-11ea-9561-755574f4ab49.png)

上面所看到的界面配色是我自行修改了的，在原界面中，图2所指的地方基本没法看

**Comment by christioner** [comment]
![image](https://user-images.githubusercontent.com/60873198/89497052-215aab80-d7ee-11ea-97f1-5f46041aaed3.png)
![image](https://user-images.githubusercontent.com/60873198/89497081-30d9f480-d7ee-11ea-8ae1-92d26d4054c4.png)

附上修改的地方，以供参考

**Comment by MustangYM** [comment]
目前这个darkMode配色也是大伙在群里讨论出来的，不再更改。至于图标看不清，之前没这问题的，是新系统导致的，我会想办法修复。
