### ISSUE TITLE
求清空记录功能

### ISSUE THREAD

**Issue by gzdzss** [MustangYM/WeChatExtension-ForMac#515]
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.3

- [ ] 清空记录功能

**Comment by MustangYM** [comment]
“清空记录”这太简短了，具体是指？

**Comment by gzdzss** [comment]
> “清空记录”这太简短了，具体是指？

就是可清空mac端的所有聊天记录, 每天打开微信就可以是一个崭新的开始, 不想被历史所牵绊,谢谢大佬. 🙏

**Comment by MustangYM** [comment]
我猜，100个人里面可能都不到一个人有这个需求。所以我想没有什么必要做。

**Comment by killsting** [comment]
非常需要，而且好几个人提到了无法关闭保存消息记录，非常不利于想要在公司清空聊天记录的用户。
