### ISSUE TITLE
macOS 11.0 Beta 闪退

### ISSUE THREAD

**Issue by JokerHB** [MustangYM/WeChatExtension-ForMac#521]
Issue示例
1. MacOS版本 : 11.0 Beta版(20A5343j)
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.3
4. BUG描述 : 闪退
5. 操作场景 : 微信启动后不久会自动闪退。
6. 日志如下：
[wechat-error.log](https://github.com/MustangYM/WeChatExtension-ForMac/files/5049872/wechat-error.log)

**Comment by MustangYM** [comment]
崩溃栈没有落在小助手里面, 这可能是微信自己的一个crash
