### ISSUE TITLE
能不能发布nightly build版本？

### ISSUE THREAD

**Issue by ShineUnM** [MustangYM/WeChatExtension-ForMac#523]
不知道发在这里合不合适，如果不合适烦请作者删除。

每次看到作者更新了代码，但是要等一段时间才会编译到release版本中，总有点等不及的感觉 ：）

印象中github有自动编译的选项，作者有没有可能在更新代码又检查无错后自动或者手动更新一个nightly build版本出来？作者每次更新总能修复一些bug，这样也方便心急的朋友今早用上。

有第三方下载网站好像跟踪了项目进度，作者一有更新就会发布二进制版本，而且那个网站还是收费下载的，拿作者免费提供的代码获利，总感觉不爽

**Comment by MustangYM** [comment]
@ShineUnM 都是些小更新修复，没必要发版打扰大家。哪个网站这么调皮？发出来瞧瞧

**Comment by ShineUnM** [comment]
比如https://www.macw.com/mac/1592.html， 这个站长还是很勤奋的，几乎是同步跟新 ：）
