### ISSUE TITLE
macOS Big Sur 微信整体卡住不动

### ISSUE THREAD

**Issue by LiYanan2004** [MustangYM/WeChatExtension-ForMac#524]
Issue示例
1. MacOS版本 : 11 beta
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.3
4. BUG描述 : 微信整体卡住不动 点不开 强制退出以后一定概率无法使用免认证登陆
5. 操作场景 : 微信启动后, 登陆 关闭窗口 使用dock栏点击微信图标 bug 复现 状态栏点击图标也有一定概率出现
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
任何Beta环境下的bug都不具备修复和调试的意义

**Comment by LiYanan2004** [comment]
确实不具备调试的意义 但是这看似并不是macOS的问题 这个问题自从beta2到现在仍然存在 卸载小插件后正常 因此判定是小插件的问题，反馈给您是让您知道一下 提前有个准备 一面大部分用户在9月或者10月使用了macOS Big Sur以后出现相同的问题儿放弃使用小插件

**Comment by MustangYM** [comment]
我暂时不会升级macOS Big Sur，因为我担心各种兼容问题导致不能正常开发，从而也无法适配小助手，趋于稳定后我再适配和升级。

**Comment by LiYanan2004** [comment]
好 但是这个问题你得现在知道一下 如果后续macOS通过OTA解决了这个bug我也会在这里给你反馈的
