### ISSUE TITLE
multiTalkButton 错误

### ISSUE THREAD

**Issue by JIAZoro** [MustangYM/WeChatExtension-ForMac#528]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.3.31 (13331)
3. 小助手版本 : 2.6.4
4. BUG描述 : multiTalkButton 错误
5. 操作场景 : 微信启动后, 自动弹出这个错误
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
更新下微信
