### ISSUE TITLE
小助手2.6.4版本点击dock栏上面的微信图标无法打开微信主界面

### ISSUE THREAD

**Issue by cuishuoguo** [MustangYM/WeChatExtension-ForMac#529]
1. MacOS版本 : 10.15.3
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.4
4. BUG描述 : 更新了最新版小助手之后，微信页面点关闭之后，点击dock栏上面的微信图标无法打开微信主界面，点击右上角菜单栏和消息通知则可以重新吧微信页面显示在桌面

**Comment by MustangYM** [comment]
懵。。。

**Comment by cuishuoguo** [comment]
新增bug描述：dock栏退出按钮，点击无效，无法退出微信

**Comment by cuishuoguo** [comment]
更新：昨晚我强制从内存关闭微信之后，重新打开微信，发现dock栏点微信也正常了，猜测可能是当时小助手更新微信时自动退出微信不彻底，导致某些配置没被加载？目前来看这个bug是没有了 ，可以正常
