### ISSUE TITLE
mac 微信客户端 表情接受不到，手机上可以。

### ISSUE THREAD

**Issue by hesj** [MustangYM/WeChatExtension-ForMac#53]
![image](https://user-images.githubusercontent.com/23515123/60952081-1f919080-a32d-11e9-8ab6-0dbab73f097f.png)
![IMG_99C9B015FFE7-1](https://user-images.githubusercontent.com/23515123/60952087-24eedb00-a32d-11e9-8515-d4f8b8729f4c.jpeg)

**Comment by MustangYM** [comment]
现在还会出现这种情况么
