### ISSUE TITLE
setNormalColor: 错误 multiTalkButton 错误

### ISSUE THREAD

**Issue by ChokW** [MustangYM/WeChatExtension-ForMac#530]
Issue示例
1. MacOS版本 : 10.12.6
2. 微信版本 : 2.3.25 (12461)
3. 小助手版本 : (8.13 看到的最新版本)
4. BUG描述 : 小助手弹窗提示 setNormalColor: 错误   multiTalkButton 错误, 微信退出
5. 操作场景 : 微信启动登录后,

**Comment by MustangYM** [comment]
更新下微信

**Comment by ChokW** [comment]
> 更新微信至2.4.2

额  能不更新吗...  那个引用太难受了

**Comment by MustangYM** [comment]
@ChokW 下个版本我加个低版本的兼容吧，目前来说唯一的解决方案就是你升级到2.4.2微信

**Comment by ChokW** [comment]
> @ChokW 下个版本我加个低版本的兼容吧，目前来说唯一的解决方案就是你升级到2.4.2微信

okok  辛苦啦  那先升上去等下版本再降吧...  或者我先卸载插件的话 是不是也可以...  但是深色主题就没了...
