### ISSUE TITLE
Version. 2.4.2 (15067) mac 微信版本，最新版小助手， 小程序无法打开

### ISSUE THREAD

**Issue by siyuana** [MustangYM/WeChatExtension-ForMac#531]
Version. 2.4.2 (15067)
mac 微信版本，最新版小助手，v2.6.4
小程序无法打开，提示你打开了一个小程序，请在手机上查看

**Comment by yanwen** [comment]
你是不是从 app store 下载的？？  app  store 下载的微信不支持小程序。

你试试从官网下载吧。 https://dldir1.qq.com/weixin/mac/WeChatMac.dmg

**Comment by NotWang** [comment]
可以奥，原来2.6.3有几天打不开小程序，突然有一天就打得开了，然后2.6.4也打开是正常的

**Comment by leeyi19910708** [comment]
不知道为什么我在mac点击小程序就弹出微信多开的登录弹窗

**Comment by gzvincen** [comment]
[升级至2.4.2(15650)Beta 148](https://developers.weixin.qq.com/community/develop/doc/0000a0544fcfc013c8b9d164a5b801)

**Comment by gzvincen** [comment]
> [升级至2.4.2(15650)Beta 148](https://developers.weixin.qq.com/community/develop/doc/0000a0544fcfc013c8b9d164a5b801)

亲测没问题，这个版本的微信，最新的助手。
