### ISSUE TITLE
你的代码是不是有后门

### ISSUE THREAD

**Issue by martin-huang** [MustangYM/WeChatExtension-ForMac#532]
Issue示例
1. MacOS版本 : 10.xx.x
2. 微信版本 : 2.x.x
3. 小助手版本 : 2.x.x
4. BUG描述 : 会话头像抖动
5. 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
6. 方便的话提供日志, 截图或者视频(可选)
毕竟看到你 mac 部分的代码是来自 适用于Mac版的WeChat拓展功能。1.7.5代码来自于WeChatPlugin，对TK在此表示感谢！
https://xlab.tencent.com/cn/2018/10/23/weixin-cheater-risks/#more-398
再看下这则新闻。。。心惊胆战。。。
![image](https://user-images.githubusercontent.com/9817146/90123372-4b354480-dd91-11ea-8888-5bc1a87806d5.png)

**Comment by MustangYM** [comment]
代码都开源了，还这样说，显得十分令人气愤。

**Comment by martin-huang** [comment]
Sorry 因为看到你借鉴的TK的代码是有后门的，被曝光了，所以才多问几句，避免不小心引用了他有后门的代码

MustangYM <notifications@github.com>于2020年8月13日 周四下午6:52写道：

**Comment by stevenliuit** [comment]
你自己检查源代码吧 都开源了 有没有漏洞都带源代码了 看看就知道了 况且很多大公司都有过漏洞记录 这个项目你要担心漏洞 真的是担心多了
