### ISSUE TITLE
安装之后，自动修改了好几个群的群名

### ISSUE THREAD

**Issue by miao0405** [MustangYM/WeChatExtension-ForMac#534]
初次安装小助手之后，好几个工作群被我修改了别的群名，可是我明明没有改动，那只能是小助手的问题了。希望能查看一下，不然改了工作群的名字挺尴尬的。
![image](https://user-images.githubusercontent.com/29529645/90202485-6dba7280-de10-11ea-86da-1acc5067e299.png)
![image](https://user-images.githubusercontent.com/29529645/90202500-7612ad80-de10-11ea-82a4-79c9284a790f.png)

**Comment by MustangYM** [comment]
小助手明明没有这个功能，那只能是你的问题了。

**Comment by miao0405** [comment]
主要是，我别的没有操作。。而且我确实是在这个点安装的小助手，所以突然大批量改群名，我也很疑惑🤔好吧，可能只是一个特例～

**Comment by MustangYM** [comment]
我也很奇怪，这个太灵异了
