### ISSUE TITLE
bugs: 透明适配、卡顿。feature: 建议新增默认主题选项。

### ISSUE THREAD

**Issue by CoderTyy** [MustangYM/WeChatExtension-ForMac#537]
Issue示例
1. MacOS版本 : 10.15.5（MBP 16寸）
2. 微信版本 : 2.4.1
3. 小助手版本 : 2.6.4
4. BUG描述 : 
  **1. 建议增加默认主题选项，用了几个星期才发现双击相同主题是恢复默认主题，还以为不能用默认😭
  2. 点击界面左侧文件图标，其顶部日期选择栏颜色没有适配。
  3. 在界面左侧的“会话图标”和“通讯录图标”切换，有点卡顿。**
5. 操作场景 : 微信启动后, 鼠标左键点击左侧纵向图标。
6. 
<img width="830" alt="bug截图" src="https://user-images.githubusercontent.com/45116321/90259217-3d102280-de7c-11ea-9ed6-86fb7301053f.png">

**Comment by MustangYM** [comment]
1. 不会增加默认主题选项 2.切换界面那里不是卡顿, 已是目前最优解 3.文件管理界面有尝试适配, 但不好实现, 打开频率不高,所以就目前的解决方案我能接受.
