### ISSUE TITLE
打开微信提示崩溃错误

### ISSUE THREAD

**Issue by archerio** [MustangYM/WeChatExtension-ForMac#538]
setNormalColor: 错误

系统是         macOS 10.15.6 (19G73) 
微信版本是 Version. 2.3.29 (12948)
小助手版本是 V2.6.4
打开微信后，提示 setNormalColor: 错误  我需要点击七八遍确定才能进入微信。

**Comment by archerio** [comment]
![截屏2020-08-15 上午3 08 34](https://user-images.githubusercontent.com/42939579/90284978-888af680-dea5-11ea-968b-9e846a63c0ca.png)
如图所示

**Comment by MustangYM** [comment]
更新微信到2.4.2
