### ISSUE TITLE
解除微信对特定的 URL 重定向

### ISSUE THREAD

**Issue by sarkrui** [MustangYM/WeChatExtension-ForMac#540]
诸如：未备案的 .info 域名、微博图床、淘宝分享链接都会被重定向，要正确打开，只能手动复制粘贴 URL 链接再到第三方浏览器打开，有没有解决方案？

![iShot2020-08-16PM01 00 42](https://user-images.githubusercontent.com/14228455/90333238-76ec4080-dfc4-11ea-980d-39d9eff71d74.jpg)

**Comment by MustangYM** [comment]
小助手有"使用系统浏览器"打开网页的功能

**Comment by sarkrui** [comment]
@MustangYM 已经确认有打开 "使用系统浏览器"
助手版本: 2.6.4
微信程序版本: 2.4.0 (13962)
macOS 版本: 10.15.6 (19G2021)

![](https://i.imgur.com/TsYH16V.gif)

测试链接 1：https://tva1.sinaimg.cn/large/007SdXQhgy1ghsutfrg8gj30k00k0aa6.jpg （微博图床链接）
测试链接 1：https://taobao.com (淘宝)

**Comment by MustangYM** [comment]
@sarkrui 办法是有, 直接提取这个url,调用系统浏览器打开, 不过这个需求比较罕见, 应该不会加到小助手里

**Comment by sarkrui** [comment]
@MustangYM 
不知道怎么回事，已解决。右键链接消息，Open in WeChat（使用微信打开），就不会被重定向了。（需开启`使用系统浏览器`）
![](https://i.imgur.com/ktToxfV.gif)
