### ISSUE TITLE
multiTalkButton 错误

### ISSUE THREAD

**Issue by maxinyong** [MustangYM/WeChatExtension-ForMac#542]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.3.30
3. 小助手版本 : 2.6.4
4. BUG描述 : "**multiTalkButton 错误 请点击【关于与捐赠】->【项目主页】 提issue联系开发者修复!**"
5. 操作场景 : 微信启动后,扫码登录，显示bug对话框。

<img width="420" alt="截屏2020-08-17 上午8 22 05" src="https://user-images.githubusercontent.com/12688816/90347615-23c9ca80-e064-11ea-9737-b023ae0df310.png">

**Comment by hujiee** [comment]
same

**Comment by MustangYM** [comment]
微信升到2.4以上即可
