### ISSUE TITLE
建议： 聊天对话框里的文字，图片，转发到公众号（服务号）

### ISSUE THREAD

**Issue by seanlvjie** [MustangYM/WeChatExtension-ForMac#544]
1. MacOS版本 :macOS 10.13.6 (17G7024)
2. 微信版本 : Version 2.4.2 (15063)
3. 小助手版本 : 2.6.4

一个微信对话里的文字，或者是图片，希望能一次性选取，然后转发到 微信公众号里（服务号）。 

现在的情况对于图片，必须先切到图片所在的对话里，然后复制，在切换到 指定公众号的对话框里复制。 每复制一个图片，都需要切换一次对话框，很繁琐。希望能加入这个功能

**Comment by seanlvjie** [comment]
为啥Close了

**Comment by MustangYM** [comment]
[请看wiki](https://github.com/MustangYM/WeChatExtension-ForMac/wiki/Issues%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)
