### ISSUE TITLE
建议出个原始主题的（白色）的选项

### ISSUE THREAD

**Issue by forging2012** [MustangYM/WeChatExtension-ForMac#545]
建议出个原始主题的（白色）的选项。
几个主题做的都很好，就想要个原版的（白色）主题的选项
谢谢~！

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/90382976-1a674f00-e0b2-11ea-816a-fe760453b8dd.png)

**Comment by forging2012** [comment]
非常感谢~！

**Comment by yyhuaisha** [comment]
简版的点击了提示重启，重启以后还是黑夜模式

**Comment by MustangYM** [comment]
@yyhuaisha 简版不支持关闭皮肤

**Comment by yyhuaisha** [comment]
> @yyhuaisha 简版不支持关闭皮肤

好的，感谢
