### ISSUE TITLE
如何关闭微信多开功能

### ISSUE THREAD

**Issue by erbaiA** [MustangYM/WeChatExtension-ForMac#547]
Issue示例
1. MacOS版本 :10.15.6
2. 微信版本 : 2.4.2
3. 小助手版本 : v2.6.4
4. BUG描述 : 开启多开后不能关闭多开，或者有没有方法可以关闭多开功能

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/90399075-f2d1b000-e0cc-11ea-91f0-59586d063747.png)

**Comment by seanlvjie** [comment]
这个2个选项互斥 目前融入在GUI的设计，不太让人容易理解。建议改进
