### ISSUE TITLE
菜单栏图标无法控制，用 BarTender 也无法隐藏

### ISSUE THREAD

**Issue by samyinyue** [MustangYM/WeChatExtension-ForMac#548]
1. MacOS版本 : 10.15.6 
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.4
4. BUG描述 : 菜单栏图标无法被隐藏
5. 操作场景 : 使用 BarTender 无法选择显示/隐藏菜单栏中的图标，提示错误如下图
6. 
![image](https://user-images.githubusercontent.com/51718011/90462093-bb015180-e13a-11ea-87e5-6ba687cea43a.png)

**Comment by samyinyue** [comment]
为什么直接关闭了？没有小助手的时候是可以收进 BarTender 里面的。

**Comment by MustangYM** [comment]
在我测试的过程中，网易云音乐也出现了你这个警告，而装有插件的微信并没有出现此警告

**Comment by samyinyue** [comment]
> 在我测试的过程中，网易云音乐也出现了你这个警告，而装有插件的微信并没有出现此警告

好吧，我卸载小助手重装后正常了。谢谢回答！

**Comment by MustangYM** [comment]
不客气

**Comment by WeiViming** [comment]
这个bug会出现在当用户直接退出微信后系统进入睡眠, 下次再打开微信的时候. 解决方案只有重装.
