### ISSUE TITLE
multiTalkButton错误

### ISSUE THREAD

**Issue by BanjinWang** [MustangYM/WeChatExtension-ForMac#549]
##1.MacOS版本 : 10.14.6 (18G103)
##2.微信版本 : 2.4.0 (14091) Beta 148
##3.小助手版本 : 2.6.4
##4. BUG描述 : 登录即弹窗
##5. 操作场景 : 微信启动后，直接弹窗。
##6. 这里是截图，![1597800516681](https://user-images.githubusercontent.com/20638142/90581775-a1c1d900-e1fe-11ea-9b07-e86332347e17.jpg)

**Comment by MustangYM** [comment]
#542
