### ISSUE TITLE
1.9.1无法更新

### ISSUE THREAD

**Issue by jjb727** [MustangYM/WeChatExtension-ForMac#55]
一直提示有更新，下载安装后点击重启后还是1.9.1
下载zip安装包也一样还是1.9.1
麻烦看下怎么回事，谢谢

**Comment by libingtong** [comment]
我也遇见了这个问题，发现更新时下载的安装包还是1.9.1的，所以会出现这个问题。直接下载 zip 安装也一样。

**Comment by MustangYM** [comment]
> 一直提示有更新，下载安装后点击重启后还是1.9.1
> 下载zip安装包也一样还是1.9.1
> 麻烦看下怎么回事，谢谢

已解决

**Comment by MustangYM** [comment]
> 我也遇见了这个问题，发现更新时下载的安装包还是1.9.1的，所以会出现这个问题。直接下载 zip 安装也一样。

已解决
