### ISSUE TITLE
远程控制是否能实现自定义控制内容或者开放接口？

### ISSUE THREAD

**Issue by AskeyNil** [MustangYM/WeChatExtension-ForMac#550]
目前只有更改控制的键值对，我想添加一些其他的控制，最好能自定义，我去执行我系统内预设的脚本，或者可以开放一个接口供我使用。谢谢。

**Comment by MustangYM** [comment]
这个属于比较偏门的个人需求，你可以根据自己的需求对小助手开源代码进行修改
