### ISSUE TITLE
撤回消息无效，一直loading

### ISSUE THREAD

**Issue by gzchenjiajun** [MustangYM/WeChatExtension-ForMac#552]
Issue示例
1. MacOS版本 : 10.15.6 
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.4
4. BUG描述 : 撤回消息无效，一直loading
5. 操作场景 :正常消息撤回，一直loading，现在发错消息非常麻烦需要去手机手动撤回
6. 方便的话提供日志, 截图或者视频(可选)

![image](https://user-images.githubusercontent.com/13104274/90588967-827f7780-e20f-11ea-8b50-ceda381e064d.png)

**Comment by MustangYM** [comment]
这是小助手的“拦截自己消息”功能

**Comment by gzchenjiajun** [comment]
![image](https://user-images.githubusercontent.com/13104274/90714381-20d80f80-e2da-11ea-90df-6afb07fe3a5f.png)
我已经关闭了小助手的“拦截自己撤回消息”功能，现象依旧

**Comment by MustangYM** [comment]
关掉了还这样，我也很奇怪。

**Comment by ueiu** [comment]
我这里也发现了这个问题，然后同事跟我说实际撤回成功了，但我这边还是显示被撤回成功的信息
