### ISSUE TITLE
出现崩溃

### ISSUE THREAD

**Issue by kimplwjf** [MustangYM/WeChatExtension-ForMac#555]
出现莫名崩溃

**Comment by MustangYM** [comment]
小助手版本号, 微信版本号, 日志贴出来瞧瞧

**Comment by kimplwjf** [comment]
小助手版本号：2.6.4
日志我不知道在哪找给你啊，大佬～我一直点击确定还是能进去使用的，只是每次打开都会提示这个之前的崩溃记录。

**Comment by MustangYM** [comment]
没有日志我确定不了，对不起

**Comment by kimplwjf** [comment]
😁好的，不要紧，非常感谢回复！

MustangYM <notifications@github.com> 于2020年8月20日周四 上午10:25写道：
