### ISSUE TITLE
安装完成以后，微信直接崩溃。

### ISSUE THREAD

**Issue by Sky-Gu** [MustangYM/WeChatExtension-ForMac#556]
Issue示例
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.2.2
3. 小助手版本 : git clone 最新版
4. BUG描述 :  安装以后无法打开微信 
5. 操作场景 : 执行 install.sh 以后，微信无法打开，提示微信崩溃
6. 方便的话提供日志, 截图或者视频(可选)

MacOS 的系统日志

Process:               WeChat [40145]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               2.4.2 (15063)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [40145]
User ID:               501

Date/Time:             2020-08-20 09:18:33.769 +0800
OS Version:            Mac OS X 10.15.6 (19G2021)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        42E9758C-CEF2-5767-8F37-136027433773

Sleep/Wake UUID:       F0DEC8BB-8DA6-455F-B8A7-37D841A7FDC3

Time Awake Since Boot: 100000 seconds
Time Since Wake:       49000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/WeChatTweak.framework/WeChatTweak
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: image not found

Binary Images:
       0x10afbe000 -        0x10f479fff +com.tencent.xinWeChat (2.4.2 - 15063) <93DF379A-4D0D-3244-959D-4870426E7C80> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x1109ee000 -        0x110a34ff7 +org.sparkle-project.Sparkle (1.20.0 913-ge196a24d - 1.20.0) <50C08D08-2F05-3F4A-A50C-46CE14FD6420> /Applications/WeChat.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x110aaa000 -        0x110bf6ff3 +com.tencent.WCDB (1.0.3 - 1) <9EB19FD7-1BFC-3D48-951D-71284A9218FB> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x110d36000 -        0x110d3cff7 +com.tencent.MMLibHooks (1.0 - 1) <C6A10DAA-93F7-3956-8351-92F3F966EAEA> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x110d4e000 -        0x110d70ff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x110dac000 -        0x110dceffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x110e0e000 -        0x110eaefff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x11bfff000 -        0x11c090f47  dyld (750.6) <F9D4DEDC-8296-3E3F-B517-9C8B89A4C094> /usr/lib/dyld
    0x7fff28cbe000 -     0x7fff28eb9ff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff28f88000 -     0x7fff290a5ff6  com.apple.AVKit (1.1 - 600.2) <41B403F1-2F32-37BB-A0D7-B84AF3F1734B> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff290a6000 -     0x7fff290a6fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff2a6d2000 -     0x7fff2b492ff2  com.apple.AppKit (6.9 - 1894.60.100) <C5D84BE3-FD1B-3141-BB78-487A83256DC5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff2b814000 -     0x7fff2b8f5ffa  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <8CFA0620-5E43-3C4D-A75B-981C0961C2DE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2b8f7000 -     0x7fff2b8f7fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <C8F9CC56-F7CF-3E77-B6FC-BD8E1D19FA92> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff2bc8e000 -     0x7fff2c01dffa  com.apple.CFNetwork (1128.0.1 - 1128.0.1) <07F9CA9C-B954-3EA0-A710-3122BFF9F057> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff2c099000 -     0x7fff2c099fff  com.apple.Carbon (160 - 162) <FB72FB7D-5985-3D9C-82DB-A729FCA1249A> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff2c57d000 -     0x7fff2c57dfff  com.apple.Cocoa (6.11 - 23) <2F5C8ABA-711F-316C-BB97-921122AEE4DF> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff2c96c000 -     0x7fff2ce75ffb  com.apple.audio.CoreAudio (5.0 - 5.0) <9DA02E7A-56A0-3FFF-94C2-1795BA761F07> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff2d41f000 -     0x7fff2d89efeb  com.apple.CoreFoundation (6.9 - 1677.104) <C0D70026-EDBE-3CBD-B317-367CF4F1C92F> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff2d8a0000 -     0x7fff2df15ff8  com.apple.CoreGraphics (2.0 - 1355.22) <4A3CDE7B-4578-3058-966A-3D1DC095A935> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff2e27f000 -     0x7fff2e2e8ff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <75966124-2FB7-33C3-BE49-3DD5F327F911> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff2e63f000 -     0x7fff2e71affc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff2e807000 -     0x7fff2e807fff  com.apple.CoreServices (1069.24 - 1069.24) <AA140158-E909-34C2-B2F5-20EBC93E0056> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff2f27a000 -     0x7fff2f431ffc  com.apple.CoreText (643.1.5.1 - 643.1.5.1) <A88F052A-C840-3E6C-9BF8-FFFED34C0667> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff2f432000 -     0x7fff2f476ffb  com.apple.CoreVideo (1.8 - 344.3) <5314E70D-325F-3E98-99FC-00FDF520747E> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff2f477000 -     0x7fff2f504ffc  com.apple.framework.CoreWLAN (13.0 - 1601.2) <6C76A9E0-430F-3B3C-AE8A-3005F8E6FCFF> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff2fadc000 -     0x7fff2fea1fff  com.apple.Foundation (6.9 - 1677.104) <7C69F845-F651-3193-8262-5938010EC67D> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff30215000 -     0x7fff302b9ff3  com.apple.framework.IOKit (2.0.2 - 1726.140.1) <14223387-6F81-3976-8605-4BC2F253A93E> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff3034b000 -     0x7fff304a7fee  com.apple.ImageIO.framework (3.3.0 - 1976.11) <C17C7280-54F6-3750-85CE-C43428256D62> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff30d15000 -     0x7fff31db5fe9  com.apple.JavaScriptCore (15609 - 15609.3.5.1.3) <1874AA53-2C73-3DB2-A98F-69D9BDB3ADC8> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff33d3b000 -     0x7fff33d85ff8  com.apple.MultipeerConnectivity (166 - 166) <ECB78B83-E384-3079-915E-2D7C791DCD2E> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff34210000 -     0x7fff34232fff  com.apple.audio.OpenAL (1.8 - 1.8) <6D66C5D7-8410-35B7-B06E-3BE56E0A708E> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL
    0x7fff37fa1000 -     0x7fff37fb0ff7  com.apple.opengl (17.10.22 - 17.10.22) <D3C57A32-6BD0-3228-B1C4-0F42A6128A6C> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff38f6d000 -     0x7fff38f6dfff  com.apple.quartzframework (1.5 - 23) <48F3D0F9-323E-34E5-8F63-CF541F2B7B0E> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff38f6e000 -     0x7fff391f1ffb  com.apple.QuartzCore (1.11 - 841.4) <FE927B0E-BD49-32CC-8A55-90F553C86C15> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff391f2000 -     0x7fff3924bff5  com.apple.QuickLookFramework (5.0 - 906.3) <959CE934-B541-3172-846F-4D1709353526> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff39d72000 -     0x7fff3a0bbff1  com.apple.security (7.0 - 59306.140.5) <B6F8368F-2395-379B-B768-71C53BB1B903> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff3ae23000 -     0x7fff3ae9dff7  com.apple.SystemConfiguration (1.19 - 1.19) <84F9B3BB-F7AF-3B7C-8CD0-D3C22D19619F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff3b11d000 -     0x7fff3b4a0ff4  com.apple.VideoToolbox (1.0 - 2625.9) <6CF18E28-A7A8-3952-8171-7E4FF4FB37FA> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff3e358000 -     0x7fff3ea5dffd  com.apple.WebKit (15609 - 15609.3.5.1.3) <77FB3BFF-DF46-3261-8A74-EAB7AF8BDB4D> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff644f2000 -     0x7fff644f3fff  libSystem.B.dylib (1281.100.1) <C0C9872A-E730-37EA-954A-3CE087C15535> /usr/lib/libSystem.B.dylib
    0x7fff647cb000 -     0x7fff647d7fff  libbz2.1.0.dylib (44) <14CC4988-B6D4-3879-AFC2-9A0DDC6388DE> /usr/lib/libbz2.1.0.dylib
    0x7fff647d8000 -     0x7fff6482afff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff652cb000 -     0x7fff653bbfff  libiconv.2.dylib (59) <18311A67-E4EF-3CC7-95B3-C0EDEE3A282F> /usr/lib/libiconv.2.dylib
    0x7fff653bc000 -     0x7fff65613fff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff66352000 -     0x7fff66385fde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff66459000 -     0x7fff66471fff  libresolv.9.dylib (67.40.1) <C57EDFEF-D36A-310B-8D14-8C68A625B1E8> /usr/lib/libresolv.9.dylib
    0x7fff6691f000 -     0x7fff66a01ff7  libxml2.2.dylib (33.4) <EFA77CC6-9139-37B3-98D4-B0E526110EE3> /usr/lib/libxml2.2.dylib
    0x7fff66a2e000 -     0x7fff66a40ff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib

Model: MacBookPro14,3, BootROM 428.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.8 GHz, 16 GB, SMC 2.45f4

**Comment by MustangYM** [comment]
WeChatTweak这玩意不是我的，你之前安过这个，请卸载干净再装小助手，或者重安微信后再装小助手

**Comment by Sky-Gu** [comment]
装了好几个这东西，忘记把这个卸载了。。。
