### ISSUE TITLE
最新安装后，耗电程太可怕了 。。。

### ISSUE THREAD

**Issue by vipadm** [MustangYM/WeChatExtension-ForMac#557]
[](url)
<img width="798" alt="pgh" src="https://user-images.githubusercontent.com/10387808/90707108-69d39800-e2c9-11ea-9933-65cb3448917e.png">

**Comment by vipadm** [comment]
首先忽略第二个耗能数字，是activity 的 每次打开都很高的
微信的插件安装后，耗电、掉电很快，卸载后就没有该问题哈

**Comment by MustangYM** [comment]
小助手版本，系统版本，微信版本，方便告知一下嘛

**Comment by MustangYM** [comment]
是否使用的迷离模式？关掉试试，关掉如果还是耗电高，就不知道原因了

**Comment by vipadm** [comment]
mac os 10.15.6 wechat  2.4.2 助手 2.6.4

**Comment by MustangYM** [comment]
是否使用的迷离模式？关掉试试，关掉如果还是耗电高，就不知道原因了

**Comment by vipadm** [comment]
迷离模式 ，我关掉试试。。有情况反馈哈 @

**Comment by MustangYM** [comment]
@vipadm 关掉迷离模式后, 耗电情况如何?

**Comment by vipadm** [comment]
> @vipadm 关掉迷离模式后, 耗电情况如何?

这几天观察，关掉了 好太多了。。
之前一晚上掉50% 以上都有的，现在 就5%左右哈
