### ISSUE TITLE
 Alfred无法跳转问题

### ISSUE THREAD

**Issue by thlz998** [MustangYM/WeChatExtension-ForMac#560]
Issue示例
1. MacOS版本 : 10.15.6 (19G2021)
2. 微信版本 : Version. 2.4.2 (15282) Beta 147
3. 小助手版本 : v2.6.3
4. BUG描述 : Alfred 可以搜索到聊天对象和记录(很慢，要1秒所有)，但是回车之后无法跳转到相应的聊天对象对话框
5. 操作场景 : Alfred搜索框，输入 wx (wx后面接一个空格)
6. 暂无

**Comment by MustangYM** [comment]
command + 回车 才是打开窗口
