### ISSUE TITLE
最新版本的黑夜模式展示问题描述

### ISSUE THREAD

**Issue by xzzai** [MustangYM/WeChatExtension-ForMac#561]
Issue示例
1. MacOS版本 : 10.13.6
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.4
4. BUG描述 : 微信黑夜模式展示有问题

![image](https://user-images.githubusercontent.com/23736683/90713449-ee2d1780-e2d7-11ea-9633-ce04651695ea.png)

**Comment by MustangYM** [comment]
更新下系统，主题不适配10.13了
