### ISSUE TITLE
点击小程序会多开一个账户然后退出账号重新扫码登陆。

### ISSUE THREAD

**Issue by luckysonyu99** [MustangYM/WeChatExtension-ForMac#562]
Issue示例
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.4
4. BUG描述 : 点击任何小程序的窗口都会多开一个登录账号然后导致微信需要重新扫码登录
5. 操作场景 : 
6. 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/28253960/90732505-c650aa80-e2fd-11ea-9416-0d586c786489.png)

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/90750645-b3db6e80-e307-11ea-9304-d14076adb663.png)
