### ISSUE TITLE
拦截到崩溃

### ISSUE THREAD

**Issue by xiemms** [MustangYM/WeChatExtension-ForMac#564]
![崩溃](https://user-images.githubusercontent.com/16432738/90843304-e763da80-e393-11ea-8c6f-cea876336b7f.png)
微信刚登陆之后每次都会弹这个

**Comment by xiemms** [comment]
微信版本： Version. 2.4.0 (14091) Beta 148
小助手版本： 2.6.4

**Comment by MustangYM** [comment]
#542

**Comment by xiemms** [comment]
> #542

thks
