### ISSUE TITLE
Mac系统安装最新问题

### ISSUE THREAD

**Issue by dudubuxing** [MustangYM/WeChatExtension-ForMac#567]
系统：macOS Catalina   版本：10.15.6
微信版本：2.4.2

终端执行：sudo rm -r -f WeChatSeptet-ForMac && git clone https://github.com/MustangYM/WeChatSeptet-ForMac.git && cd WeChatSeptet-ForMac/WeChatSeptet && ./install.sh

报错信息如下：
/Applications/WeChat.app/Contents/MacOS/WeChat already exists. Overwrite it? [y/n] y
LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat

**注：简单版本可以安装成功**

**Comment by MustangYM** [comment]
报错信息不全
