### ISSUE TITLE
multiTalkButton 错误

### ISSUE THREAD

**Issue by xushenjie** [MustangYM/WeChatExtension-ForMac#572]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.0
3. 小助手版本 : 2.6.4
4. BUG描述 : multiTalkButton 错误
5. 操作场景 : 助手更新启动后, 弹窗错误
![image](https://user-images.githubusercontent.com/24131249/91111869-2a83bd80-e6b4-11ea-868b-e39b2aa3ecf9.png)

**Comment by MustangYM** [comment]
微信升级到2.4.2
