### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by jinghuiABEL** [MustangYM/WeChatExtension-ForMac#573]
Issue示例
1. MacOS版本 : 10.13.6
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.4
4. BUG描述 : 红框内内容均不显示
![image](https://user-images.githubusercontent.com/20577478/91146769-ea3f3200-e6e9-11ea-9bf7-707f954f2df4.png)

**Comment by MustangYM** [comment]
皮肤不支持10.13，已经说了很多次，请在提issue之前，大致翻一下issues列表。
