### ISSUE TITLE
拦截到崩溃，multiTalkButton 错误

### ISSUE THREAD

**Issue by LockeXia** [MustangYM/WeChatExtension-ForMac#574]
Issue示例
1. MacOS版本 : 10.15.5 
2. 微信版本 : 2.3.30
3. 小助手版本 : 2.6.4
4. BUG描述 : multiTalkButton 错误
5. 操作场景 : 微信启动后, 弹出multiTalkButton 错误

**Comment by MustangYM** [comment]
升级到微信2.4.2
