### ISSUE TITLE
左上角搜索框结果列表问题

### ISSUE THREAD

**Issue by ppttvs** [MustangYM/WeChatExtension-ForMac#579]
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.4.2官网版
3. 小助手版本 : 2.6.5
4. BUG描述 : 左上角搜索框选择结果时会出现一条条的白背景  很扎眼 不过不知道是不是故意为之用来保证对比度...
<img width="258" alt="image" src="https://user-images.githubusercontent.com/40455362/91539487-fc200f80-e94b-11ea-9135-49ffb3b583e8.png">

![image](https://user-images.githubusercontent.com/40455362/91539584-240f7300-e94c-11ea-9759-110661e9e1ce.png)

**Comment by littlefisher666** [comment]
同问

**Comment by ppttvs** [comment]
2.6.6问题依旧😂

<img width="265" alt="image" src="https://user-images.githubusercontent.com/40455362/92059196-3150b580-edc3-11ea-8f22-b0c5e748666b.png">

**Comment by ppttvs** [comment]
2.6.6 问题依旧😂

![image](https://user-images.githubusercontent.com/40455362/92059283-6b21bc00-edc3-11ea-8624-c852547024ac.png)

**Comment by MustangYM** [comment]
我这边看了几台机器都没这问题昂，你确定你的系统，微信版本都报对了嘛
<img width="284" alt="WechatIMG1953" src="https://user-images.githubusercontent.com/21478687/92345207-18197300-f0fb-11ea-8077-babc23737190.png">

**Comment by littlefisher666** [comment]
输入关键字后，按上下键切换下试试

**Comment by MustangYM** [comment]
@littlefisher666 我在这个页面取消了方向键的控制。

**Comment by ppttvs** [comment]
不好意思 今天比较忙没注意邮件  系统和软件版本都是没问题的

**Comment by littlefisher666** [comment]
@MustangYM 做样式的调整是不是更合适一些呢？作为我个人而言，因为是从事IT开发的，能不用鼠标或者触摸板的时候就尽量不碰的，毕竟全键盘操作的效率更高一些的

**Comment by ppttvs** [comment]
> 输入关键字后，按上下键切换下试试

你这么一说还真是  方向键一按就会出现白背景 鼠标直接点击或者滑动就没问题  2.6.6依然可以使用方向键控制
