### ISSUE TITLE
11.0 Beta版 微信助手 拦截到崩溃

### ISSUE THREAD

**Issue by taochangle** [MustangYM/WeChatExtension-ForMac#581]
1. MacOS版本 : 11.0 Beta版(20A5354i)
2. 微信版本 :   2.4.2 (15067)
3. 小助手版本 : 2.6.4
4. BUG描述 : 点击dock微信图标弹出提示“如下图”
5. 操作场景 : 微信启动后,叉掉微信， 鼠标点击微信图标，连续弹出两个提示，然后才会打开微信
6. 如下图

![image](https://user-images.githubusercontent.com/7435144/91630431-f38b1000-ea03-11ea-9a7f-a36922411ba8.png)

**Comment by MustangYM** [comment]
不适配beta版本
