### ISSUE TITLE
迷离皮肤感觉透明度太高 [建议]

### ISSUE THREAD

**Issue by qyfHalLu** [MustangYM/WeChatExtension-ForMac#583]
Issue示例
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.5
4. 描述 : 迷离皮肤感觉透明度有点过高了 要是降低一下透明度会不会更好看一些

**Comment by MustangYM** [comment]
见仁见智吧
