### ISSUE TITLE
小助手2.6.5 消息通知失效

### ISSUE THREAD

**Issue by ueiu** [MustangYM/WeChatExtension-ForMac#584]
Issue示例
1. MacOS版本 : 10.14.6 (18G103)
2. 微信版本 : 2.4.2 (15067)
3. 小助手版本 : 2.6.5
4. BUG描述 :  来新消息时消息横幅失效
5. 操作场景 :  来新消息时消息横幅失效，但微信 logo 是正常提示消息数量的
6. 方便的话提供日志, 截图或者视频(可选)
视频地址：http://weihua.qn.wblym.com/iShot2020-08-30%E4%B8%8B%E5%8D%8804.21.51.mov

**Comment by ueiu** [comment]
这个的话在 2.6.2 是正常通知的，但往后的版本都失效了

**Comment by MustangYM** [comment]
这块代码没动，随缘通知。。。我也很纳闷

**Comment by ueiu** [comment]
遇事不决。。重启解决 今天电脑抽风自启后就又开始通知了。。
