### ISSUE TITLE
2.6.5启动崩溃

### ISSUE THREAD

**Issue by Alanelf245** [MustangYM/WeChatExtension-ForMac#585]
Issue\
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.5
4. BUG描述 : 启动即崩溃，无法进入登陆界面
5. 操作场景 : 微信启动后，马上出现报错信息
6. 日志：

Process:               WeChat [2228]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               2.4.2 (15063)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [2228]
User ID:               501

Date/Time:             2020-08-30 13:43:54.637 +0100
OS Version:            Mac OS X 10.15.6 (19G2021)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        B7D6D696-64F7-1165-D580-F798482C22D3

Sleep/Wake UUID:       1E3F79D9-5284-481E-954A-AB2639EDFBDD

Time Awake Since Boot: 12000 seconds
Time Since Wake:       800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: stat() failed with errno=1
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

Binary Images:
       0x102bf5000 -        0x1070b0fff +com.tencent.xinWeChat (2.4.2 - 15063) <93DF379A-4D0D-3244-959D-4870426E7C80> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x108627000 -        0x10866dff7 +org.sparkle-project.Sparkle (1.20.0 913-ge196a24d - 1.20.0) <50C08D08-2F05-3F4A-A50C-46CE14FD6420> /Applications/WeChat.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x1086df000 -        0x10882bff3 +com.tencent.WCDB (1.0.3 - 1) <9EB19FD7-1BFC-3D48-951D-71284A9218FB> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x10896b000 -        0x108971ff7 +com.tencent.MMLibHooks (1.0 - 1) <C6A10DAA-93F7-3956-8351-92F3F966EAEA> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x108984000 -        0x1089a6ff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x1089db000 -        0x1089fdffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x108a3e000 -        0x108adefff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x115b68000 -        0x115bf9f47  dyld (750.6) <F9D4DEDC-8296-3E3F-B517-9C8B89A4C094> /usr/lib/dyld
    0x7fff2a7fa000 -     0x7fff2a9f5ff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff2aac4000 -     0x7fff2abe1ff6  com.apple.AVKit (1.1 - 600.2) <41B403F1-2F32-37BB-A0D7-B84AF3F1734B> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff2abe2000 -     0x7fff2abe2fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff2c20e000 -     0x7fff2cfceff2  com.apple.AppKit (6.9 - 1894.60.100) <C5D84BE3-FD1B-3141-BB78-487A83256DC5> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff2d350000 -     0x7fff2d431ffa  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <8CFA0620-5E43-3C4D-A75B-981C0961C2DE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2d433000 -     0x7fff2d433fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <C8F9CC56-F7CF-3E77-B6FC-BD8E1D19FA92> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff2d7ca000 -     0x7fff2db59ffa  com.apple.CFNetwork (1128.0.1 - 1128.0.1) <07F9CA9C-B954-3EA0-A710-3122BFF9F057> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff2dbd5000 -     0x7fff2dbd5fff  com.apple.Carbon (160 - 162) <FB72FB7D-5985-3D9C-82DB-A729FCA1249A> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff2e0b9000 -     0x7fff2e0b9fff  com.apple.Cocoa (6.11 - 23) <2F5C8ABA-711F-316C-BB97-921122AEE4DF> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff2e4a8000 -     0x7fff2e9b1ffb  com.apple.audio.CoreAudio (5.0 - 5.0) <9DA02E7A-56A0-3FFF-94C2-1795BA761F07> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff2ef5b000 -     0x7fff2f3dafeb  com.apple.CoreFoundation (6.9 - 1677.104) <C0D70026-EDBE-3CBD-B317-367CF4F1C92F> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff2f3dc000 -     0x7fff2fa51ff8  com.apple.CoreGraphics (2.0 - 1355.22) <4A3CDE7B-4578-3058-966A-3D1DC095A935> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff2fdbb000 -     0x7fff2fe24ff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <75966124-2FB7-33C3-BE49-3DD5F327F911> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff3017b000 -     0x7fff30256ffc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff30343000 -     0x7fff30343fff  com.apple.CoreServices (1069.24 - 1069.24) <AA140158-E909-34C2-B2F5-20EBC93E0056> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff30db6000 -     0x7fff30f6dffc  com.apple.CoreText (643.1.5.1 - 643.1.5.1) <A88F052A-C840-3E6C-9BF8-FFFED34C0667> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff30f6e000 -     0x7fff30fb2ffb  com.apple.CoreVideo (1.8 - 344.3) <5314E70D-325F-3E98-99FC-00FDF520747E> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff30fb3000 -     0x7fff31040ffc  com.apple.framework.CoreWLAN (13.0 - 1601.2) <6C76A9E0-430F-3B3C-AE8A-3005F8E6FCFF> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff31618000 -     0x7fff319ddfff  com.apple.Foundation (6.9 - 1677.104) <7C69F845-F651-3193-8262-5938010EC67D> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff31d51000 -     0x7fff31df5ff3  com.apple.framework.IOKit (2.0.2 - 1726.140.1) <14223387-6F81-3976-8605-4BC2F253A93E> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff31e87000 -     0x7fff31fe3fee  com.apple.ImageIO.framework (3.3.0 - 1976.11) <C17C7280-54F6-3750-85CE-C43428256D62> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff32851000 -     0x7fff338f1fe9  com.apple.JavaScriptCore (15609 - 15609.3.5.1.3) <1874AA53-2C73-3DB2-A98F-69D9BDB3ADC8> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff35877000 -     0x7fff358c1ff8  com.apple.MultipeerConnectivity (166 - 166) <ECB78B83-E384-3079-915E-2D7C791DCD2E> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff35d4c000 -     0x7fff35d6efff  com.apple.audio.OpenAL (1.8 - 1.8) <6D66C5D7-8410-35B7-B06E-3BE56E0A708E> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL
    0x7fff39add000 -     0x7fff39aecff7  com.apple.opengl (17.10.22 - 17.10.22) <D3C57A32-6BD0-3228-B1C4-0F42A6128A6C> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff3aaa9000 -     0x7fff3aaa9fff  com.apple.quartzframework (1.5 - 23) <48F3D0F9-323E-34E5-8F63-CF541F2B7B0E> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff3aaaa000 -     0x7fff3ad2dffb  com.apple.QuartzCore (1.11 - 841.4) <FE927B0E-BD49-32CC-8A55-90F553C86C15> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff3ad2e000 -     0x7fff3ad87ff5  com.apple.QuickLookFramework (5.0 - 906.3) <959CE934-B541-3172-846F-4D1709353526> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff3b8ae000 -     0x7fff3bbf7ff1  com.apple.security (7.0 - 59306.140.5) <B6F8368F-2395-379B-B768-71C53BB1B903> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff3c95f000 -     0x7fff3c9d9ff7  com.apple.SystemConfiguration (1.19 - 1.19) <84F9B3BB-F7AF-3B7C-8CD0-D3C22D19619F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff3cc59000 -     0x7fff3cfdcff4  com.apple.VideoToolbox (1.0 - 2625.9) <6CF18E28-A7A8-3952-8171-7E4FF4FB37FA> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff3fe94000 -     0x7fff40599ffd  com.apple.WebKit (15609 - 15609.3.5.1.3) <77FB3BFF-DF46-3261-8A74-EAB7AF8BDB4D> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff6602e000 -     0x7fff6602ffff  libSystem.B.dylib (1281.100.1) <C0C9872A-E730-37EA-954A-3CE087C15535> /usr/lib/libSystem.B.dylib
    0x7fff66307000 -     0x7fff66313fff  libbz2.1.0.dylib (44) <14CC4988-B6D4-3879-AFC2-9A0DDC6388DE> /usr/lib/libbz2.1.0.dylib
    0x7fff66314000 -     0x7fff66366fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff66e07000 -     0x7fff66ef7fff  libiconv.2.dylib (59) <18311A67-E4EF-3CC7-95B3-C0EDEE3A282F> /usr/lib/libiconv.2.dylib
    0x7fff66ef8000 -     0x7fff6714ffff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff67e8e000 -     0x7fff67ec1fde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff67f95000 -     0x7fff67fadfff  libresolv.9.dylib (67.40.1) <C57EDFEF-D36A-310B-8D14-8C68A625B1E8> /usr/lib/libresolv.9.dylib
    0x7fff6845b000 -     0x7fff6853dff7  libxml2.2.dylib (33.4) <EFA77CC6-9139-37B3-98D4-B0E526110EE3> /usr/lib/libxml2.2.dylib
    0x7fff6856a000 -     0x7fff6857cff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib

Model: MacBookPro13,2, BootROM 428.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.9 GHz, 8 GB, SMC 2.37f24
Graphics: kHW_IntelIrisGraphics550Item, Intel Iris Graphics 550, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x157), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.1)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: Rugged USB-C
USB Device: USB 3.0 Bus
USB Device: USB2.0 Hub
USB Device: USB-C Digital AV Multiport Adapter
USB Device: Apple T1 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.2

**Comment by MustangYM** [comment]
没安装成功

**Comment by Navimark** [comment]
同样问题 +1 

我试过在 `/Applications` 文件夹删除 `微信.app` ，然后通过 AppStore 重新下载安装，然后再安装 `WeChatExtension-ForMac`，能打开，但当重启电脑后，打开微信时就会报错，无法启动。

应该在更新了最新版本的 `WeChatExtension-ForMac` 后出现的问题

**Comment by dcison** [comment]
同样问题 + 1
卸载 WeChatExtension-ForMac 后，微信可以正常打开

**Comment by MustangYM** [comment]
手动执行卸载流程后，重新安装小助手即可

**Comment by wozyao** [comment]
> 手动执行卸载流程后，重新安装小助手即可

经验证，在Mac关机重启后，崩溃依然存在。

**Comment by MustangYM** [comment]
@wozyao 不是关机的问题，换机也一样。。。。

**Comment by wozyao** [comment]
> @wozyao 不是关机的问题，换机也一样。。。。

已经手动卸载好几次了，重装后好了，关机后再开机又崩溃了。。。😓

**Comment by kts-kris** [comment]
同样问题，删除Application里的wechat不好使，手动卸载也还是闪退，必须用Appclean之类的删除wechat所有的文件，重新下载最新的wechat，然后再重新安装最新的助手，目前OK。PS上午更新了新的macos到10.15.6

**Comment by wozyao** [comment]
> @wozyao 不是关机的问题，换机也一样。。。。

已经手动卸载好几次了，重装后好了，关机后再开机又崩溃了。。。😓

**Comment by MustangYM** [comment]
@kts-kris 我看行。

**Comment by JJ7539** [comment]
我也是这样的问题，卸载微信重装，再安装助手重启后又闪退……

**Comment by hufengxiao** [comment]
去release下载v2.6.3的源码，运行install.sh 覆盖最新的版本。微信就可以打开了。
还没有重启机子测试，但我估计这个版本重启机器不会有问题。

**Comment by saleding** [comment]
我的也是这问题

**Comment by Navimark** [comment]
> 同样问题，删除Application里的wechat再重新安装wechat不好使，手动卸载助手后也还是闪退，卸载助手后再全新安装助手也是闪退。经过反复尝试，最后发现必须用Appclean之类的删除wechat所有的文件，重新下载最新的wechat，然后再重新安装最新的助手，目前OK。PS上午更新了新的macos到10.15.6

昨天使用 `AppDelete.app` 卸载微信后在 AppStore 重新安装，然后使用**懒癌版安装**安装了助手，启动微信时弹窗要求升级到 2.6.5，遂更新到 2.6.5，没有重启电脑和微信的情况下，一天都使用正常。今早上开机微信就打不开了，报错内容和 https://github.com/MustangYM/WeChatExtension-ForMac/issues/585#issue-688712588 一样。
还是删除然后安装旧版了🤪

**Comment by zhxiaoshi** [comment]
刚刚release的 2.6.6  仍未解决该问题。

**Comment by skpalan** [comment]
除了重装wechat和插件以外，重启崩溃问题的快捷解决方式:

1. 助手降级回2.6.3；
2. 找到`WechatExtension`的安装目录，手动运行`install.sh`。安装目录example: `~/WeChatExtension-ForMac/WeChatExtension/Rely/Install.sh`。但是麻烦在于每次重启都需要重新运行一遍。

请开发者尽快修复。

**Comment by MustangYM** [comment]
[2.6.8已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.8)
