### ISSUE TITLE
每次打开需要定位的小程序，都会弹出对话框“微信想使用您当前的位置”

### ISSUE THREAD

**Issue by kzq5** [MustangYM/WeChatExtension-ForMac#587]
Issue示例
1. MacOS版本 : 10.xx.x
2. 微信版本 : 2.x.x
3. 小助手版本 : 2.x.x
4. BUG描述 : 会话头像抖动
5. 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
6. 方便的话提供日志, 截图或者视频(可选)

**Comment by kzq5** [comment]
还有如何实现当收到小程序了自动打开呢？求知道的给个思路

**Comment by wcc4869** [comment]
![image](https://user-images.githubusercontent.com/22254090/97399303-d7ceb800-1927-11eb-9e16-3681c03c35b1.png)
MacOS版本 : 10.14.6
微信版本 : 2.4.2
小助手版本 : 2.6.4
BUG描述 :打开小程序都会弹出对话框“微信想使用您当前的位置”
操作场景 : 微信点击小程序
