### ISSUE TITLE
黑夜模式下，有些字体是黑色，看不清楚，不明显

### ISSUE THREAD

**Issue by heshangcode** [MustangYM/WeChatExtension-ForMac#589]
Issue示例
1. MacOS版本 : 10.15.6
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.6
4. BUG描述 : 黑夜模式下，有些字体显示是黑色，看不清楚，不明显
5. 操作场景 : 点击别人的头像，看信息，出现这种情况
6. 
![image](https://user-images.githubusercontent.com/39662806/92006832-cd54cf80-ed77-11ea-9f92-3cfb6c102ec3.png)

**Comment by MustangYM** [comment]
v2.6.6已修复

**Comment by heshangcode** [comment]
2.6.6 版本没有修复

**Comment by MustangYM** [comment]
少量细节没有做适配，不再适配了
