### ISSUE TITLE
安装小助手，似乎导致bartender不能隐藏图标

### ISSUE THREAD

**Issue by Creolophus** [MustangYM/WeChatExtension-ForMac#593]
Issue示例
1. MacOS版本 : 10.15.4
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.6
4. BUG描述 : 安装小助手，似乎导致bartender不能隐藏顶部微信图标

<img width="457" alt="91964820-3883af00-ed42-11ea-8e59-84b28e0a59db" src="https://user-images.githubusercontent.com/7787790/92094802-6b43ab00-ee07-11ea-83c4-3bc06e8e4f0e.png">

**Comment by MustangYM** [comment]
#548
