### ISSUE TITLE
輸入框背景在Fuzzy theme下顯得突兀

### ISSUE THREAD

**Issue by edward-martyr** [MustangYM/WeChatExtension-ForMac#596]
Issue示例
1. MacOS版本 : 11.0 Beta
2. 微信版本 : 2.4.2
3. 小助手版本 : 2.6.6
4. BUG描述 : 輸入框背景在Fuzzy theme下顯得突兀
5. 操作场景 : /
6. 方便的话提供日志, 截图或者视频(可选)

<img width="620" alt="スクリーンショット 2020-09-04 11 08 00" src="https://user-images.githubusercontent.com/42882301/92195158-e6a46b80-ee9e-11ea-9c72-b73de92eaad8.png">

**Comment by MustangYM** [comment]
有意而为之

**Comment by edward-martyr** [comment]
原版也是輸入框與周圍同色；而且這樣確實不美觀。就算是有「意」爲之，請問這有什麼意義…

**Comment by MustangYM** [comment]
这已经是在你们的意见下改了N次的结果，集体的智慧，你可以进QQ群和他们讨论下，如果大家同意，我就改。
