### ISSUE TITLE
免认证登录开启后手机微信能不一直显示Mac微信在线么？手机关了Mac微信之后再在Mac上登录就不能免认证了

### ISSUE THREAD

**Issue by zhuzhixin** [MustangYM/WeChatExtension-ForMac#6]

**Comment by MustangYM** [comment]
> _No description provided._

免认证登录后, 本质微信还是登录了的, 所以手机端会显示微信在线. 手机关了mac微信后, mac微信就相当于主动要求退出了,  但是存在不安全因素(因为第三人拿到你电脑后可以随意登你微信), 所以没必要做.
