### ISSUE TITLE
与公众号有关的显示bug

### ISSUE THREAD

**Issue by Mapleshade20** [MustangYM/WeChatExtension-ForMac#600]
- MacOS版本 : 10.15.6
- 微信版本 : 2.4.2 (15064) Beta 145
- 小助手版本 : 2.6.6
- BUG描述 : 
  【此bug出现一次后，需要退出微信再登录才能再次出现】
  首先保持在左栏的第一个，即「聊天」图标，点击公众号，看到列表。
<img width="861" alt="image" src="https://user-images.githubusercontent.com/62641761/92319715-d252a100-f04d-11ea-9a9a-506d6b501081.png">
  然后直接点击左栏的第三个，即「收藏」图标，你会发现公众号列表没有消失，而是和收藏的内容堆叠到了一块。如图：
<img width="864" alt="image" src="https://user-images.githubusercontent.com/62641761/92319648-42145c00-f04d-11ea-8466-e2ae9e9a8375.png">
  这就是bug，但是如果你回到聊天选择公众号，再次点击收藏，这个bug就不再出现了。command+Q退出微信再重新登入，这个bug又有了。

**Comment by MustangYM** [comment]
issue提得非常好，很清晰。
