### ISSUE TITLE
登录警告bug

### ISSUE THREAD

**Issue by yucaoye** [MustangYM/WeChatExtension-ForMac#601]
### issue规范
- MacOS版本 : 10.14.5
- 微信版本 : 2.x.x
- 小助手版本 : 2.6.4
- BUG描述 : 登陆时总是出现多次 warning for crash 这样的警告
- 操作场景 : 扫码登陆微信后，出现警告，点击多次才能正常进入微信界面
![image](https://user-images.githubusercontent.com/28920467/92343970-bc99b600-f0f7-11ea-9b4a-59ae2275e08d.png)
![image](https://user-images.githubusercontent.com/28920467/92344077-0a162300-f0f8-11ea-8a89-3ad5af06ee35.png)

**Comment by MustangYM** [comment]
微信版本升级到2.4.2

**Comment by yucaoye** [comment]
如何更新呢？点击插件上的更新功能毫无反应
