### ISSUE TITLE
设置为使用系统浏览器会意外退出

### ISSUE THREAD

**Issue by zy55769068** [MustangYM/WeChatExtension-ForMac#61]
小助手版本：1.9.4
系统默认浏览器：Edge Canary

设备类型：MacBookPro14,3
系统版本：版本 10.14.6（版号 18G84）
系统语言：zh-Hans
微信版本：[2019-07-23 22:30:44] v2.3.26.17 (12699) #fb58c7dc2
微信语言：zh-Hans
历史版本：[2019-07-10 08:48:26] v2.3.25.21 (12481) #6df30b55c

**Comment by MustangYM** [comment]
> 小助手版本：1.9.4
> 系统默认浏览器：Edge Canary
> 
> 设备类型：MacBookPro14,3
> 系统版本：版本 10.14.6（版号 18G84）
> 系统语言：zh-Hans
> 微信版本：[2019-07-23 22:30:44] v2.3.26.17 (12699) #fb58c7dc2
> 微信语言：zh-Hans
> 历史版本：[2019-07-10 08:48:26] v2.3.25.21 (12481) #6df30b55c

能提供下崩溃日志吗, 微信意外退出后重启会弹窗, 左下角有"显示详细信息", 点进去就是日志

**Comment by zy55769068** [comment]
[log.txt](https://github.com/MustangYM/WeChatExtension-ForMac/files/3439978/log.txt)

**Comment by MustangYM** [comment]
> 小助手版本：1.9.4
> 系统默认浏览器：Edge Canary
> 
> 设备类型：MacBookPro14,3
> 系统版本：版本 10.14.6（版号 18G84）
> 系统语言：zh-Hans
> 微信版本：[2019-07-23 22:30:44] v2.3.26.17 (12699) #fb58c7dc2
> 微信语言：zh-Hans
> 历史版本：[2019-07-10 08:48:26] v2.3.25.21 (12481) #6df30b55c

修复了, 没有发新版本, 你重新下载安装就好了
