### ISSUE TITLE
聊天列表消失

### ISSUE THREAD

**Issue by hlwojiv** [MustangYM/WeChatExtension-ForMac#610]
### issue规范
- MacOS版本 : 10.15.6
- 微信版本 : 2.4.3
- 小助手版本 : 2.6.6
- BUG描述 : 聊天列表消失
- 操作场景 : 更新微信后，小助手菜单消失，于是重新安装小助手，再打开微信时聊天列表一片空白，但实际是可以点击的

<img width="761" alt="image" src="https://user-images.githubusercontent.com/26682806/92559853-f0b1da00-f2a3-11ea-9963-5cac1f2ec654.png">

**Comment by hlwojiv** [comment]
目前更换安装了简版的小助手，暂时发现问题

**Comment by bailixi** [comment]
+1

**Comment by bailixi** [comment]
微信版本： 2.4.2 (15650) Beta 148
MAC：10.15.5 
小助手版本：2.6.6

**Comment by sarkrui** [comment]
+1 
但只是某一个群聊消失了，在手机上重新找回群聊，回复一下可以找回

**Comment by MustangYM** [comment]
2.6.7已经修复
