### ISSUE TITLE
没有新消息也头像也晃动

### ISSUE THREAD

**Issue by Piz-liu** [MustangYM/WeChatExtension-ForMac#611]
### issue规范
- MacOS版本 : 10.15.6
- 微信版本 : 2.4.2
- 小助手版本 : 2.6.6
- BUG描述 : 只要打开微信的窗口,不管有没有新消息,当前打开的会话头像都会晃动几下
- 操作场景 : 打开微信会话窗口
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
这个不是bug
