### ISSUE TITLE
重启之后不能打开微信

### ISSUE THREAD

**Issue by xuanInitial** [MustangYM/WeChatExtension-ForMac#613]
### issue规范
MacOS版本 : 10.15.6
微信版本 : 官方最新
小助手版本 : 2.6.6
BUG描述 : 脚本安装，重启电脑后无法启动wechat  

每重启一次电脑就需要卸载微信然后重装小助手

**Comment by AYJk** [comment]
相同问题+1

**Comment by a532233648** [comment]
相同问题，希望赶快修复呀

**Comment by lyt8384** [comment]
相同问题+1

**Comment by lyt8384** [comment]
#606 好像一样

**Comment by androidcn** [comment]
> #606 好像一样

是的  一样

**Comment by sarkrui** [comment]
无相同问题。
软件版本全部一致

**Comment by WPF0414** [comment]
有相同问题,版本一致

**Comment by wzc0415** [comment]
相同问题

**Comment by MustangYM** [comment]
[已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.8)
