### ISSUE TITLE
Big Sur 迷离模式下点击会话列表重的公众号崩溃

### ISSUE THREAD

**Issue by gee1k** [MustangYM/WeChatExtension-ForMac#614]
- MacOS版本 : 11.0 Beta
- 微信版本 : 2.4.2 (15282) Beta 147
- 小助手版本 : 2.6.6
- BUG描述 : 迷离模式下点击会话列表重的公众号崩溃
- 操作场景 :迷离模式下点击会话列表重的公众号崩溃

![image](https://user-images.githubusercontent.com/12059800/92729248-a3696180-f3a4-11ea-84aa-f1a082d03a84.png)

**Comment by MustangYM** [comment]
暂时不适配macOS 11 Beta版本
