### ISSUE TITLE
最新版微信没有消息列表 Version. 2.4.2 (15650) Beta 148

### ISSUE THREAD

**Issue by finding** [MustangYM/WeChatExtension-ForMac#616]
### issue规范
- MacOS版本 : 10.15.2
- 微信版本 : Version. 2.4.2 (15650) Beta 148
- 小助手版本 : 2.6.6
- BUG描述 : 消息列表看不到, 但是可以滚动, 证明是有消息只是看不到
- 操作场景 : 微信启动后, 
- 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/4138364/93154686-d611b200-f736-11ea-8f10-905fb031bf6f.png)

**Comment by wujin941005** [comment]
一样，刚出现的问题

**Comment by shier-c** [comment]
+1

**Comment by metacodes** [comment]
刚启动的时候有列表，闪一下列表就变成空白的了

**Comment by leon-hw** [comment]
+1 同样问题，不显示人员列表，但鼠标点上去可以在右侧显示具体交流内容。

**Comment by MustangYM** [comment]
微信更这么快，要把我累死啊。。。。

**Comment by leon-hw** [comment]
> 微信更这么快，要把我累死啊。。。。

主要是想让你的插件更加完备、兼容性更强！

**Comment by edward4hgl** [comment]
清除空会话功能也不可用了，按了没有达到效果

**Comment by MustangYM** [comment]
[v2.6.7已修复]（https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.6.7）
