### ISSUE TITLE
更新新版本后微信打不开了

### ISSUE THREAD

**Issue by VerusBin** [MustangYM/WeChatExtension-ForMac#617]
### issue规范
- MacOS版本 : 10.14.5
- 微信版本 : 2.4.2
- 小助手版本 : 2.2.0
- BUG描述 : 更新最新版本后微信打不开
- 操作场景 : 在小助手弹出的更新  点更新后提示重启微信   点重启后微信就退出了 再也打不开了
-

**Comment by MustangYM** [comment]
小助手都2.6.6了。。。。
