### ISSUE TITLE
请问2.4.2(15650)Beta 148在哪下载

### ISSUE THREAD

**Issue by androidcn** [MustangYM/WeChatExtension-ForMac#619]
### issue规范
- MacOS版本 : 10.15

请问2.4.2(15650)Beta 148在哪下载

**Comment by WayChan** [comment]
https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg 不谢  每次访问都会是最新的测试版

**Comment by androidcn** [comment]
> https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg 不谢 每次访问都会是最新的测试版

果然是  谢谢
