### ISSUE TITLE
 微信打开了多开后，怎么关闭？？另外打开了多开后，点击聊天记录中的小程序 会新起一个微信

### ISSUE THREAD

**Issue by gzvincen** [MustangYM/WeChatExtension-ForMac#620]
- MacOS版本 : 10.15.4
- 微信版本 : Version. 2.4.2 (15063)
- 小助手版本 : 2.6.7
- BUG描述 : 微信打开了多开后，怎么关闭？？另外打开了多开后，点击聊天记录中的小程序 会新起一个微信
- 方便的话提供日志, 截图或者视频(可选)
[iShot2020-09-16 10.58.59.mov.zip](https://github.com/MustangYM/WeChatExtension-ForMac/files/5229522/iShot2020-09-16.10.58.59.mov.zip)

**Comment by gzvincen** [comment]
另外想问一下，如何完全卸载呢？readMe 提供的卸载方式卸载后再安装，发现所有的配置都保持的原样。你的配置数据是在哪里可以删除呢？？

**Comment by MustangYM** [comment]
升级至2.4.2(15650)Beta 148

**Comment by gzvincen** [comment]
升级了，小程序可以打开了。多开也可以了。。牛皮。。但是多开怎么关闭呢？？
