### ISSUE TITLE
主键搜索结果无法通过键盘选择

### ISSUE THREAD

**Issue by yangjianyao** [MustangYM/WeChatExtension-ForMac#622]
### issue规范
- MacOS版本 : 10.15.6
- 微信版本 : 2.4.2
- 小助手版本 : 2.6.7
- BUG描述 : 搜索用户的时候，无法通过上下键选择联系人
- 操作场景 : 微信主界面，再搜索框输入关键字，出现联系人，无法用上下键进行选择，之前的版本都是可以通过上线键选择，只是UI没有适合好，这个版本无法进行选择，只能鼠标点击

**Comment by MustangYM** [comment]
我去屏蔽了用键盘控制搜索结果这个功能
