### ISSUE TITLE
搜索联系人时无法选中结果

### ISSUE THREAD

**Issue by JokerHB** [MustangYM/WeChatExtension-ForMac#624]
### issue规范
- MacOS版本 : 11.0 Beta版(20A5364e)
- 微信版本 :  2.4.2 (15650) Beta 148
- 小助手版本 : 2.6.7
- BUG描述 : 搜索联系人后，无法使用键盘的上下键进行联系人选择，更无被选中的联系人高亮显示。
- 操作场景 : 搜索联系后，按键盘的上下箭头键进行联系人选择时，无法选中联系人。
- 图片：
![1600244311416](https://user-images.githubusercontent.com/11409054/93311202-481df000-f838-11ea-9789-077906e1abc5.jpg)

**Comment by MustangYM** [comment]
#622
