### ISSUE TITLE
求接口文档

### ISSUE THREAD

**Issue by stevenliuit** [MustangYM/WeChatExtension-ForMac#63]
求楼主出一份使用文档
/wechat-plugin/user
/wechat-plugin/chatlog
/wechat-plugin/open-session
/wechat-plugin/send-message
这些接口的 我想二次开发这些接口
比如这个:
http://10.67.141.15:52700/wechat-plugin/user

**Comment by MustangYM** [comment]
> 求楼主出一份使用文档
> /wechat-plugin/user
> /wechat-plugin/chatlog
> /wechat-plugin/open-session
> /wechat-plugin/send-message
> 这些接口的 我想二次开发这些接口
> 比如这个:
> http://10.67.141.15:52700/wechat-plugin/user
Mac端都是hook原始函数的, 没有这些所谓的接口文档

**Comment by stevenliuit** [comment]
以前原作者的还能打开 现在这个打不开了
