### ISSUE TITLE
无法拦截撤回的图片

### ISSUE THREAD

**Issue by Bupterambition** [MustangYM/WeChatExtension-ForMac#630]
### issue规范
- MacOS版本 : 11.0 Beta版(20A5364e)
- 微信版本 : Version. 2.4.2 (15067)
- 小助手版本 : 2.6.7
- BUG描述 : 无法拦截撤回的图片

**Comment by MustangYM** [comment]
能详细描述下嘛？

**Comment by hdk325** [comment]
你用11系统微信没问题？不会卡死？

**Comment by MustangYM** [comment]
暂适配11beta

**Comment by Bupterambition** [comment]
11 beta也没有问题了
