### ISSUE TITLE
微信多开后合盖休眠重启后只有一个账号能自动登录

### ISSUE THREAD

**Issue by whatcall** [MustangYM/WeChatExtension-ForMac#631]
### 微信多开后合盖休眠重启后只有一个账号能自动登录
- MacOS版本 : 10.14.6
- 微信版本 : 2.4.2
- 小助手版本 : 2.6.6
- BUG描述 : 微信多开后合盖休眠重启后只有一个账号能自动登录，另外一个账号虽然设置了自动认证登录，但是还是要手动扫码。这是一个需要实现的Feature，从很久之前就存在这个现象。我觉得对于需要2个及以上账号登录的用户非常有帮助。
- 操作场景 : 微信多开后合盖休眠重启后只有一个账号能自动登录，另外一个账号虽然设置了自动认证登录，但是还是要手动扫码。

**Comment by MustangYM** [comment]
我想了下，这个除非复制一份微信，只是建立在一个微信可执行程序的情况下，免认证登录只能这样了，没办法
