### ISSUE TITLE
无法使用bartender隐藏图标， 

### ISSUE THREAD

**Issue by Pythomiere** [MustangYM/WeChatExtension-ForMac#633]
### issue规范
- MacOS版本 : 10.15.6 
- 微信版本 : 2.4.2
- 小助手版本 : 2.6.7
- bartender 版本 : 3.1.23
- BUG描述 : Bartender无法控制微信menubar图标，关闭小助手后就没有这个问题。 
- 操作场景 : 开启微信后，图标会自动出现在menubar上，但是小助手会在bartender关闭了微信图标的情况下再在menubar上新增一个微信图标。
![截屏]()

**Comment by MustangYM** [comment]
#548
