### ISSUE TITLE
微信多开勾选后，再次点击按钮只会打开新的登陆程序，而不是取消勾选

### ISSUE THREAD

**Issue by DOUBAOBABABA** [MustangYM/WeChatExtension-ForMac#634]
### issue规范
- MacOS版本 : 10.13.16
- 微信版本 : 2.4.2
- 小助手版本 : 2.6.7
- BUG描述 : 微信多开勾选后，再次点击按钮只会打开新的登陆程序，而不是取消勾选。影响到了单微信的小程序使用。
![image](https://user-images.githubusercontent.com/40243574/93708752-538c5680-fb6b-11ea-85c2-1774f3d66338.png)

- 操作场景 : 想关闭微信多开功能

**Comment by MustangYM** [comment]
[下载最新版微信](https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg)。
