### ISSUE TITLE
升级至v2.6.8失败

### ISSUE THREAD

**Issue by OCDpunk** [MustangYM/WeChatExtension-ForMac#638]
- MacOS版本 : 10.15.6
- 微信版本 : 2.4.2 (15063)
- 小助手版本 : v2.6.7
- BUG描述 : 点击小助手更新-立即更新-重启软件后还为2.6.7版本号未变
- 操作场景 : 打开微信登陆微信，点击更新小助手，点击更新，重启后还是提示有新版本

第二个问题是 有没有办法关闭微信多开 目前开启后无法关闭

**Comment by MustangYM** [comment]
[下载最新版微信](https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg)。挂VPN再更新小助手

**Comment by OCDpunk** [comment]
> [下载最新版微信](https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg)。挂VPN再更新小助手

通过SS全局+命令行代理 还是不行删除重装也更新失败 显示更新成功但实际失败
