### ISSUE TITLE
迷离模式下切换窗口有问题

### ISSUE THREAD

**Issue by jiajudu** [MustangYM/WeChatExtension-ForMac#639]
### issue规范
- MacOS版本 : 10.15.6
- 微信版本 : 2.4.2
- 小助手版本 : 2.6.8
- BUG描述 : 迷离模式下切换窗口有问题
- 操作场景 : 微信启动后, 三指向上滑动, 点击另一个窗口后微信仍然在最前面

**Comment by MustangYM** [comment]
你是否开启了微信窗口置顶，或者误触了置顶快捷键。

**Comment by jiajudu** [comment]
是开了置顶
