### ISSUE TITLE
【BUG】2.6.8版本，【手机正在浏览和浮窗的内容将会在这里展示】功能失效

### ISSUE THREAD

**Issue by laucherish** [MustangYM/WeChatExtension-ForMac#640]
### issue规范
- MacOS版本 : 10.15.6
- 微信版本 : 2.4.1
- 小助手版本 : 2.6.8
- BUG描述 : 【手机正在浏览和浮窗的内容将会在这里展示】功能失效
- 操作场景 : 【手机正在浏览和浮窗的内容将会在这里展示】功能失效
- 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/10667558/94092578-b7559e80-fe4d-11ea-8d9a-383b0bb28b01.png)

**Comment by MustangYM** [comment]
我在微信2.4.2上测试是没问题的，你升级一下微信？
