### ISSUE TITLE
不能打开小程序

### ISSUE THREAD

**Issue by hziKen** [MustangYM/WeChatExtension-ForMac#643]
### issue规范
- MacOS版本 : 10.15.6 (19G2021)
- 微信版本 :  2.4.2

**Comment by MustangYM** [comment]
[下载最新版微信](https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg)

**Comment by hziKen** [comment]
我的就是最新版微信啊 大哥

**Comment by MustangYM** [comment]
最新版是Version. 2.4.2 (15650) Beta 148
