### ISSUE TITLE
搜索框输入后结果未高亮，同时无法利用键盘对结果进行选择

### ISSUE THREAD

**Issue by WayChan** [MustangYM/WeChatExtension-ForMac#656]
- MacOS版本 : 10.15.7
- 微信版本 : 2.4.2 (15650) Beta 148
- 小助手版本 : 2.6.8
- BUG描述 : 搜索框搜索结果颜色无高亮，切换过主题依旧，同时方向键上下按键输入无效。卸载小助手，恢复正常。
- 操作场景 : 微信启动后, 在搜索输入框输入搜索关键字，并按下方向键下或者方向键上，无法进行选择。

**Comment by MustangYM** [comment]
#579 #622
