### ISSUE TITLE
能不能做一个Mac锁屏后，自动打开手机微信通知的功能

### ISSUE THREAD

**Issue by kingsword** [MustangYM/WeChatExtension-ForMac#66]
办公的时候Mac登录微信，中午吃饭或者不在工位的时候，电脑锁屏了，微信还登录了手机通知是关闭的状态，然后就错过了很多信息。能不能做个功能在电脑锁屏时，自动打开手机通知；解锁电脑之后再关闭手机通知的功能？

**Comment by MustangYM** [comment]
> 办公的时候Mac登录微信，中午吃饭或者不在工位的时候，电脑锁屏了，微信还登录了手机通知是关闭的状态，然后就错过了很多信息。能不能做个功能在电脑锁屏时，自动打开手机通知；解锁电脑之后再关闭手机通知的功能？

不能
