### ISSUE TITLE
Mac 10.12.6打开出现经常死机现象

### ISSUE THREAD

**Issue by DanielCGL** [MustangYM/WeChatExtension-ForMac#661]
10.12.6版本的mac打开小助手后会经常死机，需要强制退出。或者在输入中文时也会卡机。

**Comment by DanielCGL** [comment]
MacOS版本 : 10.12.6
微信版本 : 2.4.2
小助手版本 : 2.6.8
BUG描述 : 打开小助手后会经常死机，需要强制退出。或者在输入中文时也会卡机。
操作场景 : 微信启动后, 需要等待一段时间才能正常输入中文

**Comment by MustangYM** [comment]
理论上小助手不支持低于10.14的mac机器，因为我没有这个版本的机器作为测试和开发。
