### ISSUE TITLE
原来微信端可以直接打开小程序的，自从装了插件后，小程序无法预览和打开

### ISSUE THREAD

**Issue by czl0325** [MustangYM/WeChatExtension-ForMac#679]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 2.5.0
- 小助手版本 : 2.6.8
- BUG描述 : 原来微信端可以直接打开小程序的，自从装了插件后，小程序无法预览和打开，变成提示收到小程序信息：。。。
- 操作场景 : 
- 方便的话提供日志, 截图或者视频(可选)
<img width="585" alt="image" src="https://user-images.githubusercontent.com/2100549/97157078-949f0880-17b2-11eb-92f2-70777f6662be.png">

**Comment by MustangYM** [comment]
游戏小程序是不能打开的。
