### ISSUE TITLE
昵称颜色跟背景区分度不够，看不清楚

### ISSUE THREAD

**Issue by dwSun** [MustangYM/WeChatExtension-ForMac#682]
![image](https://user-images.githubusercontent.com/5899962/97419817-7f0e1800-1945-11eb-82f1-5a39a818a3ef.png)

这种昵称的颜色是随机的吗，像这种的颜色，在黑夜和迷离模式看起来就比较费劲。

**Comment by MustangYM** [comment]
颜色是我调配的一个固定色库，因为迷离模式属于半透明性质（背景或黑或白），所以无法保证对比度，但大体都是能看清楚的，如果你实在觉得看不清，可以关掉皮肤
