### ISSUE TITLE
是否能提供对接接口

### ISSUE THREAD

**Issue by jonnywang** [MustangYM/WeChatExtension-ForMac#684]
### issue规范
- MacOS版本 : 10.15
- 微信版本 : 2.5.0
- 小助手版本 : 2.6.8

能否内置类似websocket服务，推送消息及拉取用户信息接口

**Comment by MustangYM** [comment]
就目前Alfred所用的websocket服务都涉嫌泄露用户隐私，你所提的这种功能是要把我往火坑里推么:(
