### ISSUE TITLE
自动回复功能无效

### ISSUE THREAD

**Issue by wdkGitHub** [MustangYM/WeChatExtension-ForMac#688]
### issue规范
- MacOS版本 : 10.15.7 (19H2)
- 微信版本 : Version. 2.5.0 (15731)
- 小助手版本 : 2.7.0
- BUG描述 : 自动回复没有触发
- 操作场景 : 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/12813051/97769365-30d75f80-1b65-11eb-89a5-99e60ce8ecfd.png">

**Comment by wdkGitHub** [comment]
勾选状态无触发，图没有勾选

**Comment by MustangYM** [comment]
em。。。。。
