### ISSUE TITLE
查看具体的违规言论

### ISSUE THREAD

**Issue by daoyan90** [MustangYM/WeChatExtension-ForMac#689]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : Version. 2.5.0 (15735)
- 小助手版本 : 2.7.0
- 特性描述 : 现在可以看到违规言论的条数，但是无法了解具体的违规言论是哪些？
- 操作场景 : 嗯，其实我是不知道这个新增加的“违规言论”到底是什么意思。。。

**Comment by Mnufs** [comment]
是的，能不能解释一下，“违规言论”是什么？

**Comment by KingAmo** [comment]
群员监控 里面的 `拼多多砍一刀`是什么意思呢

**Comment by Mnufs** [comment]
> 群员监控 里面的 `拼多多砍一刀`是什么意思呢

盲猜是，在群里发过"拼多多砍价的链接或者关键词"

**Comment by KingAmo** [comment]
> > 群员监控 里面的 `拼多多砍一刀`是什么意思呢
> 
> 盲猜是，在群里发过"拼多多砍价的链接或者关键词"

监控这个有什么意义呢...

**Comment by Mnufs** [comment]
> > > 群员监控 里面的 `拼多多砍一刀`是什么意思呢
> > 
> > 
> > 盲猜是，在群里发过"拼多多砍价的链接或者关键词"
> 
> 监控这个有什么意义呢... 那`淘宝`等电商平台为何不监控呢

有的群里不让发这些东西，群管理员可能会漏掉，这个功能就是找出来谁发过吧。
作者做这个功能，是为了方便管理群。

**Comment by Mnufs** [comment]
> > > > 群员监控 里面的 `拼多多砍一刀`是什么意思呢
> > > 
> > > 
> > > 盲猜是，在群里发过"拼多多砍价的链接或者关键词"
> > 
> > 
> > 监控这个有什么意义呢... 那`淘宝`等电商平台为何不监控呢
> 
> 有的群里不让发这些东西，群管理员可能会漏掉，这个功能就是找出来谁发过吧。
> 作者做这个功能，是为了方便管理群。

至于其他平台为啥没做，可能作者是为了试水？也可能是拼多多这个砍价的，大家发的比较频繁？
这就不好说了。

**Comment by seanlvjie** [comment]
同问，这个违规言论 多少条是根据什么判断的，意义何在？

**Comment by zszen** [comment]
我居然看到我在工作群里有一条违规，我都不知道我干了啥

**Comment by Mapleshade20** [comment]
同问，群员管理的「违规言论」和「拼多多砍一刀」的判定标准是什么？ @MustangYM

**Comment by hply** [comment]
同问，这个违规言论 多少条是根据什么判断的,是微信客户端数据库里提供的字段吗

**Comment by Satria4D** [comment]
i really didn't what ur say, but if u lookin for money... join us at [Satria4D Togel Online](http://18.177.100.66/) terbaik

**Comment by zhuziyi1989** [comment]
作者把半成品功能放出来，有这方面需求的人会联系作者购买私域管理的完整版吧。

**Comment by Xavier9896** [comment]
> 是的，能不能解释一下，“违规言论”是什么？

看了一下源码，在 shieldwords.txt 里面有630个关键字主要是「红」「黄」相关到，只要信息里面匹配到关键字就是违规言论。

**Comment by MustangYM** [comment]
@zhuziyi1989 bingo！

**Comment by Xavier9896** [comment]
> @zhuziyi1989 bingo！

如果能自定义关键词，并且能将违规信息查询显示出来就更好了，目前到关键词还是有点儿少，开源到词库挺多的，可以考虑更新一下。

最后感谢做出的助手，帮助很大，另外今天更新新版后闪退有点儿频繁。

**Comment by MustangYM** [comment]
@Xavier9896 2.8小助手适配了2.6微信，你可以试试，如果还有crash，贴一下log

**Comment by Xavier9896** [comment]
> @Xavier9896 2.8小助手适配了2.6微信，你可以试试，如果还有crash，贴一下log

有2.6的下载地址吗？官网下的是 2.5，app store更加不要说来，两个版本检查更新也都显示是最新版。

**Comment by MustangYM** [comment]
@zhuziyi1989 #752 微信官网回滚了

**Comment by MustangYM** [comment]
[v2.8.2已提供查看具体违规言论](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.2)
