### ISSUE TITLE
还是闪退

### ISSUE THREAD

**Issue by stevenliuit** [MustangYM/WeChatExtension-ForMac#69]
2.3.26闪退
用的你的最新的昨天提交代码的那版 刚开始是选了远程命令然后闪退后打开微信出现免密登录 也闪退

**Comment by MustangYM** [comment]
> 2.3.26闪退
> 用的你的最新的昨天提交代码的那版 刚开始是选了远程命令然后闪退后打开微信出现免密登录 也闪退

有日志么

**Comment by stevenliuit** [comment]
WeChat_2019-08-02-172247_stevendeMacBook-Pro.crash
WeChat_2019-08-02-172311_stevendeMacBook-Pro.crash
WeChat_2019-08-02-172327_stevendeMacBook-Pro.crash

**Comment by stevenliuit** [comment]
[crash日志.zip](https://github.com/MustangYM/WeChatExtension-ForMac/files/3460543/crash.zip)
上面压缩包里是异常日志

**Comment by qq645381995** [comment]
闪退频繁，

**Comment by MustangYM** [comment]
从日志上看, 还没看出原因啊.

**Comment by MustangYM** [comment]
> 闪退频繁，

你说的闪退频繁是说下操作场景, 我好查问题

**Comment by qq645381995** [comment]
可能是电脑还有 kk 的缓存吧。

**Comment by MustangYM** [comment]
1.9.6版本已经更新

**Comment by MustangYM** [comment]
> 可能是电脑还有 kk 的缓存吧。

1.9.6版本已经更新

**Comment by MustangYM** [comment]
> [crash日志.zip](https://github.com/MustangYM/WeChatExtension-ForMac/files/3460543/crash.zip)
> 上面压缩包里是异常日志

1.9.6版本已经更新
