### ISSUE TITLE
群助手不显示群员监控功能

### ISSUE THREAD

**Issue by PlayerYK** [MustangYM/WeChatExtension-ForMac#690]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : Version. 2.4.2 (15015) Beta 11
- 小助手版本 : 2.7.0
- BUG描述 : 群助手不显示群员监控功能，具体看截图

![image](https://user-images.githubusercontent.com/672711/97782144-d40e9000-1bca-11eb-9b57-9cb294ecccf9.png)

**Comment by MustangYM** [comment]
请将微信升级至2.4.2（15650）以上
