### ISSUE TITLE
希望可以添加一个在菜单栏打开或关闭微信图标的选项

### ISSUE THREAD

**Issue by Pythomiere** [MustangYM/WeChatExtension-ForMac#692]
- MacOS版本 : 10.15.7
- 微信版本 : 2.5.0
- 小助手版本 : 2.6.8
- BUG描述 : 无法控制微信图标在状态栏的开启或关闭
- 操作场景 : 可以添加一个选项控制是否在状态栏显示

**Comment by MustangYM** [comment]
NO
