### ISSUE TITLE
对话列表bug

### ISSUE THREAD

**Issue by leepule** [MustangYM/WeChatExtension-ForMac#693]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 2.5.0
- 小助手版本 : 2.5.0 (15735)
- BUG描述 : 点击对话列表会有两层选中状态，必须再点一次才会取消
![image](https://user-images.githubusercontent.com/16642691/97936436-7474d800-1db6-11eb-8020-e0bd86e57a6f.png)

**Comment by MustangYM** [comment]
你之前是不是右键误点了“多选”？

**Comment by leepule** [comment]
哦吼，还有这个选项，😅，不知道怎么点到了，谢谢啦
