### ISSUE TITLE
功能使用问题“拒收群消息”在哪开启

### ISSUE THREAD

**Issue by zszen** [MustangYM/WeChatExtension-ForMac#696]
更新到最新的2.6.8提示支持“拒收群消息” 但不知道怎么开启，确实有很多群也没法退，有更新也不想看

**Comment by zszen** [comment]
原理是什么，是不是只要不是at自己的，接收到消息自动变为已读，已经融合到了免骚扰中了？

**Comment by MustangYM** [comment]
1.保证微信版本 >= 2.4.2（15650）
2.在群员监控的Window中，左侧会话列表右键单击会弹出菜单“拒收消息”

**Comment by zszen** [comment]
> 1.保证微信版本 >= 2.4.2（15650）
> 2.在群员监控的Window中，左侧会话列表右键单击会弹出菜单“拒收消息”

不错，能减少被分神的时间了
