### ISSUE TITLE
关于微信升级小助手消失问题

### ISSUE THREAD

**Issue by ChrisJus** [MustangYM/WeChatExtension-ForMac#698]
### issue规范
- MacOS版本 : 10.15.5
- 微信版本 : 2.5.0 (15735)
- 小助手版本 : 2.7.0
- BUG描述 : 每次微信版本更新后，小助手都会消失，需要重新安装。
- 操作场景 : 微信官方升级

**Comment by MustangYM** [comment]
我们杀死HIV病毒的唯一办法就是当这个人死掉的时候。
