### ISSUE TITLE
您好，能否增加自动下载原图的功能

### ISSUE THREAD

**Issue by reinstallsys** [MustangYM/WeChatExtension-ForMac#70]
有时群里的信息来不及看，等过几天再看的时候图片就打不开了，是否可以增加一个自动下载原图的功能，收到的图片消息时，自动下载原图，谢谢！

**Comment by MustangYM** [comment]
> 有时群里的信息来不及看，等过几天再看的时候图片就打不开了，是否可以增加一个自动下载原图的功能，收到的图片消息时，自动下载原图，谢谢！

可以

**Comment by MustangYM** [comment]
> 有时群里的信息来不及看，等过几天再看的时候图片就打不开了，是否可以增加一个自动下载原图的功能，收到的图片消息时，自动下载原图，谢谢！

已增加, 1.9.6版本已经更新
