### ISSUE TITLE
求支持视频号，可查看并保存

### ISSUE THREAD

**Issue by GarboSun** [MustangYM/WeChatExtension-ForMac#703]
求求了。

- MacOS版本 : 10.15.7
- 微信版本 : 2.4.2
- 小助手版本 : 2.6.3

**Comment by MustangYM** [comment]
聊天界面的视频消息本身支持保存。所以你说的什么的小视频，哪个界面的，长什么样，你需要以怎样的操作步骤来实现这个保存？

**Comment by GarboSun** [comment]
……呀打错了，是视频号，好像只能微信内部分享，内容不错的视频导不出来。
https://tva1.sinaimg.cn/large/0081Kckwgy1gkldzxx37kj30u01hckiq.jpg
