### ISSUE TITLE
闪退了！！！！微信无法使用了！！！！！

### ISSUE THREAD

**Issue by JerryDJX** [MustangYM/WeChatExtension-ForMac#704]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 2.5.0
- 小助手版本 : 2.7.0
- BUG描述 : 只要手机同意登录，立马删退！
- 操作场景 : Mac启动微信后点击登录，手机同意登录后，Mac上出现微信一个界面瞬间闪退，每次都如此，目前Mac无法使用微信，急急急！！！！！

**Comment by MrJiangZhiGuo** [comment]
一直闪退，重新登录，一两分钟又崩溃了

**Comment by JerryDJX** [comment]
我的解决了，别用命令安装，先把微信小助手卸载，然后下载压缩文件，利用/Users/doujiaxing/Downloads/软件/微信助手/WeChatExtension-ForMac-master/WeChatExtension/Rely里的Install.sh安装；就是作者说的 手动安装方式：
<img width="440" alt="image" src="https://user-images.githubusercontent.com/13324361/99032611-f8983e00-25b4-11eb-96ff-1b6dfd41474c.png">
