### ISSUE TITLE
主题模式——非关闭皮肤

### ISSUE THREAD

**Issue by CoderXSLee** [MustangYM/WeChatExtension-ForMac#708]
- MacOS版本 : 11.0.1
- 微信版本 : Version. 2.5.0 (15731)
- 小助手版本 : 2.7.0
- BUG描述 : Cmd+F 搜索无法使用⬆️键和⬇️键选中联系人或群聊，关闭皮肤后恢复正常。
- 操作场景 : Cmd+F 搜索无法使用⬆️键和⬇️键选中联系人或群聊

**Comment by MustangYM** [comment]
#579 #622 #670
