### ISSUE TITLE
感觉语音转换文字有问题。一直转圈圈不出文字

### ISSUE THREAD

**Issue by hubzy** [MustangYM/WeChatExtension-ForMac#726]
### issue规范
- MacOS版本 : 10.14.5
- 微信版本 : Version. 2.5.0 (15727) Beta 144
- 小助手版本 : 27.0
- BUG描述 : 语音转换文字一直转圈圈不出文字
- 操作场景 : 聊天窗口语音转文字，有时候可以转文字成功（很少），大多数一直转不成功。
- 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/50261799/100302478-5ecd8980-2fd5-11eb-86fd-a645c9c727a2.png)

**Comment by MustangYM** [comment]
微信就这尿性
