### ISSUE TITLE
最新版的微信Version. 2.3.26 (12718)也闪退了

### ISSUE THREAD

**Issue by luckysonyu99** [MustangYM/WeChatExtension-ForMac#73]

**Comment by MustangYM** [comment]
> _No description provided._

什么场景下闪退的

**Comment by luckysonyu99** [comment]
> > _No description provided._
> 
> 什么场景下闪退的

上午撤回一条消息触发闪退，然后再登录开启免认证登录之后就会频繁闪退，不过我刚刚重新装上去更新一下又好了

**Comment by plutopaner** [comment]
我是登录两个微信后，电脑闲置一会，屏幕锁定。再解锁的时候，发现第二次登录的微信闪退。

**Comment by MustangYM** [comment]
我在新版本里加入了Bug收集系统, 会修复, 但是需要一点时间




| |
晏茂
|
|
ymoomy@yeah.net
|
签名由网易邮箱大师定制


在2019年08月7日 17:37，plutopaner<notifications@github.com> 写道：

我是登录两个微信后，电脑闲置一会，屏幕锁定。再解锁的时候，发现第二次登录的微信闪退。

**Comment by XuJian1252878** [comment]
我这边是直接不能双开微信了，12718版本的

**Comment by XuJian1252878** [comment]
系统版本是
设备类型：MacBookPro13,3
系统版本：版本 10.14.6（版号 18G87）
系统语言：zh-Hans
微信版本：[2019-08-05 17:22:14] v2.3.26.16 (12718) #3a8f6c200
微信语言：zh-Hans
历史版本：[2019-06-08 15:32:09] v2.3.25.16 (12482) #3afa37559

**Comment by XuJian1252878** [comment]
> 我是登录两个微信后，电脑闲置一会，屏幕锁定。再解锁的时候，发现第二次登录的微信闪退。

我的也是这样子
