### ISSUE TITLE
微信 v2.6.0版本登录闪退

### ISSUE THREAD

**Issue by mqlsq** [MustangYM/WeChatExtension-ForMac#734]
- MacOS版本 : 11.0.1
- 微信版本 : 2.6.0 (16627) Beta 1
- 小助手版本 : 2.7.0
- BUG描述 : 登录成功就闪退.
- 操作场景 : 弹出登录界面后,点击登录成功就闪退.

**Comment by akayj** [comment]
+1

**Comment by MustangYM** [comment]
我暂时没有硬件条件对macOS 11环境进行开发测试

**Comment by mqlsq** [comment]
> 我暂时没有硬件条件对macOS 11环境进行开发测试

应该跟macOS系统无关, 主要是微信 v2.6.0版本的适配.

**Comment by MustangYM** [comment]
> > 我暂时没有硬件条件对macOS 11环境进行开发测试
> 
> 应该跟macOS系统无关, 主要是微信 v2.6.0版本的适配.

这倒不一定，看后续反馈吧，理论上Beta版本的微信或系统我都不太想再浪费时间去适配

**Comment by BruceChao** [comment]
2.6都出来了？新增了什么功能么？我刚去搜索下没搜索到这个新测试版

**Comment by leo-fengchao** [comment]
更新了 2.6 测试版，但是好像没有什么新功能，只是之前无论是 App Store 的版本还是微信小助手 GitHub 主页下载的版本都没有办法打开小程序，安装了官方的版本就可以打开，不过这个在之前官方的 2.5 beta 也可以实现。

**Comment by 13774769367** [comment]
一样遇到了，macosx11.0.1/微信2.6.0

**Comment by MustangYM** [comment]
[2.8.0已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.0)
