### ISSUE TITLE
macOS Big Sur版本11.01系统微信内测版Version. 2.6.0 (16733) Beta 4登录闪退

### ISSUE THREAD

**Issue by wuxingli** [MustangYM/WeChatExtension-ForMac#743]
### issue规范
- MacOS版本 : macOS Big Sur版本11.01
- 微信版本 : 微信内测版Version. 2.6.0 (16733) Beta 4
- 小助手版本 : 2.7.0
- BUG描述 : 安装小助手后打开微信点击登录闪退
- 操作场景 : 微信启动后, 点击登录闪退

**Comment by MustangYM** [comment]
#734 #722

**Comment by Herrengit** [comment]
请问你的内测版是从哪里来的

**Comment by MustangYM** [comment]
[2.8.0已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.0)
