### ISSUE TITLE
fictivadmin1 is not in the sudoers file.  This incident will be reported.

### ISSUE THREAD

**Issue by valens7** [MustangYM/WeChatExtension-ForMac#745]
### issue规范
- MacOS版本 : 10.0.1
- 微信版本 : 2.4.2
- 小助手版本 : 2.7
- BUG描述 : fictivadmin1 is not in the sudoers file.  This incident will be reported.
- 操作场景 : 安装小助手2.7碰到这种情况

-------------------------------------------------
以下是输入密码后碰到的情况(账号不是Mac管理员账号而是guest账号）
**fictivadmin1 is not in the sudoers file.  This incident will be reported.**
cp: /Applications/WeChat.app/Contents/MacOS/WeChat_backup: Permission denied
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework: Permission denied
cp: /Users/fictivadmin1/Downloads/WeChatExtension-ForMac-2.7.0/WeChatExtension/Rely/Plugin/WeChatExtension/WeChatExtension.framework: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework: Permission denied
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources: No such file or directory
cp: /Users/fictivadmin1/Downloads/WeChatExtension-ForMac-2.7.0/WeChatExtension/Rely/Plugin/WeChatExtension/WeChatExtension.framework/Resources: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/zh-Hans.lproj: No such file or directory
cp: /Users/fictivadmin1/Downloads/WeChatExtension-ForMac-2.7.0/WeChatExtension/Rely/Plugin/WeChatExtension/WeChatExtension.framework/Resources/zh-Hans.lproj: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/zh-Hans.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/zh-Hans.lproj/TKRemoteControlWindowController.strings: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/zh-Hans.lproj/Localizable.strings: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/TKRemoteControlScript.scpt: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/en.lproj: No such file or directory
cp: /Users/fictivadmin1/Downloads/WeChatExtension-ForMac-2.7.0/WeChatExtension/Rely/Plugin/WeChatExtension/WeChatExtension.framework/Resources/en.lproj: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/en.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/en.lproj/TKRemoteControlWindowController.strings: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/en.lproj/Localizable.strings: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/pin.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/VAutoForwardingWindowController.nib: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/en-GB.lproj: No such file or directory
cp: /Users/fictivadmin1/Downloads/WeChatExtension-ForMac-2.7.0/WeChatExtension/Rely/Plugin/WeChatExtension/WeChatExtension.framework/Resources/en-GB.lproj: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/en-GB.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/en-GB.lproj/TKRemoteControlWindowController.strings: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/en-GB.lproj/Localizable.strings: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/lock.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/add_icon.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/add_new_chat_icon.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/shieldwords.txt: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/WeChatPayCode.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/Base.lproj: No such file or directory
cp: /Users/fictivadmin1/Downloads/WeChatExtension-ForMac-2.7.0/WeChatExtension/Rely/Plugin/WeChatExtension/WeChatExtension.framework/Resources/Base.lproj: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/Base.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/Base.lproj/TKRemoteControlWindowController.nib: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/zh-Hant.lproj: No such file or directory
cp: /Users/fictivadmin1/Downloads/WeChatExtension-ForMac-2.7.0/WeChatExtension/Rely/Plugin/WeChatExtension/WeChatExtension.framework/Resources/zh-Hant.lproj: unable to copy extended attributes to /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/zh-Hant.lproj: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/zh-Hant.lproj/TKRemoteControlWindowController.strings: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/zh-Hant.lproj/Localizable.strings: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/LockPlist.plist: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/arrow_forward.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/aliPayCode.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/YMStrangerCheckWindowController.nib: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/arrow_icon.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/addIcon.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/arrow_icon_highlight.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/TKAutoReplyWindowController.nib: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/YMZGMPWindowController.nib: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/TKDownloadWindowController.nib: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/TKRemoteControlCommands.plist: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/order_avatar.png: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/Info.plist: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/TKAboutWindowController.nib: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/Resources/YMAIReplyWindowController.nib: No such file or directory
cp: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: No such file or directory
/Applications/WeChat.app/Contents/MacOS/WeChat_backup: No such file or directory
(base) MacBook-Pro-5:~ fictivadmin1$

**Comment by MustangYM** [comment]
[Google](https://www.google.com.hk/search?safe=strict&hl=zh-CN&source=hp&ei=4SfXX53FL4u6mAWS5p_ABw&q=fictivadmin1+is+not+in+the+sudoers+file&oq=fictivadmin1+is+not+in+the+sudoers+file&gs_lcp=CgZwc3ktYWIQA1D_BVj_BWDqCGgBcAB4AIABAIgBAJIBAJgBAKABAqABAaoBB2d3cy13aXqwAQA&sclient=psy-ab&ved=0ahUKEwjdubOijM3tAhULHaYKHRLzB3gQ4dUDCAc&uact=5)
