### ISSUE TITLE
小助手v1.9.5现在是直接屏蔽屏蔽更新的吗

### ISSUE THREAD

**Issue by ueiu** [MustangYM/WeChatExtension-ForMac#75]
微信版本：2.3.26
小助手：1.9.5
<img width="233" alt="屏幕快照 2019-08-07 下午2 56 54" src="https://user-images.githubusercontent.com/39592269/62601640-6ec6e300-b924-11e9-8ce7-6cee90763b2c.png">

在小助手菜单没有看到勾选是否禁止监测更新，请问是做成了默认项吗？谢谢

**Comment by MustangYM** [comment]
> 微信版本：2.3.26
> 小助手：1.9.5
> <img alt="屏幕快照 2019-08-07 下午2 56 54" width="233" src="https://user-images.githubusercontent.com/39592269/62601640-6ec6e300-b924-11e9-8ce7-6cee90763b2c.png">
> 
> 在小助手菜单没有看到勾选是否禁止监测更新，请问是做成了默认项吗？谢谢

这里我已经修复, 下一个版本会放出来

**Comment by MustangYM** [comment]
> 微信版本：2.3.26
> 小助手：1.9.5
> <img alt="屏幕快照 2019-08-07 下午2 56 54" width="233" src="https://user-images.githubusercontent.com/39592269/62601640-6ec6e300-b924-11e9-8ce7-6cee90763b2c.png">
> 
> 在小助手菜单没有看到勾选是否禁止监测更新，请问是做成了默认项吗？谢谢

1.9.6版本已经更新
