### ISSUE TITLE
Crashing on exception: -[SVGImageView setNormalColor:]: unrecognized selector

### ISSUE THREAD

**Issue by mm2m123** [MustangYM/WeChatExtension-ForMac#753]
### issue规范
- MacOS版本 : 11.1
- 微信版本 : 2.6.0
- 小助手版本 : 2.7.0
- BUG描述 : 登录微信闪退
- 操作场景 : 微信启动后, 点击登录闪退
- Crashing on exception: -[SVGImageView setNormalColor:]: unrecognized selector sent to instance 0x7fa83a67d210

**Comment by MustangYM** [comment]
[2.8.0已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.0)
