### ISSUE TITLE
小助手2.8 撤回bug

### ISSUE THREAD

**Issue by LunaYJ** [MustangYM/WeChatExtension-ForMac#756]
### issue规范
- MacOS版本 : 11.1
- 微信版本 : 2.6.0 (16787)
- 小助手版本 : 2.8.0
- BUG描述 : 撤回自己的消息一直显示菊花

- 操作场景 : 发送消息后点击撤回，聊天框中需撤回的消息旁边一直显示loading菊花，查看手机可发现消息已撤回
- 方便的话提供日志, 截图或者视频(可选)
 ![image](https://user-images.githubusercontent.com/2851302/103066773-8293e780-45f4-11eb-87e4-5d28ea239c85.png)

**Comment by mintsweet** [comment]
补一个: 不提醒别人已撤回的消息有点憨了, 别人撤回了消息自己看不到已撤回还去回复了别个...

**Comment by yangjianyao** [comment]
请教下 微信2.6 哪下的？

**Comment by LunaYJ** [comment]
> 请教下 微信2.6 哪下的？

昨天官方更新的呀

**Comment by gdoudeng** [comment]
> > 请教下 微信2.6 哪下的？
> 
> 昨天官方更新的呀

现在去看 表示没有

**Comment by LunaYJ** [comment]
> > > 请教下 微信2.6 哪下的？
> 
> > 
> 
> > 昨天官方更新的呀
> 
> 
> 
> 现在去看 表示没有

😳 我是官方下载的，前天自动弹出升级提醒时候更新的

**Comment by WXiangQian** [comment]
表示遇到了同样的情况

**Comment by rootphantomer** [comment]
发现该问题+1

**Comment by MustangYM** [comment]
#758
