### ISSUE TITLE
撤回bug，自己消息撤回 自己的聊天界面无法撤回 但是对方看到的是已经撤回

### ISSUE THREAD

**Issue by Unknownthings** [MustangYM/WeChatExtension-ForMac#758]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by buxiaomo** [comment]
+1

**Comment by renwfy** [comment]
+1

**Comment by MustangYM** [comment]
[v2.8.1已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.1)
