### ISSUE TITLE
微信转发信息闪退

### ISSUE THREAD

**Issue by susdevlop** [MustangYM/WeChatExtension-ForMac#762]
- MacOS版本 : 版本10.15.4（版号19E264b）
- 微信版本 : 2.5
- 小助手版本 : 2.8.1
- BUG描述 : 转发信息 、表情等
- 操作场景 :想转发别人的表情
系统语言：zh-Hans
微信版本：[2020-10-16 14:40:43] v2.5.0.144 (15727) #a0d90bced1
微信语言：zh-Hans
历史版本：[2020-10-21 16:14:23] v2.5.0.18 (15735) #94e220c158
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(1680x1050)/Retina, (1920x1080)

**Comment by MustangYM** [comment]
[重新更新了包，没有发版本，重新安装这个2.8.1就好了](https://github.com/MustangYM/WeChatExtension-ForMac/releases)
