### ISSUE TITLE
大佬，你的更新日志的第一条是不是写错年份了？

### ISSUE THREAD

**Issue by alexcdever** [MustangYM/WeChatExtension-ForMac#766]
我看第二条开始都是2020年的，唯独第一条是2012年的。另外整个日志从第二条开始往下，都遵循从2020年从新到旧的排序规律，第一条反而是2012年的就感觉不对劲

**Comment by savior325** [comment]
另：官网和App Store下载的Mac微信还都是2.5.0（15735），想问大佬从哪下载的2.6.0……

**Comment by MustangYM** [comment]
@savior325 @savior325 #752
