### ISSUE TITLE
多选bug

### ISSUE THREAD

**Issue by LunaYJ** [MustangYM/WeChatExtension-ForMac#767]
### issue规范
- MacOS版本 : 11.1
- 微信版本 : Version. 2.6.0 (16787)
- 小助手版本 : 2.8.1
- BUG描述 : 多选后功能图片&文字 不显示
- 操作场景 : 多选消息后底部功能图标不可见
- 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/2851302/103193124-68207d80-4916-11eb-8a64-50ff82474dae.png)

**Comment by MustangYM** [comment]
[v2.8.2已修复](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.2)
