### ISSUE TITLE
聊天输入框中外接键盘的Home和End键映射失效

### ISSUE THREAD

**Issue by reinstallsys** [MustangYM/WeChatExtension-ForMac#77]
为了映射外接键盘的Home和End键，在~/Library/KeyBindings/里增加了一个DefaultKeyBinding.dict文件，内容如下
{ 
	"\UF729" = moveToBeginningOfLine:; // home 
	"\UF72B" = moveToEndOfLine:; // end 
	"$\UF729" = moveToBeginningOfLineAndModifySelection:; // shift-home 
	"$\UF72B" = moveToEndOfLineAndModifySelection:; // shift-end 
	"^\UF729" = moveToBeginningOfDocument:; // ctrl-home 
	"^\UF72B" = moveToEndOfDocument:; // ctrl-end 
	"^$\UF729" = moveToBeginningOfDocumentAndModifySelection:; // ctrl-shift-home 
	"^$\UF72B" = moveToEndOfDocumentAndModifySelection:; // ctrl-shift-end
}
未使用插件时，在聊天输入框里可以使用Home和End键，跳到一段文字的开头和结尾
启用插件以后，Home和End键就失效了，麻烦有空看一下，谢谢！

**Comment by MustangYM** [comment]
> 为了映射外接键盘的Home和End键，在~/Library/KeyBindings/里增加了一个DefaultKeyBinding.dict文件，内容如下
> {
> "\UF729" = moveToBeginningOfLine:; // home
> "\UF72B" = moveToEndOfLine:; // end
> "$\UF729" = moveToBeginningOfLineAndModifySelection:; // shift-home
> "$\UF72B" = moveToEndOfLineAndModifySelection:; // shift-end
> "^\UF729" = moveToBeginningOfDocument:; // ctrl-home
> "^\UF72B" = moveToEndOfDocument:; // ctrl-end
> "^$\UF729" = moveToBeginningOfDocumentAndModifySelection:; // ctrl-shift-home
> "^$\UF72B" = moveToEndOfDocumentAndModifySelection:; // ctrl-shift-end
> }
> 未使用插件时，在聊天输入框里可以使用Home和End键，跳到一段文字的开头和结尾
> 启用插件以后，Home和End键就失效了，麻烦有空看一下，谢谢！

触及我的知识盲区了啊
