### ISSUE TITLE
微信转发图片闪退

### ISSUE THREAD

**Issue by bykgh** [MustangYM/WeChatExtension-ForMac#778]
- 微信版本 :  Version. 2.5.0 (15731)
- MacOS版本 :  macOS Big Sur 11.1 和 macOS Catalina 10.15.6
- 小助手版本 : V2.8.1
- BUG描述 : 转发图片闪退
- 操作场景：皮肤开启迷离模式，打开任意窗口，右键选择一张图片，选转发，微信闪退

https://user-images.githubusercontent.com/50514344/104081564-6e91ec00-526a-11eb-8c2d-0311bafcbb0b.mp4

**Comment by MustangYM** [comment]
#762
