### ISSUE TITLE
关闭防撤回后也无法自己撤回消息

### ISSUE THREAD

**Issue by gaolv123tyu** [MustangYM/WeChatExtension-ForMac#779]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 2.5.0
- 小助手版本 : 2.8.9
- BUG描述 :  关闭防撤回后也无法自己撤回消息
- 操作场景 :  无论是否开启防撤回功能，自己发送的消息点击撤回，一直转圈圈，无法撤回（实际上手机已经显示撤回）；

**Comment by MustangYM** [comment]
#758 #756
