### ISSUE TITLE
随机昵称颜色会随机到接近主题颜色，导致昵称无法看清

### ISSUE THREAD

**Issue by laojianzi** [MustangYM/WeChatExtension-ForMac#782]
- MacOS版本 : 10.15.6
- 微信版本 : 2.6.0
- 小助手版本 : 2.8.1
- BUG描述 : 当选择主题后，随机颜色的昵称可能会随机到接近主题色，那么昵称就会看的不清晰
- 操作场景 : 创建一个群，多拉一些人，加大颜色范围，总会出现的

![image](https://user-images.githubusercontent.com/42930263/104293836-6ef3e680-54f9-11eb-974f-168cb69e5da5.png)

**Comment by ninevcat** [comment]
+ 1 可以加一个取消随机颜色的功能嘛

**Comment by MustangYM** [comment]
最开始是可以取消随机颜色的，但我认为这不符合我在皮肤模式下的设计理念，就像吃油条没有配豆浆一样难受。

**Comment by laojianzi** [comment]
> 最开始是可以取消随机颜色的，但我认为这不符合我在皮肤模式下的设计理念，就像吃油条没有配豆浆一样难受。

可以考虑在随机颜色的情况下，剔除近主题的颜色组合，就像白色背景下不要白色昵称 🤪

**Comment by MustangYM** [comment]
@laojianzi 这并不是随机颜色，每一种颜色都是我提前配置好的。

**Comment by laojianzi** [comment]
@MustangYM 明白，感谢您的回复
