### ISSUE TITLE
自动回复出感叹号 输入锁屏指令一样出现红色感叹号

### ISSUE THREAD

**Issue by stevenliuit** [MustangYM/WeChatExtension-ForMac#79]
![image](https://user-images.githubusercontent.com/4044994/62749802-57a50400-ba90-11e9-96ca-3084c24a3f75.png)
现在只要自动回复和输入锁屏就是红色感叹号
![image](https://user-images.githubusercontent.com/4044994/62749835-84591b80-ba90-11e9-9658-20e8afa137fc.png)

版本是最新版本
![image](https://user-images.githubusercontent.com/4044994/62749862-a05cbd00-ba90-11e9-9ce7-78f3253b9f18.png)

**Comment by MustangYM** [comment]
> ![图片](https://user-images.githubusercontent.com/4044994/62749802-57a50400-ba90-11e9-96ca-3084c24a3f75.png)
> 现在只要自动回复和输入锁屏就是红色感叹号
> ![图片](https://user-images.githubusercontent.com/4044994/62749835-84591b80-ba90-11e9-9658-20e8afa137fc.png)
> 
> 版本是最新版本
> ![图片](https://user-images.githubusercontent.com/4044994/62749862-a05cbd00-ba90-11e9-9ce7-78f3253b9f18.png)

我测试了我这边并未出现此问题

**Comment by stevenliuit** [comment]
重新退了登录就好了
