### ISSUE TITLE
无法显示引用消息

### ISSUE THREAD

**Issue by zhan8863** [MustangYM/WeChatExtension-ForMac#790]
### issue规范
- MacOS版本 : 11.0.1 (20B29)
- 微信版本 : 2.3.31 (13331)
- 小助手版本 : 2.8.1
- BUG描述 : 无法显示对方引用消息， 此消息实为对方引用的我某条消息并回复的
-
![image](https://user-images.githubusercontent.com/10891518/104669406-e94c8280-5714-11eb-997d-fa7066720f84.png)

**Comment by xiaotianxt** [comment]
微信版本太低了吧

**Comment by MustangYM** [comment]
这个不是小助手的问题。
