### ISSUE TITLE
 打开群员监控后微信崩溃

### ISSUE THREAD

**Issue by lge6** [MustangYM/WeChatExtension-ForMac#791]
### issue规范
- MacOS版本 : 11.1
- 微信版本 : 2.5.0 (15731)
- 小助手版本 : 2.8.2
- BUG描述 : 打开群员监控后微信崩溃
- 操作场景 : 打开群员监控后一段时间（或者是打开群员监控后关闭该窗口），微信崩溃重启
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
BigSur的问题，暂时没法适配

**Comment by lge6** [comment]
> BigSur的问题，暂时没法适配

ok,那只能等后续更新了，感谢！
