### ISSUE TITLE
2.8.2 怎么没有pkg文件了？

### ISSUE THREAD

**Issue by leon-hw** [MustangYM/WeChatExtension-ForMac#793]
如题，2.8.2 没有这个PKG文件可以下载了，希望补上。 @MustangYM

**Comment by leon-hw** [comment]
另外，微信今天的最新版本已经是2.6.1 (16853)了

**Comment by MustangYM** [comment]
pkg安装方式有个致命缺陷，会导致今后的脚本更新和卸载出现文件权限问题。微信今天更新16853与小助手搭配我目前我使用还比较正常。

**Comment by leon-hw** [comment]
ok
