### ISSUE TITLE
重复提示小助手更新

### ISSUE THREAD

**Issue by jasonxytan** [MustangYM/WeChatExtension-ForMac#795]
### issue规范
- MacOS版本 : 11.1
- 微信版本 : 2.5.0 （Mac App Store版)
- 小助手版本 : 2.8.1
- BUG描述 : 每次登陆都会提示小助手更新，点击更新后会再次出现
- 操作场景 : 微信启动后, 弹出小助手更新的提示窗口，点击更新——更新并重启微信后，提示再次出现。多次重复后仍然有提示
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
不知您之前是否使用了pkg安装模式，这个模式会改变macOS文件夹权限。如果是，那么请删除微信App（不会删除聊天记录），再重新安装微信，然后再安装小助手即可。

**Comment by jasonxytan** [comment]
谢谢答复
> 然后再安装小助手即可

要先卸载小助手吗？如果是，请问如何彻底卸载pkg安装模式产生的文件？

**Comment by MustangYM** [comment]
@jasonxytan 直接删除微信App即可，重装微信，重装小助手。

**Comment by jasonxytan** [comment]
问题已解决，谢谢。
