### ISSUE TITLE
微信直接无响应，卡死了

### ISSUE THREAD

**Issue by heshangcode** [MustangYM/WeChatExtension-ForMac#796]
安装插件之后，微信变的很卡，直接进程变为了无响应。把插件卸载了，然后就不卡了
MacOS版本 : 10.15.7 (19H15)
电脑配置：2020 款，i5， 16+512。
微信版本 : 2.6.1 (16853)
小助手版本 : 2.8.2
操作场景：打字打快了，点击消息列表也卡，没有开皮肤，开启了退群监控和撤回，微信好友 3000 人，微信群 500 个，
![image](https://user-images.githubusercontent.com/39662806/104796525-e3789f00-57f1-11eb-973b-9ff6a052393d.png)

**Comment by MustangYM** [comment]
重点关注这个 退群监控，你试试把退群监控关掉。

**Comment by MustangYM** [comment]
[](https://github.com/MustangYM/WeChatExtension-ForMac/issues/786#issuecomment-762542619)
