### ISSUE TITLE
安装是成功了，2.3.24 (12246)安装后没效果

### ISSUE THREAD

**Issue by liuya891012** [MustangYM/WeChatExtension-ForMac#8]
2.3.24 (12246)安装后，不能防撤回，不能免认证登录，不能使用系统浏览器，所有的都无效

**Comment by MustangYM** [comment]
> 2.3.24 (12246)安装后，不能防撤回，不能免认证登录，不能使用系统浏览器，所有的都无效

工具栏有显示小助手么？要使用的功能勾选上了么。

**Comment by iKuiki** [comment]
你可以看看安装log，我帮朋友装tk助手的时候碰到过安装过程中报错，但是程序没中断，最后还是显示success（就是安装脚本什么都没做，然后显示成功）我朋友一直和我说装好了没用，我让他截安装过程的截图给我看才发现的

**Comment by liuya891012** [comment]
不好意思，经多次测试，发现防撤回是有效的，工具栏有显示小助手
但是免认证登录和使用系统浏览器是无效的，我都勾选了

**Comment by MustangYM** [comment]
> 不好意思，经多次测试，发现防撤回是有效的，工具栏有显示小助手
> 但是免认证登录和使用系统浏览器是无效的，我都勾选了

免认证登录已经修复, 浏览器的问题还没有

**Comment by limengyu1990** [comment]
Process:               WeChat [42199]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               2.3.23 (11914)
App Item ID:           836500024
App External ID:       830031604
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [42199]
User ID:               501

Date/Time:             2019-05-14 11:54:25.691 +0800
OS Version:            Mac OS X 10.13.6 (17G2208)
Report Version:        12
Bridge OS Version:     2.4.1 (15P6703)


安装失败

**Comment by limengyu1990** [comment]
WeChatPlugin-MacOS版本安装也失败：

/Applications/WeChat.app/Contents/MacOS/WeChat already exists. Overwrite it? [y/n] y
LC_CODE_SIGNATURE load command found. Remove it? [y/n] y
Added LC_LOAD_DYLIB to /Applications/WeChat.app/Contents/MacOS/WeChat
Find plist failed... exit

**Comment by MustangYM** [comment]
现在增加了懒癌安装
