### ISSUE TITLE
开启皮肤后多选聊天记录时菜单无法正常显示

### ISSUE THREAD

**Issue by Fanduzi** [MustangYM/WeChatExtension-ForMac#814]
### issue规范
- MacOS版本 : 10.156.6
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.1
- BUG描述 : 开启皮肤后多选聊天记录后菜单无法正常显示
- 操作场景 :  右键多选
- 方便的话提供日志, 截图或者视频(可选)

未开启皮肤
![image](https://user-images.githubusercontent.com/24428128/106835157-cb4dbe80-66d1-11eb-9b95-03ddeb35af64.png)
![image](https://user-images.githubusercontent.com/24428128/106835460-59c24000-66d2-11eb-8741-ec9e88adfa6b.png)

开启皮肤
![image](https://user-images.githubusercontent.com/24428128/106835300-12d44a80-66d2-11eb-9d72-7e1f4a8670f2.png)

**Comment by MustangYM** [comment]
更新到2.8.2即可
