### ISSUE TITLE
微信小助手 2.8.2 和 2.8.1 均会导致微信程序无法启动

### ISSUE THREAD

**Issue by SHINSHIRO** [MustangYM/WeChatExtension-ForMac#817]
- MacOS版本 : 10.14.6
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.2 及 2.8.1
- BUG描述 : 微信程序本体无法启动。点击程序直接报错。
- 操作场景 : 电脑开机后，直接启动微信，程序报错无法启动。1、重新在官网下载微信（正式版）重新安装微信再重新安装小助手 2.8.2 以后，还是在启动时直接报错。2、重启电脑，再次重复步骤1的操作，依然无法启动微信。3、重新安装2.8.1版本的小助手，微信依然无法启动。4、卸载微信小助手，微信就可以正常启动和使用了。

补充说明：其实 2.8.2 的小助手我已经用了很长一段时间了，这个版本的微信也用了很久了。之前一直都是好好的。就是今天早上开机后登陆微信才发现微信无法启动的。

**Comment by marquisXuan** [comment]
对的。昨天还在用。今天早起一起来，微信打不开了。
以下是系统信息
设备类型：MacBookPro16,1
系统版本：版本10.16（版号20D64）
系统语言：zh-Hans
微信版本：[2021-01-19 10:44:07] v2.6.1.16 (16871) #7ce0dd785a
微信语言：zh-Hans
历史版本：[2021-02-09 09:02:52] v2.6.1.16 (16871) #7ce0dd785a
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(2048x1280)/Retina
小助手版本： 2.8.2

**Comment by haha92210** [comment]
是的  早上突然就不能用了。

Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

**Comment by Andrew8102** [comment]
看一下#816 已经可以解决了
关闭微信，终端执行
```bash
codesign --sign - --force --deep /Applications/WeChat.app
```
重启微信即可

**Comment by SHINSHIRO** [comment]
> 看一下#816 已经可以解决了
> 关闭微信，终端执行
> 
> ```shell
> codesign --sign - --force --deep /Applications/WeChat.app
> ```
> 
> 重启微信即可

嗯嗯~ 我也看到了。只不过我不是程序猿，也不懂写代码🤣。也没有安装 xcode。所以我就只能反馈一下希望开发者修复啦😅~

**Comment by SHINSHIRO** [comment]
> 看一下#816 已经可以解决了
> 关闭微信，终端执行
> 
> ```shell
> codesign --sign - --force --deep /Applications/WeChat.app
> ```
> 
> 重启微信即可

**Comment by SHINSHIRO** [comment]
这个问题 #816 有解决方案。我在发完这条 issue 也看到了。
我不是程序员也不懂写代码。电脑业没有安装 Xcode 。所以就只能反馈一下啦~
希望大佬能修复一下~

**Comment by StoneVIK** [comment]
> 看一下#816 已经可以解决了
> 关闭微信，终端执行
> 
> ```shell
> codesign --sign - --force --deep /Applications/WeChat.app
> ```
> 
> 重启微信即可

你的命令写错了 应该是 codesign --sign - --force --deep /Applications/WeChat.app

**Comment by LOVEChen** [comment]
codesign --sign - --force --deep /Applications/WeChat.app 就解决了

**Comment by owen77788** [comment]
有没有具体的教程怎么解决啊

**Comment by MustangYM** [comment]
[重装微信后再安装2.8.3小助手](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/V2.8.3)

**Comment by SHINSHIRO** [comment]
> [重装微信后再安装2.8.3小助手](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/V2.8.3)

谢谢大佬~ ღ( ´･ᴗ･` )比心
