### ISSUE TITLE
安装助手后无法打开，卸载助手就可以打开

### ISSUE THREAD

**Issue by supergithuber** [MustangYM/WeChatExtension-ForMac#818]
### issue规范
- MacOS版本 : 10.15.6 (19G73)
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.2
- BUG描述 : 无法启动微信
- 操作场景 : 点击微信图标无法启动，卸载小助手就可以启动
- 方便的话提供日志, 截图或者视频：

Process:               WeChat [3125]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               2.6.1 (16855)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [3125]
User ID:               501

Date/Time:             2021-02-09 09:49:10.736 +0800
OS Version:            Mac OS X 10.15.6 (19G73)
Report Version:        12
Bridge OS Version:     4.6 (17P6065)
Anonymous UUID:        5FB81690-FDB4-7540-DCC6-E0F5AC01D0B3

Time Awake Since Boot: 880 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

Binary Images:
       0x10881f000 -        0x10cc60fef +com.tencent.xinWeChat (2.6.1 - 16855) <745EE16D-2E03-39B5-8CB7-047A9BB8617D> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x10e2b5000 -        0x10e2fbff7 +org.sparkle-project.Sparkle (1.20.0 913-ge196a24d - 1.20.0) <50C08D08-2F05-3F4A-A50C-46CE14FD6420> /Applications/WeChat.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x10e371000 -        0x10e4b1fff +com.tencent.WCDB (1.0.3 - 1) <DEEC3C4E-85D1-3CCA-A79D-22B141053268> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x10e5f0000 -        0x10e5f5ff7 +com.tencent.MMLibHooks (1.0 - 1) <8CB22C47-F6B3-3EFA-997A-0B0851B035B6> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x10e605000 -        0x10e627ff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x10e663000 -        0x10e685ffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x10e6c8000 -        0x10e768fff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x1163ae000 -        0x11643ff47  dyld (750.6) <34A11073-9E4C-38C3-9293-7D566ABAE8B6> /usr/lib/dyld
    0x7fff32645000 -     0x7fff32840ff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff3290f000 -     0x7fff32a2cff6  com.apple.AVKit (1.1 - 600.2) <B4273EA0-10F3-3CA8-81BC-FAD386497F92> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff32a2d000 -     0x7fff32a2dfff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff34059000 -     0x7fff34e19ff2  com.apple.AppKit (6.9 - 1894.60.100) <C4208642-19F7-3EAA-AACD-3B836FFDEFCF> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3519b000 -     0x7fff3527cffa  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <6BD0970D-7FD8-341D-8D82-0B3BBB565462> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff3527e000 -     0x7fff3527efff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <C8F9CC56-F7CF-3E77-B6FC-BD8E1D19FA92> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff35615000 -     0x7fff359a4ffa  com.apple.CFNetwork (1128.0.1 - 1128.0.1) <C524C617-2CEF-340C-8CE2-98EAF91CF6A8> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff35a20000 -     0x7fff35a20fff  com.apple.Carbon (160 - 162) <FB72FB7D-5985-3D9C-82DB-A729FCA1249A> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff35f04000 -     0x7fff35f04fff  com.apple.Cocoa (6.11 - 23) <2F5C8ABA-711F-316C-BB97-921122AEE4DF> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff362f3000 -     0x7fff367fcffb  com.apple.audio.CoreAudio (5.0 - 5.0) <F816D92C-9408-3279-90BC-C23B69DC75AE> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff36da6000 -     0x7fff37225feb  com.apple.CoreFoundation (6.9 - 1677.104) <C0D70026-EDBE-3CBD-B317-367CF4F1C92F> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff37227000 -     0x7fff3789cff8  com.apple.CoreGraphics (2.0 - 1355.22) <4A3CDE7B-4578-3058-966A-3D1DC095A935> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff37c06000 -     0x7fff37c6fff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <EEC17183-7908-3445-83FD-3920132AEC1B> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff37fc6000 -     0x7fff380a1ffc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff3818e000 -     0x7fff3818efff  com.apple.CoreServices (1069.24 - 1069.24) <AA140158-E909-34C2-B2F5-20EBC93E0056> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff38c01000 -     0x7fff38db8ffc  com.apple.CoreText (643.1.5.1 - 643.1.5.1) <9C7FBD03-3845-3E2B-94B8-B3110180D3F5> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff38db9000 -     0x7fff38dfdffb  com.apple.CoreVideo (1.8 - 344.3) <2F1DC859-A2E4-3983-8047-97BC0E8C55CE> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff38dfe000 -     0x7fff38e8bffc  com.apple.framework.CoreWLAN (13.0 - 1601.2) <6C76A9E0-430F-3B3C-AE8A-3005F8E6FCFF> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff39463000 -     0x7fff39828fff  com.apple.Foundation (6.9 - 1677.104) <2EF4C4DA-423B-3AFE-ACD1-7DAE64E47603> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff39b9c000 -     0x7fff39c40ff3  com.apple.framework.IOKit (2.0.2 - 1726.140.1) <31CA30A9-B32D-37A8-B5C8-20999D5D51BF> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff39cd2000 -     0x7fff39e2efee  com.apple.ImageIO.framework (3.3.0 - 1976.11) <C17C7280-54F6-3750-85CE-C43428256D62> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff3a69c000 -     0x7fff3b73cfe9  com.apple.JavaScriptCore (15609 - 15609.3.5.1.3) <1874AA53-2C73-3DB2-A98F-69D9BDB3ADC8> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff3d6c2000 -     0x7fff3d70cff8  com.apple.MultipeerConnectivity (166 - 166) <3EE4C244-DF00-390C-926A-CC31FDEA4E60> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff3db97000 -     0x7fff3dbb9fff  com.apple.audio.OpenAL (1.8 - 1.8) <BF21914B-5F40-3724-AD6B-1F04291A3CE8> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL
    0x7fff41928000 -     0x7fff41937ff7  com.apple.opengl (17.10.22 - 17.10.22) <E75C69AE-61EA-32D5-B58D-30022D68CC66> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff428f4000 -     0x7fff428f4fff  com.apple.quartzframework (1.5 - 23) <F0798D40-2A7A-3ADD-AE82-AC1A934E7EB7> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff428f5000 -     0x7fff42b78ffb  com.apple.QuartzCore (1.11 - 841.4) <FE927B0E-BD49-32CC-8A55-90F553C86C15> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff42b79000 -     0x7fff42bd2ff5  com.apple.QuickLookFramework (5.0 - 906.3) <959CE934-B541-3172-846F-4D1709353526> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff436f9000 -     0x7fff43a42ff1  com.apple.security (7.0 - 59306.140.5) <EB9E9E2A-B53B-36EE-B9CE-EEB99B603CB1> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff43afa000 -     0x7fff43afeff8  com.apple.xpc.ServiceManagement (1.0 - 1) <279E7AA9-B23D-3E32-946B-5559EDC56C86> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff447aa000 -     0x7fff44824ff7  com.apple.SystemConfiguration (1.19 - 1.19) <84F9B3BB-F7AF-3B7C-8CD0-D3C22D19619F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff44aa4000 -     0x7fff44e27ff4  com.apple.VideoToolbox (1.0 - 2625.9) <6CF18E28-A7A8-3952-8171-7E4FF4FB37FA> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff47cdf000 -     0x7fff483e4ffd  com.apple.WebKit (15609 - 15609.3.5.1.3) <77FB3BFF-DF46-3261-8A74-EAB7AF8BDB4D> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff6dec0000 -     0x7fff6dec1fff  libSystem.B.dylib (1281.100.1) <001B3B7F-D02C-31D3-B961-1ED445D5A266> /usr/lib/libSystem.B.dylib
    0x7fff6e199000 -     0x7fff6e1a5fff  libbz2.1.0.dylib (44) <14CC4988-B6D4-3879-AFC2-9A0DDC6388DE> /usr/lib/libbz2.1.0.dylib
    0x7fff6e1a6000 -     0x7fff6e1f8fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff6ec99000 -     0x7fff6ed89fff  libiconv.2.dylib (59) <18311A67-E4EF-3CC7-95B3-C0EDEE3A282F> /usr/lib/libiconv.2.dylib
    0x7fff6ed8a000 -     0x7fff6efe1fff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff6fd20000 -     0x7fff6fd53fde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff6fe27000 -     0x7fff6fe3ffff  libresolv.9.dylib (67.40.1) <C57EDFEF-D36A-310B-8D14-8C68A625B1E8> /usr/lib/libresolv.9.dylib
    0x7fff702ed000 -     0x7fff703cfff7  libxml2.2.dylib (33.4) <EFA77CC6-9139-37B3-98D4-B0E526110EE3> /usr/lib/libxml2.2.dylib
    0x7fff703fc000 -     0x7fff7040eff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff704c5000 -     0x7fff704db72f  libswiftAppKit.dylib (??? - ???) <96DF6ED6-DFEF-30CC-A2C5-7D7CB03D1C0B> /usr/lib/swift/libswiftAppKit.dylib
    0x7fff70505000 -     0x7fff708ba437  libswiftCore.dylib (5.2 - 1103.8.25.8) <E56CCFCA-99E1-36E5-A6BC-F31F53C79910> /usr/lib/swift/libswiftCore.dylib
    0x7fff708c7000 -     0x7fff708cfd7f  libswiftCoreData.dylib (??? - ???) <9962EDC3-A3FE-3B20-9159-1E1F5983E33F> /usr/lib/swift/libswiftCoreData.dylib
    0x7fff708d0000 -     0x7fff708d2fff  libswiftCoreFoundation.dylib (??? - ???) <952190C8-1D56-3F9B-A11B-DF755A3AF472> /usr/lib/swift/libswiftCoreFoundation.dylib
    0x7fff708d3000 -     0x7fff708e0fff  libswiftCoreGraphics.dylib (??? - ???) <D7AF8DE7-1CDE-33FE-9A37-A696923A9C24> /usr/lib/swift/libswiftCoreGraphics.dylib
    0x7fff708e1000 -     0x7fff708e4ffb  libswiftCoreImage.dylib (??? - ???) <1485E8EF-EDA9-3981-84D7-DF3BFE361929> /usr/lib/swift/libswiftCoreImage.dylib
    0x7fff7093f000 -     0x7fff70945fff  libswiftDarwin.dylib (??? - ???) <F3684684-8258-310F-B05B-BD8A696F0F29> /usr/lib/swift/libswiftDarwin.dylib
    0x7fff70946000 -     0x7fff7095dcdf  libswiftDispatch.dylib (??? - ???) <94D67EF4-42B5-3F54-8D86-B6B2B16827DC> /usr/lib/swift/libswiftDispatch.dylib
    0x7fff7095e000 -     0x7fff70ae3277  libswiftFoundation.dylib (??? - ???) <08CA9FFB-201E-38A9-A832-282B71341C5E> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff70af2000 -     0x7fff70af4ff3  libswiftIOKit.dylib (??? - ???) <FD313708-AE48-3C72-A154-53EC839A8D55> /usr/lib/swift/libswiftIOKit.dylib
    0x7fff70b0a000 -     0x7fff70b11f0f  libswiftMetal.dylib (??? - ???) <19448D92-15CB-3153-B13A-17A2C4C34DAB> /usr/lib/swift/libswiftMetal.dylib
    0x7fff70b8d000 -     0x7fff70b90fe7  libswiftObjectiveC.dylib (??? - ???) <E668BD5D-E1D6-3C21-BA7E-5C3A672A964E> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff70ba2000 -     0x7fff70ba7fbf  libswiftQuartzCore.dylib (??? - ???) <5DF454DA-B307-3499-B77D-7AF3646A8D4D> /usr/lib/swift/libswiftQuartzCore.dylib
    0x7fff70c91000 -     0x7fff70c93fff  libswiftXPC.dylib (??? - ???) <3CD547C3-7082-37EA-B289-F6BA6C4D4E26> /usr/lib/swift/libswiftXPC.dylib

Model: Macmini8,1, BootROM 1037.147.1.0.0 (iBridge: 17.16.16065.0.0,0), 6 processors, 6-Core Intel Core i7, 3.2 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E3
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E3
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Feb 28 2020 15:24:56 version 9.30.357.35.32.5.47 FWID 01-9ce4adf3
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Network Service: iPhone, Ethernet, en8
USB Device: USB 3.1 Bus
USB Device: USB3.1 Hub
USB Device: My Passport 261B
USB Device: USB2.1 Hub
USB Device: iPhone
USB Device: USB Keyboard
USB Device: Lenovo USB Optical Mouse
USB Device: Apple T2 Bus
USB Device: Headset
USB Device: Apple T2 Controller
Thunderbolt Bus: Mac mini, Apple Inc., 47.4
Thunderbolt Bus: Mac mini, Apple Inc., 47.4

**Comment by wang-zc** [comment]
看一下 #816 就可以完美解决了，建议 Close issue

**Comment by LOVEChen** [comment]
codesign --sign - --force --deep /Applications/WeChat.app

**Comment by supergithuber** [comment]
> 看一下 #816 就可以完美解决了，建议 Close issue

解决了，谢谢！
