### ISSUE TITLE
最新版无法启动微信问题

### ISSUE THREAD

**Issue by Eminem-liuzi** [MustangYM/WeChatExtension-ForMac#819]
### 
- MacOS版本 : 10.15.7
- 微信版本 : 2.6.1
- 小助手版本 : 2.x.x
- BUG描述 : 安装插件以后无法启动微信

**Comment by whatcall** [comment]
微信光站官网下载无法启动。

App Version: Version. 2.6.1 (16853)
Verbose: v2.6.1.19 (0x12060113)
System: OSX 10.14.6 build(18G7016)
Model: MacBookPro12,1
Hash: 08d7402a44
Build Date: Jan 14 2021
Build Time: 20:35:05
Lang: zh-Hans-CN

**Comment by whatcall** [comment]
临时解决办法，参考 [](https://github.com/MustangYM/WeChatExtension-ForMac/issues/817#issuecomment-775583528)

已验证。

**Comment by LOVEChen** [comment]
codesign --sign - --force --deep /Applications/WeChat.app

**Comment by cnyyk** [comment]
实测有效

**Comment by MustangYM** [comment]
[重装微信后再安装2.8.3小助手](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/V2.8.3)

**Comment by MustangYM** [comment]
#816
