### ISSUE TITLE
mac端不在线时，iphone无法拦截撤回消息

### ISSUE THREAD

**Issue by hbsun2113** [MustangYM/WeChatExtension-ForMac#82]
可不可以做一个后台版的，可以放在服务器上，这样无论mac是否在线，iphone都可以拦截到消息？
哈哈一个小建议～

**Comment by MustangYM** [comment]
> 可不可以做一个后台版的，可以放在服务器上，这样无论mac是否在线，iphone都可以拦截到消息？
> 哈哈一个小建议～


逻辑上就走不通啊, 兄弟. 就算能走通, 租服务器谁掏钱啊.

**Comment by hbsun2113** [comment]
自己的服务器，当作软件安装、后台运行？

**Comment by MustangYM** [comment]
> 自己的服务器，当作软件安装、后台运行？@MustangYM

逻辑上走不通, 必须要把客户端启动起来才行
