### ISSUE TITLE
启动微信后崩溃问题解决方案

### ISSUE THREAD

**Issue by cibimo** [MustangYM/WeChatExtension-ForMac#823]
### issue规范
- MacOS版本 : 11.1
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.2
- BUG描述 : 启动微信后马上崩溃
- 操作场景 : 微信启动后, 崩溃

经查看，是缺少签名导致的崩溃，运行
sudo codesign --force --deep --sign - /Applications/WeChat.app
即可

**Comment by MustangYM** [comment]
[重装微信后再安装2.8.3小助手](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/V2.8.3)

**Comment by fight2escape** [comment]
牛逼，这个响应速度可以

**Comment by ZhangTonghai** [comment]
> 重装微信后再安装2.8.3小助手

没打tag? omw 检查的还是2.8.2

**Comment by wzshiming** [comment]
没打 tag +1, 一键安装的还是旧的

**Comment by QYQSDTC** [comment]
可以结合omw load 更新
