### ISSUE TITLE
小程序打开不了

### ISSUE THREAD

**Issue by wendingp** [MustangYM/WeChatExtension-ForMac#826]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 2.1.0
- 小助手版本 : 2.8.3
- BUG描述 : 点击窗口闪退

小程序打开不了 设置里也没找到小程序 之前有Mini program配置
![image](https://user-images.githubusercontent.com/17057603/107733425-fc636a00-6d35-11eb-9548-9cf772acb751.png)

**Comment by MustangYM** [comment]
微信版本太低了，建议使用2.6.1 (16853)版本，切勿使用当前这个日期下Appstore最新版（也存在部分小程序打不开的情况），微信小程序这块官方一直不稳定

**Comment by wendingp** [comment]
打错了是 2.6.1 (16871), 是appstore下的

**Comment by wendingp** [comment]
Version 2.6.1 (16855) Beta 144

我现在用这个 也是一样没有

**Comment by MustangYM** [comment]
这个跟小助手没关系

**Comment by wendingp** [comment]
啥意思啊... 我的意思是之前有个打开小程序设置的选项 现在没了
