### ISSUE TITLE
请问可以增加根据系统自动切换主题吗？

### ISSUE THREAD

**Issue by declan-haojin** [MustangYM/WeChatExtension-ForMac#828]
### 新功能建议：根据系统自动切换主题
- MacOS版本 : Big Sur 11.2
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.3
- 功能描述 : 类似于Typora这样可以选择系统深色浅色模式下对应的不同主题
![image](https://user-images.githubusercontent.com/56029057/107905238-18127e80-6f89-11eb-9b6a-27ffed043fb0.png)
- 操作场景 : 系统外观为深色时，显示深色所选的主题，浅色同理。
- 现在好像切换主题需要重启应用，如果可以的话，能否自动重启，这样就可以实现自动切换主题？

谢谢！

**Comment by zhouxinapple** [comment]
麻烦帮我移除，谢谢

**Comment by MustangYM** [comment]
没必要
