### ISSUE TITLE
求楼主提供一个api接口 

### ISSUE THREAD

**Issue by stevenliuit** [MustangYM/WeChatExtension-ForMac#83]
求大神提供一个api接口
好友列表
群列表
好友消息推送
群消息推送
好友和群消息接收接口

**Comment by MustangYM** [comment]
> 求大神提供一个api接口
> 好友列表
> 群列表
> 好友消息推送
> 群消息推送
> 好友和群消息接收接口

都是hook微信的原始方法，并没有相关的接口
