### ISSUE TITLE
老闪退

### ISSUE THREAD

**Issue by rockmelodies** [MustangYM/WeChatExtension-ForMac#834]
### issue规范
- MacOS版本 : 11.2.1
- 微信版本 : 2.6.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by rockmelodies** [comment]
解决了

**Comment by mango-svip** [comment]
咋解决的呀 ？ 我也遇到了...
