### ISSUE TITLE
重新安装微信plus小助手，安装后打开微信时报错

### ISSUE THREAD

**Issue by leeyi19910708** [MustangYM/WeChatExtension-ForMac#841]
### issue规范
- MacOS版本 : macOS 11.2.1 (20D74)
- 微信版本 :    2.6.1 (16878)
- 小助手版本 : 2.8.3
- BUG描述 : 从官网或者从作者这边下载官方当前版本或者最新beta版本（都试过），安装后，在还未安装小助手时是可以正常使用的；安装小助手后，打开微信，提示“因为出现问题而无法打开”等相关信息。
- 操作场景 : 双击“微信”应用程序
-
![截屏2021-02-22 10 00 30](https://user-images.githubusercontent.com/48469375/108647940-d9367880-74f4-11eb-9819-70e173a4ed79.png)

**Comment by xituoche** [comment]
安装xcode后，terminal执行
`sudo codesign --sign - --force --deep /Applications/WeChat.app`

**Comment by xuxichen** [comment]
安装微信后,执行readme里的命令之后可能会出现这个问题.出现这个问题之后,
安装xcode后，terminal执行
sudo codesign --sign - --force --deep /Applications/WeChat.app

**Comment by MustangYM** [comment]
#816
