### ISSUE TITLE
微信启动失败

### ISSUE THREAD

**Issue by nerrolk** [MustangYM/WeChatExtension-ForMac#842]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 2.6.1 (16855) Beta 144
- 小助手版本 :v2.6.7 
- BUG描述 : 微信打不开
- 操作场景 : 启动微信
- 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/31092764/108708850-f1d27d00-754c-11eb-824b-6401fdb85da5.png)

**Comment by nerrolk** [comment]
Process:               WeChat [2819]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               2.6.1 (16855)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [2819]
User ID:               501

Date/Time:             2021-02-22 20:15:25.217 +0800
OS Version:            Mac OS X 10.15.7 (19H2)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
Anonymous UUID:        657B7FD9-7548-8B9A-DC9A-A11E6C37973E


Time Awake Since Boot: 6100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

Binary Images:
       0x1002c5000 -        0x104706fef +com.tencent.xinWeChat (2.6.1 - 16855) <745EE16D-2E03-39B5-8CB7-047A9BB8617D> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x105d56000 -        0x105d9cff7 +org.sparkle-project.Sparkle (1.20.0 913-ge196a24d - 1.20.0) <50C08D08-2F05-3F4A-A50C-46CE14FD6420> /Applications/WeChat.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x105e0f000 -        0x105f4ffff +com.tencent.WCDB (1.0.3 - 1) <DEEC3C4E-85D1-3CCA-A79D-22B141053268> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x10608c000 -        0x106091ff7 +com.tencent.MMLibHooks (1.0 - 1) <8CB22C47-F6B3-3EFA-997A-0B0851B035B6> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x1060a1000 -        0x1060c3ff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x1060fd000 -        0x10611fffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x10615e000 -        0x1061fefff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x10733b000 -        0x1073ccf47  dyld (750.6) <1D318D60-C9B0-3511-BE9C-82AFD2EF930D> /usr/lib/dyld
    0x7fff323b6000 -     0x7fff325b1ff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff32680000 -     0x7fff3279dff6  com.apple.AVKit (1.1 - 600.2) <41B403F1-2F32-37BB-A0D7-B84AF3F1734B> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff3279e000 -     0x7fff3279efff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff33dca000 -     0x7fff34b8aff2  com.apple.AppKit (6.9 - 1894.60.100) <A64D10A6-FE17-39CE-9392-6615BE54E10E> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff34f0c000 -     0x7fff34fedffa  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <8CFA0620-5E43-3C4D-A75B-981C0961C2DE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff34fef000 -     0x7fff34feffff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <C8F9CC56-F7CF-3E77-B6FC-BD8E1D19FA92> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff35386000 -     0x7fff35715ffa  com.apple.CFNetwork (1128.0.1 - 1128.0.1) <07F9CA9C-B954-3EA0-A710-3122BFF9F057> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff35791000 -     0x7fff35791fff  com.apple.Carbon (160 - 162) <97E334B3-7FAE-3239-9E89-5A546BC26ADE> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff35c75000 -     0x7fff35c75fff  com.apple.Cocoa (6.11 - 23) <2192EE61-8CA8-3639-B7D3-0D68F200C9EF> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff36064000 -     0x7fff3656dffb  com.apple.audio.CoreAudio (5.0 - 5.0) <9DA02E7A-56A0-3FFF-94C2-1795BA761F07> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff36b17000 -     0x7fff36f96feb  com.apple.CoreFoundation (6.9 - 1677.104) <C0D70026-EDBE-3CBD-B317-367CF4F1C92F> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff36f98000 -     0x7fff3760dff8  com.apple.CoreGraphics (2.0 - 1355.22) <4A3CDE7B-4578-3058-966A-3D1DC095A935> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff37977000 -     0x7fff379e0ff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <75966124-2FB7-33C3-BE49-3DD5F327F911> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff37d37000 -     0x7fff37e12ffc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff37eff000 -     0x7fff37efffff  com.apple.CoreServices (1069.24 - 1069.24) <AA140158-E909-34C2-B2F5-20EBC93E0056> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff38972000 -     0x7fff38b29ffc  com.apple.CoreText (643.1.5.1 - 643.1.5.1) <A88F052A-C840-3E6C-9BF8-FFFED34C0667> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff38b2a000 -     0x7fff38b6effb  com.apple.CoreVideo (1.8 - 344.3) <5314E70D-325F-3E98-99FC-00FDF520747E> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff38b6f000 -     0x7fff38bfcffc  com.apple.framework.CoreWLAN (13.0 - 1601.2) <6223BFD5-D451-3DE9-90F6-F609AC0B0027> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff391d4000 -     0x7fff39599fff  com.apple.Foundation (6.9 - 1677.104) <7C69F845-F651-3193-8262-5938010EC67D> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3990d000 -     0x7fff399b1ff3  com.apple.framework.IOKit (2.0.2 - 1726.140.1) <14223387-6F81-3976-8605-4BC2F253A93E> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff39a43000 -     0x7fff39b9fffe  com.apple.ImageIO.framework (3.3.0 - 1976.11.1) <5DBAD721-B70E-396C-922C-A2742E6815D6> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff3a40e000 -     0x7fff3b4aeff1  com.apple.JavaScriptCore (15609 - 15609.4.1) <18766B97-AB12-331C-984C-F1C7C9363E8B> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff3d435000 -     0x7fff3d47fff8  com.apple.MultipeerConnectivity (166 - 166) <ECB78B83-E384-3079-915E-2D7C791DCD2E> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff3d90a000 -     0x7fff3d92cfff  com.apple.audio.OpenAL (1.8 - 1.8) <6D66C5D7-8410-35B7-B06E-3BE56E0A708E> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL
    0x7fff4169b000 -     0x7fff416aaff7  com.apple.opengl (17.10.22 - 17.10.22) <D3C57A32-6BD0-3228-B1C4-0F42A6128A6C> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff42667000 -     0x7fff42667fff  com.apple.quartzframework (1.5 - 23) <48F3D0F9-323E-34E5-8F63-CF541F2B7B0E> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff42668000 -     0x7fff428ebffb  com.apple.QuartzCore (1.11 - 841.4) <FE927B0E-BD49-32CC-8A55-90F553C86C15> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff428ec000 -     0x7fff42945ff5  com.apple.QuickLookFramework (5.0 - 906.3) <959CE934-B541-3172-846F-4D1709353526> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff4346c000 -     0x7fff437b5ff1  com.apple.security (7.0 - 59306.140.5) <B6F8368F-2395-379B-B768-71C53BB1B903> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff4386d000 -     0x7fff43871ff8  com.apple.xpc.ServiceManagement (1.0 - 1) <2C62956C-F2D4-3EB0-86C7-EAA06331621A> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff4451d000 -     0x7fff44597ff7  com.apple.SystemConfiguration (1.19 - 1.19) <84F9B3BB-F7AF-3B7C-8CD0-D3C22D19619F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff44817000 -     0x7fff44b9aff4  com.apple.VideoToolbox (1.0 - 2625.9) <6CF18E28-A7A8-3952-8171-7E4FF4FB37FA> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff47a52000 -     0x7fff48157ffd  com.apple.WebKit (15609 - 15609.4.1) <B514329D-F257-310E-B562-C23C20920075> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff6dbed000 -     0x7fff6dbeefff  libSystem.B.dylib (1281.100.1) <0A6C8BA1-30FD-3D10-83FD-FF29E221AFFE> /usr/lib/libSystem.B.dylib
    0x7fff6dec6000 -     0x7fff6ded2fff  libbz2.1.0.dylib (44) <14CC4988-B6D4-3879-AFC2-9A0DDC6388DE> /usr/lib/libbz2.1.0.dylib
    0x7fff6ded3000 -     0x7fff6df25fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff6e9c6000 -     0x7fff6eab6fff  libiconv.2.dylib (59) <18311A67-E4EF-3CC7-95B3-C0EDEE3A282F> /usr/lib/libiconv.2.dylib
    0x7fff6eab7000 -     0x7fff6ed0efff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff6fa4d000 -     0x7fff6fa80fde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff6fb54000 -     0x7fff6fb6cfff  libresolv.9.dylib (67.40.1) <C57EDFEF-D36A-310B-8D14-8C68A625B1E8> /usr/lib/libresolv.9.dylib
    0x7fff7001a000 -     0x7fff700fcfff  libxml2.2.dylib (33.5) <A579D158-2E09-316C-872E-DD9D93401B2F> /usr/lib/libxml2.2.dylib
    0x7fff70129000 -     0x7fff7013bff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff701f2000 -     0x7fff7020872f  libswiftAppKit.dylib (??? - ???) <18802260-9EFC-3E31-B9EA-7767A8B6AB52> /usr/lib/swift/libswiftAppKit.dylib
    0x7fff70232000 -     0x7fff705e7437  libswiftCore.dylib (5.2 - 1103.8.25.8) <E56CCFCA-99E1-36E5-A6BC-F31F53C79910> /usr/lib/swift/libswiftCore.dylib
    0x7fff705f4000 -     0x7fff705fcd7f  libswiftCoreData.dylib (??? - ???) <5188E034-FC7D-3C6B-A42A-69375097E05B> /usr/lib/swift/libswiftCoreData.dylib
    0x7fff705fd000 -     0x7fff705fffff  libswiftCoreFoundation.dylib (??? - ???) <FBA4566B-AD2B-35D7-BC9A-48BE3D88B658> /usr/lib/swift/libswiftCoreFoundation.dylib
    0x7fff70600000 -     0x7fff7060dfff  libswiftCoreGraphics.dylib (??? - ???) <A8225B5F-F64D-32F8-AD91-D919DF614AA0> /usr/lib/swift/libswiftCoreGraphics.dylib
    0x7fff7060e000 -     0x7fff70611ffb  libswiftCoreImage.dylib (??? - ???) <1485E8EF-EDA9-3981-84D7-DF3BFE361929> /usr/lib/swift/libswiftCoreImage.dylib
    0x7fff7066c000 -     0x7fff70672fff  libswiftDarwin.dylib (??? - ???) <F3684684-8258-310F-B05B-BD8A696F0F29> /usr/lib/swift/libswiftDarwin.dylib
    0x7fff70673000 -     0x7fff7068acdf  libswiftDispatch.dylib (??? - ???) <94D67EF4-42B5-3F54-8D86-B6B2B16827DC> /usr/lib/swift/libswiftDispatch.dylib
    0x7fff7068b000 -     0x7fff70810277  libswiftFoundation.dylib (??? - ???) <0173898D-FDA6-378D-87E9-1F2A9BD227D3> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff7081f000 -     0x7fff70821ff3  libswiftIOKit.dylib (??? - ???) <FD313708-AE48-3C72-A154-53EC839A8D55> /usr/lib/swift/libswiftIOKit.dylib
    0x7fff70837000 -     0x7fff7083ef0f  libswiftMetal.dylib (??? - ???) <B3C74138-DE3C-3676-9983-F12757819C9C> /usr/lib/swift/libswiftMetal.dylib
    0x7fff708ba000 -     0x7fff708bdfe7  libswiftObjectiveC.dylib (??? - ???) <E668BD5D-E1D6-3C21-BA7E-5C3A672A964E> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff708cf000 -     0x7fff708d4fbf  libswiftQuartzCore.dylib (??? - ???) <101D3E4D-231A-3CD8-97B4-4E37F4081CD2> /usr/lib/swift/libswiftQuartzCore.dylib
    0x7fff709be000 -     0x7fff709c0fff  libswiftXPC.dylib (??? - ???) <3CD547C3-7082-37EA-B289-F6BA6C4D4E26> /usr/lib/swift/libswiftXPC.dylib

Model: MacBookPro16,1, BootROM 1037.147.4.0.0 (iBridge: 17.16.16610.0.0,0), 6 processors, 6-Core Intel Core i7, 2.6 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro5300MItem, AMD Radeon Pro 5300M, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E1
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 8ATF1G64HZ-2G6E1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Apr  7 2020 13:09:12 version 9.30.357.41.32.5.49 FWID 01-617711e7
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB3.0 Hub
USB Device: USB 3.1 Bus
USB Device: USB2.0 Hub
USB Device: Apple T2 Bus
USB Device: Composite Device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3

**Comment by MustangYM** [comment]
#819 #816
