### ISSUE TITLE
经常闪退

### ISSUE THREAD

**Issue by AccessRetrieved** [MustangYM/WeChatExtension-ForMac#844]
### issue规范
- MacOS版本 : 11.1
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.3
- BUG描述 : 点啥都闪退
- 操作场景 : 点击菜单
- 方便的话提供日志, 截图或者视频(可选)

啊啊啊我又回来了，现在啥功能都随机闪退，有点头疼。
试过了，重启解决不了

@MustangYM

**Comment by MustangYM** [comment]
#819
