### ISSUE TITLE
更新至 Mac OS Big Sur 11.2.1， 安装了微信小助手微信会奔溃打不开

### ISSUE THREAD

**Issue by 1006326485** [MustangYM/WeChatExtension-ForMac#845]
### issue规范
- MacOS版本 : 11.2.1
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.3
- BUG描述 : 打开微信闪退
- 操作场景 : 安装微信小助手则会闪退
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
#816
