### ISSUE TITLE
安装小助手后微信登录后闪退

### ISSUE THREAD

**Issue by larivechauche** [MustangYM/WeChatExtension-ForMac#856]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.3
- BUG描述 : 安装小助手后点开微信登录后直接闪退，再次打开后会变成安全模式，然后走完安全模式后再次登录仍然闪退。

**Comment by MustangYM** [comment]
#816
