### ISSUE TITLE
你的微信版本过低，请升级至最新版本微信后再登录微信。点击“确定”后将跳转至最新版下载页面。

### ISSUE THREAD

**Issue by AlanCheen** [MustangYM/WeChatExtension-ForMac#86]
curl 方式下载的 1.9.6 版本 打开后 登录提示版本太低，下载最新微信。

**Comment by MustangYM** [comment]
> curl 方式下载的 1.9.6 版本 打开后 登录提示版本太低，下载最新微信。

你微信什么版本的

**Comment by AlanCheen** [comment]
好像是因为微信版本高了，我下了个 2.3.x 的就好了 谢谢。
