### ISSUE TITLE
能不能做微信里点击链接用微信浏览器打开的功能

### ISSUE THREAD

**Issue by cshitian** [MustangYM/WeChatExtension-ForMac#861]
每次都去右键选择微信内打开好麻烦。
做一个开关让我们选择是否开启链接用微信浏览器打开。

**Comment by MustangYM** [comment]
小助手菜单 -> 关闭“使用系统浏览器”

**Comment by cshitian** [comment]
你可以测试下，普通的链接，还是会用系统浏览器打开，而不是内置的微信浏览器。

**Comment by MustangYM** [comment]
@cshitian 普通连接使用系统浏览器，这就是微信原始逻辑。已经可见的http地址，为何要使用微信浏览器打开？

**Comment by cshitian** [comment]
> @cshitian 普通连接使用系统浏览器，这就是微信原始逻辑。已经可见的http地址，为何要使用微信浏览器打开？

咳咳  撸羊毛能方便些.....
