### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by likeSo** [MustangYM/WeChatExtension-ForMac#863]
Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

微信无法打开，以上是系统的报错，目前我的解决方案有两种，第一个是卸载小助手，第二个是`codesign --force --deep --sign - /Applications/WeChat.app` 重新签名

**Comment by MustangYM** [comment]
#816
