### ISSUE TITLE
不行了我下什么版本的微信打开就报错，卸载就能用。mac 10.14.6

### ISSUE THREAD

**Issue by goudan1030** [MustangYM/WeChatExtension-ForMac#867]
### issue规范
- MacOS版本 : 10.14.6
- 微信版本 : 2.5.0
- 小助手版本 : 最新版
- BUG描述 : 点击窗口闪退
- 操作场景 : 启动微信就报错。
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
#816
