### ISSUE TITLE
小助手在11.3 Beta版(20E5196f)崩溃

### ISSUE THREAD

**Issue by JokerHB** [MustangYM/WeChatExtension-ForMac#869]
- MacOS版本 : 11.3 Beta
- 微信版本 : 2.6.1 (16855)
- 小助手版本 : 2.8.3
- BUG描述 : 安装小助手后无法启动微信，或者会报 微信.app已经被阻止 因为它可能暴露您的隐私并降低的安全性 的错误。
- 操作场景 : 微信启动时崩溃。

[wechat.log](https://github.com/MustangYM/WeChatExtension-ForMac/files/6090832/wechat.log)

**Comment by iszhuzhi** [comment]
遇到同问题

**Comment by iszhuzhi** [comment]
#816 
#835 
试试这两个方式

**Comment by JokerHB** [comment]
> #816
> #835
> 试试这两个方式

试了一下，我最终的解决方案是：

1. 执行 > sudo codesign --sign - --force --deep /Applications/WeChat.app

2. 右键 微信.app ，选择 显示简介，再选择 覆盖恶意软件保护。

**Comment by HenryLuoCN** [comment]
遇到同样问题
最近几天升级了Mac后不能用了，mac 11.2.2 (20D80)

**Comment by MustangYM** [comment]
> 遇到同样问题
> 最近几天升级了Mac后不能用了，mac 11.2.2 (20D80)

#816
