### ISSUE TITLE
能否加一个自动通过好友请求,并且自动回复

### ISSUE THREAD

**Issue by goodman001** [MustangYM/WeChatExtension-ForMac#87]
能否添加一个功能：别人请求好友，自动添加好友，并且按照设定自动回复，谢谢

**Comment by MustangYM** [comment]
> 能否添加一个功能：别人请求好友，自动添加好友，并且按照设定自动回复，谢谢

额……我不太能想出这个操作的使用场景是否具有普遍性。所以，不能加。
