### ISSUE TITLE
2.6.1 打开崩溃

### ISSUE THREAD

**Issue by maqingshan** [MustangYM/WeChatExtension-ForMac#870]
今天突然打开微信就崩溃。
重装微信不安装小助手可以使用，只要一安装小助手就崩溃。

报错信息如下：
Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

Binary Images:
       0x10b8c1000 -        0x10fd03fff +com.tencent.xinWeChat (2.6.1 - 16853) <2FDC0F3F-AF2A-3579-9005-826451178F80> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x111358000 -        0x11139eff7 +org.sparkle-project.Sparkle (1.20.0 913-ge196a24d - 1.20.0) <50C08D08-2F05-3F4A-A50C-46CE14FD6420> /Applications/WeChat.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x11140e000 -        0x11154efff +com.tencent.WCDB (1.0.3 - 1) <C44BD6B9-8140-34B0-A043-9C384D545980> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x11168d000 -        0x111692ff7 +com.tencent.MMLibHooks (1.0 - 1) <92C26B22-EAB0-3D0A-AECC-FC2659FCD4C1> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x1116a2000 -        0x1116c4ff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x1116ff000 -        0x111721ffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x111760000 -        0x111800fff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x11716c000 -        0x1171fdf47  dyld (750.6) <F58DDECD-315C-3B7C-8162-A5E8E1D62FE3> /usr/lib/dyld
    0x7fff34780000 -     0x7fff3497bff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff34a4a000 -     0x7fff34b67ff6  com.apple.AVKit (1.1 - 600.2) <41B403F1-2F32-37BB-A0D7-B84AF3F1734B> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff34b68000 -     0x7fff34b68fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff36194000 -     0x7fff36f54ff2  com.apple.AppKit (6.9 - 1894.60.100) <322D043D-1140-3486-9523-3F56FF4D8349> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff372d6000 -     0x7fff373b7ffa  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <6185BF20-D2E7-3812-8FD8-EC5237672104> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff373b9000 -     0x7fff373b9fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <918ED3EB-0232-31F3-9BF5-18D1CB11523F> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff37750000 -     0x7fff37adfffa  com.apple.CFNetwork (1128.0.1 - 1128.0.1) <07F9CA9C-B954-3EA0-A710-3122BFF9F057> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff37b5b000 -     0x7fff37b5bfff  com.apple.Carbon (160 - 162) <6A5EB506-7A43-3879-A358-E6B9182C3733> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3803f000 -     0x7fff3803ffff  com.apple.Cocoa (6.11 - 23) <85C8B9B4-6F0B-3BD5-8934-C299FE481A44> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff3842e000 -     0x7fff38937ffb  com.apple.audio.CoreAudio (5.0 - 5.0) <47923B12-3D14-328A-9C86-27A3A2A73068> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff38ee1000 -     0x7fff39360feb  com.apple.CoreFoundation (6.9 - 1677.201) <56B0FE5F-D493-3DF1-ABFF-ECC450268B97> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff39362000 -     0x7fff399d7ff8  com.apple.CoreGraphics (2.0 - 1355.22) <4A3CDE7B-4578-3058-966A-3D1DC095A935> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff39d41000 -     0x7fff39daaff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <75966124-2FB7-33C3-BE49-3DD5F327F911> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff3a101000 -     0x7fff3a1dcffc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff3a2c9000 -     0x7fff3a2c9fff  com.apple.CoreServices (1069.24 - 1069.24) <2D1A6C60-DD34-368F-88FF-E39C9FE549A9> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3ad3c000 -     0x7fff3aef3ffc  com.apple.CoreText (643.1.5.2 - 643.1.5.2) <ADDE38C3-C247-34AD-9903-0276050E242C> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff3aef4000 -     0x7fff3af38ffb  com.apple.CoreVideo (1.8 - 344.3) <5314E70D-325F-3E98-99FC-00FDF520747E> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff3af39000 -     0x7fff3afc6ffc  com.apple.framework.CoreWLAN (13.0 - 1601.2) <6223BFD5-D451-3DE9-90F6-F609AC0B0027> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff3b59e000 -     0x7fff3b963fff  com.apple.Foundation (6.9 - 1677.201) <E020DC09-4221-3961-A450-638525789B38> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3bcd7000 -     0x7fff3bd7bff3  com.apple.framework.IOKit (2.0.2 - 1726.140.1) <14223387-6F81-3976-8605-4BC2F253A93E> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff3be0d000 -     0x7fff3bf6afee  com.apple.ImageIO.framework (3.3.0 - 1976.11.4) <6FC6EE76-F76F-312C-9C67-4B9F0E0B832A> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff3c7d7000 -     0x7fff3d877ff1  com.apple.JavaScriptCore (15609 - 15609.4.1) <18766B97-AB12-331C-984C-F1C7C9363E8B> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff3f7fd000 -     0x7fff3f847ff8  com.apple.MultipeerConnectivity (166 - 166) <ECB78B83-E384-3079-915E-2D7C791DCD2E> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff3fcd2000 -     0x7fff3fcf4fff  com.apple.audio.OpenAL (1.8 - 1.8) <6D66C5D7-8410-35B7-B06E-3BE56E0A708E> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL
    0x7fff43a63000 -     0x7fff43a72ff7  com.apple.opengl (17.10.22 - 17.10.22) <D3C57A32-6BD0-3228-B1C4-0F42A6128A6C> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff44a2f000 -     0x7fff44a2ffff  com.apple.quartzframework (1.5 - 23) <48F3D0F9-323E-34E5-8F63-CF541F2B7B0E> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff44a30000 -     0x7fff44cb3ffb  com.apple.QuartzCore (1.11 - 841.4) <FE927B0E-BD49-32CC-8A55-90F553C86C15> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff44cb4000 -     0x7fff44d0dff5  com.apple.QuickLookFramework (5.0 - 906.3) <959CE934-B541-3172-846F-4D1709353526> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff45836000 -     0x7fff45b7fff1  com.apple.security (7.0 - 59306.140.5) <B6F8368F-2395-379B-B768-71C53BB1B903> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff45c37000 -     0x7fff45c3bff8  com.apple.xpc.ServiceManagement (1.0 - 1) <9B36FD0E-D280-35EB-ABAB-6AC5D7B2118F> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff468e7000 -     0x7fff46961ff7  com.apple.SystemConfiguration (1.19 - 1.19) <84F9B3BB-F7AF-3B7C-8CD0-D3C22D19619F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff46be1000 -     0x7fff46f64ff4  com.apple.VideoToolbox (1.0 - 2625.9) <6CF18E28-A7A8-3952-8171-7E4FF4FB37FA> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff49e1c000 -     0x7fff4a521ffd  com.apple.WebKit (15609 - 15609.4.1) <B514329D-F257-310E-B562-C23C20920075> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff6fe1b000 -     0x7fff6fe1cfff  libSystem.B.dylib (1281.100.1) <8E6AD412-91E7-36FC-A6FD-C13B06A4952A> /usr/lib/libSystem.B.dylib
    0x7fff700f4000 -     0x7fff70100fff  libbz2.1.0.dylib (44) <14CC4988-B6D4-3879-AFC2-9A0DDC6388DE> /usr/lib/libbz2.1.0.dylib
    0x7fff70101000 -     0x7fff70153fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff70bf4000 -     0x7fff70ce4fff  libiconv.2.dylib (59) <18311A67-E4EF-3CC7-95B3-C0EDEE3A282F> /usr/lib/libiconv.2.dylib
    0x7fff70ce5000 -     0x7fff70f3cfff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff71c79000 -     0x7fff71cacfde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff71d80000 -     0x7fff71d98fff  libresolv.9.dylib (67.40.1) <C57EDFEF-D36A-310B-8D14-8C68A625B1E8> /usr/lib/libresolv.9.dylib
    0x7fff72246000 -     0x7fff72328fff  libxml2.2.dylib (33.7) <20567881-7204-3C11-9179-50FE34B3301B> /usr/lib/libxml2.2.dylib
    0x7fff72355000 -     0x7fff72367ff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff7241e000 -     0x7fff7243472f  libswiftAppKit.dylib (??? - ???) <18802260-9EFC-3E31-B9EA-7767A8B6AB52> /usr/lib/swift/libswiftAppKit.dylib
    0x7fff7245e000 -     0x7fff72813437  libswiftCore.dylib (5.2 - 1103.8.25.8) <E56CCFCA-99E1-36E5-A6BC-F31F53C79910> /usr/lib/swift/libswiftCore.dylib
    0x7fff72820000 -     0x7fff72828d7f  libswiftCoreData.dylib (??? - ???) <5188E034-FC7D-3C6B-A42A-69375097E05B> /usr/lib/swift/libswiftCoreData.dylib
    0x7fff72829000 -     0x7fff7282bfff  libswiftCoreFoundation.dylib (??? - ???) <FBA4566B-AD2B-35D7-BC9A-48BE3D88B658> /usr/lib/swift/libswiftCoreFoundation.dylib
    0x7fff7282c000 -     0x7fff72839fff  libswiftCoreGraphics.dylib (??? - ???) <A8225B5F-F64D-32F8-AD91-D919DF614AA0> /usr/lib/swift/libswiftCoreGraphics.dylib
    0x7fff7283a000 -     0x7fff7283dffb  libswiftCoreImage.dylib (??? - ???) <1485E8EF-EDA9-3981-84D7-DF3BFE361929> /usr/lib/swift/libswiftCoreImage.dylib
    0x7fff72898000 -     0x7fff7289efff  libswiftDarwin.dylib (??? - ???) <F3684684-8258-310F-B05B-BD8A696F0F29> /usr/lib/swift/libswiftDarwin.dylib
    0x7fff7289f000 -     0x7fff728b6cdf  libswiftDispatch.dylib (??? - ???) <94D67EF4-42B5-3F54-8D86-B6B2B16827DC> /usr/lib/swift/libswiftDispatch.dylib
    0x7fff728b7000 -     0x7fff72a3c277  libswiftFoundation.dylib (??? - ???) <0173898D-FDA6-378D-87E9-1F2A9BD227D3> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff72a4b000 -     0x7fff72a4dff3  libswiftIOKit.dylib (??? - ???) <FD313708-AE48-3C72-A154-53EC839A8D55> /usr/lib/swift/libswiftIOKit.dylib
    0x7fff72a63000 -     0x7fff72a6af0f  libswiftMetal.dylib (??? - ???) <B3C74138-DE3C-3676-9983-F12757819C9C> /usr/lib/swift/libswiftMetal.dylib
    0x7fff72ae6000 -     0x7fff72ae9fe7  libswiftObjectiveC.dylib (??? - ???) <E668BD5D-E1D6-3C21-BA7E-5C3A672A964E> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff72afb000 -     0x7fff72b00fbf  libswiftQuartzCore.dylib (??? - ???) <101D3E4D-231A-3CD8-97B4-4E37F4081CD2> /usr/lib/swift/libswiftQuartzCore.dylib
    0x7fff72bea000 -     0x7fff72becfff  libswiftXPC.dylib (??? - ???) <3CD547C3-7082-37EA-B289-F6BA6C4D4E26> /usr/lib/swift/libswiftXPC.dylib

**Comment by MustangYM** [comment]
真的没有一点阅读Log和搜索相关issue的能力嘛
