### ISSUE TITLE
新版beta系统小助手崩溃

### ISSUE THREAD

**Issue by AmintaCCCP** [MustangYM/WeChatExtension-ForMac#871]
### issue规范
- MacOS版本 : macOS Big Sur 版本 11.3 beta版 (20E5196f)
- 微信版本 : 2.6.1 (16853)
- 小助手版本 : 2.8.3
- BUG描述 : 

更新了最新MAC测试版后,挂载小助手的微信打开崩溃.重装微信和小助手不能解决.不安装小助手微信正常.

**Comment by MustangYM** [comment]
#816
