### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by WangXiTong** [MustangYM/WeChatExtension-ForMac#874]
# bug反馈
- MacOS版本 : 11.2.1
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.3
- BUG描述 : 使用小助手之后导致微信崩溃，并且退出微信之后 再正常打开微信也打不开  只能卸载微信重新安装  重新安装之后直接打开微信可以  但是使用小助手打开还是会导致微信崩溃并且打不开
- 操作场景 : 使用小助手打开微信
- 方便的话提供日志, 截图或者视频(可选)

**Comment by MustangYM** [comment]
#816
