### ISSUE TITLE
亲测v2.8.3支持 微信3.0.0 beta1 

### ISSUE THREAD

**Issue by fhefh2015** [MustangYM/WeChatExtension-ForMac#877]
```
已失效官网文件下载：
https://dldir1.qq.com/weixin/mac/wechat-beta-17689-1615445873.dmg
```
网盘下载:
https://mega.nz/file/Us8GXbgL#nprCrDRy71wsep-xMIfELiMXsLuj_2Z93oAslR1BiYM

**Comment by MustangYM** [comment]
皮肤模式支持不是很好，别更了，敲不动了。

**Comment by androidcn** [comment]
我刚想 说  

Version 3.0.0 (17689) Beta 1

**Comment by yangjianyao** [comment]
点收藏闪退

**Comment by mifanj** [comment]
明天到公司试试再说😜

**Comment by akidan** [comment]
网上找不到3.0.0 beta1的安装包，最后还是靠github发现的，感谢！

**Comment by MadeBugs** [comment]
大佬，3.0已经发布了，赶紧适配吧[捂脸]

**Comment by baiyetao** [comment]
> 皮肤模式支持不是很好，别更了，敲不动了。

关闭皮肤使用有bug么，担心Alfred不能用

**Comment by yangjianyao** [comment]
> 点收藏闪退

关闭皮肤后，暂时未闪退

**Comment by baiyetao** [comment]
> > 点收藏闪退
> 
> 关闭皮肤后，暂时未闪退

多谢分享

**Comment by wzanbaichi** [comment]
> 皮肤模式支持不是很好，别更了，敲不动了。

哈哈哈哈哈 加油啊 大佬

**Comment by hongzk** [comment]
估摸着会有很多人来催更

**Comment by pengshengsongcode** [comment]
催更哦~

**Comment by KingAmo** [comment]
> 皮肤模式支持不是很好，别更了，敲不动了。

3.0 自带深色模式，我觉得小助手皮肤功能可以砍了

**Comment by CocoaBob** [comment]
3.0.0的浅色模式太白了，眼前白花花的都快被亮瞎了，不知道能否单独把它的侧边栏改成深色模式🤦‍♂️

**Comment by temmpw** [comment]
![image](https://user-images.githubusercontent.com/24599804/110890087-543bc380-832a-11eb-9c35-5b5997c393b9.png)
主题模式可以功成身退了吧

**Comment by zangyunfei01** [comment]
还是有一些问题的，主题模式和底色的兼容显示有问题，点击收藏就闪退，所以还需要做一些兼容的

**Comment by zangyunfei01** [comment]
> 大佬，3.0已经发布了，赶紧适配吧[捂脸]

拒绝强催更，坐等就好

**Comment by guchengod** [comment]
坐等.........................

**Comment by BruceChao** [comment]
迷离模式不比黑暗模式更好吗～～

**Comment by kingqqwx** [comment]
我就是因为更新时点错了，然后卸载重装，发现MACOS 11装不上小助手，MMP

**Comment by fyzzy1943** [comment]
更完再升级 /偷笑

**Comment by luoling76** [comment]
我只是单纯的来看看

**Comment by 986138497** [comment]
支持 3.0 的版本嘛

**Comment by telsius** [comment]
亲测，2.8.3在wechat3.0.0.beta可用

**Comment by 986138497** [comment]
> 亲测，2.8.3在wechat3.0.0.beta可用

是不是我是最新的系统,所以不行呢 (11.2.3 (20D91))

**Comment by iTofu** [comment]
> > 亲测，2.8.3在wechat3.0.0.beta可用
> 
> 是不是我是最新的系统,所以不行呢 (11.2.3 (20D91))

@986138497 
https://github.com/MustangYM/WeChatExtension-ForMac/issues/816

**Comment by GarboSun** [comment]
加油！

**Comment by GarboSun** [comment]
亲测，我不行。给作者加油啊，我等着用回去。

**Comment by Eric-Chan** [comment]
开皮肤界面显示异常

**Comment by Nixiabing** [comment]
来晚一步链接失效了，大佬们还有安装包资源可以提供嘛？

**Comment by Rhinocros** [comment]
我这别的功能正常，就是多开没反应

**Comment by jkjay** [comment]
多开很重要啊，不能多开的话我不更了

**Comment by MustangYM** [comment]
> 多开很重要啊，不能多开的话我不更了

多开正常的。

**Comment by Rhinocros** [comment]
> > 多开很重要啊，不能多开的话我不更了
> 
> 多开正常的。

正常的？为什么我的点完没反应呢，愁

**Comment by luckysonyu99** [comment]
3.0.0.2用懒癌安装法安装之后微信无限闪退啊...有人遇到这种情况吗

**Comment by GarboSun** [comment]
我歪个楼问一下，怎样可以不接收这层楼热度不减的邮件提醒？？

**Comment by MustangYM** [comment]
> 3.0.0.2用懒癌安装法安装之后微信无限闪退啊...有人遇到这种情况吗

#816

**Comment by xsnaruto** [comment]
> 3.0.0.2用懒癌安装法安装之后微信无限闪退啊...有人遇到这种情况吗

我这边也是这样子的，也懒得手动装了，等后期适配好了哈哈哈
