### ISSUE TITLE
微信启动后, 微信小助手菜单不显示

### ISSUE THREAD

**Issue by fiyueh** [MustangYM/WeChatExtension-ForMac#881]
### issue规范
- MacOS版本 : 11.2.3
- 微信版本 : 3.0.0 (17705) Beta2
- 小助手版本 : 2.8.3
- BUG描述 : 小助手无法启动
- 操作场景 : 微信启动后, 微信小助手菜单并没有出现。

**Comment by zixuan96** [comment]
重装可解

**Comment by kingqqwx** [comment]
> 重装可解

应该是系统的问题，MACOS big sur系统 不让装，我装不上

**Comment by kingqqwx** [comment]
蹲一个解决办法，我也这样

**Comment by zixuan96** [comment]
> > 重装可解
> 
> 应该是系统的问题，MACOS big sur系统 不让装，我装不上

你可以自己签名然后安装。我也是Big Sur，可以运行。

**Comment by kingqqwx** [comment]
我解决了，解决步骤：
1、安装微信；
2、需安装xcod，命令是：xcode-select --install 
3、安装完成以后然后在使用下载命令；
4、**注意：**仅能使用方式1安装，其他办法安装提示文件夹不存在，命令：sudo rm -r -f WeChatExtension-ForMac && git clone --depth=1 https://github.com/MustangYM/WeChatExtension-ForMac && cd WeChatExtension-ForMac/WeChatExtension/Rely && ./Install.sh && cd ~

以上为我的解决办法，你试试

**Comment by fiyueh** [comment]
> 我解决了，解决步骤：
> 1、安装微信；
> 2、需安装xcod，命令是：xcode-select --install
> 3、安装完成以后然后在使用下载命令；
> 4、**注意：**仅能使用方式1安装，其他办法安装提示文件夹不存在，命令：sudo rm -r -f WeChatExtension-ForMac && git clone --depth=1 https://github.com/MustangYM/WeChatExtension-ForMac && cd WeChatExtension-ForMac/WeChatExtension/Rely && ./Install.sh && cd ~
> 
> 以上为我的解决办法，你试试

试了一下此方法，有效！谢谢。
MacOS版本 : 11.2.3
微信版本 : Version 3.0.0 (17771) Beta 4
小助手版本 : 2.8.3
