### ISSUE TITLE
安装时，提示：xcrun: error: invalid active developer path

### ISSUE THREAD

**Issue by kingqqwx** [MustangYM/WeChatExtension-ForMac#884]
- MacOS版本 : MacOS Big Sur 11.0.1
- 微信版本 : 3.0.0
- 小助手版本 : 最新版
- BUG描述 : 安装时，错误提示
- 操作场景 : 使用终端安装，提示：xcrun: error: invalid active developer path 

<img width="500" alt="WeChat479c46115669f927b9622ca7e0f41e8a" src="https://user-images.githubusercontent.com/62010410/111110213-14c5df00-8597-11eb-9086-dc4742641b5e.png">

**Comment by kingqqwx** [comment]
#884

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/111110391-6d957780-8597-11eb-80a5-c4c53eb1743e.png)
文件夹的问题，这里为啥多了个2.。。

**Comment by kingqqwx** [comment]
> ![image](https://user-images.githubusercontent.com/21478687/111110391-6d957780-8597-11eb-80a5-c4c53eb1743e.png)
> 文件夹的问题，这里为啥多了个2.。。

谢大哥、、、

**Comment by kingqqwx** [comment]
我解决了，解决步骤：
1、安装微信；
2、需安装xcod，命令是：xcode-select --install 
3、安装完成以后然后在使用下载命令；
4、注意：仅能使用方式1安装，其他办法安装提示文件夹不存在，命令：sudo rm -r -f WeChatExtension-ForMac && git clone --depth=1 https://github.com/MustangYM/WeChatExtension-ForMac && cd WeChatExtension-ForMac/WeChatExtension/Rely && ./Install.sh && cd ~

以上为我的解决办法
