### ISSUE TITLE
11.2.3 无法使用Version. 3.0.0 (17739) Beta 3微信，打不开

### ISSUE THREAD

**Issue by Bupterambition** [MustangYM/WeChatExtension-ForMac#888]
### issue规范
- MacOS版本 : 11.2.3
- 微信版本 :Version. 3.0.0 (17739) Beta 3「下载链接：https://down.macsc.com/202009/WeChat_mac_lin.pkg」
- 小助手版本 : 3.17 最近版本
- BUG描述 : 无法打开微信
- 操作场景 : 无法打开微信
- 方便的话提供日志, 截图或者视频(可选)

**Comment by 520xcy** [comment]
#816

**Comment by Bupterambition** [comment]
@Bupterambition solve for: `sudo codesign --sign - --force --deep /Applications/WeChat.app`
