### ISSUE TITLE
能不能实现屏蔽文件自动下载

### ISSUE THREAD

**Issue by Suremotoo** [MustangYM/WeChatExtension-ForMac#89]
能不能实现屏蔽文件自动下载，有时候群里发个文件，并不需要下载，但是会自动下载，很烦人，想用的时候自己点击再下载。

**Comment by MustangYM** [comment]
> 能不能实现屏蔽文件自动下载，有时候群里发个文件，并不需要下载，但是会自动下载，很烦人，想用的时候自己点击再下载。

:)感觉这个不是啥问题啊, 哈哈, 忍一忍吧
