### ISSUE TITLE
【BUG】粘贴文字时，内容光标变大

### ISSUE THREAD

**Issue by X-Kay** [MustangYM/WeChatExtension-ForMac#890]
MacOS版本 : MacOS Big Sur 11.0.1
微信版本 : 3.0.0
小助手版本 : 最新版
BUG描述 : 复制粘贴文字时，内容光标变大
操作场景 : 
![image](https://user-images.githubusercontent.com/62010410/111411671-ef131400-8715-11eb-8358-75d8834f070b.png)

**Comment by MustangYM** [comment]
微信自己的问题@微信团队
