### ISSUE TITLE
下载小助手后使微信无法打开

### ISSUE THREAD

**Issue by NeilMin** [MustangYM/WeChatExtension-ForMac#896]
### issue规范
- MacOS版本 : Catalina 10.15.7
- 微信版本 : 2.6.1
- 小助手版本 : 2.8.2
- BUG描述 : 下载小助手后微信无法打开
- 操作场景 : 下载小助手后，重启微信无法打开，重装微信可以打开微信

**Comment by MustangYM** [comment]
#816
