### ISSUE TITLE
免认证登陆导致消息列表无法显示

### ISSUE THREAD

**Issue by leidi0129** [MustangYM/WeChatExtension-ForMac#898]
重新安装微信 version 3beta1：显示
重启：显示
升级微信 version 3beta4:显示
重启：显示
安装小助手 version 2.2.0，重启：显示
开启免认证登陆，重启，免认证登陆：消息列表一片空白，偶尔能接受新消息提示，但是无法显示，“发起群聊”或者从通讯录“发消息”，跳转消息列表，还是一片空白
关闭免认证登陆，重启：显示

**Comment by MustangYM** [comment]
小助手版本太老了。

**Comment by leidi0129** [comment]
非常感谢！解决了！找到了更新命令「尝试help/-h参数看看更新命令，没找到（原来是安装微信被删掉了），还以为直接使用懒人命令curl -o- -L https://raw.githubusercontent.com/lmk123/oh-my-wechat/master/install.sh | bash -s可以安装最新版>_<
