### ISSUE TITLE
无法在微信 3.0.0 使用小助手

### ISSUE THREAD

**Issue by Astatine-213-Tian** [MustangYM/WeChatExtension-ForMac#899]
### issue规范
- MacOS版本 : 11.0.1
- 微信版本 : 3.0.0
- 小助手版本 : 2.8.3
- BUG描述 : 微信无法打开

**Comment by chenkai-ifanr** [comment]
需要自行签名，安装完打开微信提示错误后，在终端签名，然后再打开就好了
codesign --sign - --force --deep /Applications/WeChat.app

**Comment by hakeedra** [comment]
签名后可以打开，打开后很有点丑

**Comment by HankinsPan** [comment]
> 签名后可以打开，打开后很有点丑

用自带的皮肤视觉感还行

**Comment by HenryLuoCN** [comment]
微信3.0，重签名失败，以前是可以这样签名的
codesign --sign - --force --deep /Applications/WeChat.app

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Applications/WeChat.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Applications/WeChat.app/Contents/MacOS/Mini Program.app

打不开微信3.0了

**Comment by char1eslu** [comment]
还是等大佬适配3.0的皮肤后再更新吧，大佬辛苦了

**Comment by chenkai-ifanr** [comment]
> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools)

https://blog.csdn.net/weixin_39172380/article/details/88388913
xcode-select --install

**Comment by Astatine-213-Tian** [comment]
> codesign --sign - --force --deep /Applications/WeChat.app

感谢 可以使用了

**Comment by HenryLuoCN** [comment]
Nice! Done!
