### ISSUE TITLE
Big Sur 窗口无法进入磨砂透明模式 - 部分窗口磨砂，消息输入框为白色，很丑

### ISSUE THREAD

**Issue by david990917** [MustangYM/WeChatExtension-ForMac#900]
### issue规范
- MacOS版本 : big sur
- 微信版本 :  latest
- 小助手版本 : latest
- BUG描述 : 窗口无法进入磨砂透明模式 - 部分窗口磨砂，消息输入框为白色，很丑
- 操作场景 : 微信使用正常场景

**Comment by sunnyjackyang** [comment]
目前小助手2.8.3好像没有对3.0微信做皮肤适配，看#906

**Comment by david990917** [comment]
现在迷离模式显示正常，关闭 issue 了！感谢！
