### ISSUE TITLE
安装小助手后启动即报错

### ISSUE THREAD

**Issue by sssshn** [MustangYM/WeChatExtension-ForMac#904]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 2.6.1/3.0.0
- 小助手版本 : 2.8.3
- BUG描述 :启动微信即崩溃
- 操作场景 : 启动微信即崩溃
Process:               WeChat [59183]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               3.0.0 (17816)
App Item ID:           836500024
App External ID:       841058874
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [59183]
User ID:               501

Date/Time:             2021-03-30 10:42:19.251 +0800
OS Version:            Mac OS X 10.15.7 (19H524)
Report Version:        12
Bridge OS Version:     5.2 (18P4346)
Anonymous UUID:        1BD2C021-D863-1EA5-E554-F2AF6DB3E342

Sleep/Wake UUID:       111CF29E-5912-4C04-901A-DCF53DDA6B96

Time Awake Since Boot: 560000 seconds
Time Since Wake:       5200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

Binary Images:
       0x1099e3000 -        0x10e31cfef +com.tencent.xinWeChat (3.0.0 - 17816) <BBD9E934-D392-37EA-90AA-214D6371CF6D> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x10fb4e000 -        0x11003fffb +com.tencent.ilinknetwork (1.1.4 - 1.1.4) <C7A68FCC-87B7-37ED-97FC-1E0200EBFF54> /Applications/WeChat.app/Contents/Frameworks/ilink_network.framework/Versions/A/ilink_network
       0x1100a8000 -        0x1101e8fff +com.tencent.WCDB (1.0.3 - 1) <70A1B57B-7EB5-3E13-91D7-E6927266EEE0> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x110283000 -        0x110288ff7 +com.tencent.MMLibHooks (1.0 - 1) <5901B561-6343-33D6-924A-43368BBD16F5> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x110295000 -        0x1102b7ff7 +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x1102f3000 -        0x110315ffb +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x110357000 -        0x1103f7fff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x1115c9000 -        0x11165af47  dyld (750.6) <326C6480-04F4-3164-A363-53079A148E2F> /usr/lib/dyld
    0x7fff35255000 -     0x7fff35450ff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff3551f000 -     0x7fff3563cff6  com.apple.AVKit (1.1 - 600.2) <41B403F1-2F32-37BB-A0D7-B84AF3F1734B> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff3563d000 -     0x7fff3563dfff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff36c69000 -     0x7fff37a29ff2  com.apple.AppKit (6.9 - 1894.60.100) <035927A5-657C-3D54-B9AA-0BBE7307514E> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff37dab000 -     0x7fff37e8cffa  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <5B249BE8-90C2-303D-9D08-7E829341DB23> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff37e8e000 -     0x7fff37e8efff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <19BFF349-A9A2-355A-96F9-3ACD50231B0D> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff38225000 -     0x7fff385b4ffa  com.apple.CFNetwork (1128.0.2 - 1128.0.2) <967D1958-9BAD-3582-B63D-C4088D43D69B> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff38630000 -     0x7fff38630fff  com.apple.Carbon (160 - 162) <93F221F5-B31E-31F4-ACC7-7840171C61E3> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff38b14000 -     0x7fff38b14fff  com.apple.Cocoa (6.11 - 23) <94D1D6CE-8EFB-3EBF-A662-29F5AA6F963D> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff38f03000 -     0x7fff3940cffb  com.apple.audio.CoreAudio (5.0 - 5.0) <47923B12-3D14-328A-9C86-27A3A2A73068> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff399b6000 -     0x7fff39e35feb  com.apple.CoreFoundation (6.9 - 1677.201) <56B0FE5F-D493-3DF1-ABFF-ECC450268B97> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff39e37000 -     0x7fff3a4acff8  com.apple.CoreGraphics (2.0 - 1355.22) <438C1588-4EA6-3648-9905-53E804DC179A> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff3a816000 -     0x7fff3a87fff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <75966124-2FB7-33C3-BE49-3DD5F327F911> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff3abd6000 -     0x7fff3acb1ffc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff3ad9e000 -     0x7fff3ad9efff  com.apple.CoreServices (1069.24 - 1069.24) <4DCFF933-1368-322A-97AB-C3BBEF8E5BBE> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3b811000 -     0x7fff3b9c8ffc  com.apple.CoreText (643.1.5.4 - 643.1.5.4) <9962BA1D-8858-36FC-9C1E-856F59CB73C8> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff3b9c9000 -     0x7fff3ba0dffb  com.apple.CoreVideo (1.8 - 344.3) <5314E70D-325F-3E98-99FC-00FDF520747E> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff3ba0e000 -     0x7fff3ba9bffc  com.apple.framework.CoreWLAN (13.0 - 1601.2) <6223BFD5-D451-3DE9-90F6-F609AC0B0027> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff3c073000 -     0x7fff3c438fff  com.apple.Foundation (6.9 - 1677.201) <E020DC09-4221-3961-A450-638525789B38> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3c7ac000 -     0x7fff3c850ff3  com.apple.framework.IOKit (2.0.2 - 1726.148.1) <0A9D244C-AECC-3D29-86DE-4F3B04F8DD25> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff3c8e2000 -     0x7fff3ca3ffe6  com.apple.ImageIO.framework (3.3.0 - 1976.11.4) <B6BE5D70-F74D-3436-BED7-E5F0BB104F74> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff3d2ac000 -     0x7fff3e34cff1  com.apple.JavaScriptCore (15609 - 15609.4.1) <18766B97-AB12-331C-984C-F1C7C9363E8B> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff402e4000 -     0x7fff4032eff8  com.apple.MultipeerConnectivity (166 - 166) <ECB78B83-E384-3079-915E-2D7C791DCD2E> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff407b9000 -     0x7fff407dbfff  com.apple.audio.OpenAL (1.8 - 1.8) <6D66C5D7-8410-35B7-B06E-3BE56E0A708E> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL
    0x7fff4454a000 -     0x7fff44559ff7  com.apple.opengl (17.10.22 - 17.10.22) <4D43EB22-BD57-3493-B574-332E13657FE9> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff45516000 -     0x7fff45516fff  com.apple.quartzframework (1.5 - 23) <112CB670-9241-3CE1-B857-B81DF2623BBC> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff45517000 -     0x7fff4579affb  com.apple.QuartzCore (1.11 - 841.4) <0028ADD7-42AD-310E-B725-2DF94C07FD6D> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff4579b000 -     0x7fff457f4ff5  com.apple.QuickLookFramework (5.0 - 906.3) <959CE934-B541-3172-846F-4D1709353526> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff4631d000 -     0x7fff46666ff1  com.apple.security (7.0 - 59306.140.5) <B6F8368F-2395-379B-B768-71C53BB1B903> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff4671e000 -     0x7fff46722ff8  com.apple.xpc.ServiceManagement (1.0 - 1) <9B36FD0E-D280-35EB-ABAB-6AC5D7B2118F> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff473ce000 -     0x7fff47448ff7  com.apple.SystemConfiguration (1.19 - 1.19) <84F9B3BB-F7AF-3B7C-8CD0-D3C22D19619F> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff476c8000 -     0x7fff47a4bff4  com.apple.VideoToolbox (1.0 - 2625.9) <6CF18E28-A7A8-3952-8171-7E4FF4FB37FA> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff4a903000 -     0x7fff4b008ffd  com.apple.WebKit (15609 - 15609.4.1) <B514329D-F257-310E-B562-C23C20920075> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff70aec000 -     0x7fff70aedfff  libSystem.B.dylib (1281.100.1) <C49167AD-722B-3DF3-9031-7D6B59FC2A06> /usr/lib/libSystem.B.dylib
    0x7fff70dc5000 -     0x7fff70dd1fff  libbz2.1.0.dylib (44) <14CC4988-B6D4-3879-AFC2-9A0DDC6388DE> /usr/lib/libbz2.1.0.dylib
    0x7fff70dd2000 -     0x7fff70e24fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff718c5000 -     0x7fff719b5fff  libiconv.2.dylib (59) <18311A67-E4EF-3CC7-95B3-C0EDEE3A282F> /usr/lib/libiconv.2.dylib
    0x7fff719b6000 -     0x7fff71c0dfff  libicucore.A.dylib (64260.0.1) <8AC2CB07-E7E0-340D-A849-186FA1F27251> /usr/lib/libicucore.A.dylib
    0x7fff7294c000 -     0x7fff7297ffde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff72a53000 -     0x7fff72a6bfff  libresolv.9.dylib (67.40.1) <C57EDFEF-D36A-310B-8D14-8C68A625B1E8> /usr/lib/libresolv.9.dylib
    0x7fff72f19000 -     0x7fff72ffbfff  libxml2.2.dylib (33.8) <FE38B007-24AF-310D-B834-2C9466154CEC> /usr/lib/libxml2.2.dylib
    0x7fff73028000 -     0x7fff7303aff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff730aa000 -     0x7fff730b5f4f  libswiftAVFoundation.dylib (??? - ???) <8EE58BB5-6915-34F6-B80A-788D89118CD7> /usr/lib/swift/libswiftAVFoundation.dylib
    0x7fff730f1000 -     0x7fff7310772f  libswiftAppKit.dylib (??? - ???) <18802260-9EFC-3E31-B9EA-7767A8B6AB52> /usr/lib/swift/libswiftAppKit.dylib
    0x7fff73131000 -     0x7fff734e6437  libswiftCore.dylib (5.2 - 1103.8.25.8) <E56CCFCA-99E1-36E5-A6BC-F31F53C79910> /usr/lib/swift/libswiftCore.dylib
    0x7fff734e7000 -     0x7fff734f2fff  libswiftCoreAudio.dylib (??? - ???) <2886B49B-6D68-3F12-B71F-704940D0A86F> /usr/lib/swift/libswiftCoreAudio.dylib
    0x7fff734f3000 -     0x7fff734fbd7f  libswiftCoreData.dylib (??? - ???) <5188E034-FC7D-3C6B-A42A-69375097E05B> /usr/lib/swift/libswiftCoreData.dylib
    0x7fff734fc000 -     0x7fff734fefff  libswiftCoreFoundation.dylib (??? - ???) <FBA4566B-AD2B-35D7-BC9A-48BE3D88B658> /usr/lib/swift/libswiftCoreFoundation.dylib
    0x7fff734ff000 -     0x7fff7350cfff  libswiftCoreGraphics.dylib (??? - ???) <A8225B5F-F64D-32F8-AD91-D919DF614AA0> /usr/lib/swift/libswiftCoreGraphics.dylib
    0x7fff7350d000 -     0x7fff73510ffb  libswiftCoreImage.dylib (??? - ???) <1485E8EF-EDA9-3981-84D7-DF3BFE361929> /usr/lib/swift/libswiftCoreImage.dylib
    0x7fff73511000 -     0x7fff73516fb7  libswiftCoreLocation.dylib (??? - ???) <3732D3F0-9586-372E-82B0-2C76F401B793> /usr/lib/swift/libswiftCoreLocation.dylib
    0x7fff73528000 -     0x7fff73564fcf  libswiftCoreMedia.dylib (??? - ???) <73B60C53-4122-35ED-AAAB-084E9722924E> /usr/lib/swift/libswiftCoreMedia.dylib
    0x7fff7356b000 -     0x7fff73571fff  libswiftDarwin.dylib (??? - ???) <F3684684-8258-310F-B05B-BD8A696F0F29> /usr/lib/swift/libswiftDarwin.dylib
    0x7fff73572000 -     0x7fff73589cdf  libswiftDispatch.dylib (??? - ???) <94D67EF4-42B5-3F54-8D86-B6B2B16827DC> /usr/lib/swift/libswiftDispatch.dylib
    0x7fff7358a000 -     0x7fff7370f277  libswiftFoundation.dylib (??? - ???) <0173898D-FDA6-378D-87E9-1F2A9BD227D3> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff7371e000 -     0x7fff73720ff3  libswiftIOKit.dylib (??? - ???) <FD313708-AE48-3C72-A154-53EC839A8D55> /usr/lib/swift/libswiftIOKit.dylib
    0x7fff73736000 -     0x7fff7373df0f  libswiftMetal.dylib (??? - ???) <B3C74138-DE3C-3676-9983-F12757819C9C> /usr/lib/swift/libswiftMetal.dylib
    0x7fff737b9000 -     0x7fff737bcfe7  libswiftObjectiveC.dylib (??? - ???) <E668BD5D-E1D6-3C21-BA7E-5C3A672A964E> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff737ce000 -     0x7fff737d3fbf  libswiftQuartzCore.dylib (??? - ???) <101D3E4D-231A-3CD8-97B4-4E37F4081CD2> /usr/lib/swift/libswiftQuartzCore.dylib
    0x7fff738bd000 -     0x7fff738bffff  libswiftXPC.dylib (??? - ???) <3CD547C3-7082-37EA-B289-F6BA6C4D4E26> /usr/lib/swift/libswiftXPC.dylib
    0x7fff738c7000 -     0x7fff738e8fff  libswiftsimd.dylib (??? - ???) <21EEA85D-EBBF-378C-8803-DCD904B93B68> /usr/lib/swift/libswiftsimd.dylib

Model: MacBookPro16,1, BootROM 1554.80.3.0.0 (iBridge: 18.16.14346.0.0,0), 6 processors, 6-Core Intel Core i7, 2.6 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro5300MItem, AMD Radeon Pro 5300M, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, SK Hynix, -
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, SK Hynix, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Oct 28 2020 14:13:29 version 9.30.357.42.32.5.48 FWID 01-767f6cce
Bluetooth: Version 7.0.6f8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Composite Device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3

**Comment by ZhaofengWu** [comment]
同样的问题，但是
```
Version:               2.5.0 (15731)
```

重启后突然遇到了这个问题，之前一直好好的。
![image](https://user-images.githubusercontent.com/11954789/113190860-af6a2300-9211-11eb-9c19-0e977fc747e8.png)

**Comment by YS-Wong** [comment]
Same issue

**Comment by MustangYM** [comment]
#816
