### ISSUE TITLE
最新版微信啥时候出兼容呀 大兄弟

### ISSUE THREAD

**Issue by c525225358** [MustangYM/WeChatExtension-ForMac#905]
- MacOS版本 : 10.15.7
- 微信版本 : 3.0.0 (17816)
- 小助手版本 : 最新版
- BUG描述 : 打开微信闪退
- 操作场景 :  刚出的版本求兼容

**Comment by gqbre** [comment]
https://github.com/MustangYM/WeChatExtension-ForMac/issues/816#issuecomment-796611009

**Comment by c525225358** [comment]
坐等


发自我的iPhone

**Comment by xiong-it** [comment]
`codesign --sign - --force --deep /Applications/WeChat.app`
[https://github.com/MustangYM/WeChatExtension-ForMac/issues/816#issuecomment-796611009](url)

**Comment by MustangYM** [comment]
[v2.8.4](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.4)
