### ISSUE TITLE
10万人血书1/100000，微信3.0.0兼容，感谢大佬们，辛苦大佬们

### ISSUE THREAD

**Issue by Aliujiayu** [MustangYM/WeChatExtension-ForMac#906]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 3.0.0
- 小助手版本 : 最新版
- BUG描述 : 微信闪退
- 操作场景 : 微信启动后, 直接微信闪退

**Comment by Thrxy1991** [comment]
加我一个，2/100000

**Comment by MQL9011** [comment]
臣附议

**Comment by JohnyWu** [comment]
+1

**Comment by 0xJacky** [comment]
https://github.com/MustangYM/WeChatExtension-ForMac/issues/885#issuecomment-806272613 能用

**Comment by BruceChao** [comment]
现在能用的啊，就是皮肤模式之类关闭就行

**Comment by wangliangyu** [comment]
希望皮肤问题帮忙修复一下，感谢！

**Comment by curryhendry** [comment]
+1，不要改皮肤了。

**Comment by Opanma** [comment]
没用皮肤，防撤回正常  Mac版本11.2.3

**Comment by hezhefly** [comment]
臣附议

**Comment by shai2** [comment]
附议，顺便参楼上一本。没有半透明皮肤，微信没有了灵魂

**Comment by RomanticHW** [comment]
求支持

**Comment by RadianceL** [comment]
附议，顺便参楼上一本。没有半透明皮肤，微信没有了灵魂

**Comment by xiaoma0304** [comment]
附议

**Comment by yaoyue** [comment]
俺也是

**Comment by NNumber** [comment]
附议

**Comment by MrYangyt** [comment]
附议，透明皮肤是灵魂！

**Comment by MrYangyt** [comment]
附议，半透明皮肤是灵魂

**Comment by Jerome-lara** [comment]
附议

**Comment by akaQin** [comment]
附议

**Comment by Lupeiwen0** [comment]
附议，半透明皮肤是灵魂

**Comment by DramerSun** [comment]
俺也一样

**Comment by HoustonDuane** [comment]
俺也一样！

**Comment by vipadm** [comment]
来复议一个

**Comment by yaolee** [comment]
附议

**Comment by sunwenli** [comment]
附议

**Comment by to404** [comment]
附议

**Comment by LawyZheng** [comment]
臣附议

**Comment by UJohn** [comment]
臣附议

**Comment by Azleal** [comment]
+1

**Comment by potatoes0521** [comment]
+1

**Comment by zongsir** [comment]
血书加一

**Comment by dwSun** [comment]
试了一下，catalina上直接就能用，重新安装一下小助手就好了

**Comment by DNSTESTWEB** [comment]
关掉皮肤就好了

**Comment by SummerAfter** [comment]
附议

**Comment by dwSun** [comment]
皮肤不用关掉，直接就能用，只是有的地方可能显示不正确。

**Comment by PeterPuffer** [comment]
臣附议

**Comment by nicecp** [comment]
附议。。。安装后右上角没有小图标了。。。

**Comment by HenryEmbrace** [comment]
附议，顺便参楼上一本。没有半透明皮肤，微信没有了灵魂

**Comment by Fizzyi** [comment]
附议

**Comment by wxiaohe** [comment]
臣附议

**Comment by Rheinmetallskorpion** [comment]
作者大大加油！

**Comment by char1eslu** [comment]
附议，迷离模式是灵魂

**Comment by zihaojiang** [comment]
+1

**Comment by orchidwyz** [comment]
+1  感谢作者大大

**Comment by T4di5** [comment]
作者是被抓进去了吗？？？

**Comment by Yuanhuafei** [comment]
臣附议

**Comment by baiyidjp** [comment]
1.安装小助手后微信无法打开？
答：常见于2.6.7版本以前的小助手，卸载小助手后重新安装小助手即可。
2.小助手皮肤不支持低于10.14的macOS系统。
3.小助手理论上不支持 3.0 及以上版本仅兼容,如出现闪退情况请自行回退版本,其他功能请自行测试.
4.微信3.0 及以上版本出现小助手皮肤无法完美适配问题,请关闭皮肤.
5.最新版小助手为 2.8.3.
6.小助手官网:https://github.com/MustangYM/WeChatExtension-ForMac
7.安装之后闪退,属于签名问题.操作方法:
第一步:在 App Store 下载 Xcode;
第二步:安装小助手,并确认版本为 2.8.3;
第三步:在在终端执行:
①sudo codesign —force —deep —sign - /Applications/WeChat.app
②codesign --sign - --force --deep /Applications/WeChat.app
7.下载最新微信：https://dldir1.qq.com/weixin/mac/WeChatMac_Beta.dmg

**Comment by X-Kay** [comment]
俺也一样

**Comment by yAoOw** [comment]
+1

**Comment by houziyu** [comment]
臣附议，已捐赠

**Comment by Darrenzzy** [comment]
快快快

**Comment by Nixiabing** [comment]
皮肤功能还存在兼容性问题。
mac 11.2.3

**Comment by forkimif** [comment]
俺也一样

**Comment by bareboy** [comment]
+1

**Comment by hvsop** [comment]
臣附议

**Comment by liermao** [comment]
俺也一样

**Comment by percyjie** [comment]
俺也一样

**Comment by nanshanyi** [comment]
无修改权限。fork 了 本项目，修改了crash，和搜索问题。
https://github.com/nanshanyi/WeChatExtension-ForMac

**Comment by nanshanyi** [comment]
修改了crash，和迷离主题搜索背景问题。其它主题未做适配
https://github.com/nanshanyi/WeChatExtension-ForMac

**Comment by Designdocs** [comment]
+1

**Comment by char1eslu** [comment]
> 修改了crash，和迷离主题搜索背景问题。其它主题未做适配
> https://github.com/nanshanyi/WeChatExtension-ForMac

是迷离主题已经适配好了吗，多谢

**Comment by YangAidi** [comment]
想要皮肤~

**Comment by coldice945** [comment]
> 修改了crash，和迷离主题搜索背景问题。其它主题未做适配
> https://github.com/nanshanyi/WeChatExtension-ForMac

可以 PR 到该项目。回馈广大社区。

**Comment by zhangxiaoyu2046** [comment]
附议+1

**Comment by sunnyjackyang** [comment]
同求3.0.0半透明毛玻璃皮肤兼容！！！感谢开发者！！

**Comment by jipiyan** [comment]
俺也一样！

**Comment by wenkesong-li** [comment]
冲

**Comment by MustangYM** [comment]
[v2.8.4](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.4)

**Comment by Jax0rz** [comment]
签名有问题，闪退
