### ISSUE TITLE
最新1.9.6小助手在Mac10.15下没有状态栏

### ISSUE THREAD

**Issue by WantD998** [MustangYM/WeChatExtension-ForMac#91]
不知道是不是哪里冲突了 

![image](https://user-images.githubusercontent.com/38783023/65003548-8fbf2280-d92b-11e9-8360-8d2974b47ce5.png)

**Comment by qiaodaima** [comment]
俺也一样

**Comment by qiaodaima** [comment]
> 俺也一样

我家里的电脑可以装成功，公司的不行

**Comment by luckysonyu99** [comment]
> 不知道是不是哪里冲突了
> 
> ![image](https://user-images.githubusercontent.com/38783023/65003548-8fbf2280-d92b-11e9-8360-8d2974b47ce5.png)

你是不是装了bartender了，是这个冲突了，更新到最新版的bartender就能解决

**Comment by WantD998** [comment]
> > 不知道是不是哪里冲突了
> > ![image](https://user-images.githubusercontent.com/38783023/65003548-8fbf2280-d92b-11e9-8360-8d2974b47ce5.png)
> 
> 你是不是装了bartender了，是这个冲突了，更新到最新版的bartender就能解决

哦！是的 我更新了，已解决 多谢🙏
