### ISSUE TITLE
微信更新后需要重新下载小助手

### ISSUE THREAD

**Issue by AccessRetrieved** [MustangYM/WeChatExtension-ForMac#910]
### issue规范
- MacOS版本 : 11.2.1
- 微信版本 : 3.0.1
- 小助手版本 : 2.8.3
- BUG描述 : 微信更新过后需要重新下载小助手
- 操作场景 : App Store更新微信
- 方便的话提供日志, 截图或者视频(可选)

试过重启电脑和微信，无效。

**Comment by AccessRetrieved** [comment]
但重新下载后数据都在

**Comment by Teacher-c** [comment]
这不是正常的吗。。。本来就是对weixin.app 动手
