### ISSUE TITLE
Mac  3.0.1微信无法打开

### ISSUE THREAD

**Issue by zcSkr** [MustangYM/WeChatExtension-ForMac#916]
### issue规范
- MacOS版本 : 10.15.7
- 微信版本 : 3.0.1
- 小助手版本 : 2.x.x
- BUG描述 : 微信无法打开
- 操作场景 : 微信启动
- 方便的话提供日志, 截图或者视频(可选)
![image](https://user-images.githubusercontent.com/30515821/114488797-91a2b200-9c44-11eb-81f0-533b2a7728f5.png)

**Comment by RaymanMartin** [comment]
同遇到这样的问题。

**Comment by YS-Wong** [comment]
Same issue.

**Comment by wayne3991** [comment]
Same issue.

**Comment by xiong-it** [comment]
same issue

**Comment by Nate-ou** [comment]
同

**Comment by YS-Wong** [comment]
[https://github.com/MustangYM/WeChatExtension-ForMac/issues/919](https://github.com/MustangYM/WeChatExtension-ForMac/issues/919)
cdpidan helped me solve this problem.
