### ISSUE TITLE
主题 Bug. 一点收藏就闪退. WeChat Version 3.0 beta6

### ISSUE THREAD

**Issue by william-chin** [MustangYM/WeChatExtension-ForMac#917]
### My Issue
- MacOS版本 : 10.15.6
- 微信版本 : Version 3.0.0 (17842) Beta 6
- 小助手版本 : v2.8.3
- BUG描述 : 主题显示特别奇怪，打开主题点收藏会闪退，关闭主题无事发生
- 操作场景 : 打开主题点收藏会闪退，关闭主题无事发生

![Snipaste_2021-04-13_13-43-06](https://user-images.githubusercontent.com/39523950/114503143-68dbe600-9c5f-11eb-9fa5-61f063625046.png)

**Comment by CheungChan** [comment]
+1

**Comment by nanshanyi** [comment]
无修改权限。fork 了 本项目，修改了crash，和搜索问题。
https://github.com/nanshanyi/WeChatExtension-ForMac

**Comment by hooksoul** [comment]
+1

**Comment by hooksoul** [comment]
+1

**Comment by char1eslu** [comment]
+1 收藏 闪退

**Comment by MustangYM** [comment]
请更新V2.8.4
