### ISSUE TITLE
期待微信 3.0

### ISSUE THREAD

**Issue by w935903854** [MustangYM/WeChatExtension-ForMac#919]
点个赞

**Comment by weimy1234** [comment]
👍

**Comment by nanshanyi** [comment]
无修改权限。fork 了 本项目，修改了crash，和搜索问题。
https://github.com/nanshanyi/WeChatExtension-ForMac

**Comment by cdpidan** [comment]
可以试试重新签名 sudo codesign --sign - --force --deep /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension

**Comment by xiongwu1** [comment]
期待3.0

**Comment by lifeva** [comment]
作者弃坑了？

**Comment by w935903854** [comment]
Haha,may be!!!

**Comment by YS-Wong** [comment]
> 可以試試重新簽名sudo codesign --sign - --force --deep /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension

IT WORKS! Thank you so much!

**Comment by MustangYM** [comment]
[v2.8.4](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.4)
