### ISSUE TITLE
登录多个微信，容易退出

### ISSUE THREAD

**Issue by naihuayang** [MustangYM/WeChatExtension-ForMac#92]
登录多个账号，很容易就退出其中的一个，不是很稳定；重新打开后，还是会自动登录没有强制退出的微信同一个账号，导致同一个账号登录了两个窗口； 同时多个微信账号的时候，点击对应的微信图标，会把所有的微信窗口置顶。

**Comment by leowang029** [comment]
同样遇到上面的问题

**Comment by cctse** [comment]
微信2.3.27
扩展2.0
我开两个微信经常会漰一个
