### ISSUE TITLE
2.7.0后版本无法安装

### ISSUE THREAD

**Issue by shirebella** [MustangYM/WeChatExtension-ForMac#922]
- MacOS版本 : 11.2.3
- 微信版本 : 3.0.1
- 小助手版本 : 2.8.2，2.8.3
<img width="518" alt="截屏2021-04-19 下午4 47 32" src="https://user-images.githubusercontent.com/20533768/115208305-fcfdef80-a12e-11eb-80c2-c94d624dd37a.png">

- BUG描述 : 2.7.0之后的版本无法安装
- 操作场景 : 安装完成后点击微信无法打开
- 方便的话提供日志, 截图或者视频(可选)

**Comment by Nate-ou** [comment]
同

**Comment by zhangxiaoyu2046** [comment]
同上, 求修复

**Comment by MustangYM** [comment]
#816
