### ISSUE TITLE
微信 Version. 3.0.2 (18007) Beta 1 防撤回功能失效

### ISSUE THREAD

**Issue by PlayerYK** [MustangYM/WeChatExtension-ForMac#929]
### issue规范
- MacOS版本 : 11.2.3
- 微信版本 : Version. 3.0.2 (18007) Beta 1
- 小助手版本 : 2.8.3
- BUG描述 : 防撤回功能失效
- 操作场景 : 不能保留撤回消息

**Comment by 520xcy** [comment]
+1

**Comment by Leeiio** [comment]
+1
