### ISSUE TITLE
如何获取图片消息体中的图片

### ISSUE THREAD

**Issue by flywithbug** [MustangYM/WeChatExtension-ForMac#930]
### issue规范
- MacOS版本 : 0.15.7 
- 微信版本 : 3.0.0
- 小助手版本 : 2.8.2
- BUG描述 : ![image](https://user-images.githubusercontent.com/3955387/116024480-e1d83600-a680-11eb-9e83-ec7931a5a898.png)   接收到的图片信息 直接获取msgData是nil  ，如何去下载消息体中的图片信息，或者如何根据消息内容获取缓存中的图片

**Comment by MustangYM** [comment]
已经写得很清楚了.....
