### ISSUE TITLE
完蛋了，更新了macos 11.3 微信就没法启动了，卸载助手后就可以了。

### ISSUE THREAD

**Issue by lifeva** [MustangYM/WeChatExtension-ForMac#932]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by yangjianyao** [comment]
O(∩_∩)O哈哈~ 我也是，重新安装了微信

**Comment by yangjianyao** [comment]
重新下载最新的助手代码，不要下载release的2.83版本。已经测试撤回正常

**Comment by bright116** [comment]
再命令行里运行下这个:
codesign --sign - --force --deep /Applications/WeChat.app

**Comment by binghan2000** [comment]
怎么下载最新的版本？

**Comment by lifeva** [comment]
> 重新下载最新的助手代码，不要下载release的2.83版本。已经测试撤回正常

具体下载什么啊？怎么下？具体说一下啊

**Comment by eplt** [comment]
重新下载 wechat，再用手动安装方法安装一遍，就可以了。我尝试了omw不可以。
sudo rm -r -f WeChatExtension-ForMac && git clone --depth=1 https://github.com/MustangYM/WeChatExtension-ForMac && cd WeChatExtension-ForMac/WeChatExtension/Rely && ./Install.sh && cd ~

**Comment by lifeva** [comment]
> 再命令行里运行下这个:
> codesign --sign - --force --deep /Applications/WeChat.app

重装助手，然后就照此办理，然后再启动微信，亲测有效！！

**Comment by itcodes** [comment]
完美

**Comment by JustDoItGit** [comment]
> 重新下载 wechat，再用手动安装方法安装一遍，就可以了。我尝试了omw不可以。
> sudo rm -r -f WeChatExtension-ForMac && git clone --depth=1 https://github.com/MustangYM/WeChatExtension-ForMac && cd WeChatExtension-ForMac/WeChatExtension/Rely && ./Install.sh && cd ~

你的方法解决了，厉害啊。
