### ISSUE TITLE
微信 3.0.9 直接启动错误

### ISSUE THREAD

**Issue by binghan2000** [MustangYM/WeChatExtension-ForMac#933]
### issue规范
- MacOS版本 : 11.3
- 微信版本 : 3.0.9
- 小助手版本 : 2.3.3
- BUG描述 : 无法启动
- 操作场景 :

**Comment by binghan2000** [comment]
另，微信回退到3.0.6。正常了

**Comment by lifeva** [comment]
> 另，微信回退到3.0.6。正常了
 #932 
无需退回，参照另贴

**Comment by binghan2000** [comment]
搞定！
