### ISSUE TITLE
最新版本3.0.0 安装插件后无法打开微信

### ISSUE THREAD

**Issue by ZedRover** [MustangYM/WeChatExtension-ForMac#936]
### issue规范
- MacOS版本 : 11.3
- 微信版本 : 3.0.0
- 小助手版本 : 2.8.3
- BUG描述 : 安装小助手后无法打开微信
- 操作场景 : 启动微信

更新最新的系统之前提示微信和隐私数据有冲突什么的警告，但是还可以打开微信，更新完系统后无法打开微信，删除小助手后可以打开微信。

**Comment by yangnaihua** [comment]
一样 等待修复

**Comment by ZedRover** [comment]
codesign --sign - --force --deep /Applications/WeChat.app
输入这个可以解决问题，但是打开微信后不能点击收藏，点击后会崩溃
