### ISSUE TITLE
Mac OS 11.3升级后微信闪退，卸载小助手后正常

### ISSUE THREAD

**Issue by MeLeo92** [MustangYM/WeChatExtension-ForMac#938]
### issue规范
- MacOS版本 : 11.3
- 微信版本 : 3.0.1 (17837)
- 小助手版本 : 2.8.3
- BUG描述 : 启动微信，mac系统提示恶意软件
- 操作场景 : 微信无法启动，系统直接弹出错误报告，提示恶意软件
- 方便的话提供日志, 截图或者视频(可选)
<img width="1036" alt="iShot2021-04-27 16 54 56" src="https://user-images.githubusercontent.com/16044509/116214920-c3a23100-a779-11eb-9497-838fd6d2978e.png">

**Comment by luozhaojie** [comment]
一样

**Comment by zhoujianjoe** [comment]
一样 等待修复

**Comment by yangnaihua** [comment]
一样 等待修复

**Comment by fenglangjunzi** [comment]
+1

**Comment by Kaiyan-Zhang** [comment]
+1

**Comment by JustDoItGit** [comment]
![image](https://user-images.githubusercontent.com/21060467/116398061-ee63b680-a859-11eb-8e01-9dfe9beaabbb.png)

**Comment by JustDoItGit** [comment]
https://github.com/MustangYM/WeChatExtension-ForMac/issues/932#issuecomment-827312059

**Comment by PurpleSweetPotatoes** [comment]
再命令行里运行下这个:
codesign --sign - --force --deep /Applications/WeChat.app

**Comment by mqliutie** [comment]
@PurpleSweetPotatoes  有效

**Comment by MasterBetter** [comment]
@PurpleSweetPotatoes 有效

**Comment by drowtram** [comment]
为什么我有这个提示？
Alee@bogon ~ % codesign --sign - --force --deep /Applications/WeChat.app
/Applications/WeChat.app: resource fork, Finder information, or similar detritus not allowed

**Comment by Char-CN** [comment]
@PurpleSweetPotatoes 有效

**Comment by supermebing** [comment]
用以下命令解决了

codesign -f -s - --deep /Applications/WeChat.app

**Comment by cat-walk** [comment]
> 再命令行里运行下这个:
> codesign --sign - --force --deep /Applications/WeChat.app

可行，但想问一下跑这条命令后会不会有什么副作用？ 比如给 微信客户端 过高的权限？
