### ISSUE TITLE
mac11.3下微信3.0失效闪退，需要更新

### ISSUE THREAD

**Issue by wq22304** [MustangYM/WeChatExtension-ForMac#939]
mac11.3下微信3.0失效闪退，需要更新

**Comment by yangnaihua** [comment]
+1

**Comment by fenglangjunzi** [comment]
+1

**Comment by zcx86ok** [comment]
1、卸载助手 own un
2、重新安装 own -n
3、codesign --sign - --force --deep /Applications/WeChat.app 签名

**Comment by wq22304** [comment]
> 1、卸载助手 omw un
> 2、重新安装 omw -n
> 3、codesign --sign - --force --deep /Applications/WeChat.app 签名

搞定了，自签下搞定了
