### ISSUE TITLE
撤回功能无效

### ISSUE THREAD

**Issue by wyfang** [MustangYM/WeChatExtension-ForMac#940]
### issue规范
- MacOS版本 : 11.2.3
- 微信版本 : Version. 3.0.2 (18006) Beta 9
- 小助手版本 : 2.8.3
- BUG描述 : 撤回功能无效
- 操作场景 : 自己、其他好友、群撤回消息后提示被撤回，但无内容。
![QQ20210428-140948](https://user-images.githubusercontent.com/17900420/116354729-69fa3f00-a82b-11eb-8ec7-ef76e3316719.png)

**Comment by ikakaxi** [comment]
我是 Version. 3.0.2 (18028)
撤回功能无效

**Comment by ikakaxi** [comment]
小助手版本 : 2.8.3

**Comment by DeepinGH** [comment]
+1，遇到无效问题。

**Comment by wyq09** [comment]
我是 Version. 3.0.2 (18028)
撤回功能无效
+1
+1
+1

**Comment by ucstone** [comment]
+1

**Comment by SunRui-cpu** [comment]
+1+1
升级微信后防撤回功能木有了

**Comment by Biobin** [comment]
+1， 难受

**Comment by Biobin** [comment]
+1，MacOS Catalina 10.15.5

**Comment by lifeva** [comment]
+1 macos11.3 wechat 3.0.2

**Comment by Lee66** [comment]
MacOS版本 : 10.13.6
微信版本 : Version. 3.0.2 (18006) Beta 9
小助手版本 : 2.8.3

**Comment by UJohn** [comment]
Version. 3.0.0 (17842)保留该版本，可以继续使用撤回功能

**Comment by Lee66** [comment]
> 17842

去哪下载这个版本，有没有下载地址

**Comment by FlameMida** [comment]
确实更新3.0.2后无效了

**Comment by LiruiErnest** [comment]
可以在商店里下载3.0.1的版本继续使用撤回功能

**Comment by hp0912** [comment]
> Version. 3.0.0 (17842)保留该版本，可以继续使用撤回功能

谁有这个版本的安装包啊，提供一个呗

**Comment by JackySunHN** [comment]
> MacOS版本 : 10.13.6
> 微信版本 : Version. 3.0.2 (18006) Beta 9
> 小助手版本 : 2.8.3

说明文档不是说了系统最低10.14吗

**Comment by JackySunHN** [comment]
> > Version. 3.0.0 (17842)保留该版本，可以继续使用撤回功能
> 
> 谁有这个版本的安装包啊，提供一个呗

3.0.0查收 链接: https://pan.baidu.com/s/1rUTdn_2nnnUKtjFshJhgFA  密码: dl2e

**Comment by hp0912** [comment]
> > > Version. 3.0.0 (17842)保留该版本，可以继续使用撤回功能
> > 
> > 
> > 谁有这个版本的安装包啊，提供一个呗
> 
> 3.0.0查收 链接: https://pan.baidu.com/s/1rUTdn_2nnnUKtjFshJhgFA 密码: dl2e

谢谢~~~

**Comment by holdthebreath** [comment]
> > > Version. 3.0.0 (17842)保留该版本，可以继续使用撤回功能
> > 
> > 
> > 谁有这个版本的安装包啊，提供一个呗
> 
> 3.0.0查收 链接: https://pan.baidu.com/s/1rUTdn_2nnnUKtjFshJhgFA 密码: dl2e

瑞思拜！
