### ISSUE TITLE
mac更新到11.3版本，使用小助手后无法打开微信

### ISSUE THREAD

**Issue by Soulmate7** [MustangYM/WeChatExtension-ForMac#942]
### issue规范
- MacOS版本 : 11.3
- 微信版本 : 3.0.1
- 小助手版本 : 2.1.1
- BUG描述 : 打开微信，系统提示微信不安全，无法打开。如果删除小助手，则可以打开
- 操作场景 : 点击微信启动
- 报错：“微信”已被阻止，因为它可能暴露您的隐私并降低Mac的安全性。 您应该将它移到废纸篓。
- 
![image](https://user-images.githubusercontent.com/48000788/116634309-3e439a00-a98e-11eb-8b42-ec9dbb151814.png)

**Comment by stevenliuit** [comment]
我重新安装的微信加小助手 好了

**Comment by Soulmate7** [comment]
已解决
方法：卸载微信小助手，并重新安装，就没有问题了
安装命令：sudo rm -r -f WeChatExtension-ForMac && git clone --depth=1 https://github.com/MustangYM/WeChatExtension-ForMac && cd WeChatExtension-ForMac/WeChatExtension/Rely && ./Install.sh && cd ~

**Comment by vcfger** [comment]
按照以上方法依旧无法打开
提示“微信.app”因为出现问题而无法打开

**Comment by vcfger** [comment]
> 按照以上方法依旧无法打开
> 提示“微信.app”因为出现问题而无法打开

参照此方案解决了https://github.com/MustangYM/WeChatExtension-ForMac/issues/938#issuecomment-828497657

**Comment by ernestyao** [comment]
11.3的时候是重装了小助手后恢复，今天11.3.1不能用这个方法解决，必须卸载微信后重装

**Comment by kong36088** [comment]
codesign -f -s - --deep /Applications/WeChat.app

亲测可行

**Comment by Lupeiwen0** [comment]
> 11.3的时候是重装了小助手后恢复，今天11.3.1不能用这个方法解决，必须卸载微信后重装

卸载小助手 卸载微信  重新安装

**Comment by linguo2625469** [comment]
> 命令行下执行：
> 
> ```shell
> codesign -f -s - --deep /Applications/WeChat.app
> ```
> 
> 亲测可行

今天重启电脑后执行此命令无效
