### ISSUE TITLE
现在除了免认证登录，已经没有任何可用功能了

### ISSUE THREAD

**Issue by lifeva** [MustangYM/WeChatExtension-ForMac#945]
### issue规范
- MacOS版本 : 11.3.1
- 微信版本 : 3.0.2
- 小助手版本 : 2.8.3
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

撤回也没有用了，小助手基本废了。

**Comment by AndrewTseZhou** [comment]
同~ 求大佬更新🙏🏻

**Comment by Lupeiwen0** [comment]
微信卸载，删除残留数据 重新安装 就好了主题 不行

**Comment by MustangYM** [comment]
[v2.8.4](https://github.com/MustangYM/WeChatExtension-ForMac/releases/tag/v2.8.4)
