### ISSUE TITLE
请问这个工具能否检测僵尸好友？

### ISSUE THREAD

**Issue by xuya227939** [MustangYM/WeChatExtension-ForMac#946]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)

**Comment by PandaZyD** [comment]
因检测单向好友功能容易骚扰到双向好友用户,此功能已暂停使用

**Comment by xuya227939** [comment]
@PandaZyD 这个逻辑不有问题吗？是否选择骚扰到双向好友用户，可以让使用方自行决定吧？

**Comment by MustangYM** [comment]
> @PandaZyD 这个逻辑不有问题吗？是否选择骚扰到双向好友用户，可以让使用方自行决定吧？

这个检测本身就是黑盒, 你根本不知道谁是双向谁是单向, 不然还检测什么?
