### ISSUE TITLE
微信3.0.2拦截无效，系统Big Sur 11.3.1，

### ISSUE THREAD

**Issue by HelloWilliam** [MustangYM/WeChatExtension-ForMac#947]
### issue规范
- MacOS版本 : 11.3.1
- 微信版本 : 3.0.2
- 小助手版本 : 2.8.3
- BUG描述 : 消息拦截无效
- 操作场景 : 别人撤回消息，拦截不了

**Comment by is-idea** [comment]
+1
借楼求一个微信的历史版本

**Comment by pistoolster** [comment]
+1

**Comment by mifanj** [comment]
+1

**Comment by Gang679** [comment]
MacOS版本 : 11.2.3
微信版本 : 3.0.2
小助手版本 : 2.8.3
BUG描述 : 消息拦截无效
操作场景 : 别人撤回消息，拦截不了

**Comment by wenwenwen888** [comment]
+1

**Comment by LAnqxpp** [comment]
mac : 11.3.1

vx : Version. 3.0.3 (18062)

+1

**Comment by wicked-wei** [comment]
我也遇到了拦截无效的问题。找了一圈，这里还有2.6.1版的可以下载：https://www.bear20.com/macsoft/2551/440002255.html 网页右边的历史版本。因为是第三方下载站，风险自己评估吧。

**Comment by SevenThreeX** [comment]
+1

**Comment by xuedygaga** [comment]
+1

**Comment by Joilence** [comment]
> https://stern.codes/1.7z 发一个可以刷朋友圈，可以拦截撤回的3.0.0Beta版本

这个版本，我 macOS 11.3.1, 然后通过 omw 安装，无法启动 WeChat。

**Comment by missuo** [comment]
> > https://stern.codes/1.7z 发一个可以刷朋友圈，可以拦截撤回的3.0.0Beta版本
> 
> 这个版本，我 macOS 11.3.1, 然后通过 omw 安装，无法启动 WeChat。

git clone 然后cd到目录下，把Install.sh 拖到终端里 回车

**Comment by Joilence** [comment]
> > https://stern.codes/1.7z 发一个可以刷朋友圈，可以拦截撤回的3.0.0Beta版本
> 
> 这个版本，我 macOS 11.3.1, 然后通过 omw 安装，无法启动 WeChat。

签名问题，通过 `codesign -f -s - --deep /Applications/WeChat.app` 解决。 @missuo
