### ISSUE TITLE
配合alfred后不能显示微信头像

### ISSUE THREAD

**Issue by ImNobody422** [MustangYM/WeChatExtension-ForMac#96]
<img width="556" alt="Screen Shot 2019-09-27 at 16 51 01" src="https://user-images.githubusercontent.com/43682501/65801536-4fd81680-e147-11e9-8a83-5e6d006a72f9.png">

**Comment by ImNobody422** [comment]
刚更新到Alfred 4，删除了之前所有alfred内容，从头配置alfred。重新下载了wechat-alfred-workflow，配合1.9.6版本的小助手与2.3.26的wechat不能显示头像。

**Comment by Jax0rz** [comment]
Same problem here.

**Comment by MustangYM** [comment]
Alfred的问题嘛, 因为我本身是不太用这个功能的, 所以一直没有去管...

**Comment by Magus4756** [comment]
我用 wx workflow 调用插件接口：
http://127.0.0.1:52700/wechat-plugin/user?keyword={keyword}
返回的 icon 路径是：
/Users/magus/Library/Containers/com.tencent.xinWeChat/Data/Library/Containers/com.tencent.xinWeChat/Data/Library/Caches/com.tencent.xinWeChat/2.0b4.0.9/29903834bd9430d1fde446954ee1a012/avatar
但是头像正确的路径是：
/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/29903834bd9430d1fde446954ee1a012/Avatar
微信版本 2.3.27 (12843)，插件版本 1.9.7

**Comment by Magus4756** [comment]
wx workflow 运行时会调用插件接口：
http://127.0.0.1:52700/wechat-plugin/user?keyword={keyword}
我手动看了一下，返回的 icon 路径是：
/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Containers/com.tencent.xinWeChat/Data/Library/Caches/com.tencent.xinWeChat/2.0b4.0.9/29903834bd9430d1fde446954ee1a012/avatar
但是头像正确的路径是：
/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/29903834bd9430d1fde446954ee1a012/Avatar
微信版本 2.3.27 (12843)，插件版本 1.9.7
这应该是微信小插件的问题。。

**Comment by MartinYuan1995** [comment]
求更新头像

**Comment by MustangYM** [comment]
> wx工作流运行时会调用插件接口：
> [http](http://127.0.0.1:52700/wechat-plugin/user?keyword=%7Bkeyword%7D) : [//127.0.0.1](http://127.0.0.1:52700/wechat-plugin/user?keyword=%7Bkeyword%7D) :52700/wechat-plugin/user?keyword [={](http://127.0.0.1:52700/wechat-plugin/user?keyword=%7Bkeyword%7D) keyword [}](http://127.0.0.1:52700/wechat-plugin/user?keyword=%7Bkeyword%7D)
> 我手动看了一下，返回的icon路径是：
> / Users / {username} / Library /Containers/com.tencent.xinWeChat/Data/Library/Containers/com.tencent.xinWeChat/Data/Library/Caches/com.tencent.xinWeChat/2.0b4.0.9/29903834bd9430d1fde446954ee1a012/avatar但看起来
> 正确的路径是：
> / Users /{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support / com.tencent.xinWeChat / 2.0b4.0.9 / 29903834bd9430d1fde446954ee1a012 / Avatar
> 微信版本2.3.27（12843），插件版本1.9.7
> 这应该是微信小插件的问题..

已修复1.9.8

**Comment by MustangYM** [comment]
> 这里同样的问题。

已修复1.9.8

**Comment by MustangYM** [comment]
> 刚更新到Alfred 4，删除了之前所有alfred内容，从头配置alfred。重新下载了wechat-alfred-workflow，配合1.9.6版本的小助手与2.3.26的wechat不能显示头像。

已修复1.9.8

**Comment by MustangYM** [comment]
> 刚更新到Alfred 4，删除了之前所有alfred内容，从头配置alfred。重新下载了wechat-alfred-workflow，配合1.9.6版本的小助手与2.3.26的wechat不能显示头像。

已修复1.9.8

**Comment by mingjun97** [comment]
我的Mac是大小写敏感的分区格式，1.9.8仍然不能工作。返回的路径是
`/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/3b9ccac508a2bff0708f04ed616fd827/avatar/`
能够正常工作的路径是
`/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/3b9ccac508a2bff0708f04ed616fd827/Avatar/`
这个路径中的Avatar也需要大写才能正常工作。

**Comment by mingjun97** [comment]
fork了之后做了如下更改
```diff
diff --git a/WeChatExtension/WeChatExtension/Sources/Managers/TKCacheManager.m b/WeChatExtension/WeChatExtension/Sources/Managers/TKCacheManager.m
index 5d58756..f26e10b 100755
--- a/WeChatExtension/WeChatExtension/Sources/Managers/TKCacheManager.m
+++ b/WeChatExtension/WeChatExtension/Sources/Managers/TKCacheManager.m
@@ -132,7 +132,7 @@ - (NSString *)cacheAvatarWithContact:(WCContactData *)contact {
         MMAvatarService *avatarService = [[objc_getClass("MMServiceCenter") defaultCenter] getService:objc_getClass("MMAvatarService")];

         NSString *userCache =  [objc_getClass("PathUtility") GetCurUserDocumentPath];
-        imgPath = [NSString stringWithFormat:@"%@/avatar/%@",userCache, imgMd5Str];
+        imgPath = [NSString stringWithFormat:@"%@/Avatar/%@",userCache, imgMd5Str];

         NSFileManager *fileMgr = [NSFileManager defaultManager];
         if (imgPath && ![fileMgr fileExistsAtPath:imgPath] && ![self.avatarSet containsObject:imgPath]) {
```
重新编译，之后重新安装好像也没有修复。

最后用如下指令临时修复。
```shell
perl -pi -e "s/\/avatar\//\/Avatar\//g" .//Rely/Plugin/WeChatExtension/WeChatExtension.framework/Versions/Current/WeChatExtension             perl -pi -e "s/\/avatar\//\/Avatar\//g" .//Rely/Plugin/WeChatExtension/WeChatExtension.framework/Versions/A/WeChatExtension
perl -pi -e "s/\/avatar\//\/Avatar\//g" .//Rely/Plugin/WeChatExtension/WeChatExtension.framework/WeChatExtension                              130 ↵
perl -pi -e "s/\/avatar\//\/Avatar\//g" .//Rely/OnLineUpdate/WeChatExtension-MacOS-1.8.0/WeChatExtension.framework/Versions/Current/WeChatExtension
perl -pi -e "s/\/avatar\//\/Avatar\//g" .//Rely/OnLineUpdate/WeChatExtension-MacOS-1.8.0/WeChatExtension.framework/Versions/A/WeChatExtension
perl -pi -e "s/\/avatar\//\/Avatar\//g" .//Rely/OnLineUpdate/WeChatExtension-MacOS-1.8.0/WeChatExtension.framework/WeChatExtension
```

**Comment by MustangYM** [comment]
> 我的Mac是大小写敏感的分区格式，1.9.8仍然不能工作。返回的路径是
> `/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/3b9ccac508a2bff0708f04ed616fd827/avatar/`
> 能够正常工作的路径是
> `/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/3b9ccac508a2bff0708f04ed616fd827/Avatar/`
> 这个路径中的Avatar也需要大写才能正常工作。
> 
> 发起了一个PR， #120

我没有针对路径做任何特殊修改, 直接使用的微信的接口, 你这个改动看起来并不是这么安全. 可能会导致别的用户出问题.

**Comment by MustangYM** [comment]
> 我的Mac是大小写敏感的分区格式，1.9.8仍然不能工作。返回的路径是
> `/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/3b9ccac508a2bff0708f04ed616fd827/avatar/`
> 能够正常工作的路径是
> `/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/3b9ccac508a2bff0708f04ed616fd827/Avatar/`
> 这个路径中的Avatar也需要大写才能正常工作。
> 
> 发起了一个PR， #120

你这个改动看起来并不安全, 如果有API区分这两种Mac 的话能这么改, 因为你无法保证在别的Mac上不出问题,.

**Comment by mingjun97** [comment]
> > 我的Mac是大小写敏感的分区格式，1.9.8仍然不能工作。返回的路径是
> > `/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/3b9ccac508a2bff0708f04ed616fd827/avatar/`
> > 能够正常工作的路径是
> > `/Users/{username}/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/3b9ccac508a2bff0708f04ed616fd827/Avatar/`
> > 这个路径中的Avatar也需要大写才能正常工作。
> > 发起了一个PR， #120
> 
> 你这个改动看起来并不安全, 如果有API区分这两种Mac 的话能这么改, 因为你无法保证在别的Mac上不出问题,.

大小写不敏感的分区对于avatar或Avatar并不作区分，这个改动对其使用没有任何影响，这也是case-insensitive的特性。
默认api输出的头像就是在Avatar而非avatar目录下的，保留原来的对avatar提供链接的代码才是不安全的。
区分大小写敏感与否的API的确是存在，但是这里没太有必要使用。
或者可以写到Install.sh文件内，判断微信cache所在的分区为case-sensitive时直接将binary文件内的字符串替换。（我自己尝试以替换binary中的字符串的形式打的patch是能用的）。
