### ISSUE TITLE
上帝模式是指？

### ISSUE THREAD

**Issue by Cat7373** [MustangYM/WeChatExtension-ForMac#967]
- MacOS版本 : 无需
- 微信版本 : 无需
- 小助手版本 : 2.8.4
- BUG描述 : 无
- 操作场景 : 无

希望介绍下 Release Note 中的上帝模式

**Comment by BruceChao** [comment]
是皮肤，除了聊天文字，窗口全透明～

**Comment by Cat7373** [comment]
好的，谢谢解答，建议在 Release Note 或 readme 中介绍下，避免其它人有同样的疑惑
