### ISSUE TITLE
在群聊里撤回链接后 拦截发送到手机的内容不对

### ISSUE THREAD

**Issue by liweiBingo** [MustangYM/WeChatExtension-ForMac#97]
版本1.9.6  
别人在群里发https://mp.weixin.qq.com/s/foG9R4nzm6JTiCH4vt25cQ链接 然后撤回  发送到手机之后是

--拦截到一条撤回消息--
群名:爱国者
撤回人:佟x
内容:https

链接只剩https头

**Comment by MustangYM** [comment]
> 版本1.9.6
> 别人在群里发[https://mp.weixin.qq.com/s/foG9R4nzm6JTiCH4vt25cQ链接](https://mp.weixin.qq.com/s/foG9R4nzm6JTiCH4vt25cQ%E9%93%BE%E6%8E%A5) 然后撤回 发送到手机之后是
> 
> --拦截到一条撤回消息--
> 群名:爱国者
> 撤回人:佟x
> 内容:https
> 
> 链接只剩https头

哈哈, 不支持这种类型的消息撤回... 我瞧一瞧

**Comment by MustangYM** [comment]
> 版本1.9.6
> 别人在群里发[https://mp.weixin.qq.com/s/foG9R4nzm6JTiCH4vt25cQ链接](https://mp.weixin.qq.com/s/foG9R4nzm6JTiCH4vt25cQ%E9%93%BE%E6%8E%A5) 然后撤回 发送到手机之后是
> 
> --拦截到一条撤回消息--
> 群名:爱国者
> 撤回人:佟x
> 内容:https
> 
> 链接只剩https头
