### ISSUE TITLE
Mac提示安全问题，直接打不开微信了

### ISSUE THREAD

**Issue by PayneSnow** [MustangYM/WeChatExtension-ForMac#971]
mac  big sur 11.4
微信 3.03
小助手：最新版本
bug：Mac提示安全问题，直接打不开微信了，提示应该将微信移到废纸篓
场景：前一天晚上安装正常使用。第二天开机后直接打不开微信了。

**Comment by PayneSnow** [comment]
提示：“微信”已被阻止，因为它可能暴露您的隐私并降低Mac的安全性。 您应该将它移到废纸篓。

**Comment by PayneSnow** [comment]
Process:               WeChat [2143]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               3.0.3 (18062)
App Item ID:           836500024
App External ID:       842122633
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [2143]
User ID:               501

Date/Time:             2021-05-17 09:36:20.015 +0800
OS Version:            macOS 11.4 (20F5046g)
Report Version:        12
Anonymous UUID:        95104F46-461A-6DED-774F-E765BEAB7D2A


Time Awake Since Boot: 4100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature in (/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension) not valid for use in process using Library Validation: library load denied by system policy
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature in (/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension) not valid for use in process using Library Validation: library load denied by system policy

Binary Images:
       0x106bf0000 -        0x10b552fff +com.tencent.xinWeChat (3.0.3 - 18062) <FAEF7490-F5E9-3251-890E-83B2285449E6> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x10cd88000 -        0x10d2a7fff +com.tencent.ilinknetwork (1.1.4 - 1.1.4) <CD5ADA11-BB16-3650-B832-8C4C1A13770A> /Applications/WeChat.app/Contents/Frameworks/ilink_network.framework/Versions/A/ilink_network
       0x10d310000 -        0x10d450fff +com.tencent.WCDB (1.0.3 - 1) <92D82082-291C-3B99-B517-C771D4C23ADD> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x10d4e8000 -        0x10d4edfff +com.tencent.MMLibHooks (1.0 - 1) <5901B561-6343-33D6-924A-43368BBD16F5> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x10d4fc000 -        0x10d51efff +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x10d557000 -        0x10d579fff +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x10d5ba000 -        0x10d65afff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x1113a1000 -        0x11143cfff  dyld (851.27) <EFF77E58-5288-3D3B-BC86-FE19ED311A6D> /usr/lib/dyld
    0x7fff201a8000 -     0x7fff201e1fff  libobjc.A.dylib (824) <A748A813-033F-33E8-AD85-4DA9A6E4199C> /usr/lib/libobjc.A.dylib
    0x7fff2026e000 -     0x7fff202c3fff  libc++.1.dylib (905.6) <8ED8A355-9FD3-3622-A3F1-C372A8A38EDF> /usr/lib/libc++.1.dylib
    0x7fff20388000 -     0x7fff20825fff  com.apple.CoreFoundation (6.9 - 1776.101) <E94D37A4-B1B6-3B5A-8F0A-CA3722D2BF38> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff20e48000 -     0x7fff20ec5fff  com.apple.SystemConfiguration (1.20 - 1.20) <DAA39F6E-6090-3BC6-A971-A95B75D901AE> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff21134000 -     0x7fff21491fff  com.apple.Foundation (6.9 - 1776.101) <CFC79DAA-E2E7-372A-B969-3822A74C022C> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff2191d000 -     0x7fff21b01fff  com.apple.CoreText (677.5.0.3 - 677.5.0.3) <5A5C3E1F-4162-3473-9422-62961EFCE6C9> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff21b02000 -     0x7fff22192fff  com.apple.audio.CoreAudio (5.0 - 5.0) <62E2BC47-C1E2-33F2-A174-BDBF4E6B04AB> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff22193000 -     0x7fff224e7fff  com.apple.security (7.0 - 59754.120.9) <38D8B7E1-9C76-339D-AABC-848A110A648C> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff224e8000 -     0x7fff22747fff  libicucore.A.dylib (66112) <DE9834AD-0D48-3F64-BA6D-99302843FB6A> /usr/lib/libicucore.A.dylib
    0x7fff22ab8000 -     0x7fff22b66fff  com.apple.framework.IOKit (2.0.2 - 1845.120.5) <17F38D5E-5952-3BC6-BA28-5AFF12F12021> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff22bc1000 -     0x7fff23908fff  com.apple.AppKit (6.9 - 2022.50.104) <51CDCF65-DF88-3E8F-8107-41DCA9358A2B> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff24655000 -     0x7fff24af3fff  com.apple.CFNetwork (1240.0.1 - 1240.0.1) <FCFC0DD7-963F-3601-9C1B-C92DEF1A0ED0> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff24ef4000 -     0x7fff2557dfff  com.apple.CoreGraphics (2.0 - 1463.14.2) <B43C23A6-9D4E-37D7-A122-5333FA1192E1> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff26b52000 -     0x7fff26e2efff  com.apple.QuartzCore (1.11 - 927.18) <17195449-45C2-3CD4-9601-75519DABA2C8> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff27153000 -     0x7fff27235fff  libxml2.2.dylib (34.9) <1D8D86C3-DF10-3F4E-86E2-53B374AC6CC2> /usr/lib/libxml2.2.dylib
    0x7fff27236000 -     0x7fff27283fff  com.apple.CoreVideo (1.8 - 414.7) <D8F403D3-0021-3F94-B7BE-58AD612389F9> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff281c1000 -     0x7fff2823dfff  com.apple.corelocation (2420.19.23 - 2420.19.23) <2F2C9171-B8E0-3BE2-A8C2-50150DB2E808> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff283ac000 -     0x7fff2853afff  com.apple.CoreMedia (1.0 - 2775.15.4.1) <0D9EC4BE-A974-30ED-B673-74C04CC4A85B> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff289da000 -     0x7fff28c15fff  com.apple.ImageIO (3.3.0 - 2130.4.7) <0B300043-9725-3284-AE43-6BD1A5B682B3> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff2994f000 -     0x7fff29a21fff  com.apple.framework.CoreWLAN (16.0 - 1657) <4A5EA914-5569-3632-B2D3-59820448FFE2> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff29cee000 -     0x7fff29cf2fff  com.apple.xpc.ServiceManagement (1.0 - 1) <68E3B6BC-D640-373A-B806-8FA6ABDE32E5> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff2a291000 -     0x7fff2a29dfff  libbz2.1.0.dylib (44) <04BEE5C2-4894-3C7F-87AA-566A6438D5BA> /usr/lib/libbz2.1.0.dylib
    0x7fff2a49f000 -     0x7fff2a4b1fff  libz.1.dylib (76) <D260A5C5-1245-3BAE-9611-46414F6BAF2B> /usr/lib/libz.1.dylib
    0x7fff2a567000 -     0x7fff2a568fff  libSystem.B.dylib (1292.120.1) <3F0702D0-CDFF-352F-B3EC-C068E4B15713> /usr/lib/libSystem.B.dylib
    0x7fff2a5a6000 -     0x7fff2a696fff  libiconv.2.dylib (59) <20D1638F-6730-3E19-9086-4C10E616D742> /usr/lib/libiconv.2.dylib
    0x7fff2bac2000 -     0x7fff2bc7ffff  com.apple.VideoToolbox (1.0 - 2775.15.4.1) <237F4FFB-64DD-3183-8519-17E98926E31F> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff2cba2000 -     0x7fff2cf78fff  libswiftCore.dylib (5.4 - 1205.0.24.14) <038F16DC-A7BA-358D-8972-670ACF7BE7EA> /usr/lib/swift/libswiftCore.dylib
    0x7fff2d03b000 -     0x7fff2d153fff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <DDD71FBD-49EF-3943-BD00-9A7B73821789> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2d24a000 -     0x7fff2d262fff  libresolv.9.dylib (68) <0397C552-2FD1-38EB-9E85-A4191D82F8F2> /usr/lib/libresolv.9.dylib
    0x7fff2e87b000 -     0x7fff2e8dafff  com.apple.QuickLookFramework (5.0 - 928.3) <C3DBC537-E91E-33F8-8DC0-C191377C86B8> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff3033d000 -     0x7fff3033dfff  com.apple.CoreServices (1122.36 - 1122.36) <E4391037-5A02-31FD-A9A1-8D6D0C5EA46E> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff304f8000 -     0x7fff304f8fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <2BCB5475-FDEF-379A-BB0E-B1A3AA7F5B83> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff30887000 -     0x7fff309dffff  libswiftFoundation.dylib (25.102) <CDC63EB0-C296-3655-8C76-58DDE103C870> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff31946000 -     0x7fff3195bfff  libswiftDispatch.dylib (4.100.1) <43DCC1E0-1BDA-3611-A799-F1730E0740F0> /usr/lib/swift/libswiftDispatch.dylib
    0x7fff33910000 -     0x7fff33910fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <DF409F22-42FC-376F-AAA0-46EE9F6F6CBE> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff33997000 -     0x7fff33998fff  libswiftObjectiveC.dylib (3) <8923E676-C2A1-3358-9F75-19978DA19BDB> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff35335000 -     0x7fff35338fff  com.apple.Cocoa (6.11 - 23) <FD1AEC22-74D6-3B64-8EC4-31CF40B38C92> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff367dc000 -     0x7fff379c8fff  com.apple.JavaScriptCore (16611 - 16611.2.3) <87A8489B-85D8-3AF1-83C8-3FC6BFF0731D> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff3c331000 -     0x7fff3c33bfff  libswiftCoreGraphics.dylib (2) <6DE21D10-7200-38AD-8336-C1C45CA9C9A6> /usr/lib/swift/libswiftCoreGraphics.dylib
    0x7fff3c33c000 -     0x7fff3c345fff  libswiftDarwin.dylib (??? - ???) <83E42D26-551D-3355-B152-0384E32551BF> /usr/lib/swift/libswiftDarwin.dylib
    0x7fff3c3e1000 -     0x7fff3cbbcfff  com.apple.WebKit (16611 - 16611.2.3) <155536FF-D085-3C59-B01C-310398F6B5BB> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff3cd73000 -     0x7fff3cd76fff  com.apple.Carbon (160 - 164) <6D8F45DF-15AD-3D69-BC18-51AD2A5A81BC> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3ce6f000 -     0x7fff3ce6ffff  com.apple.avfoundation (2.0 - 2015.15) <F5C99475-D36C-3590-BA39-8FE6C63C4F28> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff3ce70000 -     0x7fff3cf8afff  com.apple.AVKit (1.1 - 732.4.8) <70A1B4E9-179E-3BF0-818F-2925DC21C5F6> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff3d99b000 -     0x7fff3d9a3fff  libswiftCoreAudio.dylib (1.1) <103BE4EB-C81A-3899-8425-B51059ED9BA3> /usr/lib/swift/libswiftCoreAudio.dylib
    0x7fff3d9a4000 -     0x7fff3d9a4fff  libswiftCoreFoundation.dylib (1.6) <64B22520-ECCA-30ED-91A7-C9089C9F02DC> /usr/lib/swift/libswiftCoreFoundation.dylib
    0x7fff3d9b0000 -     0x7fff3d9b0fff  libswiftXPC.dylib (1.1) <041C9E9B-C7D9-3A73-89EA-78327319B0CF> /usr/lib/swift/libswiftXPC.dylib
    0x7fff3d9b1000 -     0x7fff3d9b1fff  libswiftCoreImage.dylib (1) <58B2D71A-0024-32DD-92EA-B379A98FDFC9> /usr/lib/swift/libswiftCoreImage.dylib
    0x7fff3d9b2000 -     0x7fff3d9b2fff  libswiftIOKit.dylib (1) <64CFE49F-4B3C-3064-9A89-9CD5271F03F1> /usr/lib/swift/libswiftIOKit.dylib
    0x7fff3ff54000 -     0x7fff3ff6dfff  libswiftsimd.dylib (1.3) <C6CF6645-4A9D-3C7C-84B5-98DE1D68A695> /usr/lib/swift/libswiftsimd.dylib
    0x7fff411fb000 -     0x7fff411fefff  com.apple.quartzframework (1.5 - 25) <D7C56FEE-E302-3976-B186-9926B3544DAE> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff41642000 -     0x7fff41643fff  libswiftCoreLocation.dylib (5) <A682C55F-0544-393E-B787-2C81B611753E> /usr/lib/swift/libswiftCoreLocation.dylib
    0x7fff41f3d000 -     0x7fff41f41fff  libswiftCoreData.dylib (3) <A27A2A78-243C-3485-A924-D9564960D293> /usr/lib/swift/libswiftCoreData.dylib
    0x7fff46033000 -     0x7fff46038fff  libswiftMetal.dylib (1.3.1) <9485B9ED-E495-34B3-B6AC-2AA313410098> /usr/lib/swift/libswiftMetal.dylib
    0x7fff485ea000 -     0x7fff485fefff  libswiftAppKit.dylib (104) <64AFC649-8396-38D6-85D5-1B0B54960F0B> /usr/lib/swift/libswiftAppKit.dylib
    0x7fff485ff000 -     0x7fff48600fff  libswiftQuartzCore.dylib (1) <F695B421-96D2-36CC-91C8-262413FAAC81> /usr/lib/swift/libswiftQuartzCore.dylib
    0x7fff4e5cb000 -     0x7fff4e603fff  libswiftCoreMedia.dylib (1) <D11B1921-3ADC-3D45-A6E1-E4FB3F9288BF> /usr/lib/swift/libswiftCoreMedia.dylib
    0x7fff4f163000 -     0x7fff4f169fff  libswiftAVFoundation.dylib (2015.15) <ABA13BA4-5B28-379E-94A1-C41F4C96F658> /usr/lib/swift/libswiftAVFoundation.dylib
    0x7fff6beba000 -     0x7fff6bec9fff  com.apple.opengl (18.5.8 - 18.5.8) <601456C6-07B8-33E1-9CD2-DF19A8F77A04> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6ee86000 -     0x7fff6eec8fff  com.apple.MultipeerConnectivity (172 - 172) <E452E3F1-99A4-396E-B7B3-06AAE7128158> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff6ef0e000 -     0x7fff6ef30fff  com.apple.audio.OpenAL (1.8 - 1.8) <2076F849-770C-3FC5-B2F2-89BDC8DF1D90> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL

Model: MacBookAir7,2, BootROM 427.0.0.0.0, 2 processors, Dual-Core Intel Core i7, 2.2 GHz, 8 GB, SMC 2.27f2
Graphics: kHW_IntelHDGraphics6000Item, Intel HD Graphics 6000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.8)
Bluetooth: Version 8.0.5d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: Internal Memory Card Reader
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

**Comment by acewong7** [comment]
sudo codesign --sign - --force --deep /Applications/WeChat.app

解决了

**Comment by Royage888** [comment]
打开简介->把覆盖恶意软件保护打开
<img width="262" alt="截屏2021-05-17 上午10 15 47" src="https://user-images.githubusercontent.com/56480821/118424033-f2685300-b6f8-11eb-9610-5652eadf4e92.png">

**Comment by zichenJack** [comment]
重签名即可 sudo codesign --sign - --force --deep /Applications/WeChat.app

**Comment by PayneSnow** [comment]
> 重签名即可 sudo codesign --sign - --force --deep /Applications/WeChat.app

怎么操作

**Comment by PayneSnow** [comment]
> 打开简介->把覆盖恶意软件保护打开
> <img alt="截屏2021-05-17 上午10 15 47" width="262" src="https://user-images.githubusercontent.com/56480821/118424033-f2685300-b6f8-11eb-9610-5652eadf4e92.png">

刚才由于打不开。我将微信卸载重新安装了。不过还没安装小助手。
打开简介后没有发现——把覆盖恶意软件保护 ——这个选项
如图
![截屏2021-05-17 10 24 25](https://user-images.githubusercontent.com/51922806/118424587-10828300-b6fa-11eb-9da4-58419c4f82fc.png)

**Comment by Royage888** [comment]
> > 打开简介->把覆盖恶意软件保护打开
> > <img alt="截屏2021-05-17 上午10 15 47" width="262" src="https://user-images.githubusercontent.com/56480821/118424033-f2685300-b6f8-11eb-9610-5652eadf4e92.png">
> 
> 刚才由于打不开。我将微信卸载重新安装了。不过还没安装小助手。
> 打开简介后没有发现——把覆盖恶意软件保护 ——这个选项
> 如图
> ![截屏2021-05-17 10 24 25](https://user-images.githubusercontent.com/51922806/118424587-10828300-b6fa-11eb-9da4-58419c4f82fc.png)

试试上面老哥的方法,把终端打开,把sudo codesign --sign - --force --deep /Applications/WeChat.app粘上

**Comment by PayneSnow** [comment]
> > > 打开简介->把覆盖恶意软件保护打开
> > > <img alt="截屏2021-05-17 上午10 15 47" width="262" src="https://user-images.githubusercontent.com/56480821/118424033-f2685300-b6f8-11eb-9610-5652eadf4e92.png">
> > 
> > 
> > 刚才由于打不开。我将微信卸载重新安装了。不过还没安装小助手。
> > 打开简介后没有发现——把覆盖恶意软件保护 ——这个选项
> > 如图
> > ![截屏2021-05-17 10 24 25](https://user-images.githubusercontent.com/51922806/118424587-10828300-b6fa-11eb-9da4-58419c4f82fc.png)
> 
> 试试上面老哥的方法,把终端打开,把sudo codesign --sign - --force --deep /Applications/WeChat.app粘上

哈哈，感谢两位指导。对于终端不会用。之前都是直接粘贴复制命令。刚粘贴了一下，显示command not found。是不是需要先安装小助手，再操作一遍？
![截屏2021-05-17 10 31 30](https://user-images.githubusercontent.com/51922806/118425119-0d3bc700-b6fb-11eb-8079-0b700e941aa3.png)

**Comment by PayneSnow** [comment]
> > 重签名即可 sudo codesign --sign - --force --deep /Applications/WeChat.app
> 
> 怎么操作

感谢您指点

**Comment by cat-walk** [comment]
> 打开简介->把覆盖恶意软件保护打开
> <img alt="截屏2021-05-17 上午10 15 47" width="262" src="https://user-images.githubusercontent.com/56480821/118424033-f2685300-b6f8-11eb-9610-5652eadf4e92.png">

macOS Big Sur 11.3.1，用你这个方法解决了，感谢， codesign 对我无效....

**Comment by dahhd** [comment]
如果对WeChat.app 签名不行的，单独针对WeChatExtension.framework进行重新签名即可，crash 日志里其实已经给出framework签名无效的提示了。

sudo codesign --sign - --force --deep /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension

**Comment by stephenlzc** [comment]
> 重签名即可 sudo codesign --sign - --force --deep /Applications/WeChat.app

已经尝试，但每次重新开机还会报『Mac提示安全问题，直接打不开微信了，提示应该将微信移到废纸篓』

**Comment by PayneSnow** [comment]
感谢指点


| |
pilgrim112
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年06月17日 23:56，Big ***@***.***> 写道：

重签名即可 sudo codesign --sign - --force --deep /Applications/WeChat.app

已经尝试，但每次重新开机还会报『Mac提示安全问题，直接打不开微信了，提示应该将微信移到废纸篓』
