### ISSUE TITLE
主题能整好看点吗？

### ISSUE THREAD

**Issue by DanteAndroid** [MustangYM/WeChatExtension-ForMac#972]
现在的几个主体好迷。。。颜色感觉很奇怪。如果能做的更好看一些就好了。甚至可以考虑付费

**Comment by MustangYM** [comment]
![image](https://user-images.githubusercontent.com/21478687/118440797-c78ef680-b71a-11eb-887d-c7e45b93848a.png)

这样, 先付费, 然后你给个设计图. 不然我不知道你认为的好看是什么
