### ISSUE TITLE
Version. 3.0.3 (18061)  -macOS 11.3.1 (20E241) 更新后出现闪退

### ISSUE THREAD

**Issue by changheluor007** [MustangYM/WeChatExtension-ForMac#977]
### issue规范
- MacOS版本 :  Big Sur 11.3.1 (20E241)
- 微信版本 : 3.0.3 (18061) 
- 小助手版本 :  最新版本（2.8.5）
- BUG描述 : 安装完后，点击启动微信，直接闪退了
- 操作场景 : 点击微信启动的时候直接闪退了，然后卸载小助手后就正常了

**Comment by MustangYM** [comment]
#816 提issue之前大致搜一下

**Comment by Arvay** [comment]
#971 这里也有
