### ISSUE TITLE
更新系统后闪退

### ISSUE THREAD

**Issue by Rudyy898** [MustangYM/WeChatExtension-ForMac#981]
### issue规范
- MacOS版本 : 10.xx.x
- 微信版本 : 2.x.x
- 小助手版本 : 2.x.x
- BUG描述 : 点击窗口闪退
- 操作场景 : 微信启动后, 鼠标左键点击会话列表中某个会话的头像
- 方便的话提供日志, 截图或者视频(可选)
Process:               WeChat [14426]
Path:                  /Applications/WeChat.app/Contents/MacOS/WeChat
Identifier:            com.tencent.xinWeChat
Version:               3.0.3 (18062)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WeChat [14426]
User ID:               501

Date/Time:             2021-05-18 16:09:25.170 +0800
OS Version:            macOS 11.3.1 (20E241)
Report Version:        12
Anonymous UUID:        656DA3FF-D094-6550-10F9-A8340D610FF5

Sleep/Wake UUID:       57C59436-ECFE-435E-A4FC-288B33855FA8

Time Awake Since Boot: 18000 seconds
Time Since Wake:       17000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension
  Referenced from: /Applications/WeChat.app/Contents/MacOS/WeChat
  Reason: no suitable image found.  Did find:
	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

	/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension: code signature invalid for '/Applications/WeChat.app/Contents/MacOS/WeChatExtension.framework/WeChatExtension'

Binary Images:
       0x1082ec000 -        0x10cc32fff +com.tencent.xinWeChat (3.0.3 - 18062) <BDBF599C-2249-3AE3-9BF0-F5BB2CC1ED62> /Applications/WeChat.app/Contents/MacOS/WeChat
       0x10e469000 -        0x10e4affff +org.sparkle-project.Sparkle (1.20.0 913-ge196a24d - 1.20.0) <50C08D08-2F05-3F4A-A50C-46CE14FD6420> /Applications/WeChat.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x10e520000 -        0x10ea3ffff +com.tencent.ilinknetwork (1.1.4 - 1.1.4) <CD5ADA11-BB16-3650-B832-8C4C1A13770A> /Applications/WeChat.app/Contents/Frameworks/ilink_network.framework/Versions/A/ilink_network
       0x10eaa8000 -        0x10ebe8fff +com.tencent.WCDB (1.0.3 - 1) <24379098-E876-38CE-9FB4-298C7A2CF1C6> /Applications/WeChat.app/Contents/Frameworks/WCDB.framework/Versions/A/WCDB
       0x10ed27000 -        0x10ed2cfff +com.tencent.MMLibHooks (1.0 - 1) <8CB22C47-F6B3-3EFA-997A-0B0851B035B6> /Applications/WeChat.app/Contents/Frameworks/MMLibHooks.framework/Versions/A/MMLibHooks
       0x10ed3f000 -        0x10ed61fff +com.deusty.CocoaLumberjack (2.3.0 - 1) <6BDB40E8-05DA-32DE-8C81-37632C48E80B> /Applications/WeChat.app/Contents/Frameworks/CocoaLumberjack.framework/Versions/A/CocoaLumberjack
       0x10ed9a000 -        0x10edbcfff +com.alamofire.AFNetworking (3.0.0 - 3.1.0) <BDD10371-3F15-3EF9-A0A7-E80EAC53ADF6> /Applications/WeChat.app/Contents/Frameworks/AFNetworking.framework/Versions/A/AFNetworking
       0x10edfb000 -        0x10ee9bfff +tencent.matrixreport (1.0 - 1) <2586BD60-1797-3862-B461-CA38A7E71FAA> /Applications/WeChat.app/Contents/Frameworks/matrixreport.framework/Versions/A/matrixreport
       0x112528000 -        0x1125c3fff  dyld (851.27) <7EAA668B-F906-3BAA-A980-139BBE6E8766> /usr/lib/dyld
    0x7fff205fb000 -     0x7fff20634fff  libobjc.A.dylib (824) <929E3040-4605-3C14-885B-D742EF02F2CB> /usr/lib/libobjc.A.dylib
    0x7fff206c1000 -     0x7fff20716fff  libc++.1.dylib (905.6) <B027735F-B398-381C-84A7-606D7BBE4997> /usr/lib/libc++.1.dylib
    0x7fff207db000 -     0x7fff20c78fff  com.apple.CoreFoundation (6.9 - 1775.118.101) <895AFD1C-0307-32B3-81CB-BA33DA368DE1> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff21299000 -     0x7fff21316fff  com.apple.SystemConfiguration (1.20 - 1.20) <BEDC3BFB-D680-3E56-9A3A-2FAB181C52A9> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff21585000 -     0x7fff218e2fff  com.apple.Foundation (6.9 - 1775.118.101) <5B112EDB-35C1-31A7-BFDA-E185D1B49D93> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff21d74000 -     0x7fff21f58fff  com.apple.CoreText (677.4.0.4 - 677.4.0.4) <F65330BD-9D48-3DE5-9E6B-1232B5BDB656> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff21f59000 -     0x7fff225e9fff  com.apple.audio.CoreAudio (5.0 - 5.0) <68667A4E-B4BC-3DF4-9D34-1E3ECECF7E0F> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff225ea000 -     0x7fff2293efff  com.apple.security (7.0 - 59754.100.106) <E9261CB0-E729-3F58-98B7-172F243D4427> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff2293f000 -     0x7fff22b9efff  libicucore.A.dylib (66112) <478D57C3-FFF8-35E1-A64F-8490A616AB37> /usr/lib/libicucore.A.dylib
    0x7fff22f0f000 -     0x7fff22fbdfff  com.apple.framework.IOKit (2.0.2 - 1845.100.19) <99034CC2-EC1B-38C0-A8DE-CE37672DF139> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff23018000 -     0x7fff23d5ffff  com.apple.AppKit (6.9 - 2022.44.151) <10AFBC3A-E9A4-3E62-B9F5-97DF579B7A84> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff24aac000 -     0x7fff24f4afff  com.apple.CFNetwork (1237 - 1237) <347078F9-34AC-3AD5-AA02-B7E5E1D11FB6> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff2534b000 -     0x7fff259d4fff  com.apple.CoreGraphics (2.0 - 1463.14.2) <E16063AD-03D6-3DC7-A1D4-7103D3721A5A> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff26fa9000 -     0x7fff27285fff  com.apple.QuartzCore (1.11 - 927.17) <23171B27-B274-3E1D-A6D5-AF6A390B2BAE> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff275aa000 -     0x7fff2768cfff  libxml2.2.dylib (34.9) <B3F9E655-AB90-3375-8262-EC76550929D2> /usr/lib/libxml2.2.dylib
    0x7fff2768d000 -     0x7fff276dafff  com.apple.CoreVideo (1.8 - 414.7) <2CF6A7EC-9AD1-316B-A59E-E6C2FC56E3A7> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff28618000 -     0x7fff28694fff  com.apple.corelocation (2420.16.22 - 2420.16.22) <308F9664-E1D3-37A3-A9F9-CD280F9669C5> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff28803000 -     0x7fff288edfff  com.apple.CoreMedia (1.0 - 2770.32.4.7) <DA4F8C7D-060F-36AA-BF83-2EA9FDF5E2D4> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff28d89000 -     0x7fff28fc4fff  com.apple.ImageIO (3.3.0 - 2130.4.7) <002DE84A-6CDB-30D7-8489-37D3859D3C81> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff29cfe000 -     0x7fff29dd0fff  com.apple.framework.CoreWLAN (16.0 - 1657) <38CEA388-609B-38A4-82F7-9E61EBE900FF> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff2a09d000 -     0x7fff2a0a1fff  com.apple.xpc.ServiceManagement (1.0 - 1) <309EC085-9520-3D62-BBCE-6D44117308B7> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff2a640000 -     0x7fff2a64cfff  libbz2.1.0.dylib (44) <111C16DD-70F2-3BFF-A3E1-928C7F64B0C1> /usr/lib/libbz2.1.0.dylib
    0x7fff2a84e000 -     0x7fff2a860fff  libz.1.dylib (76) <45B3DDDD-FCA5-3387-98B8-38D9BFF68588> /usr/lib/libz.1.dylib
    0x7fff2a916000 -     0x7fff2a917fff  libSystem.B.dylib (1292.100.5) <EADFB1D1-E113-35B4-BD2D-C1E4C38010D4> /usr/lib/libSystem.B.dylib
    0x7fff2a955000 -     0x7fff2aa45fff  libiconv.2.dylib (59) <FFC919B8-AA34-3C59-9927-DD1345EF3F32> /usr/lib/libiconv.2.dylib
    0x7fff2be3b000 -     0x7fff2bf99fff  com.apple.VideoToolbox (1.0 - 2770.32.4.7) <73AF0B10-EA9F-3718-9729-E80F9E4F5EBF> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff2cadc000 -     0x7fff2ceb2fff  libswiftCore.dylib (5.4 - 1205.0.24.14) <8AC9FFA1-DADA-3936-BC88-AC533C4C298B> /usr/lib/swift/libswiftCore.dylib
    0x7fff2cf75000 -     0x7fff2d0a9fff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <9E029A41-7E6D-384E-8E13-0C97DCCF34BE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2d1a0000 -     0x7fff2d1b8fff  libresolv.9.dylib (68) <7EA918BC-50B3-3ABB-9021-88CB852FF4D6> /usr/lib/libresolv.9.dylib
    0x7fff2e7ce000 -     0x7fff2e82dfff  com.apple.QuickLookFramework (5.0 - 928.3) <2B0099AF-1406-3914-9FF9-393ABA6DCD53> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff3028e000 -     0x7fff3028efff  com.apple.CoreServices (1122.33 - 1122.33) <A1E63C1B-E06B-3DE1-9C96-77E1A412D6DA> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff30445000 -     0x7fff30445fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <D8A3E393-A247-34BC-BE43-E3EA399B491D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff307d4000 -     0x7fff3092cfff  libswiftFoundation.dylib (25.102) <7B5E14AB-5B90-346E-91AD-8ED2718E3D18> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff31890000 -     0x7fff318a5fff  libswiftDispatch.dylib (4.100.1) <69B479F4-CBBE-316E-9899-DFEBE6E78337> /usr/lib/swift/libswiftDispatch.dylib
    0x7fff33809000 -     0x7fff33809fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <31CB1996-369E-3ADF-9C6E-1ADD89BD273D> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff33890000 -     0x7fff33891fff  libswiftObjectiveC.dylib (3) <C376C97B-D808-3436-A9AE-1F19D0A46318> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff3521e000 -     0x7fff35221fff  com.apple.Cocoa (6.11 - 23) <ACA14CB3-6C24-31BE-9C2B-EF3AC3754C1F> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff366aa000 -     0x7fff37896fff  com.apple.JavaScriptCore (16611 - 16611.1.21.161.6) <F73DF52A-59F7-35BD-AB65-A34EFC82A213> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff3c1a8000 -     0x7fff3c1b2fff  libswiftCoreGraphics.dylib (2) <A28BFDF3-94C2-321E-81A9-ED452D2D6E5B> /usr/lib/swift/libswiftCoreGraphics.dylib
    0x7fff3c1b3000 -     0x7fff3c1bcfff  libswiftDarwin.dylib (??? - ???) <85B29C5B-5659-3EA5-AB93-B31555236C7E> /usr/lib/swift/libswiftDarwin.dylib
    0x7fff3c258000 -     0x7fff3ca33fff  com.apple.WebKit (16611 - 16611.1.21.161.6) <C7DE8356-6B9E-323A-9F72-E6C0D3E8D26E> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff3cbee000 -     0x7fff3cbf1fff  com.apple.Carbon (160 - 164) <6E0D7D9A-2C50-3FBD-A4CF-1D1285F086F1> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3ccea000 -     0x7fff3cceafff  com.apple.avfoundation (2.0 - 2010.31) <450A2F79-8923-374A-821B-589490A30AD8> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff3cceb000 -     0x7fff3ce05fff  com.apple.AVKit (1.1 - 732.4.8) <9896B7E9-36B0-3D10-B3E7-BE1ACB7DB5F3> /System/Library/Frameworks/AVKit.framework/Versions/A/AVKit
    0x7fff3d816000 -     0x7fff3d81efff  libswiftCoreAudio.dylib (1.1) <C50B24C1-4717-31A9-962A-B1CC319AAEAE> /usr/lib/swift/libswiftCoreAudio.dylib
    0x7fff3d81f000 -     0x7fff3d81ffff  libswiftCoreFoundation.dylib (1.6) <77F6AB54-C1F2-3FF5-9420-FB6BD59AF151> /usr/lib/swift/libswiftCoreFoundation.dylib
    0x7fff3d82b000 -     0x7fff3d82bfff  libswiftXPC.dylib (1.1) <1E0443B5-E820-317B-90C6-509B87165A40> /usr/lib/swift/libswiftXPC.dylib
    0x7fff3d82c000 -     0x7fff3d82cfff  libswiftCoreImage.dylib (1) <0E2C0000-EAC7-3203-9469-08E69DBB58D7> /usr/lib/swift/libswiftCoreImage.dylib
    0x7fff3d82d000 -     0x7fff3d82dfff  libswiftIOKit.dylib (1) <E7D22C76-6493-36D5-BE79-7A5FFC64F2B0> /usr/lib/swift/libswiftIOKit.dylib
    0x7fff3fdc8000 -     0x7fff3fde1fff  libswiftsimd.dylib (1.3) <549F8C0E-6696-36A5-A79F-3620BCD0D000> /usr/lib/swift/libswiftsimd.dylib
    0x7fff41081000 -     0x7fff41084fff  com.apple.quartzframework (1.5 - 25) <CDCF923D-445F-3A32-A3CB-08A3861F3BED> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff414c8000 -     0x7fff414c9fff  libswiftCoreLocation.dylib (5) <B76BE443-211B-3128-A384-709CA9B5E06A> /usr/lib/swift/libswiftCoreLocation.dylib
    0x7fff41dbf000 -     0x7fff41dc3fff  libswiftCoreData.dylib (3) <81CF3C82-4C2A-3B04-AD53-30856B920914> /usr/lib/swift/libswiftCoreData.dylib
    0x7fff45eb2000 -     0x7fff45eb7fff  libswiftMetal.dylib (1.3.1) <B4F8FF7C-9B54-3D98-9E2C-6A657B5E701A> /usr/lib/swift/libswiftMetal.dylib
    0x7fff48460000 -     0x7fff48474fff  libswiftAppKit.dylib (104) <B340EE4B-0F53-3AEB-8E33-0FB7D5E01BE9> /usr/lib/swift/libswiftAppKit.dylib
    0x7fff48475000 -     0x7fff48476fff  libswiftQuartzCore.dylib (1) <9764F27A-77B1-3B56-A975-6064A0B1FDB2> /usr/lib/swift/libswiftQuartzCore.dylib
    0x7fff4e41b000 -     0x7fff4e453fff  libswiftCoreMedia.dylib (1) <DBF9F90A-93CD-3002-9C85-6AA5851C70C4> /usr/lib/swift/libswiftCoreMedia.dylib
    0x7fff4efb3000 -     0x7fff4efb9fff  libswiftAVFoundation.dylib (2010.31) <EEFAB06E-B1F0-3FCA-9BD4-03B0D1471B90> /usr/lib/swift/libswiftAVFoundation.dylib
    0x7fff6bcca000 -     0x7fff6bcd9fff  com.apple.opengl (18.5.8 - 18.5.8) <DFFCB9A8-90D3-3189-B3ED-DBEED6B3695D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6ec96000 -     0x7fff6ecd8fff  com.apple.MultipeerConnectivity (172 - 172) <88E43E46-C193-33C0-9E02-FB4BD81C0436> /System/Library/Frameworks/MultipeerConnectivity.framework/Versions/A/MultipeerConnectivity
    0x7fff6ed1e000 -     0x7fff6ed40fff  com.apple.audio.OpenAL (1.8 - 1.8) <2DC8F853-2AAE-39AB-8492-4791DDC7B507> /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL

**Comment by MustangYM** [comment]
Termination Reason: DYLD, [0x5] Code Signature

**Comment by Rudyy898** [comment]
big sur 基本很难重签，，

**Comment by MustangYM** [comment]
#816
