### ISSUE TITLE
启动微信失败

### ISSUE THREAD

**Issue by SuKaiFei** [MustangYM/WeChatExtension-ForMac#985]
### issue规范
- MacOS版本 : 11.3.1
- 微信版本 : 3.0.3
- 小助手版本 : 2.8.4
- BUG描述 : 启动微信失败
-
![image](https://user-images.githubusercontent.com/16851216/118967406-4004ea00-b99d-11eb-8051-453913b29667.png)

**Comment by xiemms** [comment]
+1 我也是11.3.1的系统。 装小助手，微信也是打不开，卸载掉就能打开了，一样的错误

**Comment by Gss615** [comment]
同样呀，微信版本问题么？

**Comment by HelloWilliam** [comment]
+1

**Comment by SuKaiFei** [comment]
@MustangYM 我看到你关闭了issues，请问这个问题解决了吗

**Comment by MustangYM** [comment]
@SuKaiFei 看read me
