### ISSUE TITLE
最新版本小助手 + 3.03 微信无法启动

### ISSUE THREAD

**Issue by Rheinmetallskorpion** [MustangYM/WeChatExtension-ForMac#986]
### issue规范
- MacOS版本 : 11.3.1 (20E241)
- 微信版本 : 3.0.3
- 小助手版本 : 2.8.4 / 2.8.5
- BUG描述 : 启动报错
- 操作场景 : 试图启动微信时发生如下报错
- 方便的话提供日志, 截图或者视频(可选)
-
![image](https://user-images.githubusercontent.com/23652679/119061795-c9510680-ba07-11eb-8dd3-00efb325ad6a.png)
![image](https://user-images.githubusercontent.com/23652679/119061812-d1a94180-ba07-11eb-9054-7c036aa6cdd7.png)

**Comment by PandaZyD** [comment]
尝试重新签名软件后修复.如软件为 beta 版本,故不作二次回复.

**Comment by MustangYM** [comment]
#816
