### ISSUE TITLE
关于撤回返回，请增加语音转发功能以及撤回消息返回包括语音自动转发过来！

### ISSUE THREAD

**Issue by nangua1986** [MustangYM/WeChatExtension-ForMac#99]
请增加语音转发功能以及撤回消息返回包括语音自动转发过来！这样更全面点 ·谢谢！ 手机已有此类功能 非常好用！

**Comment by Jerry007s** [comment]
请把手机的这个工具分享下 哈哈哈哈

**Comment by MustangYM** [comment]
> 请增加语音转发功能以及撤回消息返回包括语音自动转发过来！这样更全面点 ·谢谢！ 手机已有此类功能 非常好用！

语音转发功能我有认真考虑过, 但是这个需求超出底线了, 引起不必要的麻烦, 明白我意思吧
