### ISSUE TITLE
“微信”将对您的电脑造成伤害。 您应该将它移到废纸篓。

### ISSUE THREAD

**Issue by AY-afkafk** [MustangYM/WeChatExtension-ForMac#995]
2.8.4
app版本： 3.0.3 (18062)
macOS 11.4 (20F71)
更新macOS后，打开微信，系统显示：“微信”将对您的电脑造成伤害。 您应该将它移到废纸篓。
移除小插件后可以正常打开，重装小插件后微信闪退。
<img width="295" alt="Screenshot 2021-05-25 上午10 55 36" src="https://user-images.githubusercontent.com/59311298/119433673-4dc5c100-bd49-11eb-8945-96b00c564083.png">
<img width="490" alt="Screenshot 2021-05-25 上午11 05 39" src="https://user-images.githubusercontent.com/59311298/119433682-4f8f8480-bd49-11eb-9798-696f54642f6f.png">

**Comment by w1da0** [comment]
你好，请问你这个问题是怎么解决的，可以说下嘛，谢谢。

**Comment by cat-walk** [comment]
遇到了同样的问题， codesign 也没有用，博主怎么解决的呢？

**Comment by AY-afkafk** [comment]
> 遇到了同样的问题， codesign 也没有用，博主怎么解决的呢？

应用程序那里微信cmd+i，然后勾选“覆盖恶意软件以保护”

**Comment by fyaojie** [comment]
666
