### ISSUE TITLE
更新到bigsur11.4后安装小助手的微信就提示已被阻止

### ISSUE THREAD

**Issue by leosun1992** [MustangYM/WeChatExtension-ForMac#997]
- MacOS版本 : bigsur 11.4
- 微信版本 : 3.0.4 (18099
- 小助手版本 : 2.8.4
- BUG描述 : 系统更新后安装小助手的微信就打不开，提示已被阻止
- 操作场景 : 安装小助手启动微信无法打开，重新安装微信不安装小助手就可以正常使用

**Comment by MustangYM** [comment]
#816

**Comment by leosun1992** [comment]
> #816

签名后已解决，谢谢！
